# BERT Similarity Experiments

Тот же фича-инжиниринг, что и в ML_Experiments.ipynb, включая ALS и TF-IDF.
**Cosine similarity вычислены через BERT-модели и добавлены в фичи.**

In [1]:
import re
import pickle
import warnings
import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
import mlflow
import optuna
import nltk
import pymorphy3

from tqdm.auto import tqdm
from nltk.corpus import stopwords
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
from scipy.sparse import csr_matrix, vstack
from transformers import AutoTokenizer, AutoModel
from implicit.als import AlternatingLeastSquares
from optuna.integration.mlflow import MLflowCallback
from mlflow.utils.mlflow_tags import MLFLOW_PARENT_RUN_ID
from sklearn.metrics import ndcg_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.preprocessing import OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from xgboost import XGBClassifier

import nltk
import pymorphy3
from nltk.corpus import stopwords
from gensim.utils import simple_preprocess

warnings.simplefilter('ignore', FutureWarning)

In [2]:
RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

TRACKING_SERVER_HOST = "127.0.0.1"
TRACKING_SERVER_PORT = 5000
EXPERIMENT_NAME = "hr-ai-scout-bert"

mlflow.set_tracking_uri(f"http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}")
mlflow.set_registry_uri(f"http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}")

In [3]:
if torch.cuda.is_available():
    DEVICE = torch.device('cuda')
elif torch.backends.mps.is_available():
    DEVICE = torch.device('mps')
else:
    DEVICE = torch.device('cpu')
print(f"Device: {DEVICE}")

torch.manual_seed(RANDOM_STATE)
if DEVICE.type == 'cuda':
    torch.cuda.manual_seed_all(RANDOM_STATE)

Device: mps

## 1. Load data

In [4]:
df = pd.read_csv('/Users/user/Documents/Magistracy/year_project/hr-ai-scout/total_df.csv')
df.head()

,vacancy_id,vacancy_name,vacancy_area,vacancy_experience,vacancy_employment,vacancy_schedule,vacancy_salary_from,vacancy_salary_to,vacancy_salary_currency,vacancy_salary_gross,...,resume_education,resume_courses,resume_salary,resume_age,resume_total_experience,resume_experience_months,resume_location,resume_gender,resume_applicant_status,target
0,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,300000.0,NaN,RUR,False,...,['Казанский Авиационный Институт'],NaN,NaN,65.0,19 лет,228.0,Москва,Мужчина,Рассматривает предложения,1
1,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,300000.0,NaN,RUR,False,...,"['ООО ""Открытый Учебный Центр СофтБаланс"", г. ...","['ООО ""Открытый Учебный Центр СофтБаланс"", г. ...",NaN,43.0,17 лет 4 месяца,208.0,Москва,Мужчина,Рассматривает предложения,1
2,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,300000.0,NaN,RUR,False,...,['Орский государственный педагогический инстит...,NaN,200 000 ₽ на руки,52.0,30 лет,360.0,Москва,Женщина,NaN,1
3,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,300000.0,NaN,RUR,False,...,['Красноярский государственный университет'],NaN,500 000 ₽ на руки,56.0,29 лет 8 месяцев,356.0,Красноярск,Мужчина,Рассматривает предложения,1
4,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,300000.0,NaN,RUR,False,...,['Белоруский Гос. Университет Информатики и Ра...,"['SAP CIS, SAP XI', 'Школа Логистики МАДИ', 'S...",NaN,48.0,25 лет 1 месяц,301.0,Moscow,Male,NaN,1

## 2. Preprocessing

*(скопировано из ML_Experiments.ipynb без изменений)*

In [5]:
t1 = df.shape[0]
df = df.dropna(subset=[
    "resume_education", "resume_last_experience_description",
    "resume_last_position", "resume_last_company_experience_period",
    "resume_total_experience", "resume_experience_months",
    "resume_location", "resume_specialization",
], how="all")
print('Удалено ', t1 - df.shape[0], ' строки')

Удалено  84  строки

In [6]:
t1 = df.shape[0]
df = df.loc[~(df["resume_total_experience"].notna()
              & df["resume_last_experience_description"].isna()
              & df["resume_last_position"].isna())]
df = df.loc[~(df["resume_total_experience"].isna()
              & df["resume_last_experience_description"].notna()
              & df["resume_last_position"].notna())]
print('Удалено ', t1 - df.shape[0], ' строк')

Удалено  1543  строк

In [7]:
num_cols = df.select_dtypes(include=[np.number]).columns
cat_cols = df.select_dtypes(include=['object']).columns
df[cat_cols] = df[cat_cols].fillna('NDT')
df['resume_age'] = df['resume_age'].fillna(df['resume_age'].mean())
df['resume_experience_months'] = df['resume_experience_months'].fillna(0)
df = df.drop(['vacancy_salary_to', 'vacancy_salary_from',
              'vacancy_salary_currency', 'vacancy_salary_gross'], axis=1)

In [8]:
df['resume_salary_split'] = df['resume_salary'].apply(lambda x: x.split())
df['salary_int'] = df['resume_salary_split'].apply(
    lambda x: int(''.join(p for p in x if re.fullmatch(r'\d+', p)))
              if any(re.fullmatch(r'\d+', p) for p in x) else np.nan
)
currency_symbols = ['₽', '$', '€', '₴', '₸', '₼', '₾', 'Br', "so'm"]
rates_rub = {'₽':1.0,'$':80.85,'€':94.14,'₴':1.94,'₸':0.150,
             '₼':47.8,'₾':33.5,'Br':28.7,"so'm":0.0068}
df['currency_symbol'] = df['resume_salary_split'].apply(
    lambda x: next((s for s in x if s in currency_symbols), np.nan))
df['salary_converted'] = (df['salary_int'] * df['currency_symbol'].map(rates_rub)).fillna(0)
df['resume_salary'] = df['salary_converted']
df = df.drop(['resume_salary_split','salary_int','currency_symbol','salary_converted'], axis=1)

In [9]:
def experience_to_months(text):
    months = 0
    for pat in [r'(\d+)\s*год', r'(\d+)\s*лет']:
        m = re.search(pat, text)
        if m: months += int(m.group(1)) * 12
    m = re.search(r'(\d+)\s*месяц', text)
    if m: months += int(m.group(1))
    return months if months > 0 else np.nan

df['resume_last_company_experience_months'] = \
    df['resume_last_company_experience_period'].apply(experience_to_months)
df['resume_last_company_experience_months'] = \
    df['resume_last_company_experience_months'].fillna(0)

In [10]:
df = df[~(df.resume_salary > 1e7)]
df.loc[df['resume_experience_months'] > 720, 'resume_experience_months'] = 720
df.loc[df['resume_last_company_experience_months'] > 720, 'resume_last_company_experience_months'] = 720
df = df[~(df.resume_age > 90)]
df = df[~(df.resume_experience_months < df.resume_last_company_experience_months)]
df = df[~(df.resume_age < (df.resume_experience_months // 12) + 16)]

gender_map = {'Мужчина':'Мужчина','Male':'Мужчина','Женщина':'Женщина','Female':'Женщина'}
df['resume_gender'] = df['resume_gender'].apply(
    lambda x: gender_map.get(x, 'Неизвестно'))

print(f"Датасет после очистки: {df.shape}")

Датасет после очистки: (325543, 25)

## 3. Feature engineering (с TF-IDF)

In [11]:
# Признак совпадения локации
df['location_matching'] = (df['vacancy_area'] == df['resume_location']).astype(int)

# Количество навыков резюме в тексте вакансии
def resume_skill_count_in_vacancy(row):
    skills = row['resume_skills'].replace('[','').replace(']','').replace("'","").split(', ')
    return sum(1 for s in skills if s in row['vacancy_description'])

df['resume_skill_count_in_vacancy'] = df.apply(resume_skill_count_in_vacancy, axis=1)

# Доля слов последней должности, встречающихся в описании вакансии
def last_position_in_vacancy(row):
    bow = []
    for sep in [' ', '-', '_']:
        bow += row['resume_last_position'].split(sep=sep)
    bow = list(set(bow))
    return sum(1 for w in bow if w in row['vacancy_description']) / len(bow)

df['last_position_in_vacancy'] = df.apply(last_position_in_vacancy, axis=1)

print("Признаки добавлены: location_matching, resume_skill_count_in_vacancy, last_position_in_vacancy")

Признаки добавлены: location_matching, resume_skill_count_in_vacancy, last_position_in_vacancy

In [12]:
def preprocess_data(df):
    """Обработка пропущенных значений в текстовых полях"""
    print("Проверка пропущенных значений...")
    print(f"Пропуски в vacancy_description: {df['vacancy_description'].isna().sum()}")
    print(f"Пропуски в resume_last_experience_description: {df['resume_last_experience_description'].isna().sum()}")
    
    # Заполняем пропуски пустыми строками
    df['vacancy_description'] = df['vacancy_description'].fillna('')
    df['resume_last_experience_description'] = df['resume_last_experience_description'].fillna('')
    
    # Проверяем, что все значения теперь строковые
    df['vacancy_description'] = df['vacancy_description'].astype(str)
    df['resume_last_experience_description'] = df['resume_last_experience_description'].astype(str)
    
    return df

In [13]:
def save_results(df, output_file):
    """Сохранение результатов в CSV файл"""
    df.to_csv(output_file, index=False, encoding='utf-8')
    print(f"Результаты сохранены в файл: {output_file}")

In [14]:
def calculate_cosine_similarity(embeddings1, embeddings2):
    """Вычисление косинусного сходства между двумя наборами эмбеддингов"""
    similarities = []
    
    for i in tqdm(range(embeddings1.shape[0])):
        emb1_row = embeddings1[i]
        emb2_row = embeddings2[i]
        
        similarity = cosine_similarity(emb1_row, emb2_row)[0][0]
        similarities.append(similarity)
    
    return similarities

In [15]:
warnings.filterwarnings('ignore')

try:
    nltk.data.find('corpora/stopwords')
except LookupError:
    nltk.download('stopwords')

try:
    nltk.data.find('taggers/averaged_perceptron_tagger_ru')
except LookupError:
    nltk.download('averaged_perceptron_tagger_ru')

try:
    nltk.data.find('corpora/wordnet')
except LookupError:
    nltk.download('wordnet')

morph = pymorphy3.MorphAnalyzer()

[nltk_data] Downloading package wordnet to /Users/user/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [16]:
def lemmatize_russian(tokens):
    """Лемматизация русских слов"""
    lemmas = []
    for token in tokens:
        parsed = morph.parse(token)[0]  # Берем самый вероятный разбор
        lemmas.append(parsed.normal_form)
    return lemmas

In [17]:
def tokenize_and_lemmatize(text):
    """Токенизация текста с лемматизацией и удалением стоп-слов"""
    tokens = simple_preprocess(text, deacc=True, min_len=2)
    stop_words = set(stopwords.words('russian') + stopwords.words('english'))
    tokens = [token for token in tokens if token not in stop_words]
    lemmatized_tokens = lemmatize_russian(tokens)
    
    return lemmatized_tokens

In [18]:
def get_tfidf_embeddings(texts, vectorizer=None, fit=True):
    """Создание TF-IDF эмбеддингов для списка текстов с лемматизацией"""
    if fit:
        vectorizer = TfidfVectorizer(
            max_features=5000,
            min_df=2,
            max_df=0.8,
            ngram_range=(1, 2),
            tokenizer=tokenize_and_lemmatize,
            token_pattern=None,
            lowercase=False  # Уже сделано в токенизации
        )
        embeddings = vectorizer.fit_transform(texts)
    else:
        embeddings = vectorizer.transform(texts)
    
    return embeddings, vectorizer

In [19]:
def get_tfidf_vacancy_embeddings(df, vectorizer=None):
    """Создание эмбеддингов для уникальных вакансий с лемматизацией"""
    unique_vacancies = df[['vacancy_id', 'vacancy_description']].drop_duplicates()
    
    unique_embeddings, vectorizer = get_tfidf_embeddings(
        unique_vacancies['vacancy_description'].tolist(), 
        vectorizer=vectorizer, 
        fit=(vectorizer is None)
    )
    
    vacancy_embedding_dict = dict(zip(unique_vacancies['vacancy_id'], unique_embeddings))
    
    rows = []
    for vid in df['vacancy_id']:
        rows.append(vacancy_embedding_dict[vid])
    
    all_vacancy_embeddings = vstack(rows)
    
    return all_vacancy_embeddings, vectorizer

In [20]:
def process_similarity_scores_tfidf(df, vectorizer=None, fit=True):
    """Функция для вычисления схожести с использованием TF-IDF и лемматизации"""
    df = preprocess_data(df)
    
    print("Создание TF-IDF эмбеддингов для описаний опыта в резюме...")
    experience_embeddings, tfidf_vectorizer = get_tfidf_embeddings(df['resume_last_experience_description'].tolist(), vectorizer=vectorizer, fit=fit)
    
    print("Создание TF-IDF эмбеддингов для описаний вакансий...")
    vacancy_embeddings, _ = get_tfidf_vacancy_embeddings(df, vectorizer=tfidf_vectorizer)
    
    print("Вычисление косинусного сходства...")
    similarity_scores = calculate_cosine_similarity(vacancy_embeddings, experience_embeddings)
    
    df['similarity_score_tfidf'] = similarity_scores
    
    return df, tfidf_vectorizer

In [21]:
try:
    df_tfidf = pd.read_csv('description_df_with_scores_tfidf.csv')
except:
    df_tfidf = process_similarity_scores_tfidf(df.copy())
    save_results(df_tfidf, 'description_df_with_scores_tfidf.csv')

In [22]:
df = df.merge(df_tfidf)

In [23]:
df.head()

,vacancy_id,vacancy_name,vacancy_area,vacancy_experience,vacancy_employment,vacancy_schedule,vacancy_description,resume_id,resume_title,resume_specialization,...,resume_location,resume_gender,resume_applicant_status,target,resume_last_company_experience_months,location_matching,resume_skill_count_in_vacancy,last_position_in_vacancy,resume_skill_count,similarity_score_tfidf
0,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,"Привет!.redev — технологическая компания, созд...",6969174,ABAP-разработчик,"['Программист, разработчик']",...,Москва,Мужчина,Рассматривает предложения,1,76.0,1,3,0.666667,3,0.284047
1,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,"Привет!.redev — технологическая компания, созд...",9100077,"ABAP разработчик - SAP HCM, CRM, S/4HANA ERP(F...","['Программист, разработчик']",...,Москва,Мужчина,Рассматривает предложения,1,8.0,1,2,0.500000,2,0.308726
2,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,"Привет!.redev — технологическая компания, созд...",32644957,Разработчик ABAP,"['Программист, разработчик']",...,Москва,Женщина,NDT,1,136.0,1,1,0.000000,1,0.510093
3,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,"Привет!.redev — технологическая компания, созд...",27220466,ABAP-разработчик,"['Программист, разработчик']",...,Красноярск,Мужчина,Рассматривает предложения,1,135.0,0,2,0.333333,2,0.301062
4,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,"Привет!.redev — технологическая компания, созд...",7532708,ABAP разработчик. Senior ABAP Developer. SAP T...,"['Programmer, developer']",...,Moscow,Мужчина,NDT,1,0.0,0,2,0.600000,2,0.075429

## 4. BERT Similarity

Ключ оптимизации — кодируем только **уникальные** вакансии и резюме, затем маппим на все строки df.

In [24]:
def encode_texts(texts, tokenizer, model, batch_size=64, prefix=''):
    """
    Батчевое кодирование текстов в L2-нормированные эмбеддинги.
    Mean pooling по токенам, взвешенный attention mask.
    """
    if prefix:
        texts = [prefix + t for t in texts]

    all_embeddings = []
    for i in tqdm(range(0, len(texts), batch_size), desc="    encoding"):
        batch = texts[i : i + batch_size]
        encoded = tokenizer(
            batch, padding=True, truncation=True,
            max_length=512, return_tensors='pt'
        ).to(DEVICE)

        with torch.no_grad():
            out = model(**encoded)

        # Mean pooling
        token_emb = out.last_hidden_state                              # (B, T, H)
        mask = encoded['attention_mask'].unsqueeze(-1).float()         # (B, T, 1)
        pooled = (token_emb * mask).sum(1) / mask.sum(1).clamp(min=1e-9)

        pooled = F.normalize(pooled, p=2, dim=1)
        all_embeddings.append(pooled.cpu().numpy())

    return np.vstack(all_embeddings)

In [25]:
def compute_bert_similarity(df, tokenizer, model, batch_size=64,
                             vacancy_prefix='', resume_prefix=''):
    """
    Cosine similarity между vacancy_description и resume_last_experience_description.
    Эмбеддинги вычисляются только для уникальных текстов.
    """
    df = df.copy()
    df['vacancy_description'] = df['vacancy_description'].fillna('').astype(str)
    df['resume_last_experience_description'] = \
        df['resume_last_experience_description'].fillna('').astype(str)

    # ── Уникальные вакансии ──────────────────────────────────────────
    unique_vac = df[['vacancy_id','vacancy_description']].drop_duplicates('vacancy_id')
    print(f"  Уникальных вакансий: {len(unique_vac)} / всего строк: {len(df)}")
    print("  Эмбеддинги вакансий...")
    vac_emb = encode_texts(unique_vac['vacancy_description'].tolist(),
                           tokenizer, model, batch_size, prefix=vacancy_prefix)
    vac_map = dict(zip(unique_vac['vacancy_id'], vac_emb))

    # ── Уникальные резюме ────────────────────────────────────────────
    unique_res = df[['resume_id','resume_last_experience_description']].drop_duplicates('resume_id')
    print(f"  Уникальных резюме: {len(unique_res)}")
    print("  Эмбеддинги резюме...")
    res_emb = encode_texts(unique_res['resume_last_experience_description'].tolist(),
                           tokenizer, model, batch_size, prefix=resume_prefix)
    res_map = dict(zip(unique_res['resume_id'], res_emb))

    # ── Попарное сходство (L2-норм → cosine = dot) ───────────────────
    sims = []
    for _, row in df.iterrows():
        v = vac_map.get(row['vacancy_id'])
        r = res_map.get(row['resume_id'])
        sims.append(float(np.dot(v, r)) if v is not None and r is not None else 0.0)

    return sims

In [26]:
# (model_name, vacancy_prefix, resume_prefix, batch_size)
BERT_MODELS = [
    ('cointegrated/LaBSE-en-ru',                                    '', '',           64),
    ('sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2', '', '',           64),
    ('ai-forever/sbert_large_nlu_ru',                               '', '',           32),
    ('intfloat/multilingual-e5-base',                   'query: ', 'passage: ',      32),
]

## 4.1 Кеш эмбеддингов в ClickHouse

Сохраняем вычисленные эмбеддинги в ClickHouse один раз.  
При следующем запуске — загружаем из базы, **не пересчитываем**.

In [27]:
from clickhouse_driver import Client
import os
from dotenv import load_dotenv

load_dotenv('/Users/user/Documents/Magistracy/year_project/hr-ai-scout/.env')

ch = Client(
    host=os.getenv('CLICKHOUSE_HOST', 'localhost'),
    port=int(os.getenv('CLICKHOUSE_PORT', 9000)),
    user=os.getenv('CLICKHOUSE_USER', 'default'),
    password=os.getenv('CLICKHOUSE_PASSWORD', ''),
    database=os.getenv('CLICKHOUSE_DATABASE', 'default'),
)
print("ClickHouse подключён")

ClickHouse подключён

In [28]:
def get_missing_ids(ids_needed: list, table: str, id_col: str,
                    model_name: str, clickhouse) -> list:
    """
    Возвращает те id из ids_needed, для которых в ClickHouse
    ещё нет эмбеддингов (по model_name).
    """
    if not ids_needed:
        return []
    str_ids = [str(i) for i in ids_needed]
    rows = clickhouse.execute(
        f"SELECT {id_col} FROM {table} "
        f"WHERE model_name = %(m)s AND {id_col} IN %(ids)s",
        {'m': model_name, 'ids': str_ids}
    )
    existing = {row[0] for row in rows}
    missing = [i for i in str_ids if i not in existing]
    print(f"  {table}: {len(existing)} в кеше, {len(missing)} новых из {len(str_ids)}")
    return missing


def save_embeddings_to_ch(emb_map: dict, id_col: str, table: str,
                           model_name: str, clickhouse):
    """Дописывает только новые эмбеддинги — существующие не удаляет."""
    rows = [
        (str(k), model_name, v.tolist())
        for k, v in emb_map.items()
    ]
    clickhouse.execute(
        f"INSERT INTO {table} ({id_col}, model_name, embedding) VALUES",
        rows,
    )
    print(f"  Сохранено {len(rows)} эмбеддингов → {table}")


def load_embeddings_from_ch(table: str, id_col: str, model_name: str,
                              clickhouse, ids: list = None) -> dict:
    """
    Загружает эмбеддинги из ClickHouse.
    ids — если передан, загружает только указанные id (экономит память).
    """
    params = {'m': model_name}
    query = f"SELECT {id_col}, embedding FROM {table} WHERE model_name = %(m)s"
    if ids:
        params['ids'] = [str(i) for i in ids]
        query += f" AND {id_col} IN %(ids)s"
    rows = clickhouse.execute(query, params)
    return {row[0]: np.array(row[1], dtype=np.float32) for row in rows}

In [29]:
bert_sim_cols = {}

for model_name, vac_prefix, res_prefix, bs in BERT_MODELS:
    short = model_name.split('/')[-1].replace('-', '_').lower()
    col   = f'sim_{short}'
    print(f"\n{'='*60}\n{model_name}\n{'='*60}")

    # Уникальные тексты текущего датасета
    unique_vac = (df[['vacancy_id', 'vacancy_description']]
                  .drop_duplicates('vacancy_id'))
    unique_res = (df[['resume_id', 'resume_last_experience_description']]
                  .drop_duplicates('resume_id'))

    all_vac_ids = unique_vac['vacancy_id'].tolist()
    all_res_ids = unique_res['resume_id'].tolist()

    # Проверяем, каких id нет в кеше
    missing_vac = get_missing_ids(all_vac_ids, 'vacancy_embeddings',
                                   'vacancy_id', model_name, ch)
    missing_res = get_missing_ids(all_res_ids, 'resume_embeddings',
                                   'resume_id', model_name, ch)

    # Загружаем BERT только если есть пропуски
    if missing_vac or missing_res:
        tokenizer  = AutoTokenizer.from_pretrained(model_name)
        bert_model = AutoModel.from_pretrained(model_name).to(DEVICE).eval()

        if missing_vac:
            texts = (unique_vac[unique_vac['vacancy_id'].astype(str).isin(missing_vac)]
                     ['vacancy_description'].fillna('').tolist())
            emb = encode_texts(texts, tokenizer, bert_model, bs, prefix=vac_prefix)
            save_embeddings_to_ch(dict(zip(missing_vac, emb)),
                                  'vacancy_id', 'vacancy_embeddings', model_name, ch)

        if missing_res:
            texts = (unique_res[unique_res['resume_id'].astype(str).isin(missing_res)]
                     ['resume_last_experience_description'].fillna('').tolist())
            emb = encode_texts(texts, tokenizer, bert_model, bs, prefix=res_prefix)
            save_embeddings_to_ch(dict(zip(missing_res, emb)),
                                  'resume_id', 'resume_embeddings', model_name, ch)

        del bert_model, tokenizer
        if DEVICE.type == 'mps':    torch.mps.empty_cache()
        elif DEVICE.type == 'cuda': torch.cuda.empty_cache()
    else:
        print("  Все эмбеддинги уже в кеше ClickHouse — загружаем")

    # Загружаем только нужные id текущего датасета
    vac_map = load_embeddings_from_ch('vacancy_embeddings', 'vacancy_id',
                                       model_name, ch, ids=all_vac_ids)
    res_map = load_embeddings_from_ch('resume_embeddings', 'resume_id',
                                       model_name, ch, ids=all_res_ids)

    # Косинусное сходство для каждой строки df
    df['vacancy_description'] = df['vacancy_description'].fillna('').astype(str)
    df['resume_last_experience_description'] = \
        df['resume_last_experience_description'].fillna('').astype(str)

    sims = [
        float(np.dot(vac_map[str(row.vacancy_id)], res_map[str(row.resume_id)]))
        if str(row.vacancy_id) in vac_map and str(row.resume_id) in res_map
        else 0.0
        for row in df.itertuples()
    ]
    df[col] = sims
    bert_sim_cols[model_name] = col
    print(f"  Среднее сходство: {df[col].mean():.4f}")

print("\nГотово:", list(bert_sim_cols.values()))

============================================================
cointegrated/LaBSE-en-ru
============================================================
  vacancy_embeddings: 3409 в кеше, 0 новых из 3409
  resume_embeddings: 20130 в кеше, 0 новых из 20130
  Все эмбеддинги уже в кеше ClickHouse — загружаем
  Среднее сходство: 0.6486

============================================================
sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
============================================================
  vacancy_embeddings: 3409 в кеше, 0 новых из 3409
  resume_embeddings: 20130 в кеше, 0 новых из 20130
  Все эмбеддинги уже в кеше ClickHouse — загружаем
  Среднее сходство: 0.3834

============================================================
ai-forever/sbert_large_nlu_ru
============================================================
  vacancy_embeddings: 3409 в кеше, 0 новых из 3409
  resume_embeddings: 20130 в кеше, 0 новых из 20130
  Все эмбеддинги уже в кеше ClickHouse — загружаем
  Среднее сходство: 0.6443

============================================================
intfloat/multilingual-e5-base
============================================================
  vacancy_embeddings: 3409 в кеше, 0 новых из 3409
  resume_embeddings: 20130 в кеше, 0 новых из 20130
  Все эмбеддинги уже в кеше ClickHouse — загружаем
  Среднее сходство: 0.8039

Готово: ['sim_labse_en_ru', 'sim_paraphrase_multilingual_minilm_l12_v2', 'sim_sbert_large_nlu_ru', 'sim_multilingual_e5_base']

## 5. ALS

In [30]:
def create_interaction_matrix(df):
    unique_vacancies = df['vacancy_id'].unique().tolist()
    unique_resumes   = df['resume_id'].unique().tolist()
    id2vacancy = dict(enumerate(unique_vacancies))
    id2resume  = dict(enumerate(unique_resumes))
    vacancy2id = {v: k for k, v in id2vacancy.items()}
    resume2id  = {v: k for k, v in id2resume.items()}
    rows = [vacancy2id[v] for v in df['vacancy_id']]
    cols = [resume2id[r]  for r in df['resume_id']]
    matrix = csr_matrix((df['target'], (rows, cols)),
                        shape=(len(unique_vacancies), len(unique_resumes)),
                        dtype=np.float32)
    return matrix, id2vacancy, id2resume, vacancy2id, resume2id, unique_vacancies, unique_resumes

def get_factors(interactions_matrix):
    als = AlternatingLeastSquares(
        factors=64, regularization=0.1, iterations=30,
        random_state=RANDOM_STATE, num_threads=0)
    als.fit(interactions_matrix.T)
    return als.item_factors, als.user_factors

def get_als_score(vacancy_id, resume_id):
    if vacancy_id not in vacancy2id or resume_id not in resume2id:
        return 0
    return float(np.dot(vacancy_factors[vacancy2id[vacancy_id]],
                         resume_factors[resume2id[resume_id]]))

## 6. Train / Test split + ALS score

In [31]:
# Базовые признаки (без similarity — добавим bert-вариант в цикле)
BASE_FEATURES = [
    'vacancy_area', 
    'vacancy_experience', 
    'vacancy_employment', 
    'vacancy_schedule',
    'resume_salary', 
    'resume_age', 
    'resume_experience_months', 
    'resume_location',
    'resume_gender', 
    'resume_applicant_status', 
    'resume_last_company_experience_months',
    'location_matching', 
    'resume_skill_count_in_vacancy', 
    'last_position_in_vacancy',
    'similarity_score_tfidf'
]

categorical_features = df[BASE_FEATURES].select_dtypes(exclude=np.number).columns.tolist()
numeric_features     = df[BASE_FEATURES].select_dtypes(include=np.number).columns.tolist()

X_base = df[BASE_FEATURES].copy()
y      = df['target'].copy()

X_train, X_test, y_train, y_test = train_test_split(
    X_base, y, test_size=0.2, random_state=RANDOM_STATE, stratify=y)

print(f"Train: {X_train.shape}, Test: {X_test.shape}")

Train: (257313, 15), Test: (64329, 15)

In [32]:
# ALS: обучаем на части train, чтобы избежать data leakage
X_train_als, _, y_train_als, _ = train_test_split(
    X_train, y_train, test_size=0.3, random_state=RANDOM_STATE, stratify=y_train)

train_als_interactions = df.loc[X_train_als.index, ['vacancy_id','resume_id','target']]
interactions_matrix, id2vacancy, id2resume, vacancy2id, resume2id, \
    unique_vacancies, unique_resumes = create_interaction_matrix(train_als_interactions)
vacancy_factors, resume_factors = get_factors(interactions_matrix)

X_train['als_score'] = df.loc[X_train.index].apply(
    lambda row: get_als_score(row['vacancy_id'], row['resume_id']), axis=1)

# Для test — ALS на полном train
train_interactions = df.loc[X_train.index, ['vacancy_id','resume_id','target']]
interactions_matrix, id2vacancy, id2resume, vacancy2id, resume2id, \
    unique_vacancies, unique_resumes = create_interaction_matrix(train_interactions)
vacancy_factors, resume_factors = get_factors(interactions_matrix)

X_test['als_score'] = df.loc[X_test.index].apply(
    lambda row: get_als_score(row['vacancy_id'], row['resume_id']), axis=1)

print(f"als_score в train (нули): {(X_train['als_score']==0).sum()}")
print(f"als_score в test  (нули): {(X_test['als_score']==0).sum()}")

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

als_score в train (нули): 14
als_score в test  (нули): 0

In [33]:
X_train

,vacancy_area,vacancy_experience,vacancy_employment,vacancy_schedule,resume_salary,resume_age,resume_experience_months,resume_location,resume_gender,resume_applicant_status,resume_last_company_experience_months,location_matching,resume_skill_count_in_vacancy,last_position_in_vacancy,similarity_score_tfidf,als_score
188418,Москва,От 1 года до 3 лет,Полная занятость,Полный день,0.0,49.0,309.0,Москва,Мужчина,Активно ищет работу,50.0,1,0,0.000000,0.006885,2.024440e-14
275162,Санкт-Петербург,От 3 до 6 лет,Полная занятость,Удаленная работа,0.0,29.0,136.0,Москва,Женщина,NDT,122.0,0,0,0.000000,0.068443,-5.261681e-15
231710,Москва,Более 6 лет,Полная занятость,Удаленная работа,150000.0,42.0,174.0,Энгельс,Мужчина,NDT,174.0,0,0,0.000000,0.087216,2.107787e-14
196958,Москва,Более 6 лет,Полная занятость,Полный день,0.0,32.0,144.0,Москва,Мужчина,NDT,106.0,1,1,0.000000,0.004965,-2.525638e-04
285737,Москва,От 3 до 6 лет,Полная занятость,Удаленная работа,0.0,42.0,248.0,Москва,Мужчина,NDT,93.0,1,2,0.000000,0.078090,-5.521995e-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311519,Москва,От 1 года до 3 лет,Полная занятость,Полный день,140000.0,45.0,202.0,Москва,Мужчина,Рассматривает предложения,14.0,1,0,0.166667,0.024229,-4.243372e-13
116481,Москва,От 3 до 6 лет,Полная занятость,Удаленная работа,30000.0,68.0,80.0,Москва,Мужчина,NDT,3.0,1,0,0.200000,0.000000,-4.975336e-15
288694,Москва,От 3 до 6 лет,Полная занятость,Удаленная работа,0.0,36.0,132.0,Moscow,Мужчина,NDT,0.0,0,0,0.000000,0.016053,-2.403483e-13
198848,Москва,От 3 до 6 лет,Полная занятость,Полный день,0.0,28.0,65.0,Москва,Женщина,NDT,65.0,1,0,0.000000,0.044461,1.493353e-04
283280,Москва,От 3 до 6 лет,Полная занятость,Полный день,0.0,29.0,21.0,Moscow,Мужчина,NDT,0.0,0,0,0.000000,0.000000,-5.521605e-13

## 7. Metrics

In [34]:
def calculate_metrics(df_test: pd.DataFrame) -> pd.DataFrame:
    ndcg_scores = []
    precision_scores = []
    recall_scores = []
    f1_scores = []
    vacancy_ids = df_test['vacancy_id'].unique()
    
    for vacancy_id in vacancy_ids:
        mask = df_test['vacancy_id'] == vacancy_id
        y_true = df_test.loc[mask, 'target'].values
        y_score = df_test.loc[mask, 'y_pred_proba'].values
        
        if len(y_true) <= 1:
            continue
        
        y_true_2d = y_true.reshape(1, -1)
        y_score_2d = y_score.reshape(1, -1)
        
        ndcg = ndcg_score(y_true_2d, y_score_2d)
        ndcg_scores.append(ndcg)
        
        y_pred_binary = (y_score >= 0.5).astype(int)
        
        precision = precision_score(y_true, y_pred_binary, zero_division=0)
        recall = recall_score(y_true, y_pred_binary, zero_division=0)
        f1 = f1_score(y_true, y_pred_binary, zero_division=0)
        
        precision_scores.append(precision)
        recall_scores.append(recall)
        f1_scores.append(f1)
    
    if ndcg_scores:
        print(f"Средний NDCG: {np.mean(ndcg_scores):.4f}")
        print(f"Средний Precision: {np.mean(precision_scores):.4f}")
        print(f"Средний Recall: {np.mean(recall_scores):.4f}")
        print(f"Средний F1-Score: {np.mean(f1_scores):.4f}")

        return np.mean(ndcg_scores), np.mean(precision_scores), np.mean(recall_scores), np.mean(f1_scores)
    else:
        print("Недостаточно данных для расчета метрик")

        return None, None, None, None

## 8. CatBoost + ALS + BERT Similarity

Для каждой BERT-модели запускаем Optuna (15 trials) и логируем NDCG в MLflow.

In [35]:
try:
    experiment_id = mlflow.get_experiment_by_name(EXPERIMENT_NAME).experiment_id
except:
    experiment_id = mlflow.create_experiment(EXPERIMENT_NAME)

STUDY_DB_NAME = "sqlite:///local.study.db"

In [37]:
def run_cat_bert(model_name, sim_col):
    short = model_name.split('/')[-1].replace('-', '_').lower()
    cat_bert = categorical_features

    X_tr = X_train[BASE_FEATURES + ['als_score']].copy()
    X_tr[sim_col] = df.loc[X_train.index, sim_col].values

    X_te = X_test[BASE_FEATURES + ['als_score']].copy()
    X_te[sim_col] = df.loc[X_test.index, sim_col].values

    def objective_catboost(trial: optuna.Trial) -> float:
        params = {
            'model__iterations': trial.suggest_int('iterations', 100, 1000, step=50),
            'model__depth': trial.suggest_int('depth', 3, 10),
            'model__learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
            'model__l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 1, 10, log=True)
        }
        
        pipeline_catboost = Pipeline([
            ('preprocessing', ColumnTransformer([
                ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
            ], remainder='passthrough')),
            ('model', CatBoostClassifier(
                random_state=RANDOM_STATE, 
                verbose=0, 
                auto_class_weights='Balanced'
            ))
        ])
        
        pipeline_catboost.set_params(**params)
        
        kfold = StratifiedKFold(n_splits=3, shuffle=True, random_state=RANDOM_STATE)
        
        for train_idx, val_idx in kfold.split(X_tr, y_train):
            X_fold_train, X_fold_val = X_tr.iloc[train_idx], X_tr.iloc[val_idx]
            y_fold_train, y_fold_val = y_train.iloc[train_idx], y_train.iloc[val_idx]
            
            pipeline_catboost.fit(X_fold_train, y_fold_train)
            y_pred_proba = pipeline_catboost.predict_proba(X_fold_val)
            
            df_val = df.loc[X_fold_val.index].copy()
            df_val['y_pred_proba'] = y_pred_proba[:, 1]
            
            ndcg, _, _, _ = calculate_metrics(df_val)
            
            trial.set_user_attr('pipeline_params', params)
        
        return ndcg

    RUN_NAME_OPTUNE_CATBOOST = f'CatBoostClassifier_optuna_als_tfidf_{short}'

    with mlflow.start_run(run_name=RUN_NAME_OPTUNE_CATBOOST, experiment_id=experiment_id) as run:
        run_id_catboost = run.info.run_id

    STUDY_NAME_CATBOOST = f'CatBoostClassifier_optuna_als_tfidf_{short}'

    mlflc_catboost = MLflowCallback(
        tracking_uri=f'http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}',
        metric_name="NDCG",
        create_experiment=False,
        mlflow_kwargs={'experiment_id': experiment_id, 'tags': {MLFLOW_PARENT_RUN_ID: run_id_catboost}}
    )

    study_catboost = optuna.create_study(direction='maximize', 
                                     sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
                                     study_name=STUDY_NAME_CATBOOST,
                                     storage=STUDY_DB_NAME,
                                     load_if_exists=False)

    study_catboost.optimize(objective_catboost, 
                            n_trials=50, 
                            callbacks=[mlflc_catboost]
                           )
    
    best_params_catboost = study_catboost.best_params
    print(f"Number of finished trials: {len(study_catboost.trials)}")
    print(f"Best params CatBoost: {best_params_catboost}")

    pipeline_catboost_best = Pipeline([
        ('preprocessing', ColumnTransformer([
            ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
        ], remainder='passthrough')),
        ('model', CatBoostClassifier(
            random_state=RANDOM_STATE, 
            verbose=0, 
            auto_class_weights='Balanced'
        ))
    ])
    
    pipeline_catboost_best.set_params(**study_catboost.best_trial.user_attrs['pipeline_params'])
    pipeline_catboost_best.fit(X_tr, y_train)
    
    y_pred_proba_catboost = pipeline_catboost_best.predict_proba(X_te)
    
    df_test_catboost = df.loc[X_te.index].copy()
    df_test_catboost['y_pred_proba'] = y_pred_proba_catboost[:, 1]
    
    ndcg_catboost_als, precision_catboost_als, recall_catboost_als, f1_catboost_als = calculate_metrics(df_test_catboost)
    metrics_catboost_als = {
        'NDCG': ndcg_catboost_als,
        'Precision': precision_catboost_als,
        'Recall': recall_catboost_als,
        'F1': f1_catboost_als
    }

    RUN_NAME_CATBOOST = f"best_optuna_catboost_als_tfidf_{short}"
    REGISTRY_MODEL_NAME_CATBOOST = f"best_optuna_catboost_als_tfidf_{short}"
    
    signature = mlflow.models.infer_signature(X_te, y_test)
    input_example = X_te[:10]
    code_paths = ["BERT_Experiments.ipynb"]
    
    with mlflow.start_run(run_name=RUN_NAME_CATBOOST, experiment_id=experiment_id) as run:
        run_id = run.info.run_id
        
        catboost_info = mlflow.sklearn.log_model(sk_model=pipeline_catboost_best, 
                                                 artifact_path=f'best_optuna_catboost_als_tfidf_{short}',
                                                 registered_model_name=REGISTRY_MODEL_NAME_CATBOOST,
                                                 input_example=input_example,
                                                 code_paths=code_paths,
                                                 await_registration_for=60
                                                )
        mlflow.log_metrics(metrics_catboost_als)
        mlflow.log_params(best_params_catboost)

    return {'Model': model_name, 'sim_col': sim_col, 'Pipeline': pipeline_catboost_best, **metrics_catboost_als}

In [38]:
all_results = []

for model_name, _, _, _ in BERT_MODELS:
    sim_col = bert_sim_cols[model_name]
    print(f"\n{'='*60}\nЭксперимент: {model_name}\n{'='*60}")
    try:
        result = run_cat_bert(model_name, sim_col)
        all_results.append(result)
    except Exception as e:
        print(f"[ОШИБКА] {e}")
        all_results.append({'Model': model_name, 'sim_col': sim_col,
                             'NDCG': None, 'Pipeline': None})
        break

============================================================
Эксперимент: cointegrated/LaBSE-en-ru
============================================================

[I 2026-05-04 13:06:23,571] A new study created in RDB with name: CatBoostClassifier_optuna_als_tfidf_labse_en_ru

🏃 View run CatBoostClassifier_optuna_als_tfidf_labse_en_ru at: http://127.0.0.1:5000/#/experiments/2/runs/11f80c89024449a79ccc0cbb5fca005a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8676
Средний Precision: 0.7933
Средний Recall: 0.8421
Средний F1-Score: 0.8069
Средний NDCG: 0.8582
Средний Precision: 0.7838
Средний Recall: 0.8305
Средний F1-Score: 0.7963

[I 2026-05-04 13:06:49,682] Trial 0 finished with value: 0.8634461370080225 and parameters: {'iterations': 450, 'depth': 10, 'learning_rate': 0.1205712628744377, 'l2_leaf_reg': 3.968793330444372}. Best is trial 0 with value: 0.8634461370080225.

Средний NDCG: 0.8634
Средний Precision: 0.7909
Средний Recall: 0.8332
Средний F1-Score: 0.8012
🏃 View run 0 at: http://127.0.0.1:5000/#/experiments/2/runs/a0d57c9fde894254bcfda8b72efc40c6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8649
Средний Precision: 0.7146
Средний Recall: 0.8496
Средний F1-Score: 0.7590
Средний NDCG: 0.8544
Средний Precision: 0.7127
Средний Recall: 0.8389
Средний F1-Score: 0.7538

[I 2026-05-04 13:07:04,248] Trial 1 finished with value: 0.859869655140647 and parameters: {'iterations': 200, 'depth': 4, 'learning_rate': 0.012184186502221764, 'l2_leaf_reg': 7.348118405270449}. Best is trial 0 with value: 0.8634461370080225.

Средний NDCG: 0.8599
Средний Precision: 0.7158
Средний Recall: 0.8433
Средний F1-Score: 0.7580
🏃 View run 1 at: http://127.0.0.1:5000/#/experiments/2/runs/c65b1f7cd2884d49a0923954f9ae63dc
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8672
Средний Precision: 0.7388
Средний Recall: 0.8546
Средний F1-Score: 0.7771
Средний NDCG: 0.8579
Средний Precision: 0.7277
Средний Recall: 0.8431
Средний F1-Score: 0.7660

[I 2026-05-04 13:07:27,857] Trial 2 finished with value: 0.8631793910976125 and parameters: {'iterations': 650, 'depth': 8, 'learning_rate': 0.010725209743171997, 'l2_leaf_reg': 9.330606024425668}. Best is trial 0 with value: 0.8634461370080225.

Средний NDCG: 0.8632
Средний Precision: 0.7400
Средний Recall: 0.8474
Средний F1-Score: 0.7757
🏃 View run 2 at: http://127.0.0.1:5000/#/experiments/2/runs/db720e4b091c4cd8a076949e3eb1d8b6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8668
Средний Precision: 0.7333
Средний Recall: 0.8559
Средний F1-Score: 0.7738
Средний NDCG: 0.8578
Средний Precision: 0.7252
Средний Recall: 0.8430
Средний F1-Score: 0.7646

[I 2026-05-04 13:07:49,396] Trial 3 finished with value: 0.8628030244302032 and parameters: {'iterations': 850, 'depth': 4, 'learning_rate': 0.01855998084649058, 'l2_leaf_reg': 1.5254729458052607}. Best is trial 0 with value: 0.8634461370080225.

Средний NDCG: 0.8628
Средний Precision: 0.7344
Средний Recall: 0.8479
Средний F1-Score: 0.7719
🏃 View run 3 at: http://127.0.0.1:5000/#/experiments/2/runs/870448ca68ba411283e1737bba59d6a0
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8677
Средний Precision: 0.7495
Средний Recall: 0.8550
Средний F1-Score: 0.7843
Средний NDCG: 0.8585
Средний Precision: 0.7402
Средний Recall: 0.8427
Средний F1-Score: 0.7738

[I 2026-05-04 13:08:07,207] Trial 4 finished with value: 0.8640915016226953 and parameters: {'iterations': 350, 'depth': 7, 'learning_rate': 0.04345454109729477, 'l2_leaf_reg': 1.9553708662745248}. Best is trial 4 with value: 0.8640915016226953.

Средний NDCG: 0.8641
Средний Precision: 0.7509
Средний Recall: 0.8477
Средний F1-Score: 0.7826
🏃 View run 4 at: http://127.0.0.1:5000/#/experiments/2/runs/b6774520129c448da9f1d6db7e57fb2d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8671
Средний Precision: 0.7336
Средний Recall: 0.8557
Средний F1-Score: 0.7740
Средний NDCG: 0.8578
Средний Precision: 0.7272
Средний Recall: 0.8440
Средний F1-Score: 0.7662

[I 2026-05-04 13:08:26,689] Trial 5 finished with value: 0.8632777710346731 and parameters: {'iterations': 650, 'depth': 4, 'learning_rate': 0.027010527749605478, 'l2_leaf_reg': 2.324672848950434}. Best is trial 4 with value: 0.8640915016226953.

Средний NDCG: 0.8633
Средний Precision: 0.7363
Средний Recall: 0.8483
Средний F1-Score: 0.7733
🏃 View run 5 at: http://127.0.0.1:5000/#/experiments/2/runs/285718d6020d40fcb286ff17f326500e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8680
Средний Precision: 0.7541
Средний Recall: 0.8533
Средний F1-Score: 0.7865
Средний NDCG: 0.8579
Средний Precision: 0.7444
Средний Recall: 0.8421
Средний F1-Score: 0.7764

[I 2026-05-04 13:08:50,180] Trial 6 finished with value: 0.8639288641886502 and parameters: {'iterations': 500, 'depth': 9, 'learning_rate': 0.019721610970574007, 'l2_leaf_reg': 3.2676417657817622}. Best is trial 4 with value: 0.8640915016226953.

Средний NDCG: 0.8639
Средний Precision: 0.7548
Средний Recall: 0.8471
Средний F1-Score: 0.7850
🏃 View run 6 at: http://127.0.0.1:5000/#/experiments/2/runs/53f257c0912a4c2db4de3bb27df59541
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8677
Средний Precision: 0.7429
Средний Recall: 0.8555
Средний F1-Score: 0.7802
Средний NDCG: 0.8577
Средний Precision: 0.7358
Средний Recall: 0.8439
Средний F1-Score: 0.7715

[I 2026-05-04 13:09:08,921] Trial 7 finished with value: 0.8626939322748851 and parameters: {'iterations': 650, 'depth': 3, 'learning_rate': 0.07896186801026692, 'l2_leaf_reg': 1.4808945119975185}. Best is trial 4 with value: 0.8640915016226953.

Средний NDCG: 0.8627
Средний Precision: 0.7438
Средний Recall: 0.8475
Средний F1-Score: 0.7783
🏃 View run 7 at: http://127.0.0.1:5000/#/experiments/2/runs/6be0ba07c7da4b5bb2b2676fa0803268
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8681
Средний Precision: 0.7678
Средний Recall: 0.8510
Средний F1-Score: 0.7947
Средний NDCG: 0.8577
Средний Precision: 0.7548
Средний Recall: 0.8393
Средний F1-Score: 0.7819

[I 2026-05-04 13:09:24,784] Trial 8 finished with value: 0.863280943347345 and parameters: {'iterations': 150, 'depth': 10, 'learning_rate': 0.26690431824362526, 'l2_leaf_reg': 6.432759992849893}. Best is trial 4 with value: 0.8640915016226953.

Средний NDCG: 0.8633
Средний Precision: 0.7674
Средний Recall: 0.8429
Средний F1-Score: 0.7907
🏃 View run 8 at: http://127.0.0.1:5000/#/experiments/2/runs/ee11b18fb5d644cf91825834bfba6aad
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8671
Средний Precision: 0.7393
Средний Recall: 0.8551
Средний F1-Score: 0.7776
Средний NDCG: 0.8572
Средний Precision: 0.7296
Средний Recall: 0.8442
Средний F1-Score: 0.7677

[I 2026-05-04 13:09:40,871] Trial 9 finished with value: 0.8627981313147998 and parameters: {'iterations': 350, 'depth': 3, 'learning_rate': 0.1024932221692416, 'l2_leaf_reg': 2.7551959649510764}. Best is trial 4 with value: 0.8640915016226953.

Средний NDCG: 0.8628
Средний Precision: 0.7403
Средний Recall: 0.8483
Средний F1-Score: 0.7764
🏃 View run 9 at: http://127.0.0.1:5000/#/experiments/2/runs/d18fc8eb013c4f8692eff83fadd952e1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Number of finished trials: 10
Best params CatBoost: {'iterations': 350, 'depth': 7, 'learning_rate': 0.04345454109729477, 'l2_leaf_reg': 1.9553708662745248}
Средний NDCG: 0.7814
Средний Precision: 0.6744
Средний Recall: 0.7620
Средний F1-Score: 0.7008

Successfully registered model 'best_optuna_catboost_als_tfidf_labse_en_ru'.
2026/05/04 13:09:50 INFO mlflow.store.model_registry.abstract_store: Waiting up to 60 seconds for model version to finish creation. Model name: best_optuna_catboost_als_tfidf_labse_en_ru, version 1
Created version '1' of model 'best_optuna_catboost_als_tfidf_labse_en_ru'.
[I 2026-05-04 13:09:50,130] A new study created in RDB with name: CatBoostClassifier_optuna_als_tfidf_paraphrase_multilingual_minilm_l12_v2

🏃 View run best_optuna_catboost_als_tfidf_labse_en_ru at: http://127.0.0.1:5000/#/experiments/2/runs/ebf7a52d0d884164b6a92488957ff1a2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

============================================================
Эксперимент: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
============================================================
🏃 View run CatBoostClassifier_optuna_als_tfidf_paraphrase_multilingual_minilm_l12_v2 at: http://127.0.0.1:5000/#/experiments/2/runs/674c04a13ebe4079a775e1466ec8b7d4
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8677
Средний Precision: 0.7929
Средний Recall: 0.8418
Средний F1-Score: 0.8063
Средний NDCG: 0.8578
Средний Precision: 0.7827
Средний Recall: 0.8305
Средний F1-Score: 0.7952

[I 2026-05-04 13:10:16,225] Trial 0 finished with value: 0.8631572294798157 and parameters: {'iterations': 450, 'depth': 10, 'learning_rate': 0.1205712628744377, 'l2_leaf_reg': 3.968793330444372}. Best is trial 0 with value: 0.8631572294798157.

Средний NDCG: 0.8632
Средний Precision: 0.7896
Средний Recall: 0.8345
Средний F1-Score: 0.8009
🏃 View run 0 at: http://127.0.0.1:5000/#/experiments/2/runs/6d71804568ea45c09c12347a87380554
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8649
Средний Precision: 0.7164
Средний Recall: 0.8495
Средний F1-Score: 0.7603
Средний NDCG: 0.8545
Средний Precision: 0.7082
Средний Recall: 0.8382
Средний F1-Score: 0.7506

[I 2026-05-04 13:10:31,108] Trial 1 finished with value: 0.8597693957957748 and parameters: {'iterations': 200, 'depth': 4, 'learning_rate': 0.012184186502221764, 'l2_leaf_reg': 7.348118405270449}. Best is trial 0 with value: 0.8631572294798157.

Средний NDCG: 0.8598
Средний Precision: 0.7197
Средний Recall: 0.8435
Средний F1-Score: 0.7607
🏃 View run 1 at: http://127.0.0.1:5000/#/experiments/2/runs/d402701274aa452fa68f1bc64e8d8cc9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8673
Средний Precision: 0.7369
Средний Recall: 0.8533
Средний F1-Score: 0.7751
Средний NDCG: 0.8578
Средний Precision: 0.7274
Средний Recall: 0.8439
Средний F1-Score: 0.7663

[I 2026-05-04 13:10:54,955] Trial 2 finished with value: 0.8635473076253672 and parameters: {'iterations': 650, 'depth': 8, 'learning_rate': 0.010725209743171997, 'l2_leaf_reg': 9.330606024425668}. Best is trial 2 with value: 0.8635473076253672.

Средний NDCG: 0.8635
Средний Precision: 0.7409
Средний Recall: 0.8475
Средний F1-Score: 0.7761
🏃 View run 2 at: http://127.0.0.1:5000/#/experiments/2/runs/b63630a10c5b4c8ca29d8bb9297f305a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8672
Средний Precision: 0.7331
Средний Recall: 0.8546
Средний F1-Score: 0.7733
Средний NDCG: 0.8579
Средний Precision: 0.7243
Средний Recall: 0.8442
Средний F1-Score: 0.7643

[I 2026-05-04 13:11:16,652] Trial 3 finished with value: 0.8629663169905297 and parameters: {'iterations': 850, 'depth': 4, 'learning_rate': 0.01855998084649058, 'l2_leaf_reg': 1.5254729458052607}. Best is trial 2 with value: 0.8635473076253672.

Средний NDCG: 0.8630
Средний Precision: 0.7357
Средний Recall: 0.8483
Средний F1-Score: 0.7732
🏃 View run 3 at: http://127.0.0.1:5000/#/experiments/2/runs/b879ec044e8145bf880a870595e32bff
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8681
Средний Precision: 0.7504
Средний Recall: 0.8544
Средний F1-Score: 0.7844
Средний NDCG: 0.8582
Средний Precision: 0.7402
Средний Recall: 0.8434
Средний F1-Score: 0.7742

[I 2026-05-04 13:11:34,553] Trial 4 finished with value: 0.8634819793131777 and parameters: {'iterations': 350, 'depth': 7, 'learning_rate': 0.04345454109729477, 'l2_leaf_reg': 1.9553708662745248}. Best is trial 2 with value: 0.8635473076253672.

Средний NDCG: 0.8635
Средний Precision: 0.7524
Средний Recall: 0.8474
Средний F1-Score: 0.7836
🏃 View run 4 at: http://127.0.0.1:5000/#/experiments/2/runs/a251bdb5b98f44f1b50e6a09efe2d863
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8673
Средний Precision: 0.7334
Средний Recall: 0.8550
Средний F1-Score: 0.7735
Средний NDCG: 0.8575
Средний Precision: 0.7254
Средний Recall: 0.8447
Средний F1-Score: 0.7652

[I 2026-05-04 13:11:54,150] Trial 5 finished with value: 0.8630773857596234 and parameters: {'iterations': 650, 'depth': 4, 'learning_rate': 0.027010527749605478, 'l2_leaf_reg': 2.324672848950434}. Best is trial 2 with value: 0.8635473076253672.

Средний NDCG: 0.8631
Средний Precision: 0.7363
Средний Recall: 0.8486
Средний F1-Score: 0.7737
🏃 View run 5 at: http://127.0.0.1:5000/#/experiments/2/runs/ce9f407294f64da4a67c400f2bf72bf8
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8683
Средний Precision: 0.7519
Средний Recall: 0.8519
Средний F1-Score: 0.7842
Средний NDCG: 0.8581
Средний Precision: 0.7438
Средний Recall: 0.8426
Средний F1-Score: 0.7762

[I 2026-05-04 13:12:17,687] Trial 6 finished with value: 0.8637424460692948 and parameters: {'iterations': 500, 'depth': 9, 'learning_rate': 0.019721610970574007, 'l2_leaf_reg': 3.2676417657817622}. Best is trial 6 with value: 0.8637424460692948.

Средний NDCG: 0.8637
Средний Precision: 0.7550
Средний Recall: 0.8460
Средний F1-Score: 0.7848
🏃 View run 6 at: http://127.0.0.1:5000/#/experiments/2/runs/5fff60e65b7e404d8e748c7216ec5528
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8674
Средний Precision: 0.7415
Средний Recall: 0.8544
Средний F1-Score: 0.7786
Средний NDCG: 0.8578
Средний Precision: 0.7373
Средний Recall: 0.8453
Средний F1-Score: 0.7731

[I 2026-05-04 13:12:36,464] Trial 7 finished with value: 0.8627711236331731 and parameters: {'iterations': 650, 'depth': 3, 'learning_rate': 0.07896186801026692, 'l2_leaf_reg': 1.4808945119975185}. Best is trial 6 with value: 0.8637424460692948.

Средний NDCG: 0.8628
Средний Precision: 0.7448
Средний Recall: 0.8482
Средний F1-Score: 0.7794
🏃 View run 7 at: http://127.0.0.1:5000/#/experiments/2/runs/c6050ed7119947dc95920c4fead87c14
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8677
Средний Precision: 0.7683
Средний Recall: 0.8487
Средний F1-Score: 0.7934
Средний NDCG: 0.8577
Средний Precision: 0.7578
Средний Recall: 0.8398
Средний F1-Score: 0.7840

[I 2026-05-04 13:12:52,342] Trial 8 finished with value: 0.8638124069836481 and parameters: {'iterations': 150, 'depth': 10, 'learning_rate': 0.26690431824362526, 'l2_leaf_reg': 6.432759992849893}. Best is trial 8 with value: 0.8638124069836481.

Средний NDCG: 0.8638
Средний Precision: 0.7648
Средний Recall: 0.8437
Средний F1-Score: 0.7896
🏃 View run 8 at: http://127.0.0.1:5000/#/experiments/2/runs/1b5a83c66f9d4bf68781c1ab86893bda
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8676
Средний Precision: 0.7378
Средний Recall: 0.8546
Средний F1-Score: 0.7763
Средний NDCG: 0.8581
Средний Precision: 0.7304
Средний Recall: 0.8450
Средний F1-Score: 0.7684

[I 2026-05-04 13:13:08,395] Trial 9 finished with value: 0.8627530610645275 and parameters: {'iterations': 350, 'depth': 3, 'learning_rate': 0.1024932221692416, 'l2_leaf_reg': 2.7551959649510764}. Best is trial 8 with value: 0.8638124069836481.

Средний NDCG: 0.8628
Средний Precision: 0.7410
Средний Recall: 0.8497
Средний F1-Score: 0.7773
🏃 View run 9 at: http://127.0.0.1:5000/#/experiments/2/runs/fc1abed7429342f1829c967b0207be5f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Number of finished trials: 10
Best params CatBoost: {'iterations': 150, 'depth': 10, 'learning_rate': 0.26690431824362526, 'l2_leaf_reg': 6.432759992849893}
Средний NDCG: 0.7814
Средний Precision: 0.6852
Средний Recall: 0.7551
Средний F1-Score: 0.7045

Successfully registered model 'best_optuna_catboost_als_tfidf_paraphrase_multilingual_minilm_l12_v2'.
2026/05/04 13:13:16 INFO mlflow.store.model_registry.abstract_store: Waiting up to 60 seconds for model version to finish creation. Model name: best_optuna_catboost_als_tfidf_paraphrase_multilingual_minilm_l12_v2, version 1
Created version '1' of model 'best_optuna_catboost_als_tfidf_paraphrase_multilingual_minilm_l12_v2'.
[I 2026-05-04 13:13:16,412] A new study created in RDB with name: CatBoostClassifier_optuna_als_tfidf_sbert_large_nlu_ru

🏃 View run best_optuna_catboost_als_tfidf_paraphrase_multilingual_minilm_l12_v2 at: http://127.0.0.1:5000/#/experiments/2/runs/788e07cf57324b189da0eb94cbca0e33
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

============================================================
Эксперимент: ai-forever/sbert_large_nlu_ru
============================================================
🏃 View run CatBoostClassifier_optuna_als_tfidf_sbert_large_nlu_ru at: http://127.0.0.1:5000/#/experiments/2/runs/2b2be4edf3c64a18b3210e39663dfa87
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8674
Средний Precision: 0.7893
Средний Recall: 0.8426
Средний F1-Score: 0.8042
Средний NDCG: 0.8575
Средний Precision: 0.7828
Средний Recall: 0.8316
Средний F1-Score: 0.7961

[I 2026-05-04 13:13:42,347] Trial 0 finished with value: 0.8636907574758983 and parameters: {'iterations': 450, 'depth': 10, 'learning_rate': 0.1205712628744377, 'l2_leaf_reg': 3.968793330444372}. Best is trial 0 with value: 0.8636907574758983.

Средний NDCG: 0.8637
Средний Precision: 0.7884
Средний Recall: 0.8337
Средний F1-Score: 0.7997
🏃 View run 0 at: http://127.0.0.1:5000/#/experiments/2/runs/817a49668af74b7bafca7f559b00080b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8650
Средний Precision: 0.7179
Средний Recall: 0.8496
Средний F1-Score: 0.7611
Средний NDCG: 0.8543
Средний Precision: 0.7065
Средний Recall: 0.8393
Средний F1-Score: 0.7499

[I 2026-05-04 13:13:57,438] Trial 1 finished with value: 0.8597507501786076 and parameters: {'iterations': 200, 'depth': 4, 'learning_rate': 0.012184186502221764, 'l2_leaf_reg': 7.348118405270449}. Best is trial 0 with value: 0.8636907574758983.

Средний NDCG: 0.8598
Средний Precision: 0.7169
Средний Recall: 0.8438
Средний F1-Score: 0.7589
🏃 View run 1 at: http://127.0.0.1:5000/#/experiments/2/runs/ac497f0ca312438b82a82d58504ad658
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8675
Средний Precision: 0.7390
Средний Recall: 0.8545
Средний F1-Score: 0.7771
Средний NDCG: 0.8577
Средний Precision: 0.7272
Средний Recall: 0.8438
Средний F1-Score: 0.7660

[I 2026-05-04 13:14:21,247] Trial 2 finished with value: 0.8633116928483325 and parameters: {'iterations': 650, 'depth': 8, 'learning_rate': 0.010725209743171997, 'l2_leaf_reg': 9.330606024425668}. Best is trial 0 with value: 0.8636907574758983.

Средний NDCG: 0.8633
Средний Precision: 0.7364
Средний Recall: 0.8472
Средний F1-Score: 0.7733
🏃 View run 2 at: http://127.0.0.1:5000/#/experiments/2/runs/485a5824e92c49d2a4701dc033817517
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8672
Средний Precision: 0.7336
Средний Recall: 0.8551
Средний F1-Score: 0.7738
Средний NDCG: 0.8576
Средний Precision: 0.7231
Средний Recall: 0.8445
Средний F1-Score: 0.7637

[I 2026-05-04 13:14:42,859] Trial 3 finished with value: 0.8626775703182241 and parameters: {'iterations': 850, 'depth': 4, 'learning_rate': 0.01855998084649058, 'l2_leaf_reg': 1.5254729458052607}. Best is trial 0 with value: 0.8636907574758983.

Средний NDCG: 0.8627
Средний Precision: 0.7344
Средний Recall: 0.8488
Средний F1-Score: 0.7723
🏃 View run 3 at: http://127.0.0.1:5000/#/experiments/2/runs/e26d7020338c49a9a71f6638057bedb6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8678
Средний Precision: 0.7490
Средний Recall: 0.8541
Средний F1-Score: 0.7837
Средний NDCG: 0.8581
Средний Precision: 0.7396
Средний Recall: 0.8427
Средний F1-Score: 0.7735

[I 2026-05-04 13:15:00,934] Trial 4 finished with value: 0.8634839021012114 and parameters: {'iterations': 350, 'depth': 7, 'learning_rate': 0.04345454109729477, 'l2_leaf_reg': 1.9553708662745248}. Best is trial 0 with value: 0.8636907574758983.

Средний NDCG: 0.8635
Средний Precision: 0.7475
Средний Recall: 0.8470
Средний F1-Score: 0.7802
🏃 View run 4 at: http://127.0.0.1:5000/#/experiments/2/runs/cc7be01f766b4e19a00672d26120c1b2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8672
Средний Precision: 0.7342
Средний Recall: 0.8560
Средний F1-Score: 0.7746
Средний NDCG: 0.8577
Средний Precision: 0.7271
Средний Recall: 0.8447
Средний F1-Score: 0.7663

[I 2026-05-04 13:15:20,514] Trial 5 finished with value: 0.862910749870655 and parameters: {'iterations': 650, 'depth': 4, 'learning_rate': 0.027010527749605478, 'l2_leaf_reg': 2.324672848950434}. Best is trial 0 with value: 0.8636907574758983.

Средний NDCG: 0.8629
Средний Precision: 0.7354
Средний Recall: 0.8488
Средний F1-Score: 0.7731
🏃 View run 5 at: http://127.0.0.1:5000/#/experiments/2/runs/8a01f1c2df7d4415a4ee31ca5cb4e0b9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8681
Средний Precision: 0.7513
Средний Recall: 0.8530
Средний F1-Score: 0.7846
Средний NDCG: 0.8579
Средний Precision: 0.7421
Средний Recall: 0.8418
Средний F1-Score: 0.7749

[I 2026-05-04 13:15:43,982] Trial 6 finished with value: 0.8635038239284654 and parameters: {'iterations': 500, 'depth': 9, 'learning_rate': 0.019721610970574007, 'l2_leaf_reg': 3.2676417657817622}. Best is trial 0 with value: 0.8636907574758983.

Средний NDCG: 0.8635
Средний Precision: 0.7544
Средний Recall: 0.8462
Средний F1-Score: 0.7844
🏃 View run 6 at: http://127.0.0.1:5000/#/experiments/2/runs/8ee96b38acbe4e39a45c41cd79514f07
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8677
Средний Precision: 0.7413
Средний Recall: 0.8554
Средний F1-Score: 0.7790
Средний NDCG: 0.8578
Средний Precision: 0.7344
Средний Recall: 0.8449
Средний F1-Score: 0.7712

[I 2026-05-04 13:16:02,791] Trial 7 finished with value: 0.8626776135578367 and parameters: {'iterations': 650, 'depth': 3, 'learning_rate': 0.07896186801026692, 'l2_leaf_reg': 1.4808945119975185}. Best is trial 0 with value: 0.8636907574758983.

Средний NDCG: 0.8627
Средний Precision: 0.7430
Средний Recall: 0.8480
Средний F1-Score: 0.7778
🏃 View run 7 at: http://127.0.0.1:5000/#/experiments/2/runs/9d89d0260a21484c819a5f6d9bb5175f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8678
Средний Precision: 0.7653
Средний Recall: 0.8508
Средний F1-Score: 0.7926
Средний NDCG: 0.8573
Средний Precision: 0.7527
Средний Recall: 0.8401
Средний F1-Score: 0.7808

[I 2026-05-04 13:16:18,648] Trial 8 finished with value: 0.8634995882342326 and parameters: {'iterations': 150, 'depth': 10, 'learning_rate': 0.26690431824362526, 'l2_leaf_reg': 6.432759992849893}. Best is trial 0 with value: 0.8636907574758983.

Средний NDCG: 0.8635
Средний Precision: 0.7638
Средний Recall: 0.8428
Средний F1-Score: 0.7886
🏃 View run 8 at: http://127.0.0.1:5000/#/experiments/2/runs/54eb96a4b12947cb9d8007c2d6456029
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8676
Средний Precision: 0.7368
Средний Recall: 0.8551
Средний F1-Score: 0.7762
Средний NDCG: 0.8576
Средний Precision: 0.7317
Средний Recall: 0.8446
Средний F1-Score: 0.7691

[I 2026-05-04 13:16:34,674] Trial 9 finished with value: 0.8630062342949265 and parameters: {'iterations': 350, 'depth': 3, 'learning_rate': 0.1024932221692416, 'l2_leaf_reg': 2.7551959649510764}. Best is trial 0 with value: 0.8636907574758983.

Средний NDCG: 0.8630
Средний Precision: 0.7402
Средний Recall: 0.8487
Средний F1-Score: 0.7763
🏃 View run 9 at: http://127.0.0.1:5000/#/experiments/2/runs/e0df65d5b6474d36a5afec193378d6e2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Number of finished trials: 10
Best params CatBoost: {'iterations': 450, 'depth': 10, 'learning_rate': 0.1205712628744377, 'l2_leaf_reg': 3.968793330444372}
Средний NDCG: 0.7814
Средний Precision: 0.7023
Средний Recall: 0.7493
Средний F1-Score: 0.7132

Successfully registered model 'best_optuna_catboost_als_tfidf_sbert_large_nlu_ru'.
2026/05/04 13:16:47 INFO mlflow.store.model_registry.abstract_store: Waiting up to 60 seconds for model version to finish creation. Model name: best_optuna_catboost_als_tfidf_sbert_large_nlu_ru, version 1
Created version '1' of model 'best_optuna_catboost_als_tfidf_sbert_large_nlu_ru'.
[I 2026-05-04 13:16:47,283] A new study created in RDB with name: CatBoostClassifier_optuna_als_tfidf_multilingual_e5_base

🏃 View run best_optuna_catboost_als_tfidf_sbert_large_nlu_ru at: http://127.0.0.1:5000/#/experiments/2/runs/c32e918c95904ff0b1033e99d9a28202
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

============================================================
Эксперимент: intfloat/multilingual-e5-base
============================================================
🏃 View run CatBoostClassifier_optuna_als_tfidf_multilingual_e5_base at: http://127.0.0.1:5000/#/experiments/2/runs/056c339e7fcc4f219c779c3b901537f3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8675
Средний Precision: 0.7922
Средний Recall: 0.8402
Средний F1-Score: 0.8053
Средний NDCG: 0.8576
Средний Precision: 0.7771
Средний Recall: 0.8317
Средний F1-Score: 0.7923

[I 2026-05-04 13:17:14,350] Trial 0 finished with value: 0.8634723114925772 and parameters: {'iterations': 450, 'depth': 10, 'learning_rate': 0.1205712628744377, 'l2_leaf_reg': 3.968793330444372}. Best is trial 0 with value: 0.8634723114925772.

Средний NDCG: 0.8635
Средний Precision: 0.7890
Средний Recall: 0.8345
Средний F1-Score: 0.8006
🏃 View run 0 at: http://127.0.0.1:5000/#/experiments/2/runs/039d380bc24a46b1830d0c0659614fdd
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8649
Средний Precision: 0.7131
Средний Recall: 0.8499
Средний F1-Score: 0.7583
Средний NDCG: 0.8544
Средний Precision: 0.7063
Средний Recall: 0.8384
Средний F1-Score: 0.7493

[I 2026-05-04 13:17:29,522] Trial 1 finished with value: 0.8599700791054788 and parameters: {'iterations': 200, 'depth': 4, 'learning_rate': 0.012184186502221764, 'l2_leaf_reg': 7.348118405270449}. Best is trial 0 with value: 0.8634723114925772.

Средний NDCG: 0.8600
Средний Precision: 0.7169
Средний Recall: 0.8433
Средний F1-Score: 0.7587
🏃 View run 1 at: http://127.0.0.1:5000/#/experiments/2/runs/d1340d4169d84483a742fb8d57087d19
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8673
Средний Precision: 0.7367
Средний Recall: 0.8543
Средний F1-Score: 0.7759
Средний NDCG: 0.8578
Средний Precision: 0.7268
Средний Recall: 0.8431
Средний F1-Score: 0.7655

[I 2026-05-04 13:17:53,226] Trial 2 finished with value: 0.863173786757025 and parameters: {'iterations': 650, 'depth': 8, 'learning_rate': 0.010725209743171997, 'l2_leaf_reg': 9.330606024425668}. Best is trial 0 with value: 0.8634723114925772.

Средний NDCG: 0.8632
Средний Precision: 0.7354
Средний Recall: 0.8482
Средний F1-Score: 0.7730
🏃 View run 2 at: http://127.0.0.1:5000/#/experiments/2/runs/13cba9bb9a4144e39fec910d3c978cb2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8670
Средний Precision: 0.7314
Средний Recall: 0.8544
Средний F1-Score: 0.7722
Средний NDCG: 0.8577
Средний Precision: 0.7223
Средний Recall: 0.8440
Средний F1-Score: 0.7630

[I 2026-05-04 13:18:14,667] Trial 3 finished with value: 0.8625936965219144 and parameters: {'iterations': 850, 'depth': 4, 'learning_rate': 0.01855998084649058, 'l2_leaf_reg': 1.5254729458052607}. Best is trial 0 with value: 0.8634723114925772.

Средний NDCG: 0.8626
Средний Precision: 0.7312
Средний Recall: 0.8492
Средний F1-Score: 0.7706
🏃 View run 3 at: http://127.0.0.1:5000/#/experiments/2/runs/80e2db9214a6425c8cd08393c8529eb2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8675
Средний Precision: 0.7477
Средний Recall: 0.8539
Средний F1-Score: 0.7827
Средний NDCG: 0.8584
Средний Precision: 0.7392
Средний Recall: 0.8426
Средний F1-Score: 0.7733

[I 2026-05-04 13:18:32,617] Trial 4 finished with value: 0.8635031248671999 and parameters: {'iterations': 350, 'depth': 7, 'learning_rate': 0.04345454109729477, 'l2_leaf_reg': 1.9553708662745248}. Best is trial 4 with value: 0.8635031248671999.

Средний NDCG: 0.8635
Средний Precision: 0.7488
Средний Recall: 0.8476
Средний F1-Score: 0.7815
🏃 View run 4 at: http://127.0.0.1:5000/#/experiments/2/runs/8daa48c4e7844a31a52f43adc7c7b5c5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8671
Средний Precision: 0.7339
Средний Recall: 0.8547
Средний F1-Score: 0.7739
Средний NDCG: 0.8582
Средний Precision: 0.7257
Средний Recall: 0.8445
Средний F1-Score: 0.7653

[I 2026-05-04 13:18:52,052] Trial 5 finished with value: 0.8626355186199738 and parameters: {'iterations': 650, 'depth': 4, 'learning_rate': 0.027010527749605478, 'l2_leaf_reg': 2.324672848950434}. Best is trial 4 with value: 0.8635031248671999.

Средний NDCG: 0.8626
Средний Precision: 0.7325
Средний Recall: 0.8495
Средний F1-Score: 0.7716
🏃 View run 5 at: http://127.0.0.1:5000/#/experiments/2/runs/7d89ace2b4e44cf088c3f085f1b33ce8
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8680
Средний Precision: 0.7519
Средний Recall: 0.8520
Средний F1-Score: 0.7845
Средний NDCG: 0.8583
Средний Precision: 0.7406
Средний Recall: 0.8419
Средний F1-Score: 0.7740

[I 2026-05-04 13:19:15,407] Trial 6 finished with value: 0.8632907212717209 and parameters: {'iterations': 500, 'depth': 9, 'learning_rate': 0.019721610970574007, 'l2_leaf_reg': 3.2676417657817622}. Best is trial 4 with value: 0.8635031248671999.

Средний NDCG: 0.8633
Средний Precision: 0.7507
Средний Recall: 0.8469
Средний F1-Score: 0.7825
🏃 View run 6 at: http://127.0.0.1:5000/#/experiments/2/runs/f00998d68631405783dcc3b419e4f8c6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8679
Средний Precision: 0.7419
Средний Recall: 0.8547
Средний F1-Score: 0.7791
Средний NDCG: 0.8579
Средний Precision: 0.7333
Средний Recall: 0.8442
Средний F1-Score: 0.7698

[I 2026-05-04 13:19:34,122] Trial 7 finished with value: 0.8624575680890215 and parameters: {'iterations': 650, 'depth': 3, 'learning_rate': 0.07896186801026692, 'l2_leaf_reg': 1.4808945119975185}. Best is trial 4 with value: 0.8635031248671999.

Средний NDCG: 0.8625
Средний Precision: 0.7381
Средний Recall: 0.8494
Средний F1-Score: 0.7754
🏃 View run 7 at: http://127.0.0.1:5000/#/experiments/2/runs/b4186462dd1f4a1f920f5a386a9e6172
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8676
Средний Precision: 0.7622
Средний Recall: 0.8495
Средний F1-Score: 0.7903
Средний NDCG: 0.8579
Средний Precision: 0.7531
Средний Recall: 0.8390
Средний F1-Score: 0.7806

[I 2026-05-04 13:19:49,827] Trial 8 finished with value: 0.8635646928784688 and parameters: {'iterations': 150, 'depth': 10, 'learning_rate': 0.26690431824362526, 'l2_leaf_reg': 6.432759992849893}. Best is trial 8 with value: 0.8635646928784688.

Средний NDCG: 0.8636
Средний Precision: 0.7623
Средний Recall: 0.8414
Средний F1-Score: 0.7870
🏃 View run 8 at: http://127.0.0.1:5000/#/experiments/2/runs/90293e774e0c4aebac54f7e010654606
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Средний NDCG: 0.8679
Средний Precision: 0.7368
Средний Recall: 0.8548
Средний F1-Score: 0.7756
Средний NDCG: 0.8574
Средний Precision: 0.7303
Средний Recall: 0.8448
Средний F1-Score: 0.7685

[I 2026-05-04 13:20:05,789] Trial 9 finished with value: 0.8622653555799666 and parameters: {'iterations': 350, 'depth': 3, 'learning_rate': 0.1024932221692416, 'l2_leaf_reg': 2.7551959649510764}. Best is trial 8 with value: 0.8635646928784688.

Средний NDCG: 0.8623
Средний Precision: 0.7385
Средний Recall: 0.8511
Средний F1-Score: 0.7763
🏃 View run 9 at: http://127.0.0.1:5000/#/experiments/2/runs/5fe25d654bb749048ccc24ad0d2f0faa
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
Number of finished trials: 10
Best params CatBoost: {'iterations': 150, 'depth': 10, 'learning_rate': 0.26690431824362526, 'l2_leaf_reg': 6.432759992849893}
Средний NDCG: 0.7812
Средний Precision: 0.6861
Средний Recall: 0.7574
Средний F1-Score: 0.7063

Successfully registered model 'best_optuna_catboost_als_tfidf_multilingual_e5_base'.
2026/05/04 13:20:13 INFO mlflow.store.model_registry.abstract_store: Waiting up to 60 seconds for model version to finish creation. Model name: best_optuna_catboost_als_tfidf_multilingual_e5_base, version 1

🏃 View run best_optuna_catboost_als_tfidf_multilingual_e5_base at: http://127.0.0.1:5000/#/experiments/2/runs/430ab10831c44219b5eed0185d21afbe
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

Created version '1' of model 'best_optuna_catboost_als_tfidf_multilingual_e5_base'.

## 9. Результаты

In [39]:
NDCG_TFIDF_BASELINE = 0.7817  # LightGBM + ALS + TF-IDF из ML_Experiments.ipynb

results_df = pd.DataFrame([
    {'Model': r['Model'], 'NDCG': r['NDCG'],
     'Precision': r.get('Precision'), 'Recall': r.get('Recall'), 'F1': r.get('F1')}
    for r in all_results
])
results_df['Delta vs TF-IDF'] = results_df['NDCG'] - NDCG_TFIDF_BASELINE
results_df = results_df.sort_values('NDCG', ascending=False).reset_index(drop=True)

print(f"Базовая линия TF-IDF: NDCG = {NDCG_TFIDF_BASELINE}")
print()
print(results_df[['Model','NDCG','Delta vs TF-IDF']].to_string(index=False))

Базовая линия TF-IDF: NDCG = 0.7817

                                                      Model     NDCG  Delta vs TF-IDF
                              ai-forever/sbert_large_nlu_ru 0.781438        -0.000262
                                   cointegrated/LaBSE-en-ru 0.781434        -0.000266
sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2 0.781407        -0.000293
                              intfloat/multilingual-e5-base 0.781204        -0.000496

In [41]:
def show_vacancy_predictions(pipeline, X_test, y_test, df,
                             n_top=10, vacancy_id=None, random_state=None):
    """
    Показывает предсказания пайплайна для выбранной вакансии из тест-сета.

    Args:
        pipeline     : обученный sklearn Pipeline
        X_test       : тестовые признаки (те же колонки, на которых обучался pipeline)
        y_test       : истинные метки
        df           : исходный датафрейм со всеми колонками (для отображения)
        n_top        : сколько топ-резюме показать
        vacancy_id   : None = случайная вакансия; иначе конкретный ID
        random_state : seed для воспроизводимости случайного выбора

    Returns:
        pd.DataFrame, отсортированный по pred_proba убыванием
    """
    df_test = df.loc[X_test.index].copy()
    df_test['target'] = y_test.values

    if vacancy_id is None:
        rng = np.random.RandomState(random_state)
        vacancy_id = rng.choice(df_test['vacancy_id'].unique())

    mask = df_test['vacancy_id'] == vacancy_id
    if not mask.any():
        print(f"[!] vacancy_id={vacancy_id} не найден в тестовой выборке.")
        return None

    df_vac = df_test[mask].copy()
    X_vac  = X_test.loc[df_vac.index]

    df_vac['pred_proba'] = pipeline.predict_proba(X_vac)[:, 1]
    df_vac = df_vac.sort_values('pred_proba', ascending=False).reset_index(drop=True)

    r0       = df_vac.iloc[0]
    vac_name = str(r0.get('vacancy_name', '—'))
    vac_desc = str(r0.get('vacancy_description', '—'))
    SEP, SEP2 = "=" * 90, "─" * 90

    print(SEP)
    print(f"  ВАКАНСИЯ : {vac_name}   [id={vacancy_id}]")
    print(f"  Опыт     : {r0.get('vacancy_experience','—')}  |  "
          f"Занятость : {r0.get('vacancy_employment','—')}  |  "
          f"График : {r0.get('vacancy_schedule','—')}")
    print(SEP2)
    print("  ОПИСАНИЕ ВАКАНСИИ:")
    for line in vac_desc[:1200].split('\n')[:25]:
        if line.strip():
            print(f"    {line.strip()}")
    if len(vac_desc) > 1200:
        print("    [... сокращено]")
    print(SEP)

    n_pos = int(df_vac['target'].sum())
    print(f"\n  ТОП-{n_top} из {len(df_vac)} кандидатов  "
          f"(всего реально подходящих в выборке: {n_pos})\n")

    for rank, (_, row) in enumerate(df_vac.head(n_top).iterrows(), 1):
        icon   = "✅" if row['target'] == 1 else "❌"
        exp    = str(row.get('resume_last_experience_description', '—'))
        skills = str(row.get('resume_skills', '—'))
        print(SEP2)
        print(f"  #{rank}  {icon}  score={row['pred_proba']:.4f}  "
              f"target={int(row['target'])}  [resume_id={row.get('resume_id','—')}]")
        print(f"  Должность : {row.get('resume_last_position','—')}")
        print(f"  Локация   : {row.get('resume_location','—')}  |  "
              f"Опыт: {row.get('resume_experience_months','—')} мес.")
        print(f"  Навыки    : {skills[:180]}{'...' if len(skills) > 180 else ''}")
        print(f"  Описание последнего места:")
        for line in exp[:700].split('\n')[:14]:
            if line.strip():
                print(f"    {line.strip()}")
        if len(exp) > 700:
            print("    [... сокращено]")
        print()

    print(SEP2)
    n_hit = int(df_vac.head(n_top)['target'].sum())
    print(f"\n  Попаданий в топ-{n_top}: {n_hit}/{n_top} ({100*n_hit//n_top}%)")
    print(f"  Всего релевантных в тест-сете для этой вакансии: {n_pos}\n")

    return df_vac

In [42]:
# ── Пример: лучший BERT-пайплайн ────────────────────────────────────────────
valid = [r for r in all_results if r.get('NDCG') is not None]
best  = max(valid, key=lambda r: r['NDCG'])
sim_col_best = best['sim_col']

# Добавляем BERT-колонку к тестовой матрице (BASE_FEATURES + als_score уже в X_test)
X_test_best = X_test[BASE_FEATURES + ['als_score']].copy()
X_test_best[sim_col_best] = df.loc[X_test.index, sim_col_best].values

print(f"Используемый пайплайн: {best['Model']}  NDCG={best['NDCG']:.4f}")
result = show_vacancy_predictions(best['Pipeline'], X_test_best, y_test, df,
                                  n_top=10, random_state=42)

# ── Сравнить другой пайплайн на той же вакансии: ────────────────────────────
# vacancy_id_to_compare = result.iloc[0]['vacancy_id']
# r2 = all_results[1]  # например, MiniLM
# X_test_r2 = X_test[BASE_FEATURES + ['als_score']].copy()
# X_test_r2[r2['sim_col']] = df.loc[X_test.index, r2['sim_col']].values
# show_vacancy_predictions(r2['Pipeline'], X_test_r2, y_test, df,
#                          n_top=10, vacancy_id=vacancy_id_to_compare)

Используемый пайплайн: ai-forever/sbert_large_nlu_ru  NDCG=0.7814
==========================================================================================
  ВАКАНСИЯ : Интернет-Маркетолог в Wildcrm   [id=126372900]
  Опыт     : От 3 до 6 лет  |  Занятость : Полная занятость  |  График : Удаленная работа
──────────────────────────────────────────────────────────────────────────────────────────
  ОПИСАНИЕ ВАКАНСИИ:
    О компании WildCRM — новый B2B-продукт для оцифровки финансовых данных маркетплейсов. Мы работаем с крупнейшими представителями рынка, такими как Wildberries и Ozon. Упрощаем финансовую отчетность и даем бизнесу возможность принимать data-driven решения. Мы хотим вырастить тебя с миддла до лида, который сможет возглавить направление интернет-маркетинга!   С нас:  Доход 130к- 150к Полная удаленка Рост от эксперта до лида команды Минимум бюрократии Поддержка коллег-маркетологов Команда исполнителей Атмосфера стартапа, стабильность зрелой компании    С тебя:  Запускать и масштабировать Telegram Ads Настраивать сквозную аналитику Быть &quot;руками&quot; CEO в создании и развитии продукта, управлять подрядчиками - командами разработки и дизайна и редакторским отделом Проводить кастдевы Работать на стыке маркетинга, продаж и продукта — выстраивать кросс-функциональное взаимодействие Внедрять культуру экспериментов: A/B-тесты креативов, аудиторий, гипотез Работать с CRM: настраивать цепочки коммуникаций, выстраивать омниканальную систему общения с пользователями Искать, как мы можем &quot;достучаться&quot; до максимального количества пользователей с минимальными затратами    Ты - наш канд
    [... сокращено]
==========================================================================================

  ТОП-10 из 15 кандидатов  (всего реально подходящих в выборке: 1)

──────────────────────────────────────────────────────────────────────────────────────────
  #1  ✅  score=0.9983  target=1  [resume_id=141504612]
  Должность : Product Owner/Project Manager/CEO
  Локация   : Москва  |  Опыт: 142.0 мес.
  Навыки    : ['Управление проектами', 'Управление командой', 'Product Management', 'Бизнес-анализ', 'Product Marketing', 'Presentation skills', 'Управление рисками', 'Time management', 'Start-u...
  Описание последнего места:
    Создал продуктовый бизнес, совмещенный с проектами по разработке и внедрению.
    Направление - Hardware, RnD, Системы мониторинга, Data Analysis, Частные облака/Виртуализация.
    Исполнял обязанности владельца продукта и руководителя проектов по разработке и внедрению, в т.ч.:
    • Создание и расширение продуктовой команды (разработчики back/front/mobile, QA, аналитики, DevOps, дизайнеры);
    • Оценка проектов, планирование ресурсов, контроль сроков, процессы сдачи приемки;
    • Составление и ведение бюджета CF/PL;
    • Подбор сотрудников и подрядчиков в основной (продуктовой и проектной) и операционной (бухгалтерия, юристы, АХО, HR) деятельности;
    • Внедрение и поддержка Scrum, фасилитация;
    • Взаимодействие
    [... сокращено]

──────────────────────────────────────────────────────────────────────────────────────────
  #2  ❌  score=0.9554  target=0  [resume_id=48884897]
  Должность : Маркетолог, исследователь, консультант, эксперт, руководитель
  Локация   : Москва  |  Опыт: 422.0 мес.
  Навыки    : ['B2B маркетинг', 'Стратегический маркетинг', 'Маркетинговые исследования', 'Разработка маркетинговой стратегии', 'Вывод продукта на рынок', 'Маркетинговое планирование', 'Подготов...
  Описание последнего места:
    СМОТРИТЕ МОЮ ЛИЧНУЮ ПРЕЗЕНТАЦИЮ:
    http://marketolog.biz/uploads/surin.pdf
    Выполнены многочисленные исследовательские и консалтинговые работы для различных компаний / брендов: Stockmann, EastLine (Домодедово), ИРИТО, Комупак, Императорский Фарфоровый Завод, Сладонеж, Insight-m, ММЦ, DOW, SPIRE, РУССКИЙ МИР, Оптимист, розничная сеть "Алексеевский", Геострой, BCS, ГУП МПТЦИР, Лакокраска, ИД Гребенников, AWT, Molson beer, Egger beer, Tokaji wines, Hochriegel sparkling wines, Post cereals, Merz Tetesept bath foam, Gap jeans, Aral oils and greases, Baygon и прочие.
    Маркетинговые исследования: организация и руководство исследовательским проектом полного цикла - цели и задачи, затраты и стоимо
    [... сокращено]

──────────────────────────────────────────────────────────────────────────────────────────
  #3  ❌  score=0.0024  target=0  [resume_id=107822043]
  Должность : Младший специалист по тестированию
  Локация   : Москва  |  Опыт: 90.0 мес.
  Навыки    : ['HTML', 'HTML5', 'CSS', 'Node.js', 'JavaScript', 'Git', 'MySQL', 'Java']
  Описание последнего места:
    Автотестирование

──────────────────────────────────────────────────────────────────────────────────────────
  #4  ❌  score=0.0014  target=0  [resume_id=61797615]
  Должность : Главный инженер
  Локация   : Москва  |  Опыт: 370.0 мес.
  Навыки    : ['Управление проектами', 'Производство строительно-монтажных работ', 'Инженерные системы', 'Управление производством', 'Управление персоналом', 'MS Project', 'Организаторские навык...
  Описание последнего места:
    Проектные работы, перевооружение и реконструкция, строительно-монтажные работы, пуско-наладочные рабо-ты, сервисное техническое обслуживание котельных, ИТП, ЦТП, наружные тепловые сети, внутренние технологи-ческие сети.
    Подразделение входящие в службу Главного инженера: Производственно-технический отдел, отдел снабжения, проектный отдел, монтажные участки, участки КИПиА.
    Обязанности:
    - участие в переговорах с потенциальными заказчиками, подготовка технических заданий на проектирование и строительство, подготовка графиков производства работ и финансирование;
    - подготовка технико-коммерческих предложений;
    - подготовка пакета документов для тендера;
    - разработка и контроль за выполнением
    [... сокращено]

──────────────────────────────────────────────────────────────────────────────────────────
  #5  ❌  score=0.0008  target=0  [resume_id=52062956]
  Должность : Начальник отдела поддержки пользователей
  Локация   : Москва  |  Опыт: 212.0 мес.
  Навыки    : ['Windows Server 2012', 'Mac Os', 'Техническая поддержка']
  Описание последнего места:
    Поддержка пользователей в офисе (Windows, MacOS около 500 машин)
    Установка, настройка, администрирование MS 2003-2008-2012 Server (AD, DNS, DHCP, Hyper-V, RDS, WDS, WSUS), резервирование данных
    Работа с Active Directory и групповыми политиками
    Настройка виртуализации Microsoft Hyper-V
    Планировать и разворачивать рабочие станции с помощью Microsoft Deployment Toolkit
    Перевел все клиентские компьютеры с Windows XP на Windows 7, провожу внедрение Windows 10
    Обеспечение централизованного управление антивирусными продуктами Eset
    Удаленное администрирование филиалов Банка
    Учет лицензий программных продуктов
    Подбор, закупка, настройка, обслуживание ПК и периферийного оборудования, диагнос
    [... сокращено]

──────────────────────────────────────────────────────────────────────────────────────────
  #6  ❌  score=0.0005  target=0  [resume_id=29969557]
  Должность : Ведущий Oracle-разработчик Департамента автоматизации бизнеса,  Team Lead направления: депозитные, комиссионные продукты розничного бизнеса
  Локация   : Москва  |  Опыт: 279.0 мес.
  Навыки    : ['имею способности и опыт организатора', 'Инициативность', 'Исполнительность', 'Ответственность', 'Целеустремленность']
  Описание последнего места:
    -	Управление командой (в подчинении 4 человека) по автоматизации банковского направления: депозитные, комиссионные продукты. Взаимодействие с бизнес-заказчиками в части согласования задач и утверждения квартального и месячного планов работ по автоматизации процессов в АБС Банка. Аналитика задач и БТ, поступающих от бизнес-заказчиков, определение трудозатрат и ресурсов на реализацию поступающих задач. Распределение и постановка задач для подчиненных сотрудников курируемого направления.
    -	Исполнение роли архитектора АБС Банка. Знания и опыт работы с продуктами как ФЛ, так и ЮЛ, позволяют выполнять роль аналитика.
    -	Разработка Oracle-функций, процедур, пакетов, триггеров, создание таблиц, предс
    [... сокращено]

──────────────────────────────────────────────────────────────────────────────────────────
  #7  ❌  score=0.0005  target=0  [resume_id=42542684]
  Должность : Marketing manager assistant
  Локация   : Moscow  |  Опыт: 135.0 мес.
  Навыки    : ['MS Office', 'Process improvement', 'Customer Service', 'Customer Relationship Management', 'Customer orientation', 'MS Excel', 'SAP ERP', 'HTML', 'CSS', 'Joomla CMS', 'Adobe Phot...
  Описание последнего места:
    - managing social networks (posting, working with the community, ads);
    - e-mail marketing;
    - data collection;
    - various tasks

──────────────────────────────────────────────────────────────────────────────────────────
  #8  ❌  score=0.0005  target=0  [resume_id=58838432]
  Должность : Transmission Networks Planning Engineer
  Локация   : Москва  |  Опыт: 200.0 мес.
  Навыки    : NDT
  Описание последнего места:
    •	Planning and optimization of the microwave and fibre network supporting both the mobile and fixed (voice and broadband) customers
    •	Significant contribution to the successful launch of the first 4G/LTE network in Cyprus

──────────────────────────────────────────────────────────────────────────────────────────
  #9  ❌  score=0.0004  target=0  [resume_id=85941829]
  Должность : Rerun Analyst
  Локация   : Москва  |  Опыт: 125.0 мес.
  Навыки    : ['1С: Предприятие', 'Пользователь ПК', 'Time management', 'Data Analysis', 'Market Research', 'MS Outlook', 'MS PowerPoint', 'Marketing Analysis', 'Presentation skills', 'План-факт...
  Описание последнего места:
    	Perform in-depth analytical review of sales in order to prepare reports for management
    	Analyze revenue for the day, residual inventory and profitability to assign products for night sales
    	Assess profitability and sales dynamics, review of return coefficients by product and factors affecting profitability
    	Forecast sales revenue and budgeting as well as subsequent review of actual versus projected
    	Ongoing interaction with other stakeholders to coordinate data collection, review and analysis

──────────────────────────────────────────────────────────────────────────────────────────
  #10  ❌  score=0.0003  target=0  [resume_id=94494969]
  Должность : Директор по подготовке производства
  Локация   : Самара  |  Опыт: 176.0 мес.
  Навыки    : ['Управление производством', 'Умение работать в команде', 'Автоматизация производства', 'Производственный контроль', 'Подбор производственного персонала', 'Умение принимать решения...
  Описание последнего места:
    - Обеспечение технологической подготовки и оснащения производства в соответствии с утвержденными планами и графиками, контроль, анализ и мониторинг выполнения директивных графиков на технологическую подготовку и изготовление первых комплектов ДСЕ новых(вновь осваиваемых/ не изготавливаемых более 5 лет) изделий(например: Д18Т; НК-32 сер.02; ТС-12М; НК-12МПТ);
    - Обеспечение взаимодействия между основным производством, инструментальным производством и службами предприятия в целях контроля выполнения директивных графиков ТПП.
    - Организация и обеспечение реализации проектов по новым(вновь осваиваемым/ не изготавливаемым более 5 лет) изделиям, взаимодействие с головной организацией, Заказчиком,
    [... сокращено]

──────────────────────────────────────────────────────────────────────────────────────────

  Попаданий в топ-10: 1/10 (10%)
  Всего релевантных в тест-сете для этой вакансии: 1