In [1]:
import re
import pandas as pd
import numpy as np
import nltk
import pymorphy3
import optuna
import mlflow
import pickle
import implicit

from implicit.als import AlternatingLeastSquares
from scipy.sparse import coo_matrix, csr_matrix, vstack
from optuna.integration.mlflow import MLflowCallback
from mlflow.utils.mlflow_tags import MLFLOW_PARENT_RUN_ID
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import ndcg_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from nltk.corpus import stopwords
from tqdm import tqdm
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from gensim.utils import simple_preprocess
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

import warnings
warnings.simplefilter('ignore', FutureWarning)

from sklearn import set_config
set_config(display='diagram')

In [2]:
RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

In [154]:
TRACKING_SERVER_HOST = "127.0.0.1"
TRACKING_SERVER_PORT = 5000

EXPERIMENT_NAME = "hr-ai-scout_test"

STUDY_DB_NAME = "sqlite:///local.study.test.db"

mlflow.set_tracking_uri(f"http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}")
mlflow.set_registry_uri(f"http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}")

# Load data

In [4]:
df = pd.read_csv('/Users/user/Documents/Magistracy/year_project/hr-ai-scout/total_df.csv')
df.head()

,vacancy_id,vacancy_name,vacancy_area,vacancy_experience,vacancy_employment,vacancy_schedule,vacancy_salary_from,vacancy_salary_to,vacancy_salary_currency,vacancy_salary_gross,...,resume_education,resume_courses,resume_salary,resume_age,resume_total_experience,resume_experience_months,resume_location,resume_gender,resume_applicant_status,target
0,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,300000.0,NaN,RUR,False,...,['Казанский Авиационный Институт'],NaN,NaN,65.0,19 лет,228.0,Москва,Мужчина,Рассматривает предложения,1
1,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,300000.0,NaN,RUR,False,...,"['ООО ""Открытый Учебный Центр СофтБаланс"", г. ...","['ООО ""Открытый Учебный Центр СофтБаланс"", г. ...",NaN,43.0,17 лет 4 месяца,208.0,Москва,Мужчина,Рассматривает предложения,1
2,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,300000.0,NaN,RUR,False,...,['Орский государственный педагогический инстит...,NaN,200 000 ₽ на руки,52.0,30 лет,360.0,Москва,Женщина,NaN,1
3,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,300000.0,NaN,RUR,False,...,['Красноярский государственный университет'],NaN,500 000 ₽ на руки,56.0,29 лет 8 месяцев,356.0,Красноярск,Мужчина,Рассматривает предложения,1
4,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,300000.0,NaN,RUR,False,...,['Белоруский Гос. Университет Информатики и Ра...,"['SAP CIS, SAP XI', 'Школа Логистики МАДИ', 'S...",NaN,48.0,25 лет 1 месяц,301.0,Moscow,Male,NaN,1

# Preprocessing

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">
В первую очередь уберем строки, где пропущены все ключевые значения в резюме:
</div>

In [5]:
t1 = df.shape[0]
df = df.dropna(subset= ["resume_education",
                        "resume_last_experience_description",
                        "resume_last_position",
                        "resume_last_company_experience_period",
                        "resume_total_experience",
                        "resume_experience_months",
                        "resume_location",
                        "resume_specialization",
                        # "resume_gender",
                        # "resume_title"
                       ], how="all")
t2 = df.shape[0]
print('Удалено ', t1 - t2 ,' строки')

Удалено  84  строки

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">
Удалим еще те строки, где случился технический сбой в парсинге, где у кандидата общий опыт есть, а последний опыт не указан (и наоборот):
</div>

In [6]:
t1 = df.shape[0]
df = df.loc[~(df["resume_total_experience"].notna()
        & df["resume_last_experience_description"].isna()
        & df["resume_last_position"].isna())]
t2 = df.shape[0]
print('Удалено ', t1 - t2 ,' строк')

Удалено  1543  строк

In [7]:
t1 = df.shape[0]
df = df.loc[~(df["resume_total_experience"].isna()
        & df["resume_last_experience_description"].notna()
        & df["resume_last_position"].notna())]
t2 = df.shape[0]
print('Удалено ', t1 - t2 ,' строк')

Удалено  0  строк

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">
Посмотрим на пропуски отдельно по категориальным и числовым признакам.
</div>

In [8]:
num_cols = df.select_dtypes(include=[np.number]).columns
cat_cols = df.select_dtypes(include=['object']).columns

In [9]:
df[cat_cols] = df[cat_cols].fillna('NDT')

In [10]:
df.loc[df['resume_experience_months'].isna(), 'resume_last_experience_description'].unique()

array(['NDT'], dtype=object)

In [11]:
df['resume_age'] = df['resume_age'].fillna(df['resume_age'].mean())
df['resume_experience_months'] = df['resume_experience_months'].fillna(0)

In [12]:
df = df.drop(['vacancy_salary_to', 'vacancy_salary_from',
              'vacancy_salary_currency', 'vacancy_salary_gross'], axis=1)

In [13]:
df.loc[df['resume_last_company_experience_period'] == 'NDT', 'resume_last_experience_description'].unique()

array(['NDT'], dtype=object)

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">
Преобразуем сначала ожидаемые зарплаты
</div>

In [14]:
df['resume_salary_split'] = df['resume_salary'].apply(lambda x: x.split())

df['salary_int'] = df['resume_salary_split'].apply(
    lambda x: int(''.join(part for part in x if re.fullmatch(r'\d+', part)))
              if any(re.fullmatch(r'\d+', part) for part in x)
              else np.nan
)

currency_symbols = ['₽', '$', '€', '₴', '₸', '₼', '₾', 'Br', "so'm"]

rates_rub = {
    "₽": 1.0,
    "$": 80.85,
    "€": 94.14,
    "₴": 1.94,
    "₸": 0.150,
    "₼": 47.8,
    "₾": 33.5,
    "Br": 28.7,
    "so'm": 0.0068
}

df['currency_symbol'] = df['resume_salary_split'].apply(
    lambda x: next((sym for sym in x if sym in currency_symbols), np.nan)
)

df['salary_converted'] = (df['salary_int'] * df['currency_symbol'].map(rates_rub)).fillna(0)

df['resume_salary'] = df['salary_converted']

df = df.drop(['resume_salary_split', 'salary_int', 'currency_symbol', 'salary_converted'], axis=1)

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">
Добавим дополнительный столбец с опытом работы в последней компании в месяцах для удобства
</div>

In [15]:
def experience_to_months(experience_text):
    months = 0
    # Опыт в годах
    years_match = re.search(r'(\d+)\s*год', experience_text)
    if years_match:
        months += int(years_match.group(1)) * 12

    years_match = re.search(r'(\d+)\s*лет', experience_text)
    if years_match:
        months += int(years_match.group(1)) * 12

    # Опыт в месяцах
    months_match = re.search(r'(\d+)\s*месяц', experience_text)
    if months_match:
        months += int(months_match.group(1))

    return months if months > 0 else np.nan

In [16]:
df['resume_last_company_experience_months'] = df['resume_last_company_experience_period'].apply(experience_to_months)

In [17]:
df.loc[df['resume_last_company_experience_period'] == 'NDT', 'resume_last_experience_description'].unique()

array(['NDT'], dtype=object)

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">
Т.к. в названии компании стоит NDT, можно столбец resume_last_company_experience_months заполнять нулевыми значениями.
</div>

In [18]:
df['resume_last_company_experience_months'] = df['resume_last_company_experience_months'].fillna(0)

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

- Ограничим выбросы по зарплате, потому что ровно одно значение по ожидаемой заработоной плате = 999,999,999 (смешно, но нет)

- Ограничим опыт общий и внутри одной компании до 720 месяцев (60 лет, ничего себе уже)

- Уберем возраст > 90, не ждем, что эти кандидаты находятся в поиске вакансии
</div>

In [19]:
df = df[~(df.resume_salary > 1e7)]
df.loc[df['resume_experience_months'] > 720, 'resume_experience_months'] = 720
df.loc[df['resume_last_company_experience_months'] > 720, 'resume_last_company_experience_months'] = 720
df = df[~(df.resume_age > 90)]

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

- Также уберем строки, где последний опыт кандидата больше, чем общий

- И где общий опыт кандидата +16 лет больше чем возраст (хоть так)

</div>

In [20]:
df = df[~(df.resume_experience_months < df.resume_last_company_experience_months)]
df = df[~(df.resume_age < (df.resume_experience_months // 12) + 16)]

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

Заменим текущий формат разброса полов в датасете на унифицированный

</div>

In [21]:
gender_map = {
    'Мужчина': 'Мужчина',
    'Male': 'Мужчина',
    'Женщина': 'Женщина',
    'Female': 'Женщина'
}

df['resume_gender'] = df['resume_gender'].apply(lambda x: gender_map[x] if x in gender_map else 'Неизвестно')

In [22]:
print(f"Датасет после очистки: {df.shape}")

Датасет после очистки: (325543, 25)

# Feature engineering

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">
Добавим признак матчинга локации вакансии и резюме

</div>

In [23]:
df['location_matching'] = df.apply(lambda row: 1 if row['vacancy_area'] == row['resume_location'] else 0, axis=1)

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

Сделаем новый признак, а именно посчитаем количество навыков кандидата, которые указаны в вакансии.

</div>

In [24]:
def resume_skill_count_in_vacancy(row):
    count = 0
    skill_list = row['resume_skills'].replace('[', '').replace(']', '').replace("'", "").split(', ')
    for i in skill_list:
        if i in row['vacancy_description']:
            count += 1
    return count

df['resume_skill_count_in_vacancy'] = df.apply(resume_skill_count_in_vacancy, axis=1)

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

Также посчитаем долю слов из последней должности в резюме, которые указаны в вакансии.

</div>

In [25]:
def last_position_in_vacancy(row):
    bow = []
    seps = [' ', '-', '_']
    for sep in seps:
        bow += row['resume_last_position'].split(sep=sep)
        bow = list(set(bow))
    
    c = 0
    for word in bow:
        if word in row['vacancy_description']:
            c +=1
    
    return c / len(bow)

In [26]:
df['last_position_in_vacancy'] = df.apply(last_position_in_vacancy, axis=1)

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

Теперь закодируем описание вакансии и последнего опыта работы и сравним через косинусное расстояние.

</div>

In [27]:
def preprocess_data(df):
    """Обработка пропущенных значений в текстовых полях"""
    print("Проверка пропущенных значений...")
    print(f"Пропуски в vacancy_description: {df['vacancy_description'].isna().sum()}")
    print(f"Пропуски в resume_last_experience_description: {df['resume_last_experience_description'].isna().sum()}")
    
    # Заполняем пропуски пустыми строками
    df['vacancy_description'] = df['vacancy_description'].fillna('')
    df['resume_last_experience_description'] = df['resume_last_experience_description'].fillna('')
    
    # Проверяем, что все значения теперь строковые
    df['vacancy_description'] = df['vacancy_description'].astype(str)
    df['resume_last_experience_description'] = df['resume_last_experience_description'].astype(str)
    
    return df

In [28]:
def save_results(df, output_file):
    """Сохранение результатов в CSV файл"""
    df.to_csv(output_file, index=False, encoding='utf-8')
    print(f"Результаты сохранены в файл: {output_file}")

In [29]:
def calculate_cosine_similarity(embeddings1, embeddings2):
    """Вычисление косинусного сходства между двумя наборами эмбеддингов"""
    similarities = []
    
    for i in tqdm(range(embeddings1.shape[0])):
        emb1_row = embeddings1[i]
        emb2_row = embeddings2[i]
        
        similarity = cosine_similarity(emb1_row, emb2_row)[0][0]
        similarities.append(similarity)
    
    return similarities

In [30]:
warnings.filterwarnings('ignore')

try:
    nltk.data.find('corpora/stopwords')
except LookupError:
    nltk.download('stopwords')

try:
    nltk.data.find('taggers/averaged_perceptron_tagger_ru')
except LookupError:
    nltk.download('averaged_perceptron_tagger_ru')

try:
    nltk.data.find('corpora/wordnet')
except LookupError:
    nltk.download('wordnet')

morph = pymorphy3.MorphAnalyzer()

[nltk_data] Downloading package wordnet to /Users/user/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [31]:
def lemmatize_russian(tokens):
    """Лемматизация русских слов"""
    lemmas = []
    for token in tokens:
        parsed = morph.parse(token)[0]  # Берем самый вероятный разбор
        lemmas.append(parsed.normal_form)
    return lemmas

In [32]:
def tokenize_and_lemmatize(text):
    """Токенизация текста с лемматизацией и удалением стоп-слов"""
    tokens = simple_preprocess(text, deacc=True, min_len=2)
    stop_words = set(stopwords.words('russian') + stopwords.words('english'))
    tokens = [token for token in tokens if token not in stop_words]
    lemmatized_tokens = lemmatize_russian(tokens)
    
    return lemmatized_tokens

In [33]:
def get_tfidf_embeddings(texts, vectorizer=None, fit=True):
    """Создание TF-IDF эмбеддингов для списка текстов с лемматизацией"""
    if fit:
        vectorizer = TfidfVectorizer(
            max_features=5000,
            min_df=2,
            max_df=0.8,
            ngram_range=(1, 2),
            tokenizer=tokenize_and_lemmatize,
            token_pattern=None,
            lowercase=False  # Уже сделано в токенизации
        )
        embeddings = vectorizer.fit_transform(texts)
    else:
        embeddings = vectorizer.transform(texts)
    
    return embeddings, vectorizer

In [34]:
def get_tfidf_vacancy_embeddings(df, vectorizer=None):
    """Создание эмбеддингов для уникальных вакансий с лемматизацией"""
    unique_vacancies = df[['vacancy_id', 'vacancy_description']].drop_duplicates()
    
    unique_embeddings, vectorizer = get_tfidf_embeddings(
        unique_vacancies['vacancy_description'].tolist(), 
        vectorizer=vectorizer, 
        fit=(vectorizer is None)
    )
    
    vacancy_embedding_dict = dict(zip(unique_vacancies['vacancy_id'], unique_embeddings))
    
    rows = []
    for vid in df['vacancy_id']:
        rows.append(vacancy_embedding_dict[vid])
    
    all_vacancy_embeddings = vstack(rows)
    
    return all_vacancy_embeddings, vectorizer

In [35]:
def process_similarity_scores_tfidf(df, vectorizer=None, fit=True):
    """Функция для вычисления схожести с использованием TF-IDF и лемматизации"""
    df = preprocess_data(df)
    
    print("Создание TF-IDF эмбеддингов для описаний опыта в резюме...")
    experience_embeddings, tfidf_vectorizer = get_tfidf_embeddings(df['resume_last_experience_description'].tolist(), vectorizer=vectorizer, fit=fit)
    
    print("Создание TF-IDF эмбеддингов для описаний вакансий...")
    vacancy_embeddings, _ = get_tfidf_vacancy_embeddings(df, vectorizer=tfidf_vectorizer)
    
    print("Вычисление косинусного сходства...")
    similarity_scores = calculate_cosine_similarity(vacancy_embeddings, experience_embeddings)
    
    df['similarity_score_tfidf'] = similarity_scores
    
    return df, tfidf_vectorizer

In [36]:
try:
    df_tfidf = pd.read_csv('description_df_with_scores_tfidf.csv')
except:
    df_tfidf = process_similarity_scores_tfidf(df.copy())
    save_results(df_tfidf, 'description_df_with_scores_tfidf.csv')

In [37]:
df = df.merge(df_tfidf)

In [38]:
df.head()

,vacancy_id,vacancy_name,vacancy_area,vacancy_experience,vacancy_employment,vacancy_schedule,vacancy_description,resume_id,resume_title,resume_specialization,...,resume_location,resume_gender,resume_applicant_status,target,resume_last_company_experience_months,location_matching,resume_skill_count_in_vacancy,last_position_in_vacancy,resume_skill_count,similarity_score_tfidf
0,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,"Привет!.redev — технологическая компания, созд...",6969174,ABAP-разработчик,"['Программист, разработчик']",...,Москва,Мужчина,Рассматривает предложения,1,76.0,1,3,0.666667,3,0.284047
1,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,"Привет!.redev — технологическая компания, созд...",9100077,"ABAP разработчик - SAP HCM, CRM, S/4HANA ERP(F...","['Программист, разработчик']",...,Москва,Мужчина,Рассматривает предложения,1,8.0,1,2,0.500000,2,0.308726
2,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,"Привет!.redev — технологическая компания, созд...",32644957,Разработчик ABAP,"['Программист, разработчик']",...,Москва,Женщина,NDT,1,136.0,1,1,0.000000,1,0.510093
3,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,"Привет!.redev — технологическая компания, созд...",27220466,ABAP-разработчик,"['Программист, разработчик']",...,Красноярск,Мужчина,Рассматривает предложения,1,135.0,0,2,0.333333,2,0.301062
4,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,"Привет!.redev — технологическая компания, созд...",7532708,ABAP разработчик. Senior ABAP Developer. SAP T...,"['Programmer, developer']",...,Moscow,Мужчина,NDT,1,0.0,0,2,0.600000,2,0.075429

# Train-test split

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

Добавим новые признаки в обучение и тестирование

</div>

In [39]:
features = [
    'vacancy_area',
    'vacancy_experience',
    'vacancy_employment', 
    'vacancy_schedule',
    # 'resume_specialization',
    # 'resume_education', 
    # 'resume_courses', 
    'resume_salary',
    'resume_age', 
    'resume_experience_months',
    'resume_location',
    'resume_gender', 
    'resume_applicant_status', 
    'resume_last_company_experience_months', 
    'location_matching',
    'resume_skill_count_in_vacancy',
    'last_position_in_vacancy',
    'similarity_score_tfidf'
]
df[features]

,vacancy_area,vacancy_experience,vacancy_employment,vacancy_schedule,resume_salary,resume_age,resume_experience_months,resume_location,resume_gender,resume_applicant_status,resume_last_company_experience_months,location_matching,resume_skill_count_in_vacancy,last_position_in_vacancy,similarity_score_tfidf
0,Москва,Более 6 лет,Полная занятость,Удаленная работа,0.0,65.000000,228.0,Москва,Мужчина,Рассматривает предложения,76.0,1,3,0.666667,0.284047
1,Москва,Более 6 лет,Полная занятость,Удаленная работа,0.0,43.000000,208.0,Москва,Мужчина,Рассматривает предложения,8.0,1,2,0.500000,0.308726
2,Москва,Более 6 лет,Полная занятость,Удаленная работа,200000.0,52.000000,360.0,Москва,Женщина,NDT,136.0,1,1,0.000000,0.510093
3,Москва,Более 6 лет,Полная занятость,Удаленная работа,500000.0,56.000000,356.0,Красноярск,Мужчина,Рассматривает предложения,135.0,0,2,0.333333,0.301062
4,Москва,Более 6 лет,Полная занятость,Удаленная работа,0.0,48.000000,301.0,Moscow,Мужчина,NDT,0.0,0,2,0.600000,0.075429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321637,Москва,От 3 до 6 лет,Полная занятость,Удаленная работа,242550.0,66.000000,521.0,Санкт-Петербург,Женщина,NDT,270.0,0,0,0.166667,0.072670
321638,Москва,От 3 до 6 лет,Полная занятость,Удаленная работа,0.0,40.000000,213.0,Москва,Мужчина,Активно ищет работу,35.0,1,0,0.000000,0.000000
321639,Москва,От 3 до 6 лет,Полная занятость,Удаленная работа,80000.0,44.060813,121.0,Москва,Мужчина,NDT,44.0,1,0,0.200000,0.047398
321640,Москва,От 3 до 6 лет,Полная занятость,Удаленная работа,0.0,32.000000,117.0,Москва,Женщина,NDT,96.0,1,0,0.200000,0.029086
321641,Москва,От 3 до 6 лет,Полная занятость,Удаленная работа,0.0,63.000000,513.0,Москва,Мужчина,NDT,262.0,1,0,0.000000,0.043344

In [40]:
numeric_features = df[features].select_dtypes(include=np.number).columns
categorical_features = df[features].select_dtypes(exclude=np.number).columns

In [41]:
X = df[features].copy()
y = df['target'].copy()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=RANDOM_STATE, stratify=y)

In [42]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((257313, 15), (64329, 15), (257313,), (64329,))

In [43]:
def calculate_metrics(df_test: pd.DataFrame) -> pd.DataFrame:
    ndcg_scores = []
    precision_scores = []
    recall_scores = []
    f1_scores = []
    vacancy_ids = df_test['vacancy_id'].unique()
    
    for vacancy_id in vacancy_ids:
        mask = df_test['vacancy_id'] == vacancy_id
        y_true = df_test.loc[mask, 'target'].values
        y_score = df_test.loc[mask, 'y_pred_proba'].values
        
        if len(y_true) <= 1:
            continue
        
        y_true_2d = y_true.reshape(1, -1)
        y_score_2d = y_score.reshape(1, -1)
        
        ndcg = ndcg_score(y_true_2d, y_score_2d)
        ndcg_scores.append(ndcg)
        
        y_pred_binary = (y_score >= 0.5).astype(int)
        
        precision = precision_score(y_true, y_pred_binary, zero_division=0)
        recall = recall_score(y_true, y_pred_binary, zero_division=0)
        f1 = f1_score(y_true, y_pred_binary, zero_division=0)
        
        precision_scores.append(precision)
        recall_scores.append(recall)
        f1_scores.append(f1)
    
    if ndcg_scores:
        print(f"Средний NDCG: {np.mean(ndcg_scores):.4f}")
        print(f"Средний Precision: {np.mean(precision_scores):.4f}")
        print(f"Средний Recall: {np.mean(recall_scores):.4f}")
        print(f"Средний F1-Score: {np.mean(f1_scores):.4f}")

        return np.mean(ndcg_scores), np.mean(precision_scores), np.mean(recall_scores), np.mean(f1_scores)
    else:
        print("Недостаточно данных для расчета метрик")

        return None, None, None, None

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

Обучим с подбором гиперпараметров `LogisticRegression`, как бейзлайн для сравнения с нелинейными моделями, `RandomForestClassifier`, как разновидность бэггинга, и три разные вида градиентного бустинга: `XGBClassifier`, `LGBMClassifier` и `CatBoostClassifier`.

</div>

# LogisticRegression

In [44]:
def objective(trial: optuna.Trial) -> float:
    params = {
        'model__C': trial.suggest_float('C', 1e-4, 1e4, log=True),
        'model__penalty': trial.suggest_categorical('penalty', ['l1', 'l2']),
        'model__solver': trial.suggest_categorical('solver', ['liblinear', 'saga'])
    }
    
    pipeline_lr_optuna = Pipeline([
        ('preprocessing', ColumnTransformer([
            ('numeric_scaling', StandardScaler(), numeric_features),
            ('categorical_encoding', OneHotEncoder(drop='first', handle_unknown='ignore'), categorical_features)
        ])),
        ('model', LogisticRegression(random_state=RANDOM_STATE, class_weight='balanced'))
    ])
    
    pipeline_lr_optuna.set_params(**params)
    
    kfold = StratifiedKFold(n_splits=3, shuffle=True, random_state=RANDOM_STATE)
    
    for train_idx, val_idx in kfold.split(X_train, y_train):
        X_fold_train, X_fold_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_fold_train, y_fold_val = y_train.iloc[train_idx], y_train.iloc[val_idx]
        
        pipeline_lr_optuna.fit(X_fold_train, y_fold_train)
        y_pred_proba = pipeline_lr_optuna.predict_proba(X_fold_val)
        

        df_val = df.loc[X_fold_val.index].copy()
        df_val['y_pred_proba'] = y_pred_proba[:, 1]
        
        ndcg, _, _, _ = calculate_metrics(df_val)

        trial.set_user_attr('pipeline_params', params)
    
    return ndcg

In [45]:
try:
    experiment_id = mlflow.get_experiment_by_name(EXPERIMENT_NAME).experiment_id
except:
    experiment_id = mlflow.create_experiment(EXPERIMENT_NAME)

RUN_NAME_OPTUNE = 'LogisticRegression_optuna'

with mlflow.start_run(run_name=RUN_NAME_OPTUNE, experiment_id=experiment_id) as run:
    run_id = run.info.run_id

🏃 View run LogisticRegression_optuna at: http://127.0.0.1:5000/#/experiments/4/runs/353d6e9787ba48e0bc3f7cd20b91d42c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

In [46]:
STUDY_NAME = "LogisticRegression_optuna"

mlflc = MLflowCallback(
    tracking_uri=f'http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}',
    metric_name="NDCG",
    create_experiment=False,
    mlflow_kwargs={'experiment_id': experiment_id, 'tags': {MLFLOW_PARENT_RUN_ID: run_id}}
)

In [47]:
study = optuna.create_study(direction='maximize', 
                            sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
                            study_name=STUDY_NAME,
                            storage=STUDY_DB_NAME,
                            load_if_exists=False)
study.optimize(objective, 
               n_trials=20, 
               callbacks=[mlflc]
              )
best_params_optuna = study.best_params

print(f"Number of finished trials: {len(study.trials)}")
print(f"Best params: {best_params_optuna}")

[I 2026-05-08 11:26:03,753] A new study created in RDB with name: LogisticRegression_optuna

Средний NDCG: 0.8300
Средний Precision: 0.5702
Средний Recall: 0.7888
Средний F1-Score: 0.6312
Средний NDCG: 0.8191
Средний Precision: 0.5614
Средний Recall: 0.7788
Средний F1-Score: 0.6213

[I 2026-05-08 11:26:41,360] Trial 0 finished with value: 0.8270779138714848 and parameters: {'C': 0.09915644566638405, 'penalty': 'l1', 'solver': 'liblinear'}. Best is trial 0 with value: 0.8270779138714848.

Средний NDCG: 0.8271
Средний Precision: 0.5711
Средний Recall: 0.7823
Средний F1-Score: 0.6304
🏃 View run 0 at: http://127.0.0.1:5000/#/experiments/4/runs/f99cbe5b71d24992a36b968a222caa5a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8260
Средний Precision: 0.5665
Средний Recall: 0.7821
Средний F1-Score: 0.6264
Средний NDCG: 0.8150
Средний Precision: 0.5597
Средний Recall: 0.7711
Средний F1-Score: 0.6166

[I 2026-05-08 11:27:00,499] Trial 1 finished with value: 0.8219108201868665 and parameters: {'C': 0.001769930294063334, 'penalty': 'l2', 'solver': 'saga'}. Best is trial 0 with value: 0.8270779138714848.

Средний NDCG: 0.8219
Средний Precision: 0.5667
Средний Recall: 0.7771
Средний F1-Score: 0.6251
🏃 View run 1 at: http://127.0.0.1:5000/#/experiments/4/runs/1dc08c4880d443e5ac22ee8bfdbbf2c1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8195
Средний Precision: 0.5155
Средний Recall: 0.7796
Средний F1-Score: 0.5887
Средний NDCG: 0.8106
Средний Precision: 0.5041
Средний Recall: 0.7665
Средний F1-Score: 0.5753

[I 2026-05-08 11:27:13,284] Trial 2 finished with value: 0.8157981400733071 and parameters: {'C': 0.00014610865886287216, 'penalty': 'l1', 'solver': 'liblinear'}. Best is trial 0 with value: 0.8270779138714848.

Средний NDCG: 0.8158
Средний Precision: 0.5076
Средний Recall: 0.7715
Средний F1-Score: 0.5811
🏃 View run 2 at: http://127.0.0.1:5000/#/experiments/4/runs/43096f32d2784515ab790a06be2d8231
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8266
Средний Precision: 0.5666
Средний Recall: 0.7838
Средний F1-Score: 0.6272
Средний NDCG: 0.8153
Средний Precision: 0.5598
Средний Recall: 0.7739
Средний F1-Score: 0.6176

[I 2026-05-08 11:27:26,055] Trial 3 finished with value: 0.8226595212568117 and parameters: {'C': 0.0029324868872723777, 'penalty': 'l2', 'solver': 'liblinear'}. Best is trial 0 with value: 0.8270779138714848.

Средний NDCG: 0.8227
Средний Precision: 0.5661
Средний Recall: 0.7795
Средний F1-Score: 0.6257
🏃 View run 3 at: http://127.0.0.1:5000/#/experiments/4/runs/57fd27c4e1ac4fbfb7431f80f6881a54
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8304
Средний Precision: 0.5688
Средний Recall: 0.7896
Средний F1-Score: 0.6306
Средний NDCG: 0.8191
Средний Precision: 0.5620
Средний Recall: 0.7794
Средний F1-Score: 0.6220

[I 2026-05-08 11:27:44,753] Trial 4 finished with value: 0.8269999989560172 and parameters: {'C': 7.849159562555087, 'penalty': 'l2', 'solver': 'saga'}. Best is trial 0 with value: 0.8270779138714848.

Средний NDCG: 0.8270
Средний Precision: 0.5715
Средний Recall: 0.7817
Средний F1-Score: 0.6303
🏃 View run 4 at: http://127.0.0.1:5000/#/experiments/4/runs/6382f9ab78d04de39b8c1c3def2fc9e4
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8297
Средний Precision: 0.5677
Средний Recall: 0.7879
Средний F1-Score: 0.6293
Средний NDCG: 0.8188
Средний Precision: 0.5624
Средний Recall: 0.7794
Средний F1-Score: 0.6223

[I 2026-05-08 11:28:02,262] Trial 5 finished with value: 0.8264039116629283 and parameters: {'C': 191.16469627784286, 'penalty': 'l2', 'solver': 'liblinear'}. Best is trial 0 with value: 0.8270779138714848.

Средний NDCG: 0.8264
Средний Precision: 0.5702
Средний Recall: 0.7811
Средний F1-Score: 0.6294
🏃 View run 5 at: http://127.0.0.1:5000/#/experiments/4/runs/d1de56a66afc42a484429e2852699d45
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8304
Средний Precision: 0.5688
Средний Recall: 0.7896
Средний F1-Score: 0.6306
Средний NDCG: 0.8191
Средний Precision: 0.5618
Средний Recall: 0.7795
Средний F1-Score: 0.6219

[I 2026-05-08 11:29:46,124] Trial 6 finished with value: 0.8269902824978899 and parameters: {'C': 7.250347382396651, 'penalty': 'l1', 'solver': 'saga'}. Best is trial 0 with value: 0.8270779138714848.

Средний NDCG: 0.8270
Средний Precision: 0.5716
Средний Recall: 0.7817
Средний F1-Score: 0.6304
🏃 View run 6 at: http://127.0.0.1:5000/#/experiments/4/runs/0bd49eb63cb844038ee13ed9cad0dfec
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8296
Средний Precision: 0.5676
Средний Recall: 0.7878
Средний F1-Score: 0.6292
Средний NDCG: 0.8187
Средний Precision: 0.5622
Средний Recall: 0.7792
Средний F1-Score: 0.6222

[I 2026-05-08 11:32:36,092] Trial 7 finished with value: 0.8259835018149861 and parameters: {'C': 293.21000471832957, 'penalty': 'l1', 'solver': 'liblinear'}. Best is trial 0 with value: 0.8270779138714848.

Средний NDCG: 0.8260
Средний Precision: 0.5701
Средний Recall: 0.7807
Средний F1-Score: 0.6292
🏃 View run 7 at: http://127.0.0.1:5000/#/experiments/4/runs/26ca52b6d40544e7b0ffc8462450f98d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8224
Средний Precision: 0.5508
Средний Recall: 0.7776
Средний F1-Score: 0.6133
Средний NDCG: 0.8117
Средний Precision: 0.5405
Средний Recall: 0.7621
Средний F1-Score: 0.6000

[I 2026-05-08 11:32:49,733] Trial 8 finished with value: 0.8184566752240834 and parameters: {'C': 0.000946903842177445, 'penalty': 'l1', 'solver': 'liblinear'}. Best is trial 0 with value: 0.8270779138714848.

Средний NDCG: 0.8185
Средний Precision: 0.5486
Средний Recall: 0.7686
Средний F1-Score: 0.6097
🏃 View run 8 at: http://127.0.0.1:5000/#/experiments/4/runs/008930dcd60d4ec5936e3ec6cd02f5da
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8299
Средний Precision: 0.5677
Средний Recall: 0.7880
Средний F1-Score: 0.6293
Средний NDCG: 0.8189
Средний Precision: 0.5618
Средний Recall: 0.7793
Средний F1-Score: 0.6220

[I 2026-05-08 11:33:05,350] Trial 9 finished with value: 0.8265828725577935 and parameters: {'C': 19.960815242513796, 'penalty': 'l2', 'solver': 'liblinear'}. Best is trial 0 with value: 0.8270779138714848.

Средний NDCG: 0.8266
Средний Precision: 0.5706
Средний Recall: 0.7817
Средний F1-Score: 0.6298
🏃 View run 9 at: http://127.0.0.1:5000/#/experiments/4/runs/1386f46772aa4715b77459c1150656ce
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Number of finished trials: 10
Best params: {'C': 0.09915644566638405, 'penalty': 'l1', 'solver': 'liblinear'}

In [48]:
study.best_trial.user_attrs['pipeline_params']

{'model__C': 0.09915644566638405,
 'model__penalty': 'l1',
 'model__solver': 'liblinear'}

In [49]:
pipeline_lr_best_optuna = Pipeline([
    ('preprocessing', ColumnTransformer([
        ('numeric_scaling', StandardScaler(), numeric_features),
        ('categorical_encoding', OneHotEncoder(drop='first', handle_unknown='ignore'), categorical_features)
    ])),
    ('model', LogisticRegression(random_state=RANDOM_STATE))
])

pipeline_lr_best_optuna.set_params(**study.best_trial.user_attrs['pipeline_params'])
pipeline_lr_best_optuna.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('numeric_scaling',
                                                  StandardScaler(),
                                                  Index(['resume_salary', 'resume_age', 'resume_experience_months',
       'resume_last_company_experience_months', 'location_matching',
       'resume_skill_count_in_vacancy', 'last_position_in_vacancy',
       'similarity_score_tfidf'],
      dtype='object')),
                                                 ('categorical_encoding',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  Index(['vacancy_area', 'vacancy_experience', 'vacancy_employment',
       'vacancy_schedule', 'resume_location', 'resume_gender',
       'resume_applicant_status'],
      dtype='object'))])),
                ('model',
                 LogisticRegression(C=0.09915644566638405, penalty='l1',
                                    random_state=42, solver='liblinear'))])

In [50]:
y_pred_proba = pipeline_lr_best_optuna.predict_proba(X_test)

df_test = df.loc[X_test.index].copy()
df_test['y_pred_proba'] = y_pred_proba[:, 1]

In [51]:
ndcg_lr, precision_lr, recall_lr, f1_lr = calculate_metrics(df_test)

metrics_lr = {
    'NDCG': ndcg_lr,
    'Precision': precision_lr,
    'Recall': recall_lr,
    'F1': f1_lr
}

Средний NDCG: 0.7513
Средний Precision: 0.6370
Средний Recall: 0.5964
Средний F1-Score: 0.5999

In [52]:
RUN_NAME = "best_optuna_lr" 
REGISTRY_MODEL_NAME = "best_optuna_lr"

In [53]:
signature = mlflow.models.infer_signature(X_test, y_test)
input_example = X_test[:10]
code_paths = ["ML_Experiments.ipynb"]

try:
    experiment_id = mlflow.get_experiment_by_name(EXPERIMENT_NAME).experiment_id
except:
    experiment_id = mlflow.create_experiment(EXPERIMENT_NAME)

with mlflow.start_run(run_name=RUN_NAME, experiment_id=experiment_id) as run:
    run_id = run.info.run_id

    lr_info = mlflow.sklearn.log_model(sk_model=pipeline_lr_best_optuna, 
                                       artifact_path='best_optuna_lr',
                                       registered_model_name=REGISTRY_MODEL_NAME,
                                       input_example=input_example,
                                       code_paths=code_paths,
                                       await_registration_for=60
                                      )
    mlflow.log_metrics(metrics_lr)
    mlflow.log_params(best_params_optuna)

Registered model 'best_optuna_lr' already exists. Creating a new version of this model...
2026/05/08 11:33:15 INFO mlflow.store.model_registry.abstract_store: Waiting up to 60 seconds for model version to finish creation. Model name: best_optuna_lr, version 9

🏃 View run best_optuna_lr at: http://127.0.0.1:5000/#/experiments/4/runs/4f8cdfb40f984d02a0fa4c7e537d2893
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

Created version '9' of model 'best_optuna_lr'.

# RandomForestClassifier

In [54]:
def objective(trial: optuna.Trial) -> float:
    params = {
        'model__n_estimators': trial.suggest_int('n_estimators', 100, 1000, step=50),
        'model__max_depth': trial.suggest_int('max_depth', 3, 30),
        'model__min_samples_split': trial.suggest_int('min_samples_split', 2, 20),
        'model__min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 20)
    }
    
    pipeline_rf = Pipeline([
        ('preprocessing', ColumnTransformer([
            ('numeric_scaling', StandardScaler(), numeric_features),
            ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
        ])),
        ('model', RandomForestClassifier(random_state=RANDOM_STATE, class_weight='balanced'))
    ])
    
    pipeline_rf.set_params(**params)
    
    kfold = StratifiedKFold(n_splits=3, shuffle=True, random_state=RANDOM_STATE)
    
    for train_idx, val_idx in kfold.split(X_train, y_train):
        X_fold_train, X_fold_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_fold_train, y_fold_val = y_train.iloc[train_idx], y_train.iloc[val_idx]
        
        pipeline_rf.fit(X_fold_train, y_fold_train)
        y_pred_proba = pipeline_rf.predict_proba(X_fold_val)
        

        df_val = df.loc[X_fold_val.index].copy()
        df_val['y_pred_proba'] = y_pred_proba[:, 1]
        
        ndcg, _, _, _ = calculate_metrics(df_val)

        trial.set_user_attr('pipeline_params', params)
    
    return ndcg

In [55]:
try:
    experiment_id = mlflow.get_experiment_by_name(EXPERIMENT_NAME).experiment_id
except:
    experiment_id = mlflow.create_experiment(EXPERIMENT_NAME)

RUN_NAME_OPTUNE = 'RandomForestClassifier_optuna'

with mlflow.start_run(run_name=RUN_NAME_OPTUNE, experiment_id=experiment_id) as run:
    run_id = run.info.run_id

🏃 View run RandomForestClassifier_optuna at: http://127.0.0.1:5000/#/experiments/4/runs/16e5d0bba6484eb1b33d9d6cf6a49720
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

In [56]:
STUDY_NAME = "RandomForestClassifier_optuna"

mlflc = MLflowCallback(
    tracking_uri=f'http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}',
    metric_name="NDCG",
    create_experiment=False,
    mlflow_kwargs={'experiment_id': experiment_id, 'tags': {MLFLOW_PARENT_RUN_ID: run_id}}
)

In [57]:
study = optuna.create_study(direction='maximize', 
                            sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
                            study_name=STUDY_NAME,
                            storage=STUDY_DB_NAME,
                            load_if_exists=False)
study.optimize(objective, 
               n_trials=20, 
               callbacks=[mlflc]
              )
best_params_optuna = study.best_params

print(f"Number of finished trials: {len(study.trials)}")
print(f"Best params: {best_params_optuna}")

[I 2026-05-08 11:33:15,453] A new study created in RDB with name: RandomForestClassifier_optuna

Средний NDCG: 0.8564
Средний Precision: 0.6951
Средний Recall: 0.8292
Средний F1-Score: 0.7345
Средний NDCG: 0.8447
Средний Precision: 0.6848
Средний Recall: 0.8185
Средний F1-Score: 0.7240

[I 2026-05-08 11:34:58,387] Trial 0 finished with value: 0.8523321436552282 and parameters: {'n_estimators': 450, 'max_depth': 29, 'min_samples_split': 15, 'min_samples_leaf': 12}. Best is trial 0 with value: 0.8523321436552282.

Средний NDCG: 0.8523
Средний Precision: 0.6910
Средний Recall: 0.8239
Средний F1-Score: 0.7303
🏃 View run 0 at: http://127.0.0.1:5000/#/experiments/4/runs/ce8cae4ebbde4b13ac84f7e8c00aa25e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8332
Средний Precision: 0.6222
Средний Recall: 0.7997
Средний F1-Score: 0.6726
Средний NDCG: 0.8211
Средний Precision: 0.5975
Средний Recall: 0.7907
Средний F1-Score: 0.6518

[I 2026-05-08 11:35:32,928] Trial 1 finished with value: 0.8295085461850679 and parameters: {'n_estimators': 200, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 18}. Best is trial 0 with value: 0.8523321436552282.

Средний NDCG: 0.8295
Средний Precision: 0.6107
Средний Recall: 0.7980
Средний F1-Score: 0.6638
🏃 View run 1 at: http://127.0.0.1:5000/#/experiments/4/runs/19af7369f2c34b12a8c495b82c19f416
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8542
Средний Precision: 0.6749
Средний Recall: 0.8332
Средний F1-Score: 0.7225
Средний NDCG: 0.8431
Средний Precision: 0.6603
Средний Recall: 0.8219
Средний F1-Score: 0.7091

[I 2026-05-08 11:37:53,083] Trial 2 finished with value: 0.8504921953023532 and parameters: {'n_estimators': 650, 'max_depth': 22, 'min_samples_split': 2, 'min_samples_leaf': 20}. Best is trial 0 with value: 0.8523321436552282.

Средний NDCG: 0.8505
Средний Precision: 0.6704
Средний Recall: 0.8263
Средний F1-Score: 0.7174
🏃 View run 2 at: http://127.0.0.1:5000/#/experiments/4/runs/424b6eb7867e48059505915482b62fd9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8407
Средний Precision: 0.6366
Средний Recall: 0.8081
Средний F1-Score: 0.6858
Средний NDCG: 0.8272
Средний Precision: 0.6154
Средний Recall: 0.7955
Средний F1-Score: 0.6663

[I 2026-05-08 11:39:50,495] Trial 3 finished with value: 0.8367149550025557 and parameters: {'n_estimators': 850, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.8523321436552282.

Средний NDCG: 0.8367
Средний Precision: 0.6321
Средний Recall: 0.8021
Средний F1-Score: 0.6807
🏃 View run 3 at: http://127.0.0.1:5000/#/experiments/4/runs/1f63e8254b7a45beb9103460c048e4eb
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8578
Средний Precision: 0.7195
Средний Recall: 0.8227
Средний F1-Score: 0.7480
Средний NDCG: 0.8458
Средний Precision: 0.7089
Средний Recall: 0.8107
Средний F1-Score: 0.7367

[I 2026-05-08 11:41:11,467] Trial 4 finished with value: 0.8538255587853936 and parameters: {'n_estimators': 350, 'max_depth': 17, 'min_samples_split': 10, 'min_samples_leaf': 6}. Best is trial 4 with value: 0.8538255587853936.

Средний NDCG: 0.8538
Средний Precision: 0.7147
Средний Recall: 0.8168
Средний F1-Score: 0.7427
🏃 View run 4 at: http://127.0.0.1:5000/#/experiments/4/runs/695180f52f694b1c9e47f04b154547da
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8277
Средний Precision: 0.6095
Средний Recall: 0.7963
Средний F1-Score: 0.6626
Средний NDCG: 0.8131
Средний Precision: 0.5863
Средний Recall: 0.7872
Средний F1-Score: 0.6425

[I 2026-05-08 11:42:27,172] Trial 5 finished with value: 0.822946864692375 and parameters: {'n_estimators': 650, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 8}. Best is trial 4 with value: 0.8538255587853936.

Средний NDCG: 0.8229
Средний Precision: 0.6000
Средний Recall: 0.7956
Средний F1-Score: 0.6559
🏃 View run 5 at: http://127.0.0.1:5000/#/experiments/4/runs/62341480c2f247bfb2440870e3f6b187
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8565
Средний Precision: 0.6990
Средний Recall: 0.8279
Средний F1-Score: 0.7366
Средний NDCG: 0.8450
Средний Precision: 0.6890
Средний Recall: 0.8183
Средний F1-Score: 0.7268

[I 2026-05-08 11:44:20,020] Trial 6 finished with value: 0.8530654852788387 and parameters: {'n_estimators': 500, 'max_depth': 24, 'min_samples_split': 5, 'min_samples_leaf': 11}. Best is trial 4 with value: 0.8538255587853936.

Средний NDCG: 0.8531
Средний Precision: 0.6929
Средний Recall: 0.8232
Средний F1-Score: 0.7312
🏃 View run 6 at: http://127.0.0.1:5000/#/experiments/4/runs/6185d913ee944fd7b0178be9a296f751
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8121
Средний Precision: 0.5637
Средний Recall: 0.7881
Средний F1-Score: 0.6272
Средний NDCG: 0.7965
Средний Precision: 0.5436
Средний Recall: 0.7743
Средний F1-Score: 0.6076

[I 2026-05-08 11:45:19,245] Trial 7 finished with value: 0.8051316004865074 and parameters: {'n_estimators': 650, 'max_depth': 4, 'min_samples_split': 13, 'min_samples_leaf': 4}. Best is trial 4 with value: 0.8538255587853936.

Средний NDCG: 0.8051
Средний Precision: 0.5594
Средний Recall: 0.7823
Средний F1-Score: 0.6226
🏃 View run 7 at: http://127.0.0.1:5000/#/experiments/4/runs/005dca9820554f67b350a3a22166f71a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8542
Средний Precision: 0.6828
Средний Recall: 0.8311
Средний F1-Score: 0.7270
Средний NDCG: 0.8434
Средний Precision: 0.6663
Средний Recall: 0.8208
Средний F1-Score: 0.7128

[I 2026-05-08 11:46:05,501] Trial 8 finished with value: 0.850158502450918 and parameters: {'n_estimators': 150, 'max_depth': 29, 'min_samples_split': 20, 'min_samples_leaf': 17}. Best is trial 4 with value: 0.8538255587853936.

Средний NDCG: 0.8502
Средний Precision: 0.6763
Средний Recall: 0.8267
Средний F1-Score: 0.7220
🏃 View run 8 at: http://127.0.0.1:5000/#/experiments/4/runs/4b88ce85000d47c5870429a70d1f41db
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8178
Средний Precision: 0.5822
Средний Recall: 0.7942
Средний F1-Score: 0.6428
Средний NDCG: 0.8031
Средний Precision: 0.5604
Средний Recall: 0.7830
Средний F1-Score: 0.6222

[I 2026-05-08 11:46:49,154] Trial 9 finished with value: 0.8127352825473224 and parameters: {'n_estimators': 350, 'max_depth': 5, 'min_samples_split': 15, 'min_samples_leaf': 9}. Best is trial 4 with value: 0.8538255587853936.

Средний NDCG: 0.8127
Средний Precision: 0.5802
Средний Recall: 0.7886
Средний F1-Score: 0.6395
🏃 View run 9 at: http://127.0.0.1:5000/#/experiments/4/runs/86a864dd03a34acdacce58943e98f363
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Number of finished trials: 10
Best params: {'n_estimators': 350, 'max_depth': 17, 'min_samples_split': 10, 'min_samples_leaf': 6}

In [58]:
study.best_trial.user_attrs['pipeline_params']

{'model__n_estimators': 350,
 'model__max_depth': 17,
 'model__min_samples_split': 10,
 'model__min_samples_leaf': 6}

In [59]:
pipeline_rf_best_optuna = Pipeline([
        ('preprocessing', ColumnTransformer([
            ('numeric_scaling', StandardScaler(), numeric_features),
            ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
        ])),
        ('model', RandomForestClassifier(random_state=RANDOM_STATE, class_weight='balanced'))
    ])

pipeline_rf_best_optuna.set_params(**study.best_trial.user_attrs['pipeline_params'])
pipeline_rf_best_optuna.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('numeric_scaling',
                                                  StandardScaler(),
                                                  Index(['resume_salary', 'resume_age', 'resume_experience_months',
       'resume_last_company_experience_months', 'location_matching',
       'resume_skill_count_in_vacancy', 'last_position_in_vacancy',
       'similarity_score_tfidf'],
      dtype='object')),
                                                 ('categorical_encoding',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  Index(['vacancy_area', 'vacancy_experience', 'vacancy_employment',
       'vacancy_schedule', 'resume_location', 'resume_gender',
       'resume_applicant_status'],
      dtype='object'))])),
                ('model',
                 RandomForestClassifier(class_weight='balanced', max_depth=17,
                                        min_samples_leaf=6,
                                        min_samples_split=10, n_estimators=350,
                                        random_state=42))])

In [60]:
y_pred_proba = pipeline_rf_best_optuna.predict_proba(X_test)

df_test = df.loc[X_test.index].copy()
df_test['y_pred_proba'] = y_pred_proba[:, 1]

In [61]:
ndcg_rf, precision_rf, recall_rf, f1_rf = calculate_metrics(df_test)

metrics_rf = {
    'NDCG': ndcg_rf,
    'Precision': precision_rf,
    'Recall': recall_rf,
    'F1': f1_rf
}

Средний NDCG: 0.7757
Средний Precision: 0.6606
Средний Recall: 0.7424
Средний F1-Score: 0.6824

In [62]:
RUN_NAME = "best_optuna_rf" 
REGISTRY_MODEL_NAME = "best_optuna_rf"

In [63]:
signature = mlflow.models.infer_signature(X_test, y_test)
input_example = X_test[:10]
code_paths = ["ML_Experiments.ipynb"]

try:
    experiment_id = mlflow.get_experiment_by_name(EXPERIMENT_NAME).experiment_id
except:
    experiment_id = mlflow.create_experiment(EXPERIMENT_NAME)

with mlflow.start_run(run_name=RUN_NAME, experiment_id=experiment_id) as run:
    run_id = run.info.run_id

    lr_info = mlflow.sklearn.log_model(sk_model=pipeline_rf_best_optuna, 
                                       artifact_path='best_optuna_rf',
                                       registered_model_name=REGISTRY_MODEL_NAME,
                                       input_example=input_example,
                                       code_paths=code_paths,
                                       await_registration_for=60
                                      )
    mlflow.log_metrics(metrics_rf)
    mlflow.log_params(best_params_optuna)

Registered model 'best_optuna_rf' already exists. Creating a new version of this model...
2026/05/08 11:47:30 INFO mlflow.store.model_registry.abstract_store: Waiting up to 60 seconds for model version to finish creation. Model name: best_optuna_rf, version 7

🏃 View run best_optuna_rf at: http://127.0.0.1:5000/#/experiments/4/runs/c83f2aeeaf0a405380dd69b1991729f1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

Created version '7' of model 'best_optuna_rf'.

# XGBClassifier

In [64]:
def objective_xgb(trial: optuna.Trial) -> float:
    params = {
        'model__n_estimators': trial.suggest_int('n_estimators', 100, 1000, step=50),
        'model__max_depth': trial.suggest_int('max_depth', 3, 15),
        'model__learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'model__min_child_weight': trial.suggest_int('min_child_weight', 1, 10)
    }
    
    pipeline_xgb = Pipeline([
        ('preprocessing', ColumnTransformer([
            ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
        ], remainder='passthrough')),
        ('model', XGBClassifier(
            random_state=RANDOM_STATE, 
            eval_metric='logloss', 
            use_label_encoder=False, 
            verbosity=0,
            scale_pos_weight=(len(y_train) - sum(y_train)) / sum(y_train)
        ))
    ])
    
    pipeline_xgb.set_params(**params)
    
    kfold = StratifiedKFold(n_splits=3, shuffle=True, random_state=RANDOM_STATE)
    
    for train_idx, val_idx in kfold.split(X_train, y_train):
        X_fold_train, X_fold_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_fold_train, y_fold_val = y_train.iloc[train_idx], y_train.iloc[val_idx]
        
        pipeline_xgb.fit(X_fold_train, y_fold_train)
        y_pred_proba = pipeline_xgb.predict_proba(X_fold_val)
        
        df_val = df.loc[X_fold_val.index].copy()
        df_val['y_pred_proba'] = y_pred_proba[:, 1]
        
        ndcg, _, _, _ = calculate_metrics(df_val)
        
        trial.set_user_attr('pipeline_params', params)
    
    return ndcg

In [65]:
try:
    experiment_id = mlflow.get_experiment_by_name(EXPERIMENT_NAME).experiment_id
except:
    experiment_id = mlflow.create_experiment(EXPERIMENT_NAME)

RUN_NAME_OPTUNE_XGB = 'XGBClassifier_optuna'

with mlflow.start_run(run_name=RUN_NAME_OPTUNE_XGB, experiment_id=experiment_id) as run:
    run_id_xgb = run.info.run_id

🏃 View run XGBClassifier_optuna at: http://127.0.0.1:5000/#/experiments/4/runs/9c59d66473c9414ba450cd7ad562510e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

In [66]:
STUDY_NAME_XGB = "XGBClassifier_optuna"

mlflc_xgb = MLflowCallback(
    tracking_uri=f'http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}',
    metric_name="NDCG",
    create_experiment=False,
    mlflow_kwargs={'experiment_id': experiment_id, 'tags': {MLFLOW_PARENT_RUN_ID: run_id_xgb}}
)

In [67]:
study_xgb = optuna.create_study(direction='maximize', 
                                sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
                                study_name=STUDY_NAME_XGB,
                                storage=STUDY_DB_NAME,
                                load_if_exists=False)

study_xgb.optimize(objective_xgb, 
                   n_trials=20, 
                   callbacks=[mlflc_xgb]
                  )

best_params_xgb = study_xgb.best_params
print(f"Number of finished trials: {len(study_xgb.trials)}")
print(f"Best params XGBoost: {best_params_xgb}")

[I 2026-05-08 11:47:30,750] A new study created in RDB with name: XGBClassifier_optuna

Средний NDCG: 0.8600
Средний Precision: 0.7702
Средний Recall: 0.8029
Средний F1-Score: 0.7708
Средний NDCG: 0.8474
Средний Precision: 0.7509
Средний Recall: 0.7874
Средний F1-Score: 0.7534

[I 2026-05-08 11:47:51,625] Trial 0 finished with value: 0.8558738164850641 and parameters: {'n_estimators': 450, 'max_depth': 15, 'learning_rate': 0.1205712628744377, 'min_child_weight': 6}. Best is trial 0 with value: 0.8558738164850641.

Средний NDCG: 0.8559
Средний Precision: 0.7618
Средний Recall: 0.7934
Средний F1-Score: 0.7620
🏃 View run 0 at: http://127.0.0.1:5000/#/experiments/4/runs/651ba6a3aa3e4149bc8419fb2b61110a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8386
Средний Precision: 0.6220
Средний Recall: 0.8042
Средний F1-Score: 0.6742
Средний NDCG: 0.8291
Средний Precision: 0.6081
Средний Recall: 0.7930
Средний F1-Score: 0.6597

[I 2026-05-08 11:48:05,545] Trial 1 finished with value: 0.8353950197667808 and parameters: {'n_estimators': 200, 'max_depth': 5, 'learning_rate': 0.012184186502221764, 'min_child_weight': 9}. Best is trial 0 with value: 0.8558738164850641.

Средний NDCG: 0.8354
Средний Precision: 0.6198
Средний Recall: 0.7989
Средний F1-Score: 0.6712
🏃 View run 1 at: http://127.0.0.1:5000/#/experiments/4/runs/c125ddb1b2de4ebe970b2fb9b7c89ae5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8572
Средний Precision: 0.7214
Средний Recall: 0.8251
Средний F1-Score: 0.7505
Средний NDCG: 0.8460
Средний Precision: 0.7055
Средний Recall: 0.8125
Средний F1-Score: 0.7359

[I 2026-05-08 11:48:28,833] Trial 2 finished with value: 0.8536724408121985 and parameters: {'n_estimators': 650, 'max_depth': 12, 'learning_rate': 0.010725209743171997, 'min_child_weight': 10}. Best is trial 0 with value: 0.8558738164850641.

Средний NDCG: 0.8537
Средний Precision: 0.7149
Средний Recall: 0.8153
Средний F1-Score: 0.7429
🏃 View run 2 at: http://127.0.0.1:5000/#/experiments/4/runs/d58dbb77e0e84550b9782f65f8cac89d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8549
Средний Precision: 0.6634
Средний Recall: 0.8323
Средний F1-Score: 0.7147
Средний NDCG: 0.8446
Средний Precision: 0.6555
Средний Recall: 0.8202
Средний F1-Score: 0.7042

[I 2026-05-08 11:48:47,201] Trial 3 finished with value: 0.851348108983658 and parameters: {'n_estimators': 850, 'max_depth': 5, 'learning_rate': 0.01855998084649058, 'min_child_weight': 2}. Best is trial 0 with value: 0.8558738164850641.

Средний NDCG: 0.8513
Средний Precision: 0.6651
Средний Recall: 0.8270
Средний F1-Score: 0.7139
🏃 View run 3 at: http://127.0.0.1:5000/#/experiments/4/runs/883f33a3ed01402ab2c6aef16d0b68d6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8602
Средний Precision: 0.7239
Средний Recall: 0.8259
Средний F1-Score: 0.7525
Средний NDCG: 0.8471
Средний Precision: 0.7184
Средний Recall: 0.8187
Средний F1-Score: 0.7471

[I 2026-05-08 11:49:03,950] Trial 4 finished with value: 0.8556496280306192 and parameters: {'n_estimators': 350, 'max_depth': 9, 'learning_rate': 0.04345454109729477, 'min_child_weight': 3}. Best is trial 0 with value: 0.8558738164850641.

Средний NDCG: 0.8556
Средний Precision: 0.7239
Средний Recall: 0.8200
Средний F1-Score: 0.7509
🏃 View run 4 at: http://127.0.0.1:5000/#/experiments/4/runs/302075e0922d4cce875325eb7f19bc95
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8524
Средний Precision: 0.6530
Средний Recall: 0.8288
Средний F1-Score: 0.7061
Средний NDCG: 0.8414
Средний Precision: 0.6441
Средний Recall: 0.8188
Средний F1-Score: 0.6956

[I 2026-05-08 11:49:20,277] Trial 5 finished with value: 0.8485689474664239 and parameters: {'n_estimators': 650, 'max_depth': 4, 'learning_rate': 0.027010527749605478, 'min_child_weight': 4}. Best is trial 0 with value: 0.8558738164850641.

Средний NDCG: 0.8486
Средний Precision: 0.6517
Средний Recall: 0.8262
Средний F1-Score: 0.7043
🏃 View run 5 at: http://127.0.0.1:5000/#/experiments/4/runs/8acdab6554c04f8a894808cbe3e9a41b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8592
Средний Precision: 0.7420
Средний Recall: 0.8159
Средний F1-Score: 0.7593
Средний NDCG: 0.8471
Средний Precision: 0.7259
Средний Recall: 0.8049
Средний F1-Score: 0.7456

[I 2026-05-08 11:49:41,540] Trial 6 finished with value: 0.8553548180045428 and parameters: {'n_estimators': 500, 'max_depth': 13, 'learning_rate': 0.019721610970574007, 'min_child_weight': 6}. Best is trial 0 with value: 0.8558738164850641.

Средний NDCG: 0.8554
Средний Precision: 0.7387
Средний Recall: 0.8102
Средний F1-Score: 0.7558
🏃 View run 6 at: http://127.0.0.1:5000/#/experiments/4/runs/32b839c32fad4e4cb4cdab110c299629
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8536
Средний Precision: 0.6616
Средний Recall: 0.8328
Средний F1-Score: 0.7134
Средний NDCG: 0.8449
Средний Precision: 0.6519
Средний Recall: 0.8230
Средний F1-Score: 0.7028

[I 2026-05-08 11:49:57,176] Trial 7 finished with value: 0.8500549667096924 and parameters: {'n_estimators': 650, 'max_depth': 3, 'learning_rate': 0.07896186801026692, 'min_child_weight': 2}. Best is trial 0 with value: 0.8558738164850641.

Средний NDCG: 0.8501
Средний Precision: 0.6606
Средний Recall: 0.8268
Средний F1-Score: 0.7106
🏃 View run 7 at: http://127.0.0.1:5000/#/experiments/4/runs/a1128f8ad0d44052bf0d820d2a16573c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8592
Средний Precision: 0.7626
Средний Recall: 0.8094
Средний F1-Score: 0.7700
Средний NDCG: 0.8474
Средний Precision: 0.7515
Средний Recall: 0.7930
Средний F1-Score: 0.7564

[I 2026-05-08 11:50:12,656] Trial 8 finished with value: 0.8562507847014694 and parameters: {'n_estimators': 150, 'max_depth': 15, 'learning_rate': 0.26690431824362526, 'min_child_weight': 9}. Best is trial 8 with value: 0.8562507847014694.

Средний NDCG: 0.8563
Средний Precision: 0.7585
Средний Recall: 0.7979
Средний F1-Score: 0.7621
🏃 View run 8 at: http://127.0.0.1:5000/#/experiments/4/runs/9ef629299dd7450f87299eeae7acd361
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8557
Средний Precision: 0.6731
Средний Recall: 0.8346
Средний F1-Score: 0.7226
Средний NDCG: 0.8456
Средний Precision: 0.6630
Средний Recall: 0.8226
Средний F1-Score: 0.7105

[I 2026-05-08 11:50:27,511] Trial 9 finished with value: 0.8521226821676651 and parameters: {'n_estimators': 350, 'max_depth': 4, 'learning_rate': 0.1024932221692416, 'min_child_weight': 5}. Best is trial 8 with value: 0.8562507847014694.

Средний NDCG: 0.8521
Средний Precision: 0.6753
Средний Recall: 0.8300
Средний F1-Score: 0.7218
🏃 View run 9 at: http://127.0.0.1:5000/#/experiments/4/runs/26a913b73e384b0a8cc3d58030b2212e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Number of finished trials: 10
Best params XGBoost: {'n_estimators': 150, 'max_depth': 15, 'learning_rate': 0.26690431824362526, 'min_child_weight': 9}

In [68]:
pipeline_xgb_best = Pipeline([
    ('preprocessing', ColumnTransformer([
        ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
    ], remainder='passthrough')),
    ('model', XGBClassifier(
        random_state=RANDOM_STATE, 
        eval_metric='logloss', 
        use_label_encoder=False, 
        verbosity=0,
        scale_pos_weight=(len(y_train) - sum(y_train)) / sum(y_train)
    ))
])

pipeline_xgb_best.set_params(**study_xgb.best_trial.user_attrs['pipeline_params'])
pipeline_xgb_best.fit(X_train, y_train)

y_pred_proba_xgb = pipeline_xgb_best.predict_proba(X_test)

df_test_xgb = df.loc[X_test.index].copy()
df_test_xgb['y_pred_proba'] = y_pred_proba_xgb[:, 1]

ndcg_xgb, precision_xgb, recall_xgb, f1_xgb = calculate_metrics(df_test_xgb)
metrics_xgb = {
    'NDCG': ndcg_xgb,
    'Precision': precision_xgb,
    'Recall': recall_xgb,
    'F1': f1_xgb
}

Средний NDCG: 0.7781
Средний Precision: 0.6988
Средний Recall: 0.7342
Средний F1-Score: 0.7036

In [69]:
RUN_NAME_XGB = "best_optuna_xgb"
REGISTRY_MODEL_NAME_XGB = "best_optuna_xgb"

signature = mlflow.models.infer_signature(X_test, y_test)
input_example = X_test[:10]
code_paths = ["ML_Experiments.ipynb"]

with mlflow.start_run(run_name=RUN_NAME_XGB, experiment_id=experiment_id) as run:
    run_id = run.info.run_id
    
    xgb_info = mlflow.sklearn.log_model(sk_model=pipeline_xgb_best, 
                                       artifact_path='best_optuna_xgb',
                                       registered_model_name=REGISTRY_MODEL_NAME_XGB,
                                       input_example=input_example,
                                       code_paths=code_paths,
                                       await_registration_for=60
                                      )
    mlflow.log_metrics(metrics_xgb)
    mlflow.log_params(best_params_xgb)

Registered model 'best_optuna_xgb' already exists. Creating a new version of this model...
2026/05/08 11:50:35 INFO mlflow.store.model_registry.abstract_store: Waiting up to 60 seconds for model version to finish creation. Model name: best_optuna_xgb, version 8

🏃 View run best_optuna_xgb at: http://127.0.0.1:5000/#/experiments/4/runs/a8c24fb7da0042f69f3aee9d5b838387
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

Created version '8' of model 'best_optuna_xgb'.

# LGBMClassifier

In [70]:
def objective_lgbm(trial: optuna.Trial) -> float:
    params = {
        'model__n_estimators': trial.suggest_int('n_estimators', 100, 1000, step=50),
        'model__max_depth': trial.suggest_int('max_depth', 3, 15),
        'model__learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'model__num_leaves': trial.suggest_int('num_leaves', 20, 300),
        'model__min_child_samples': trial.suggest_int('min_child_samples', 5, 100)
    }
    
    pipeline_lgbm = Pipeline([
        ('preprocessing', ColumnTransformer([
            ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
        ], remainder='passthrough')),
        ('model', LGBMClassifier(
            random_state=RANDOM_STATE, 
            verbose=-1,
            class_weight='balanced'
        ))
    ])
    
    pipeline_lgbm.set_params(**params)
    
    kfold = StratifiedKFold(n_splits=3, shuffle=True, random_state=RANDOM_STATE)
    
    for train_idx, val_idx in kfold.split(X_train, y_train):
        X_fold_train, X_fold_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_fold_train, y_fold_val = y_train.iloc[train_idx], y_train.iloc[val_idx]
        
        pipeline_lgbm.fit(X_fold_train, y_fold_train)
        y_pred_proba = pipeline_lgbm.predict_proba(X_fold_val)
        
        df_val = df.loc[X_fold_val.index].copy()
        df_val['y_pred_proba'] = y_pred_proba[:, 1]
        
        ndcg, _, _, _ = calculate_metrics(df_val)
        
        trial.set_user_attr('pipeline_params', params)
    
    return ndcg

In [71]:
RUN_NAME_OPTUNE_LGBM = 'LGBMClassifier_optuna'

with mlflow.start_run(run_name=RUN_NAME_OPTUNE_LGBM, experiment_id=experiment_id) as run:
    run_id_lgbm = run.info.run_id

🏃 View run LGBMClassifier_optuna at: http://127.0.0.1:5000/#/experiments/4/runs/479e2d1d0d1a471495375f0b8b569090
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

In [72]:
STUDY_NAME_LGBM = "LGBMClassifier_optuna"

mlflc_lgbm = MLflowCallback(
    tracking_uri=f'http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}',
    metric_name="NDCG",
    create_experiment=False,
    mlflow_kwargs={'experiment_id': experiment_id, 'tags': {MLFLOW_PARENT_RUN_ID: run_id_lgbm}}
)

In [73]:
study_lgbm = optuna.create_study(direction='maximize', 
                                 sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
                                 study_name=STUDY_NAME_LGBM,
                                 storage=STUDY_DB_NAME,
                                 load_if_exists=False)

study_lgbm.optimize(objective_lgbm, 
                    n_trials=20, 
                    callbacks=[mlflc_lgbm]
                   )

best_params_lgbm = study_lgbm.best_params
print(f"Number of finished trials: {len(study_lgbm.trials)}")
print(f"Best params LGBM: {best_params_lgbm}")

[I 2026-05-08 11:50:35,057] A new study created in RDB with name: LGBMClassifier_optuna

Средний NDCG: 0.8603
Средний Precision: 0.7741
Средний Recall: 0.7994
Средний F1-Score: 0.7718
Средний NDCG: 0.8472
Средний Precision: 0.7656
Средний Recall: 0.7870
Средний F1-Score: 0.7619

[I 2026-05-08 11:51:52,652] Trial 0 finished with value: 0.85649136123959 and parameters: {'n_estimators': 450, 'max_depth': 15, 'learning_rate': 0.1205712628744377, 'num_leaves': 188, 'min_child_samples': 19}. Best is trial 0 with value: 0.85649136123959.

Средний NDCG: 0.8565
Средний Precision: 0.7675
Средний Recall: 0.7869
Средний F1-Score: 0.7622
🏃 View run 0 at: http://127.0.0.1:5000/#/experiments/4/runs/370cb644064d4160a8b116afec4cacfa
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8525
Средний Precision: 0.6547
Средний Recall: 0.8323
Средний F1-Score: 0.7091
Средний NDCG: 0.8432
Средний Precision: 0.6440
Средний Recall: 0.8218
Средний F1-Score: 0.6971

[I 2026-05-08 11:52:06,876] Trial 1 finished with value: 0.8492437739747656 and parameters: {'n_estimators': 200, 'max_depth': 3, 'learning_rate': 0.19030368381735815, 'num_leaves': 188, 'min_child_samples': 72}. Best is trial 0 with value: 0.85649136123959.

Средний NDCG: 0.8492
Средний Precision: 0.6507
Средний Recall: 0.8265
Средний F1-Score: 0.7039
🏃 View run 1 at: http://127.0.0.1:5000/#/experiments/4/runs/639998d0720e4e658ca5763820d70081
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8595
Средний Precision: 0.7153
Средний Recall: 0.8311
Средний F1-Score: 0.7496
Средний NDCG: 0.8483
Средний Precision: 0.7075
Средний Recall: 0.8216
Средний F1-Score: 0.7408

[I 2026-05-08 11:52:25,958] Trial 2 finished with value: 0.8571175629509271 and parameters: {'n_estimators': 100, 'max_depth': 15, 'learning_rate': 0.1696753360719655, 'num_leaves': 79, 'min_child_samples': 22}. Best is trial 2 with value: 0.8571175629509271.

Средний NDCG: 0.8571
Средний Precision: 0.7175
Средний Recall: 0.8259
Средний F1-Score: 0.7489
🏃 View run 2 at: http://127.0.0.1:5000/#/experiments/4/runs/4fdecdc0fb00429cba32fd865a310d71
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8563
Средний Precision: 0.6804
Средний Recall: 0.8347
Средний F1-Score: 0.7273
Средний NDCG: 0.8463
Средний Precision: 0.6695
Средний Recall: 0.8209
Средний F1-Score: 0.7145

[I 2026-05-08 11:52:46,572] Trial 3 finished with value: 0.852488913058401 and parameters: {'n_estimators': 250, 'max_depth': 6, 'learning_rate': 0.05958389350068958, 'num_leaves': 141, 'min_child_samples': 32}. Best is trial 2 with value: 0.8571175629509271.

Средний NDCG: 0.8525
Средний Precision: 0.6786
Средний Recall: 0.8286
Средний F1-Score: 0.7241
🏃 View run 3 at: http://127.0.0.1:5000/#/experiments/4/runs/d129fcc04749418888a293174fc1fd37
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8522
Средний Precision: 0.6533
Средний Recall: 0.8294
Средний F1-Score: 0.7067
Средний NDCG: 0.8420
Средний Precision: 0.6423
Средний Recall: 0.8185
Средний F1-Score: 0.6942

[I 2026-05-08 11:53:06,281] Trial 4 finished with value: 0.847984290013643 and parameters: {'n_estimators': 650, 'max_depth': 4, 'learning_rate': 0.027010527749605478, 'num_leaves': 122, 'min_child_samples': 48}. Best is trial 2 with value: 0.8571175629509271.

Средний NDCG: 0.8480
Средний Precision: 0.6501
Средний Recall: 0.8264
Средний F1-Score: 0.7039
🏃 View run 4 at: http://127.0.0.1:5000/#/experiments/4/runs/8fb82df0117c44bcbcad1ab8f94a4199
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8587
Средний Precision: 0.7008
Средний Recall: 0.8332
Средний F1-Score: 0.7412
Средний NDCG: 0.8468
Средний Precision: 0.6911
Средний Recall: 0.8223
Средний F1-Score: 0.7302

[I 2026-05-08 11:53:33,968] Trial 5 finished with value: 0.8565733933427125 and parameters: {'n_estimators': 800, 'max_depth': 5, 'learning_rate': 0.05748924681991978, 'num_leaves': 186, 'min_child_samples': 9}. Best is trial 2 with value: 0.8571175629509271.

Средний NDCG: 0.8566
Средний Precision: 0.7013
Средний Recall: 0.8283
Средний F1-Score: 0.7395
🏃 View run 5 at: http://127.0.0.1:5000/#/experiments/4/runs/fe3ce71ad9354e0e95ef1ee2bbc4880f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8496
Средний Precision: 0.6449
Средний Recall: 0.8277
Средний F1-Score: 0.6996
Средний NDCG: 0.8388
Средний Precision: 0.6303
Средний Recall: 0.8180
Средний F1-Score: 0.6855

[I 2026-05-08 11:53:58,938] Trial 6 finished with value: 0.8457247017141889 and parameters: {'n_estimators': 650, 'max_depth': 5, 'learning_rate': 0.012476394272569451, 'num_leaves': 286, 'min_child_samples': 97}. Best is trial 2 with value: 0.8571175629509271.

Средний NDCG: 0.8457
Средний Precision: 0.6408
Средний Recall: 0.8210
Средний F1-Score: 0.6948
🏃 View run 6 at: http://127.0.0.1:5000/#/experiments/4/runs/458b66af8d4a40b7b46f2e75b951724d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8552
Средний Precision: 0.6698
Средний Recall: 0.8331
Средний F1-Score: 0.7193
Средний NDCG: 0.8448
Средний Precision: 0.6580
Средний Recall: 0.8213
Средний F1-Score: 0.7063

[I 2026-05-08 11:54:38,973] Trial 7 finished with value: 0.8523309120537447 and parameters: {'n_estimators': 850, 'max_depth': 6, 'learning_rate': 0.013940346079873234, 'num_leaves': 212, 'min_child_samples': 47}. Best is trial 2 with value: 0.8571175629509271.

Средний NDCG: 0.8523
Средний Precision: 0.6714
Средний Recall: 0.8276
Средний F1-Score: 0.7186
🏃 View run 7 at: http://127.0.0.1:5000/#/experiments/4/runs/3a1be3e731264b0995973bcf57a3be41
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8510
Средний Precision: 0.6632
Средний Recall: 0.8263
Средний F1-Score: 0.7113
Средний NDCG: 0.8396
Средний Precision: 0.6490
Средний Recall: 0.8145
Средний F1-Score: 0.6983

[I 2026-05-08 11:55:26,586] Trial 8 finished with value: 0.8468207651350818 and parameters: {'n_estimators': 200, 'max_depth': 9, 'learning_rate': 0.011240768803005551, 'num_leaves': 275, 'min_child_samples': 29}. Best is trial 2 with value: 0.8571175629509271.

Средний NDCG: 0.8468
Средний Precision: 0.6598
Средний Recall: 0.8218
Средний F1-Score: 0.7082
🏃 View run 8 at: http://127.0.0.1:5000/#/experiments/4/runs/ce17806b5b614497913d43fe148695d5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8616
Средний Precision: 0.7351
Средний Recall: 0.8281
Средний F1-Score: 0.7609
Средний NDCG: 0.8478
Средний Precision: 0.7245
Средний Recall: 0.8169
Средний F1-Score: 0.7505

[I 2026-05-08 11:56:15,009] Trial 9 finished with value: 0.8572511149122544 and parameters: {'n_estimators': 700, 'max_depth': 7, 'learning_rate': 0.05864129169696527, 'num_leaves': 173, 'min_child_samples': 22}. Best is trial 9 with value: 0.8572511149122544.

Средний NDCG: 0.8573
Средний Precision: 0.7346
Средний Recall: 0.8201
Средний F1-Score: 0.7577
🏃 View run 9 at: http://127.0.0.1:5000/#/experiments/4/runs/8df10bec24fd4e9fa810945625d89ec5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Number of finished trials: 10
Best params LGBM: {'n_estimators': 700, 'max_depth': 7, 'learning_rate': 0.05864129169696527, 'num_leaves': 173, 'min_child_samples': 22}

In [74]:
pipeline_lgbm_best = Pipeline([
    ('preprocessing', ColumnTransformer([
        ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
    ], remainder='passthrough')),
    ('model', LGBMClassifier(
        random_state=RANDOM_STATE, 
        verbose=-1,
        class_weight='balanced'
    ))
])

pipeline_lgbm_best.set_params(**study_lgbm.best_trial.user_attrs['pipeline_params'])
pipeline_lgbm_best.fit(X_train, y_train)

y_pred_proba_lgbm = pipeline_lgbm_best.predict_proba(X_test)

df_test_lgbm = df.loc[X_test.index].copy()
df_test_lgbm['y_pred_proba'] = y_pred_proba_lgbm[:, 1]

ndcg_lgbm, precision_lgbm, recall_lgbm, f1_lgbm = calculate_metrics(df_test_lgbm)
metrics_lgbm = {
    'NDCG': ndcg_lgbm,
    'Precision': precision_lgbm,
    'Recall': recall_lgbm,
    'F1': f1_lgbm
}

Средний NDCG: 0.7784
Средний Precision: 0.6697
Средний Recall: 0.7507
Средний F1-Score: 0.6918

In [75]:
RUN_NAME_LGBM = "best_optuna_lgbm"
REGISTRY_MODEL_NAME_LGBM = "best_optuna_lgbm"

signature = mlflow.models.infer_signature(X_test, y_test)
input_example = X_test[:10]
code_paths = ["ML_Experiments.ipynb"]

with mlflow.start_run(run_name=RUN_NAME_LGBM, experiment_id=experiment_id) as run:
    run_id = run.info.run_id
    
    lgbm_info = mlflow.sklearn.log_model(sk_model=pipeline_lgbm_best, 
                                        artifact_path='best_optuna_lgbm',
                                        registered_model_name=REGISTRY_MODEL_NAME_LGBM,
                                        input_example=input_example,
                                        code_paths=code_paths,
                                        await_registration_for=60
                                       )
    mlflow.log_metrics(metrics_lgbm)
    mlflow.log_params(best_params_lgbm)

Registered model 'best_optuna_lgbm' already exists. Creating a new version of this model...
2026/05/08 11:56:33 INFO mlflow.store.model_registry.abstract_store: Waiting up to 60 seconds for model version to finish creation. Model name: best_optuna_lgbm, version 8

🏃 View run best_optuna_lgbm at: http://127.0.0.1:5000/#/experiments/4/runs/7ed6b71d3aa7493d9205af718accdfc6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

Created version '8' of model 'best_optuna_lgbm'.

# CatBoostClassifier

In [132]:
def objective_catboost(trial: optuna.Trial) -> float:
    params = {
        'model__iterations': trial.suggest_int('iterations', 100, 1000, step=50),
        'model__depth': trial.suggest_int('depth', 3, 10),
        'model__learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'model__l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 1, 10, log=True)
    }
    
    pipeline_catboost = Pipeline([
        ('preprocessing', ColumnTransformer([
            ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
        ], remainder='passthrough')),
        ('model', CatBoostClassifier(
            random_state=RANDOM_STATE, 
            verbose=0, 
            auto_class_weights='Balanced'
        ))
    ])
    
    pipeline_catboost.set_params(**params)
    
    kfold = StratifiedKFold(n_splits=3, shuffle=True, random_state=RANDOM_STATE)
    
    for train_idx, val_idx in kfold.split(X_train, y_train):
        X_fold_train, X_fold_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_fold_train, y_fold_val = y_train.iloc[train_idx], y_train.iloc[val_idx]
        
        pipeline_catboost.fit(X_fold_train, y_fold_train)
        y_pred_proba = pipeline_catboost.predict_proba(X_fold_val)
        
        df_val = df.loc[X_fold_val.index].copy()
        df_val['y_pred_proba'] = y_pred_proba[:, 1]
        
        ndcg, _, _, _ = calculate_metrics(df_val)
        
        trial.set_user_attr('pipeline_params', params)
    
    return ndcg

In [133]:
RUN_NAME_OPTUNE_CATBOOST = 'CatBoostClassifier_optuna'

with mlflow.start_run(run_name=RUN_NAME_OPTUNE_CATBOOST, experiment_id=experiment_id) as run:
    run_id_catboost = run.info.run_id

🏃 View run CatBoostClassifier_optuna at: http://127.0.0.1:5000/#/experiments/4/runs/cd4a948c5b394f0dacb3a87920431397
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

In [134]:
STUDY_NAME_CATBOOST = "CatBoostClassifier_optuna"

mlflc_catboost = MLflowCallback(
    tracking_uri=f'http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}',
    metric_name="NDCG",
    create_experiment=False,
    mlflow_kwargs={'experiment_id': experiment_id, 'tags': {MLFLOW_PARENT_RUN_ID: run_id_catboost}}
)

In [135]:
study_catboost = optuna.create_study(direction='maximize', 
                                     sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
                                     study_name=STUDY_NAME_CATBOOST,
                                     storage=STUDY_DB_NAME,
                                     load_if_exists=False)

study_catboost.optimize(objective_catboost, 
                        n_trials=20, 
                        callbacks=[mlflc_catboost]
                       )

best_params_catboost = study_catboost.best_params
print(f"Number of finished trials: {len(study_catboost.trials)}")
print(f"Best params CatBoost: {best_params_catboost}")

[I 2026-05-08 12:35:33,877] A new study created in RDB with name: CatBoostClassifier_optuna

Средний NDCG: 0.8675
Средний Precision: 0.7940
Средний Recall: 0.8398
Средний F1-Score: 0.8061
Средний NDCG: 0.8574
Средний Precision: 0.7767
Средний Recall: 0.8346
Средний F1-Score: 0.7937

[I 2026-05-08 12:35:59,375] Trial 0 finished with value: 0.8630071503949772 and parameters: {'iterations': 450, 'depth': 10, 'learning_rate': 0.1205712628744377, 'l2_leaf_reg': 3.968793330444372}. Best is trial 0 with value: 0.8630071503949772.

Средний NDCG: 0.8630
Средний Precision: 0.7867
Средний Recall: 0.8376
Средний F1-Score: 0.8003
🏃 View run 0 at: http://127.0.0.1:5000/#/experiments/4/runs/1381b37eaa7e4b829eb2e27463ee841b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8648
Средний Precision: 0.7135
Средний Recall: 0.8486
Средний F1-Score: 0.7581
Средний NDCG: 0.8546
Средний Precision: 0.7048
Средний Recall: 0.8401
Средний F1-Score: 0.7491

[I 2026-05-08 12:36:13,894] Trial 1 finished with value: 0.859660166890884 and parameters: {'iterations': 200, 'depth': 4, 'learning_rate': 0.012184186502221764, 'l2_leaf_reg': 7.348118405270449}. Best is trial 0 with value: 0.8630071503949772.

Средний NDCG: 0.8597
Средний Precision: 0.7160
Средний Recall: 0.8441
Средний F1-Score: 0.7582
🏃 View run 1 at: http://127.0.0.1:5000/#/experiments/4/runs/1bd76db0a99e451aadfd6d89032f8b99
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8674
Средний Precision: 0.7365
Средний Recall: 0.8537
Средний F1-Score: 0.7752
Средний NDCG: 0.8576
Средний Precision: 0.7267
Средний Recall: 0.8436
Средний F1-Score: 0.7656

[I 2026-05-08 12:36:38,183] Trial 2 finished with value: 0.8633058135239318 and parameters: {'iterations': 650, 'depth': 8, 'learning_rate': 0.010725209743171997, 'l2_leaf_reg': 9.330606024425668}. Best is trial 2 with value: 0.8633058135239318.

Средний NDCG: 0.8633
Средний Precision: 0.7360
Средний Recall: 0.8484
Средний F1-Score: 0.7735
🏃 View run 2 at: http://127.0.0.1:5000/#/experiments/4/runs/ab1dbb50e9674fd191e96834ee783271
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8669
Средний Precision: 0.7316
Средний Recall: 0.8549
Средний F1-Score: 0.7722
Средний NDCG: 0.8576
Средний Precision: 0.7233
Средний Recall: 0.8442
Средний F1-Score: 0.7638

[I 2026-05-08 12:37:00,089] Trial 3 finished with value: 0.862283149144489 and parameters: {'iterations': 850, 'depth': 4, 'learning_rate': 0.01855998084649058, 'l2_leaf_reg': 1.5254729458052607}. Best is trial 2 with value: 0.8633058135239318.

Средний NDCG: 0.8623
Средний Precision: 0.7325
Средний Recall: 0.8484
Средний F1-Score: 0.7712
🏃 View run 3 at: http://127.0.0.1:5000/#/experiments/4/runs/a68e396c521a4a2cba43d982eadee52a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8677
Средний Precision: 0.7457
Средний Recall: 0.8535
Средний F1-Score: 0.7811
Средний NDCG: 0.8583
Средний Precision: 0.7364
Средний Recall: 0.8431
Средний F1-Score: 0.7716

[I 2026-05-08 12:37:18,191] Trial 4 finished with value: 0.8637070436546284 and parameters: {'iterations': 350, 'depth': 7, 'learning_rate': 0.04345454109729477, 'l2_leaf_reg': 1.9553708662745248}. Best is trial 4 with value: 0.8637070436546284.

Средний NDCG: 0.8637
Средний Precision: 0.7502
Средний Recall: 0.8479
Средний F1-Score: 0.7824
🏃 View run 4 at: http://127.0.0.1:5000/#/experiments/4/runs/5133fff9926547d2a26031090c0bd2d6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8673
Средний Precision: 0.7332
Средний Recall: 0.8546
Средний F1-Score: 0.7732
Средний NDCG: 0.8576
Средний Precision: 0.7247
Средний Recall: 0.8445
Средний F1-Score: 0.7647

[I 2026-05-08 12:37:37,940] Trial 5 finished with value: 0.8620598427047703 and parameters: {'iterations': 650, 'depth': 4, 'learning_rate': 0.027010527749605478, 'l2_leaf_reg': 2.324672848950434}. Best is trial 4 with value: 0.8637070436546284.

Средний NDCG: 0.8621
Средний Precision: 0.7340
Средний Recall: 0.8498
Средний F1-Score: 0.7727
🏃 View run 5 at: http://127.0.0.1:5000/#/experiments/4/runs/eaefde8c66d04459932a9c7e96fdbf67
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8680
Средний Precision: 0.7496
Средний Recall: 0.8530
Средний F1-Score: 0.7835
Средний NDCG: 0.8583
Средний Precision: 0.7388
Средний Recall: 0.8424
Средний F1-Score: 0.7730

[I 2026-05-08 12:38:01,384] Trial 6 finished with value: 0.863485014604646 and parameters: {'iterations': 500, 'depth': 9, 'learning_rate': 0.019721610970574007, 'l2_leaf_reg': 3.2676417657817622}. Best is trial 4 with value: 0.8637070436546284.

Средний NDCG: 0.8635
Средний Precision: 0.7511
Средний Recall: 0.8464
Средний F1-Score: 0.7824
🏃 View run 6 at: http://127.0.0.1:5000/#/experiments/4/runs/b744914392ff494cbf44bdc1b96c5f33
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8680
Средний Precision: 0.7408
Средний Recall: 0.8545
Средний F1-Score: 0.7783
Средний NDCG: 0.8576
Средний Precision: 0.7334
Средний Recall: 0.8446
Средний F1-Score: 0.7703

[I 2026-05-08 12:38:20,254] Trial 7 finished with value: 0.8628064681814461 and parameters: {'iterations': 650, 'depth': 3, 'learning_rate': 0.07896186801026692, 'l2_leaf_reg': 1.4808945119975185}. Best is trial 4 with value: 0.8637070436546284.

Средний NDCG: 0.8628
Средний Precision: 0.7402
Средний Recall: 0.8491
Средний F1-Score: 0.7768
🏃 View run 7 at: http://127.0.0.1:5000/#/experiments/4/runs/89677af0edab48228717fc0b2d0492ac
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8678
Средний Precision: 0.7622
Средний Recall: 0.8504
Средний F1-Score: 0.7907
Средний NDCG: 0.8579
Средний Precision: 0.7520
Средний Recall: 0.8406
Средний F1-Score: 0.7806

[I 2026-05-08 12:38:36,006] Trial 8 finished with value: 0.8629998576474387 and parameters: {'iterations': 150, 'depth': 10, 'learning_rate': 0.26690431824362526, 'l2_leaf_reg': 6.432759992849893}. Best is trial 4 with value: 0.8637070436546284.

Средний NDCG: 0.8630
Средний Precision: 0.7628
Средний Recall: 0.8430
Средний F1-Score: 0.7879
🏃 View run 8 at: http://127.0.0.1:5000/#/experiments/4/runs/cf7b58a24b634b68bb50e31795348432
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8679
Средний Precision: 0.7345
Средний Recall: 0.8534
Средний F1-Score: 0.7738
Средний NDCG: 0.8575
Средний Precision: 0.7312
Средний Recall: 0.8444
Средний F1-Score: 0.7688

[I 2026-05-08 12:38:52,084] Trial 9 finished with value: 0.8625514548698989 and parameters: {'iterations': 350, 'depth': 3, 'learning_rate': 0.1024932221692416, 'l2_leaf_reg': 2.7551959649510764}. Best is trial 4 with value: 0.8637070436546284.

Средний NDCG: 0.8626
Средний Precision: 0.7385
Средний Recall: 0.8494
Средний F1-Score: 0.7757
🏃 View run 9 at: http://127.0.0.1:5000/#/experiments/4/runs/d25df541e75448ce85c02058f23ff622
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8680
Средний Precision: 0.7610
Средний Recall: 0.8523
Средний F1-Score: 0.7908
Средний NDCG: 0.8578
Средний Precision: 0.7504
Средний Recall: 0.8414
Средний F1-Score: 0.7798

[I 2026-05-08 12:39:17,179] Trial 10 finished with value: 0.863442131762524 and parameters: {'iterations': 950, 'depth': 6, 'learning_rate': 0.0431646733732235, 'l2_leaf_reg': 1.0422259339479671}. Best is trial 4 with value: 0.8637070436546284.

Средний NDCG: 0.8634
Средний Precision: 0.7613
Средний Recall: 0.8470
Средний F1-Score: 0.7890
🏃 View run 10 at: http://127.0.0.1:5000/#/experiments/4/runs/10d755d64599438e88fbdf3d5488eb42
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8677
Средний Precision: 0.7472
Средний Recall: 0.8543
Средний F1-Score: 0.7824
Средний NDCG: 0.8580
Средний Precision: 0.7366
Средний Recall: 0.8433
Средний F1-Score: 0.7717

[I 2026-05-08 12:39:35,889] Trial 11 finished with value: 0.8635067451952506 and parameters: {'iterations': 350, 'depth': 8, 'learning_rate': 0.03336774144514092, 'l2_leaf_reg': 4.208075538548374}. Best is trial 4 with value: 0.8637070436546284.

Средний NDCG: 0.8635
Средний Precision: 0.7476
Средний Recall: 0.8478
Средний F1-Score: 0.7804
🏃 View run 11 at: http://127.0.0.1:5000/#/experiments/4/runs/d1b435f763d140c1bd8d5086c563c3ca
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8679
Средний Precision: 0.7429
Средний Recall: 0.8541
Средний F1-Score: 0.7794
Средний NDCG: 0.8581
Средний Precision: 0.7343
Средний Recall: 0.8434
Средний F1-Score: 0.7705

[I 2026-05-08 12:39:53,076] Trial 12 finished with value: 0.8632017842472168 and parameters: {'iterations': 300, 'depth': 7, 'learning_rate': 0.0435527342638097, 'l2_leaf_reg': 4.545919880494837}. Best is trial 4 with value: 0.8637070436546284.

Средний NDCG: 0.8632
Средний Precision: 0.7446
Средний Recall: 0.8481
Средний F1-Score: 0.7788
🏃 View run 12 at: http://127.0.0.1:5000/#/experiments/4/runs/ef4494eb401148588b8c49f0b1135f25
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8674
Средний Precision: 0.7370
Средний Recall: 0.8548
Средний F1-Score: 0.7760
Средний NDCG: 0.8580
Средний Precision: 0.7261
Средний Recall: 0.8436
Средний F1-Score: 0.7651

[I 2026-05-08 12:40:10,333] Trial 13 finished with value: 0.8628845185552917 and parameters: {'iterations': 350, 'depth': 6, 'learning_rate': 0.03205809078417295, 'l2_leaf_reg': 2.081067898791295}. Best is trial 4 with value: 0.8637070436546284.

Средний NDCG: 0.8629
Средний Precision: 0.7358
Средний Recall: 0.8480
Средний F1-Score: 0.7733
🏃 View run 13 at: http://127.0.0.1:5000/#/experiments/4/runs/e2e40cad1bb549fd939d4c924cca3cf3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8671
Средний Precision: 0.7281
Средний Recall: 0.8548
Средний F1-Score: 0.7700
Средний NDCG: 0.8570
Средний Precision: 0.7201
Средний Recall: 0.8426
Средний F1-Score: 0.7607

[I 2026-05-08 12:40:24,089] Trial 14 finished with value: 0.862717737194281 and parameters: {'iterations': 100, 'depth': 8, 'learning_rate': 0.07235090658068707, 'l2_leaf_reg': 5.0401290506972325}. Best is trial 4 with value: 0.8637070436546284.

Средний NDCG: 0.8627
Средний Precision: 0.7265
Средний Recall: 0.8473
Средний F1-Score: 0.7667
🏃 View run 14 at: http://127.0.0.1:5000/#/experiments/4/runs/1b95cf19a71943a5b751bf3c6d50907d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8677
Средний Precision: 0.7669
Средний Recall: 0.8484
Средний F1-Score: 0.7929
Средний NDCG: 0.8573
Средний Precision: 0.7583
Средний Recall: 0.8395
Средний F1-Score: 0.7841

[I 2026-05-08 12:40:40,581] Trial 15 finished with value: 0.8632186192544116 and parameters: {'iterations': 250, 'depth': 7, 'learning_rate': 0.1566833742481893, 'l2_leaf_reg': 1.8814166075210883}. Best is trial 4 with value: 0.8637070436546284.

Средний NDCG: 0.8632
Средний Precision: 0.7645
Средний Recall: 0.8439
Средний F1-Score: 0.7901
🏃 View run 15 at: http://127.0.0.1:5000/#/experiments/4/runs/8688261bcd9542728941f22b21190ae3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8681
Средний Precision: 0.7650
Средний Recall: 0.8514
Средний F1-Score: 0.7930
Средний NDCG: 0.8579
Средний Precision: 0.7548
Средний Recall: 0.8408
Средний F1-Score: 0.7826

[I 2026-05-08 12:41:01,250] Trial 16 finished with value: 0.8638302816847026 and parameters: {'iterations': 450, 'depth': 8, 'learning_rate': 0.055091259509447536, 'l2_leaf_reg': 3.1496925034466776}. Best is trial 16 with value: 0.8638302816847026.

Средний NDCG: 0.8638
Средний Precision: 0.7654
Средний Recall: 0.8448
Средний F1-Score: 0.7906
🏃 View run 16 at: http://127.0.0.1:5000/#/experiments/4/runs/2d8404d132d24e65b1340b0b40b0c4aa
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8677
Средний Precision: 0.7494
Средний Recall: 0.8539
Средний F1-Score: 0.7839
Средний NDCG: 0.8582
Средний Precision: 0.7401
Средний Recall: 0.8428
Средний F1-Score: 0.7740

[I 2026-05-08 12:41:20,764] Trial 17 finished with value: 0.8633226619530092 and parameters: {'iterations': 550, 'depth': 5, 'learning_rate': 0.06817779343845322, 'l2_leaf_reg': 3.090653980194989}. Best is trial 16 with value: 0.8638302816847026.

Средний NDCG: 0.8633
Средний Precision: 0.7499
Средний Recall: 0.8482
Средний F1-Score: 0.7823
🏃 View run 17 at: http://127.0.0.1:5000/#/experiments/4/runs/e74af7bc6aaa4574aa9a0b3addad8cd2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8678
Средний Precision: 0.7748
Средний Recall: 0.8477
Средний F1-Score: 0.7978
Средний NDCG: 0.8580
Средний Precision: 0.7673
Средний Recall: 0.8377
Средний F1-Score: 0.7889

[I 2026-05-08 12:41:43,220] Trial 18 finished with value: 0.8637405989677146 and parameters: {'iterations': 450, 'depth': 9, 'learning_rate': 0.05423197245433309, 'l2_leaf_reg': 1.1365679800644353}. Best is trial 16 with value: 0.8638302816847026.

Средний NDCG: 0.8637
Средний Precision: 0.7764
Средний Recall: 0.8405
Средний F1-Score: 0.7952
🏃 View run 18 at: http://127.0.0.1:5000/#/experiments/4/runs/787c54f1789c4391ae8ff66b8fda5b51
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8673
Средний Precision: 0.7998
Средний Recall: 0.8317
Средний F1-Score: 0.8057
Средний NDCG: 0.8570
Средний Precision: 0.7901
Средний Recall: 0.8271
Средний F1-Score: 0.7979

[I 2026-05-08 12:42:09,891] Trial 19 finished with value: 0.8629210581911069 and parameters: {'iterations': 750, 'depth': 9, 'learning_rate': 0.18266145263423655, 'l2_leaf_reg': 1.0072079372182763}. Best is trial 16 with value: 0.8638302816847026.

Средний NDCG: 0.8629
Средний Precision: 0.7954
Средний Recall: 0.8303
Средний F1-Score: 0.8020
🏃 View run 19 at: http://127.0.0.1:5000/#/experiments/4/runs/5c9f3bc954294bbfbbb5800b8f40c29b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8676
Средний Precision: 0.7770
Средний Recall: 0.8475
Средний F1-Score: 0.7992
Средний NDCG: 0.8580
Средний Precision: 0.7664
Средний Recall: 0.8373
Средний F1-Score: 0.7883

[I 2026-05-08 12:42:32,265] Trial 20 finished with value: 0.8639416954550785 and parameters: {'iterations': 450, 'depth': 9, 'learning_rate': 0.05646629464262635, 'l2_leaf_reg': 1.3181570756956231}. Best is trial 20 with value: 0.8639416954550785.

Средний NDCG: 0.8639
Средний Precision: 0.7777
Средний Recall: 0.8406
Средний F1-Score: 0.7963
🏃 View run 20 at: http://127.0.0.1:5000/#/experiments/4/runs/bf719834e497480993b19c462dd8786e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8683
Средний Precision: 0.7779
Средний Recall: 0.8467
Средний F1-Score: 0.7993
Средний NDCG: 0.8573
Средний Precision: 0.7688
Средний Recall: 0.8369
Средний F1-Score: 0.7897

[I 2026-05-08 12:42:54,649] Trial 21 finished with value: 0.8637116115458832 and parameters: {'iterations': 450, 'depth': 9, 'learning_rate': 0.05846499716926664, 'l2_leaf_reg': 1.306873420026626}. Best is trial 20 with value: 0.8639416954550785.

Средний NDCG: 0.8637
Средний Precision: 0.7785
Средний Recall: 0.8410
Средний F1-Score: 0.7970
🏃 View run 21 at: http://127.0.0.1:5000/#/experiments/4/runs/f39869b5476e4780b66ebaf35d8ab0c3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8675
Средний Precision: 0.7889
Средний Recall: 0.8438
Средний F1-Score: 0.8047
Средний NDCG: 0.8575
Средний Precision: 0.7788
Средний Recall: 0.8347
Средний F1-Score: 0.7950

[I 2026-05-08 12:43:16,975] Trial 22 finished with value: 0.8633003606613572 and parameters: {'iterations': 450, 'depth': 9, 'learning_rate': 0.08878044506606117, 'l2_leaf_reg': 1.2251023726868293}. Best is trial 20 with value: 0.8639416954550785.

Средний NDCG: 0.8633
Средний Precision: 0.7887
Средний Recall: 0.8375
Средний F1-Score: 0.8015
🏃 View run 22 at: http://127.0.0.1:5000/#/experiments/4/runs/fbe443da4fd040a29f97a8a9939799c5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8682
Средний Precision: 0.7875
Средний Recall: 0.8459
Средний F1-Score: 0.8044
Средний NDCG: 0.8579
Средний Precision: 0.7795
Средний Recall: 0.8338
Средний F1-Score: 0.7947

[I 2026-05-08 12:43:46,714] Trial 23 finished with value: 0.863685504169242 and parameters: {'iterations': 550, 'depth': 10, 'learning_rate': 0.05450643503437656, 'l2_leaf_reg': 1.675542240588265}. Best is trial 20 with value: 0.8639416954550785.

Средний NDCG: 0.8637
Средний Precision: 0.7845
Средний Recall: 0.8362
Средний F1-Score: 0.7985
🏃 View run 23 at: http://127.0.0.1:5000/#/experiments/4/runs/213f82dfe3a549418fcae7e92c091c5c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8681
Средний Precision: 0.7714
Средний Recall: 0.8500
Средний F1-Score: 0.7962
Средний NDCG: 0.8576
Средний Precision: 0.7596
Средний Recall: 0.8394
Средний F1-Score: 0.7850

[I 2026-05-08 12:44:09,383] Trial 24 finished with value: 0.8640742113987412 and parameters: {'iterations': 550, 'depth': 8, 'learning_rate': 0.05145941702318975, 'l2_leaf_reg': 1.2859315144066832}. Best is trial 24 with value: 0.8640742113987412.

Средний NDCG: 0.8641
Средний Precision: 0.7715
Средний Recall: 0.8433
Средний F1-Score: 0.7939
🏃 View run 24 at: http://127.0.0.1:5000/#/experiments/4/runs/b225dc4f857342f0adbcf2c0922281b2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8680
Средний Precision: 0.7905
Средний Recall: 0.8414
Средний F1-Score: 0.8048
Средний NDCG: 0.8571
Средний Precision: 0.7769
Средний Recall: 0.8340
Средний F1-Score: 0.7935

[I 2026-05-08 12:44:33,983] Trial 25 finished with value: 0.8633087826576192 and parameters: {'iterations': 750, 'depth': 8, 'learning_rate': 0.12426141641409144, 'l2_leaf_reg': 2.3745290913167674}. Best is trial 24 with value: 0.8640742113987412.

Средний NDCG: 0.8633
Средний Precision: 0.7885
Средний Recall: 0.8353
Средний F1-Score: 0.8004
🏃 View run 25 at: http://127.0.0.1:5000/#/experiments/4/runs/1068fe01b8714eca9ba70e38911d252e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8678
Средний Precision: 0.7519
Средний Recall: 0.8528
Средний F1-Score: 0.7849
Средний NDCG: 0.8582
Средний Precision: 0.7414
Средний Recall: 0.8419
Средний F1-Score: 0.7743

[I 2026-05-08 12:44:57,381] Trial 26 finished with value: 0.8636147482111293 and parameters: {'iterations': 600, 'depth': 8, 'learning_rate': 0.023688918550202012, 'l2_leaf_reg': 1.3329433724798874}. Best is trial 24 with value: 0.8640742113987412.

Средний NDCG: 0.8636
Средний Precision: 0.7562
Средний Recall: 0.8468
Средний F1-Score: 0.7856
🏃 View run 26 at: http://127.0.0.1:5000/#/experiments/4/runs/a754b64135a14b3480f9b14321ff2083
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8681
Средний Precision: 0.7613
Средний Recall: 0.8527
Средний F1-Score: 0.7911
Средний NDCG: 0.8577
Средний Precision: 0.7507
Средний Recall: 0.8418
Средний F1-Score: 0.7802

[I 2026-05-08 12:45:21,449] Trial 27 finished with value: 0.8636637415005539 and parameters: {'iterations': 750, 'depth': 7, 'learning_rate': 0.038089524984774935, 'l2_leaf_reg': 1.7595168493524127}. Best is trial 24 with value: 0.8640742113987412.

Средний NDCG: 0.8637
Средний Precision: 0.7620
Средний Recall: 0.8452
Средний F1-Score: 0.7889
🏃 View run 27 at: http://127.0.0.1:5000/#/experiments/4/runs/bbe2991f417d450c8aa6b56a41391d28
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8680
Средний Precision: 0.7513
Средний Recall: 0.8540
Средний F1-Score: 0.7853
Средний NDCG: 0.8581
Средний Precision: 0.7418
Средний Recall: 0.8432
Средний F1-Score: 0.7750

[I 2026-05-08 12:45:41,508] Trial 28 finished with value: 0.8634132975297156 and parameters: {'iterations': 500, 'depth': 6, 'learning_rate': 0.05541391289981187, 'l2_leaf_reg': 5.52809928577831}. Best is trial 24 with value: 0.8640742113987412.

Средний NDCG: 0.8634
Средний Precision: 0.7509
Средний Recall: 0.8469
Средний F1-Score: 0.7824
🏃 View run 28 at: http://127.0.0.1:5000/#/experiments/4/runs/dcff429616fe4f598b63dec34b61d7bf
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8676
Средний Precision: 0.7920
Средний Recall: 0.8407
Средний F1-Score: 0.8051
Средний NDCG: 0.8575
Средний Precision: 0.7823
Средний Recall: 0.8306
Средний F1-Score: 0.7953

[I 2026-05-08 12:46:09,272] Trial 29 finished with value: 0.8631752573625705 and parameters: {'iterations': 400, 'depth': 10, 'learning_rate': 0.11795461483860593, 'l2_leaf_reg': 3.54961576515996}. Best is trial 24 with value: 0.8640742113987412.

Средний NDCG: 0.8632
Средний Precision: 0.7854
Средний Recall: 0.8361
Средний F1-Score: 0.7988
🏃 View run 29 at: http://127.0.0.1:5000/#/experiments/4/runs/9e8a59cbc11e4755adf2e45a56be9878
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Number of finished trials: 30
Best params CatBoost: {'iterations': 550, 'depth': 8, 'learning_rate': 0.05145941702318975, 'l2_leaf_reg': 1.2859315144066832}

In [80]:
pipeline_catboost_best = Pipeline([
    ('preprocessing', ColumnTransformer([
        ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
    ], remainder='passthrough')),
    ('model', CatBoostClassifier(
        random_state=RANDOM_STATE, 
        verbose=0, 
        auto_class_weights='Balanced'
    ))
])

pipeline_catboost_best.set_params(**study_catboost.best_trial.user_attrs['pipeline_params'])
pipeline_catboost_best.fit(X_train, y_train)

y_pred_proba_catboost = pipeline_catboost_best.predict_proba(X_test)

df_test_catboost = df.loc[X_test.index].copy()
df_test_catboost['y_pred_proba'] = y_pred_proba_catboost[:, 1]

ndcg_catboost, precision_catboost, recall_catboost, f1_catboost = calculate_metrics(df_test_catboost)
metrics_catboost = {
    'NDCG': ndcg_catboost,
    'Precision': precision_catboost,
    'Recall': recall_catboost,
    'F1': f1_catboost
}

Средний NDCG: 0.7787
Средний Precision: 0.6782
Средний Recall: 0.7471
Средний F1-Score: 0.6955

In [81]:
RUN_NAME_CATBOOST = "best_optuna_catboost"
REGISTRY_MODEL_NAME_CATBOOST = "best_optuna_catboost"

signature = mlflow.models.infer_signature(X_test, y_test)
input_example = X_test[:10]
code_paths = ["ML_Experiments.ipynb"]

with mlflow.start_run(run_name=RUN_NAME_CATBOOST, experiment_id=experiment_id) as run:
    run_id = run.info.run_id
    
    catboost_info = mlflow.sklearn.log_model(sk_model=pipeline_catboost_best, 
                                             artifact_path='best_optuna_catboost',
                                             registered_model_name=REGISTRY_MODEL_NAME_CATBOOST,
                                             input_example=input_example,
                                             code_paths=code_paths,
                                             await_registration_for=60
                                            )
    mlflow.log_metrics(metrics_catboost)
    mlflow.log_params(best_params_catboost)

Registered model 'best_optuna_catboost' already exists. Creating a new version of this model...
2026/05/08 12:00:04 INFO mlflow.store.model_registry.abstract_store: Waiting up to 60 seconds for model version to finish creation. Model name: best_optuna_catboost, version 9

🏃 View run best_optuna_catboost at: http://127.0.0.1:5000/#/experiments/4/runs/f9832bc307544afcaa60de60a7d08116
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

Created version '9' of model 'best_optuna_catboost'.

# Model comparison

In [82]:
models_comparison = pd.DataFrame({
    'Model': ['LogisticRegression', 'RandomForest', 'XGBoost', 'LightGBM', 'CatBoost'],
    'NDCG': [ndcg_lr, ndcg_rf, 
             ndcg_xgb, ndcg_lgbm, ndcg_catboost],
    'Precision': [precision_lr, precision_rf, 
                  precision_xgb, precision_lgbm, precision_catboost],
    'Recall': [recall_lr, recall_rf, 
               recall_xgb, recall_lgbm, recall_catboost],
    'F1': [f1_lr, f1_rf, 
           f1_xgb, f1_lgbm, f1_catboost]
})

models_comparison

                Model      NDCG  Precision    Recall        F1
0  LogisticRegression  0.751349   0.637015  0.596379  0.599915
1        RandomForest  0.775653   0.660585  0.742407  0.682372
2             XGBoost  0.778059   0.698832  0.734174  0.703595
3            LightGBM  0.778390   0.669718  0.750699  0.691776
4            CatBoost  0.778681   0.678187  0.747071  0.695479

In [83]:
best_model_idx = models_comparison['NDCG'].idxmax()
print(f"\nЛучшая модель: {models_comparison.iloc[best_model_idx]['Model']} с NDCG = {models_comparison.iloc[best_model_idx]['NDCG']:.4f}")

Лучшая модель: CatBoost с NDCG = 0.7787

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

По итогам подбора гиперпараметров лучшее качество показала модель `XGBClassifier`. Теперь попробуем добавить дополнительные признаки от кандидата генераторов. В первую очередь используем коллаборативную фильтрацию.

</div>

# ALS

## Feature engineering

In [84]:
def create_interaction_matrix(df):
    unique_vacancies = df['vacancy_id'].unique().tolist()
    unique_resumes = df['resume_id'].unique().tolist()

    id2vacancy = dict(enumerate(unique_vacancies))
    id2resume = dict(enumerate(unique_resumes))
    vacancy2id = {v: k for k, v in id2vacancy.items()}
    resume2id = {v: k for k, v in id2resume.items()}

    rows = [vacancy2id[vacancy] for vacancy in df['vacancy_id']]
    cols = [resume2id[resume] for resume in df['resume_id']]

    interactions_matrix = csr_matrix(
        (df['target'], (rows, cols)),
        shape=(len(unique_vacancies), len(unique_resumes)),
        dtype=np.float32,
    )

    return interactions_matrix, id2vacancy, id2resume, vacancy2id, resume2id, unique_vacancies, unique_resumes

In [85]:
interactions_matrix, id2vacancy, id2resume, vacancy2id, resume2id, unique_vacancies, unique_resumes = create_interaction_matrix(df)

print(f"Размерность матрицы взаимодействий: {interactions_matrix.shape}")
print(f"Плотность матрицы: {interactions_matrix.nnz / (interactions_matrix.shape[0] * interactions_matrix.shape[1]):.6f}")

Размерность матрицы взаимодействий: (3409, 20130)
Плотность матрицы: 0.004687

In [86]:
def get_factors(interactions_matrix):
    als_model = AlternatingLeastSquares(
        factors=64,          
        regularization=0.1,  
        iterations=30,       
        random_state=RANDOM_STATE,
        num_threads=0
    )
    
    als_model.fit(interactions_matrix.T)

    vacancy_factors = als_model.item_factors
    resume_factors = als_model.user_factors

    return vacancy_factors, resume_factors

In [87]:
vacancy_factors, resume_factors = get_factors(interactions_matrix)

print(f"Размерность эмбеддингов вакансий: {vacancy_factors.shape}")
print(f"Размерность эмбеддингов резюме: {resume_factors.shape}")

  0%|          | 0/30 [00:00<?, ?it/s]

Размерность эмбеддингов вакансий: (3409, 64)
Размерность эмбеддингов резюме: (20130, 64)

In [88]:
def get_als_score(vacancy_id, resume_id):
    if vacancy_id not in vacancy2id or resume_id not in resume2id:
        return 0
    else:
        vac_idx = vacancy2id[vacancy_id]
        res_idx = resume2id[resume_id]
        score = np.dot(vacancy_factors[vac_idx], resume_factors[res_idx])
        return score

df['als_score'] = df.apply(
    lambda row: get_als_score(row['vacancy_id'], row['resume_id']), 
    axis=1
)

In [89]:
df[['vacancy_id', 'resume_id', 'target', 'als_score']].head()

   vacancy_id  resume_id  target  als_score
0   126167948    6969174       1   0.000042
1   126167948    9100077       1   0.000033
2   126167948   32644957       1   0.000019
3   126167948   27220466       1   0.000021
4   126167948    7532708       1   0.000021

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

Проверим схожесть резюме по латентным векторам.

</div>

In [90]:
def find_similar_resumes(resume_id, resume_factors, n_similar=10, metric='cosine'):
    """
    Находит N наиболее похожих резюме на заданное.
    """
    if resume_id not in resume2id:
        print(f"Резюме с ID {resume_id} не найдено")
        return []

    target_idx = resume2id[resume_id]
    target_vector = resume_factors[target_idx].reshape(1, -1)
    
    if metric == 'cosine':
        similarities = cosine_similarity(target_vector, resume_factors)[0]
    else:
        similarities = np.dot(resume_factors, target_vector.T).flatten()
    
    similar_indices = np.argsort(similarities)[::-1][1:n_similar+1]
    
    similar_resumes = []
    for idx in similar_indices:
        sim_resume_id = unique_resumes[idx]
        similarity_score = similarities[idx]
        similar_resumes.append((sim_resume_id, similarity_score))
    
    return similar_resumes

def get_resume_profile(resume_id, df):
    """Вспомогательная функция для получения информации о резюме"""
    resume_data = df[df['resume_id'] == resume_id].iloc[0]
    return {
        'resume_id': resume_id,
        'title': resume_data.get('resume_title', 'N/A'),
        'specialization': resume_data.get('resume_specialization', 'N/A'),
        'skills': resume_data.get('resume_skills', 'N/A'),
        'experience': resume_data.get('resume_total_experience', 'N/A'),
        'salary': resume_data.get('resume_salary', 'N/A'),
        'location': resume_data.get('resume_location', 'N/A')
    }

In [91]:
example_resume_id = df['resume_id'].sample(1, random_state=RANDOM_STATE).values[0].item()
print(f"Исходное резюме (ID: {example_resume_id}):")
original_profile = get_resume_profile(example_resume_id, df)
for key, value in original_profile.items():
    print(f"  {key}: {value}")

print(f"\nТоп-5 похожих резюме (косинусная близость):")
similar_resumes = find_similar_resumes(example_resume_id, resume_factors, n_similar=5, metric='cosine')

for i, (sim_id, score) in enumerate(similar_resumes, 1):
    profile = get_resume_profile(sim_id, df)
    print(f"\n{i}. Резюме ID: {sim_id} (сходство: {score:.4f})")
    print(f"   Должность: {profile['title']}")
    print(f"   Специализация: {profile['specialization']}")
    print(f"   Локация: {profile['location']}")
    print(f"   Опыт: {profile['experience']}")

Исходное резюме (ID: 65353364):
  resume_id: 65353364
  title: Системный администратор
  specialization: ['Сетевой инженер', 'Системный администратор', 'Системный инженер']
  skills: [' Linux', 'Основы анализа данных.', 'Основы Python', 'Информационные технологии', 'Администрирование сетевого оборудования', 'Сетевые технологии', 'Active Directory', 'VLAN', 'OSPF', 'Системное администрирование', 'Техническая поддержка', 'Cisco', 'Qtech', 'Huawei', 'Eltex', 'Основы SQL', 'Helpdesk', 'Cloud', 'OSI', 'Администрирование серверов Linux', 'Zabbix']
  experience: 15 лет 10 месяцев
  salary: 170000.0
  location: Москва

Топ-5 похожих резюме (косинусная близость):

1. Резюме ID: 55976730 (сходство: 0.0000)
   Должность: Инженер-программист .Net/C#
   Специализация: ['Программист, разработчик']
   Локация: Москва
   Опыт: 5 лет 9 месяцев

2. Резюме ID: 37812953 (сходство: 0.0000)
   Должность: Joomla Developer
   Специализация: ['Программист, разработчик']
   Локация: Донецк
   Опыт: 12 лет 7 месяцев

3. Резюме ID: 32588218 (сходство: 0.0000)
   Должность: Wordpress Фулстек-разработчик, Joomla Фулстек-разработчик,   Wordpress/Joomla fullstack developer
   Специализация: ['Программист, разработчик']
   Локация: Москва
   Опыт: 18 лет 5 месяцев

4. Резюме ID: 12029678 (сходство: 0.0000)
   Должность: руководитель IT отдела, ведущий системный администратор
   Специализация: ['Системный администратор']
   Локация: Москва
   Опыт: 12 лет

5. Резюме ID: 103220731 (сходство: 0.0000)
   Должность: Fullstack-разработчик
   Специализация: ['Программист, разработчик']
   Локация: Москва
   Опыт: 6 лет 8 месяцев

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

Разделим тренировочную выборку еще на две, чтобы избежать подглядывания и добавить в признак `als_score` нулевые значения в тренировочный датасет, т.к. у нас могут быть вакансии и резюме без взаимодействий до обучения.

</div>

In [92]:
X_train_als, X_test_als, y_train_als, y_test_als = train_test_split(X_train, y_train, test_size=0.3, random_state=RANDOM_STATE, stratify=y_train)

In [93]:
train_als_interactions = df.loc[X_train_als.index, ['vacancy_id', 'resume_id', 'target']]

interactions_matrix, id2vacancy, id2resume, vacancy2id, resume2id, unique_vacancies, unique_resumes = create_interaction_matrix(train_als_interactions)
vacancy_factors, resume_factors = get_factors(interactions_matrix)

# возвращаем айдишники вакансий и резюме для расчета als score
X_train[['vacancy_id', 'resume_id']] = df.loc[X_train.index, ['vacancy_id', 'resume_id']]
X_train['als_score'] = X_train.apply(
    lambda row: get_als_score(row['vacancy_id'], row['resume_id']), 
    axis=1
)

X_train = X_train.drop(['vacancy_id', 'resume_id'], axis=1)

  0%|          | 0/30 [00:00<?, ?it/s]

In [94]:
# проверим есть ли вакансии и резюме без взаимодействий до обучения
X_train[X_train['als_score'] == 0]

,vacancy_area,vacancy_experience,vacancy_employment,vacancy_schedule,resume_salary,resume_age,resume_experience_months,resume_location,resume_gender,resume_applicant_status,resume_last_company_experience_months,location_matching,resume_skill_count_in_vacancy,last_position_in_vacancy,similarity_score_tfidf,als_score
286115,Москва,От 3 до 6 лет,Полная занятость,Удаленная работа,40000.0,38.0,223.0,Москва,Неизвестно,NDT,208.0,1,0,0.25,0.015081,0.0
216165,Москва,От 1 года до 3 лет,Полная занятость,Удаленная работа,150000.0,35.0,152.0,Москва,Мужчина,Активно ищет работу,89.0,1,0,0.00,0.038536,0.0
297591,Москва,От 3 до 6 лет,Полная занятость,Удаленная работа,150000.0,35.0,152.0,Москва,Мужчина,Активно ищет работу,89.0,1,0,0.00,0.016496,0.0
192099,Москва,Более 6 лет,Полная занятость,Полный день,30000.0,57.0,289.0,Москва,Мужчина,NDT,170.0,1,0,0.00,0.000000,0.0
82523,Москва,От 1 года до 3 лет,Полная занятость,Удаленная работа,0.0,38.0,185.0,Москва,Мужчина,NDT,114.0,1,4,0.00,0.063418,0.0
32590,Москва,От 3 до 6 лет,Полная занятость,Удаленная работа,0.0,38.0,185.0,Москва,Мужчина,NDT,114.0,1,2,0.00,0.101719,0.0
260861,Москва,От 1 года до 3 лет,Полная занятость,Удаленная работа,30000.0,57.0,289.0,Москва,Мужчина,NDT,170.0,1,0,0.00,0.020658,0.0
52865,Москва,От 3 до 6 лет,Полная занятость,Удаленная работа,150000.0,35.0,152.0,Москва,Мужчина,Активно ищет работу,89.0,1,0,0.00,0.011811,0.0
175258,Москва,От 1 года до 3 лет,Полная занятость,Удаленная работа,150000.0,35.0,152.0,Москва,Мужчина,Активно ищет работу,89.0,1,0,0.00,0.021698,0.0
217714,Москва,От 3 до 6 лет,Полная занятость,Удаленная работа,150000.0,35.0,152.0,Москва,Мужчина,Активно ищет работу,89.0,1,0,0.00,0.012118,0.0
193275,Москва,От 1 года до 3 лет,Полная занятость,Удаленная работа,150000.0,35.0,152.0,Москва,Мужчина,Активно ищет работу,89.0,1,0,0.00,0.016826,0.0
258695,Москва,От 1 года до 3 лет,Полная занятость,Полный день,0.0,26.0,52.0,Москва,Мужчина,Активно ищет работу,22.0,1,0,0.00,0.028331,0.0
59178,Москва,От 3 до 6 лет,Полная занятость,Удаленная работа,30000.0,57.0,289.0,Москва,Мужчина,NDT,170.0,1,0,0.00,0.024778,0.0
85465,Москва,Более 6 лет,Полная занятость,Удаленная работа,0.0,38.0,185.0,Москва,Мужчина,NDT,114.0,1,0,0.00,0.070065,0.0

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

Теперь добавим признак `als_score` для тестовой выборке, но уже возьмем матрицу интеракций на полной тренировочной выборке.

</div>

In [95]:
train_interactions = df.loc[X_train.index, ['vacancy_id', 'resume_id', 'target']]

interactions_matrix, id2vacancy, id2resume, vacancy2id, resume2id, unique_vacancies, unique_resumes = create_interaction_matrix(train_interactions)
vacancy_factors, resume_factors = get_factors(interactions_matrix)

# возвращаем айдишники вакансий и резюме для расчета als score
X_test[['vacancy_id', 'resume_id']] = df.loc[X_test.index, ['vacancy_id', 'resume_id']]
X_test['als_score'] = X_test.apply(
    lambda row: get_als_score(row['vacancy_id'], row['resume_id']), 
    axis=1
)

X_test = X_test.drop(['vacancy_id', 'resume_id'], axis=1)

  0%|          | 0/30 [00:00<?, ?it/s]

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

Выборки получены, обучим `XGBClassifier` с подбором гиперпараметров.

</div>

In [96]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 257313 entries, 188418 to 283280
Data columns (total 16 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   vacancy_area                           257313 non-null  object
 1   vacancy_experience                     257313 non-null  object
 2   vacancy_employment                     257313 non-null  object
 3   vacancy_schedule                       257313 non-null  object
 4   resume_salary                          257313 non-null  float64
 5   resume_age                             257313 non-null  float64
 6   resume_experience_months               257313 non-null  float64
 7   resume_location                        257313 non-null  object
 8   resume_gender                          257313 non-null  object
 9   resume_applicant_status                257313 non-null  object
 10  resume_last_company_experience_months  257313 non-null  float64
 11  location_matching                      257313 non-null  int64
 12  resume_skill_count_in_vacancy          257313 non-null  int64
 13  last_position_in_vacancy               257313 non-null  float64
 14  similarity_score_tfidf                 257313 non-null  float64
 15  als_score                              257313 non-null  float64
dtypes: float64(7), int64(2), object(7)
memory usage: 33.4+ MB

## XGBClassifier

In [155]:
def objective_xgb(trial: optuna.Trial) -> float:
    params = {
        'model__n_estimators': trial.suggest_int('n_estimators', 100, 1000, step=50),
        'model__max_depth': trial.suggest_int('max_depth', 3, 15),
        'model__learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'model__min_child_weight': trial.suggest_int('min_child_weight', 1, 10)
    }
    
    pipeline_xgb = Pipeline([
        ('preprocessing', ColumnTransformer([
            ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
        ], remainder='passthrough')),
        ('model', XGBClassifier(
            random_state=RANDOM_STATE, 
            eval_metric='logloss', 
            use_label_encoder=False, 
            verbosity=0,
            scale_pos_weight=(len(y_train) - sum(y_train)) / sum(y_train)
        ))
    ])
    
    pipeline_xgb.set_params(**params)
    
    kfold = StratifiedKFold(n_splits=3, shuffle=True, random_state=RANDOM_STATE)
    
    for train_idx, val_idx in kfold.split(X_train, y_train):
        X_fold_train, X_fold_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_fold_train, y_fold_val = y_train.iloc[train_idx], y_train.iloc[val_idx]
        
        pipeline_xgb.fit(X_fold_train, y_fold_train)
        y_pred_proba = pipeline_xgb.predict_proba(X_fold_val)
        
        df_val = df.loc[X_fold_val.index].copy()
        df_val['y_pred_proba'] = y_pred_proba[:, 1]
        
        ndcg, _, _, _ = calculate_metrics(df_val)
        
        trial.set_user_attr('pipeline_params', params)
    
    return ndcg

In [156]:
try:
    experiment_id = mlflow.get_experiment_by_name(EXPERIMENT_NAME).experiment_id
except:
    experiment_id = mlflow.create_experiment(EXPERIMENT_NAME)

RUN_NAME_OPTUNE_XGB = 'XGBClassifier_optuna_als'

with mlflow.start_run(run_name=RUN_NAME_OPTUNE_XGB, experiment_id=experiment_id) as run:
    run_id_xgb = run.info.run_id

🏃 View run XGBClassifier_optuna_als at: http://127.0.0.1:5000/#/experiments/4/runs/5ca02b043a0d40e192b7c3b929678b00
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

In [157]:
STUDY_NAME_XGB = "XGBClassifier_optuna_als"

mlflc_xgb = MLflowCallback(
    tracking_uri=f'http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}',
    metric_name="NDCG",
    create_experiment=False,
    mlflow_kwargs={'experiment_id': experiment_id, 'tags': {MLFLOW_PARENT_RUN_ID: run_id_xgb}}
)

In [158]:
study_xgb = optuna.create_study(direction='maximize', 
                                sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
                                study_name=STUDY_NAME_XGB,
                                storage=STUDY_DB_NAME,
                                load_if_exists=False)

study_xgb.optimize(objective_xgb, 
                   n_trials=20, 
                   callbacks=[mlflc_xgb]
                  )

best_params_xgb = study_xgb.best_params
print(f"Number of finished trials: {len(study_xgb.trials)}")
print(f"Best params XGBoost: {best_params_xgb}")

[I 2026-05-08 13:43:46,145] A new study created in RDB with name: XGBClassifier_optuna_als

Средний NDCG: 0.8671
Средний Precision: 0.8041
Средний Recall: 0.8249
Средний F1-Score: 0.8053
Средний NDCG: 0.8577
Средний Precision: 0.7954
Средний Recall: 0.8186
Средний F1-Score: 0.7970

[I 2026-05-08 13:44:06,674] Trial 0 finished with value: 0.862374049641984 and parameters: {'n_estimators': 450, 'max_depth': 15, 'learning_rate': 0.1205712628744377, 'min_child_weight': 6}. Best is trial 0 with value: 0.862374049641984.

Средний NDCG: 0.8624
Средний Precision: 0.7982
Средний Recall: 0.8189
Средний F1-Score: 0.7986
🏃 View run 0 at: http://127.0.0.1:5000/#/experiments/4/runs/15b5da731f014d5d9ac2b94752425861
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8654
Средний Precision: 0.7224
Средний Recall: 0.8518
Средний F1-Score: 0.7650
Средний NDCG: 0.8566
Средний Precision: 0.7141
Средний Recall: 0.8398
Средний F1-Score: 0.7554

[I 2026-05-08 13:44:20,113] Trial 1 finished with value: 0.8600862278339769 and parameters: {'n_estimators': 200, 'max_depth': 5, 'learning_rate': 0.012184186502221764, 'min_child_weight': 9}. Best is trial 0 with value: 0.862374049641984.

Средний NDCG: 0.8601
Средний Precision: 0.7243
Средний Recall: 0.8442
Средний F1-Score: 0.7637
🏃 View run 1 at: http://127.0.0.1:5000/#/experiments/4/runs/dc73ef6342974295bab99c0ab5e85557
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8675
Средний Precision: 0.7831
Средний Recall: 0.8419
Средний F1-Score: 0.8002
Средний NDCG: 0.8577
Средний Precision: 0.7735
Средний Recall: 0.8338
Средний F1-Score: 0.7909

[I 2026-05-08 13:44:43,195] Trial 2 finished with value: 0.8622602315525298 and parameters: {'n_estimators': 650, 'max_depth': 12, 'learning_rate': 0.010725209743171997, 'min_child_weight': 10}. Best is trial 0 with value: 0.862374049641984.

Средний NDCG: 0.8623
Средний Precision: 0.7773
Средний Recall: 0.8346
Средний F1-Score: 0.7933
🏃 View run 2 at: http://127.0.0.1:5000/#/experiments/4/runs/4be37d7468e1461cb4b8b2ce77a84b0c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8681
Средний Precision: 0.7473
Средний Recall: 0.8545
Средний F1-Score: 0.7827
Средний NDCG: 0.8584
Средний Precision: 0.7402
Средний Recall: 0.8420
Средний F1-Score: 0.7734

[I 2026-05-08 13:45:01,462] Trial 3 finished with value: 0.8631784484452834 and parameters: {'n_estimators': 850, 'max_depth': 5, 'learning_rate': 0.01855998084649058, 'min_child_weight': 2}. Best is trial 3 with value: 0.8631784484452834.

Средний NDCG: 0.8632
Средний Precision: 0.7483
Средний Recall: 0.8472
Средний F1-Score: 0.7807
🏃 View run 3 at: http://127.0.0.1:5000/#/experiments/4/runs/b69db070daa4421fbf91fe672710eaae
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8675
Средний Precision: 0.7881
Средний Recall: 0.8384
Средний F1-Score: 0.8020
Средний NDCG: 0.8577
Средний Precision: 0.7800
Средний Recall: 0.8302
Средний F1-Score: 0.7932

[I 2026-05-08 13:45:18,123] Trial 4 finished with value: 0.8630823725553375 and parameters: {'n_estimators': 350, 'max_depth': 9, 'learning_rate': 0.04345454109729477, 'min_child_weight': 3}. Best is trial 3 with value: 0.8631784484452834.

Средний NDCG: 0.8631
Средний Precision: 0.7853
Средний Recall: 0.8323
Средний F1-Score: 0.7972
🏃 View run 4 at: http://127.0.0.1:5000/#/experiments/4/runs/6532f6dbd0204a09a967e38294277fda
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8681
Средний Precision: 0.7374
Средний Recall: 0.8543
Средний F1-Score: 0.7760
Средний NDCG: 0.8581
Средний Precision: 0.7333
Средний Recall: 0.8435
Средний F1-Score: 0.7695

[I 2026-05-08 13:45:34,411] Trial 5 finished with value: 0.8625217210414047 and parameters: {'n_estimators': 650, 'max_depth': 4, 'learning_rate': 0.027010527749605478, 'min_child_weight': 4}. Best is trial 3 with value: 0.8631784484452834.

Средний NDCG: 0.8625
Средний Precision: 0.7376
Средний Recall: 0.8494
Средний F1-Score: 0.7749
🏃 View run 5 at: http://127.0.0.1:5000/#/experiments/4/runs/3b84de6dd0ac4beb8e0a630ef1d70669
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8674
Средний Precision: 0.7924
Средний Recall: 0.8331
Средний F1-Score: 0.8020
Средний NDCG: 0.8582
Средний Precision: 0.7861
Средний Recall: 0.8280
Средний F1-Score: 0.7958

[I 2026-05-08 13:45:56,289] Trial 6 finished with value: 0.8630566787449119 and parameters: {'n_estimators': 500, 'max_depth': 13, 'learning_rate': 0.019721610970574007, 'min_child_weight': 6}. Best is trial 3 with value: 0.8631784484452834.

Средний NDCG: 0.8631
Средний Precision: 0.7863
Средний Recall: 0.8279
Средний F1-Score: 0.7959
🏃 View run 6 at: http://127.0.0.1:5000/#/experiments/4/runs/43652c7163174385aa9b9e0ed82d2f65
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8675
Средний Precision: 0.7462
Средний Recall: 0.8541
Средний F1-Score: 0.7822
Средний NDCG: 0.8577
Средний Precision: 0.7416
Средний Recall: 0.8435
Средний F1-Score: 0.7750

[I 2026-05-08 13:46:12,854] Trial 7 finished with value: 0.8624138221106981 and parameters: {'n_estimators': 650, 'max_depth': 3, 'learning_rate': 0.07896186801026692, 'min_child_weight': 2}. Best is trial 3 with value: 0.8631784484452834.

Средний NDCG: 0.8624
Средний Precision: 0.7472
Средний Recall: 0.8477
Средний F1-Score: 0.7807
🏃 View run 7 at: http://127.0.0.1:5000/#/experiments/4/runs/2e89ff45d85f4beb83d2545014fd6864
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8659
Средний Precision: 0.8019
Средний Recall: 0.8250
Средний F1-Score: 0.8038
Средний NDCG: 0.8571
Средний Precision: 0.7955
Средний Recall: 0.8205
Средний F1-Score: 0.7977

[I 2026-05-08 13:46:29,005] Trial 8 finished with value: 0.8625144538300084 and parameters: {'n_estimators': 150, 'max_depth': 15, 'learning_rate': 0.26690431824362526, 'min_child_weight': 9}. Best is trial 3 with value: 0.8631784484452834.

Средний NDCG: 0.8625
Средний Precision: 0.7973
Средний Recall: 0.8219
Средний F1-Score: 0.7991
🏃 View run 8 at: http://127.0.0.1:5000/#/experiments/4/runs/62b7a8110af34f6eb0528ccb551ccdaa
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8680
Средний Precision: 0.7517
Средний Recall: 0.8531
Средний F1-Score: 0.7851
Средний NDCG: 0.8576
Средний Precision: 0.7448
Средний Recall: 0.8429
Средний F1-Score: 0.7766

[I 2026-05-08 13:46:44,234] Trial 9 finished with value: 0.8629562210108517 and parameters: {'n_estimators': 350, 'max_depth': 4, 'learning_rate': 0.1024932221692416, 'min_child_weight': 5}. Best is trial 3 with value: 0.8631784484452834.

Средний NDCG: 0.8630
Средний Precision: 0.7531
Средний Recall: 0.8477
Средний F1-Score: 0.7841
🏃 View run 9 at: http://127.0.0.1:5000/#/experiments/4/runs/ad05e0c41a6848b8945a2bf19ca32b35
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8677
Средний Precision: 0.7891
Средний Recall: 0.8389
Средний F1-Score: 0.8027
Средний NDCG: 0.8579
Средний Precision: 0.7814
Средний Recall: 0.8315
Средний F1-Score: 0.7950

[I 2026-05-08 13:47:05,924] Trial 10 finished with value: 0.8633361540747726 and parameters: {'n_estimators': 1000, 'max_depth': 7, 'learning_rate': 0.03504750508385013, 'min_child_weight': 1}. Best is trial 10 with value: 0.8633361540747726.

Средний NDCG: 0.8633
Средний Precision: 0.7871
Средний Recall: 0.8345
Средний F1-Score: 0.7995
🏃 View run 10 at: http://127.0.0.1:5000/#/experiments/4/runs/90f53fb1a86941c2ad396e93761f69df
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8681
Средний Precision: 0.7900
Средний Recall: 0.8394
Средний F1-Score: 0.8034
Средний NDCG: 0.8576
Средний Precision: 0.7794
Средний Recall: 0.8324
Средний F1-Score: 0.7941

[I 2026-05-08 13:47:27,550] Trial 11 finished with value: 0.8633593145079731 and parameters: {'n_estimators': 1000, 'max_depth': 7, 'learning_rate': 0.03445887563419279, 'min_child_weight': 1}. Best is trial 11 with value: 0.8633593145079731.

Средний NDCG: 0.8634
Средний Precision: 0.7862
Средний Recall: 0.8347
Средний F1-Score: 0.7991
🏃 View run 11 at: http://127.0.0.1:5000/#/experiments/4/runs/f078033158814160a4645bb10367887b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8678
Средний Precision: 0.8020
Средний Recall: 0.8306
Средний F1-Score: 0.8062
Средний NDCG: 0.8577
Средний Precision: 0.7937
Средний Recall: 0.8247
Средний F1-Score: 0.7989

[I 2026-05-08 13:47:50,507] Trial 12 finished with value: 0.862997692419074 and parameters: {'n_estimators': 1000, 'max_depth': 8, 'learning_rate': 0.04472412777512317, 'min_child_weight': 1}. Best is trial 11 with value: 0.8633593145079731.

Средний NDCG: 0.8630
Средний Precision: 0.7952
Средний Recall: 0.8256
Средний F1-Score: 0.8000
🏃 View run 12 at: http://127.0.0.1:5000/#/experiments/4/runs/d893131a76c24d4cb7f0049eadbb3a81
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8684
Средний Precision: 0.7884
Средний Recall: 0.8397
Средний F1-Score: 0.8022
Средний NDCG: 0.8577
Средний Precision: 0.7783
Средний Recall: 0.8330
Средний F1-Score: 0.7938

[I 2026-05-08 13:48:12,208] Trial 13 finished with value: 0.8634783775833251 and parameters: {'n_estimators': 1000, 'max_depth': 7, 'learning_rate': 0.031543166246511836, 'min_child_weight': 1}. Best is trial 13 with value: 0.8634783775833251.

Средний NDCG: 0.8635
Средний Precision: 0.7856
Средний Recall: 0.8363
Средний F1-Score: 0.7995
🏃 View run 13 at: http://127.0.0.1:5000/#/experiments/4/runs/3a18c62eecbe4329900af952bc4664ad
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8682
Средний Precision: 0.7942
Средний Recall: 0.8368
Средний F1-Score: 0.8046
Средний NDCG: 0.8572
Средний Precision: 0.7868
Средний Recall: 0.8285
Средний F1-Score: 0.7970

[I 2026-05-08 13:48:32,680] Trial 14 finished with value: 0.8631280667301211 and parameters: {'n_estimators': 850, 'max_depth': 7, 'learning_rate': 0.05932349924052295, 'min_child_weight': 3}. Best is trial 13 with value: 0.8634783775833251.

Средний NDCG: 0.8631
Средний Precision: 0.7929
Средний Recall: 0.8314
Средний F1-Score: 0.8013
🏃 View run 14 at: http://127.0.0.1:5000/#/experiments/4/runs/d0e6744721a74d09b7b04f17413bce08
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8681
Средний Precision: 0.8017
Средний Recall: 0.8261
Средний F1-Score: 0.8045
Средний NDCG: 0.8578
Средний Precision: 0.7949
Средний Recall: 0.8195
Средний F1-Score: 0.7970

[I 2026-05-08 13:48:57,910] Trial 15 finished with value: 0.8629509968358297 and parameters: {'n_estimators': 850, 'max_depth': 11, 'learning_rate': 0.025774599003700965, 'min_child_weight': 1}. Best is trial 13 with value: 0.8634783775833251.

Средний NDCG: 0.8630
Средний Precision: 0.7963
Средний Recall: 0.8212
Средний F1-Score: 0.7989
🏃 View run 15 at: http://127.0.0.1:5000/#/experiments/4/runs/ac91ac4f4ab14401bf201ead2dd1fa77
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8663
Средний Precision: 0.8035
Средний Recall: 0.8215
Средний F1-Score: 0.8029
Средний NDCG: 0.8557
Средний Precision: 0.7990
Средний Recall: 0.8167
Средний F1-Score: 0.7979

[I 2026-05-08 13:49:21,772] Trial 16 finished with value: 0.8624495119318226 and parameters: {'n_estimators': 900, 'max_depth': 10, 'learning_rate': 0.20591818942346019, 'min_child_weight': 7}. Best is trial 13 with value: 0.8634783775833251.

Средний NDCG: 0.8624
Средний Precision: 0.8016
Средний Recall: 0.8180
Средний F1-Score: 0.7999
🏃 View run 16 at: http://127.0.0.1:5000/#/experiments/4/runs/ef535a4c490b44a5b2dee30bfab72145
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8677
Средний Precision: 0.7937
Средний Recall: 0.8386
Средний F1-Score: 0.8052
Средний NDCG: 0.8577
Средний Precision: 0.7830
Средний Recall: 0.8308
Средний F1-Score: 0.7957

[I 2026-05-08 13:49:41,317] Trial 17 finished with value: 0.8634109893312404 and parameters: {'n_estimators': 750, 'max_depth': 7, 'learning_rate': 0.060858530583022305, 'min_child_weight': 4}. Best is trial 13 with value: 0.8634783775833251.

Средний NDCG: 0.8634
Средний Precision: 0.7902
Средний Recall: 0.8334
Средний F1-Score: 0.8008
🏃 View run 17 at: http://127.0.0.1:5000/#/experiments/4/runs/ccbba7a56f80439c818685d4414b58ed
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8676
Средний Precision: 0.7861
Средний Recall: 0.8438
Средний F1-Score: 0.8027
Средний NDCG: 0.8582
Средний Precision: 0.7743
Средний Recall: 0.8343
Средний F1-Score: 0.7917

[I 2026-05-08 13:49:59,584] Trial 18 finished with value: 0.8628368522191118 and parameters: {'n_estimators': 700, 'max_depth': 6, 'learning_rate': 0.06692989126162775, 'min_child_weight': 4}. Best is trial 13 with value: 0.8634783775833251.

Средний NDCG: 0.8628
Средний Precision: 0.7833
Средний Recall: 0.8376
Средний F1-Score: 0.7984
🏃 View run 18 at: http://127.0.0.1:5000/#/experiments/4/runs/c805ca20b1fb48829268a156008c3986
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8663
Средний Precision: 0.8042
Средний Recall: 0.8245
Средний F1-Score: 0.8049
Средний NDCG: 0.8571
Средний Precision: 0.7963
Средний Recall: 0.8191
Средний F1-Score: 0.7979

[I 2026-05-08 13:50:21,316] Trial 19 finished with value: 0.8625694451730985 and parameters: {'n_estimators': 750, 'max_depth': 9, 'learning_rate': 0.1536344370984978, 'min_child_weight': 7}. Best is trial 13 with value: 0.8634783775833251.

Средний NDCG: 0.8626
Средний Precision: 0.8001
Средний Recall: 0.8215
Средний F1-Score: 0.8008
🏃 View run 19 at: http://127.0.0.1:5000/#/experiments/4/runs/4b214513bad84697b42c67d8543e2807
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Number of finished trials: 20
Best params XGBoost: {'n_estimators': 1000, 'max_depth': 7, 'learning_rate': 0.031543166246511836, 'min_child_weight': 1}

In [159]:
pipeline_xgb_best = Pipeline([
    ('preprocessing', ColumnTransformer([
        ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
    ], remainder='passthrough')),
    ('model', XGBClassifier(
        random_state=RANDOM_STATE, 
        eval_metric='logloss', 
        use_label_encoder=False, 
        verbosity=0,
        scale_pos_weight=(len(y_train) - sum(y_train)) / sum(y_train)
    ))
])

pipeline_xgb_best.set_params(**study_xgb.best_trial.user_attrs['pipeline_params'])
pipeline_xgb_best.fit(X_train, y_train)

y_pred_proba_xgb = pipeline_xgb_best.predict_proba(X_test)

df_test_xgb = df.loc[X_test.index].copy()
df_test_xgb['y_pred_proba'] = y_pred_proba_xgb[:, 1]

ndcg_xgb_als, precision_xgb_als, recall_xgb_als, f1_xgb_als = calculate_metrics(df_test_xgb)
metrics_xgb_als = {
    'NDCG': ndcg_xgb_als,
    'Precision': precision_xgb_als,
    'Recall': recall_xgb_als,
    'F1': f1_xgb_als
}

Средний NDCG: 0.7816
Средний Precision: 0.7035
Средний Recall: 0.7550
Средний F1-Score: 0.7159

In [160]:
RUN_NAME_XGB = "best_optuna_xgb_als"
REGISTRY_MODEL_NAME_XGB = "best_optuna_xgb_als"

signature = mlflow.models.infer_signature(X_test, y_test)
input_example = X_test[:10]
code_paths = ["ML_Experiments.ipynb"]

with mlflow.start_run(run_name=RUN_NAME_XGB, experiment_id=experiment_id) as run:
    run_id = run.info.run_id
    
    xgb_info = mlflow.sklearn.log_model(sk_model=pipeline_xgb_best, 
                                       artifact_path='best_optuna_xgb_als',
                                       registered_model_name=REGISTRY_MODEL_NAME_XGB,
                                       input_example=input_example,
                                       code_paths=code_paths,
                                       await_registration_for=60
                                      )
    mlflow.log_metrics(metrics_xgb_als)
    mlflow.log_params(best_params_xgb)

Registered model 'best_optuna_xgb_als' already exists. Creating a new version of this model...
2026/05/08 13:50:31 INFO mlflow.store.model_registry.abstract_store: Waiting up to 60 seconds for model version to finish creation. Model name: best_optuna_xgb_als, version 9

🏃 View run best_optuna_xgb_als at: http://127.0.0.1:5000/#/experiments/4/runs/c44c2cc749be4c7c8e02c45d7ee3e9ca
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

Created version '9' of model 'best_optuna_xgb_als'.

## LGBMClassifier

In [161]:
def objective_lgbm(trial: optuna.Trial) -> float:
    params = {
        'model__n_estimators': trial.suggest_int('n_estimators', 100, 1000, step=50),
        'model__max_depth': trial.suggest_int('max_depth', 3, 15),
        'model__learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'model__num_leaves': trial.suggest_int('num_leaves', 20, 300),
        'model__min_child_samples': trial.suggest_int('min_child_samples', 5, 100)
    }
    
    pipeline_lgbm = Pipeline([
        ('preprocessing', ColumnTransformer([
            ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
        ], remainder='passthrough')),
        ('model', LGBMClassifier(
            random_state=RANDOM_STATE, 
            verbose=-1,
            class_weight='balanced'
        ))
    ])
    
    pipeline_lgbm.set_params(**params)
    
    kfold = StratifiedKFold(n_splits=3, shuffle=True, random_state=RANDOM_STATE)
    
    for train_idx, val_idx in kfold.split(X_train, y_train):
        X_fold_train, X_fold_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_fold_train, y_fold_val = y_train.iloc[train_idx], y_train.iloc[val_idx]
        
        pipeline_lgbm.fit(X_fold_train, y_fold_train)
        y_pred_proba = pipeline_lgbm.predict_proba(X_fold_val)
        
        df_val = df.loc[X_fold_val.index].copy()
        df_val['y_pred_proba'] = y_pred_proba[:, 1]
        
        ndcg, _, _, _ = calculate_metrics(df_val)
        
        trial.set_user_attr('pipeline_params', params)
    
    return ndcg

In [162]:
RUN_NAME_OPTUNE_LGBM = 'LGBMClassifier_optuna_als'

with mlflow.start_run(run_name=RUN_NAME_OPTUNE_LGBM, experiment_id=experiment_id) as run:
    run_id_lgbm = run.info.run_id

🏃 View run LGBMClassifier_optuna_als at: http://127.0.0.1:5000/#/experiments/4/runs/055bb6b8fe114e2cb59c37d0c3fd624b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

In [163]:
STUDY_NAME_LGBM = "LGBMClassifier_optuna_als"

mlflc_lgbm = MLflowCallback(
    tracking_uri=f'http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}',
    metric_name="NDCG",
    create_experiment=False,
    mlflow_kwargs={'experiment_id': experiment_id, 'tags': {MLFLOW_PARENT_RUN_ID: run_id_lgbm}}
)

In [164]:
study_lgbm = optuna.create_study(direction='maximize', 
                                 sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
                                 study_name=STUDY_NAME_LGBM,
                                 storage=STUDY_DB_NAME,
                                 load_if_exists=False)

study_lgbm.optimize(objective_lgbm, 
                    n_trials=20, 
                    callbacks=[mlflc_lgbm]
                   )

best_params_lgbm = study_lgbm.best_params
print(f"Number of finished trials: {len(study_lgbm.trials)}")
print(f"Best params LGBM: {best_params_lgbm}")

[I 2026-05-08 13:50:31,385] A new study created in RDB with name: LGBMClassifier_optuna_als

Средний NDCG: 0.8674
Средний Precision: 0.8066
Средний Recall: 0.8177
Средний F1-Score: 0.8029
Средний NDCG: 0.8570
Средний Precision: 0.8012
Средний Recall: 0.8145
Средний F1-Score: 0.7986

[I 2026-05-08 13:51:48,464] Trial 0 finished with value: 0.8625345482755766 and parameters: {'n_estimators': 450, 'max_depth': 15, 'learning_rate': 0.1205712628744377, 'num_leaves': 188, 'min_child_samples': 19}. Best is trial 0 with value: 0.8625345482755766.

Средний NDCG: 0.8625
Средний Precision: 0.8022
Средний Recall: 0.8118
Средний F1-Score: 0.7972
🏃 View run 0 at: http://127.0.0.1:5000/#/experiments/4/runs/a801362c7b2940cbb9db9e0463471748
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8677
Средний Precision: 0.7433
Средний Recall: 0.8557
Средний F1-Score: 0.7809
Средний NDCG: 0.8579
Средний Precision: 0.7355
Средний Recall: 0.8442
Средний F1-Score: 0.7714

[I 2026-05-08 13:52:02,627] Trial 1 finished with value: 0.8627822824951703 and parameters: {'n_estimators': 200, 'max_depth': 3, 'learning_rate': 0.19030368381735815, 'num_leaves': 188, 'min_child_samples': 72}. Best is trial 1 with value: 0.8627822824951703.

Средний NDCG: 0.8628
Средний Precision: 0.7421
Средний Recall: 0.8484
Средний F1-Score: 0.7777
🏃 View run 1 at: http://127.0.0.1:5000/#/experiments/4/runs/e93a7b147e5e4f5c9c510ef7f57ab5fc
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8676
Средний Precision: 0.7868
Средний Recall: 0.8424
Средний F1-Score: 0.8026
Средний NDCG: 0.8531
Средний Precision: 0.7649
Средний Recall: 0.8332
Средний F1-Score: 0.7847

[I 2026-05-08 13:52:21,821] Trial 2 finished with value: 0.8613598684064494 and parameters: {'n_estimators': 100, 'max_depth': 15, 'learning_rate': 0.1696753360719655, 'num_leaves': 79, 'min_child_samples': 22}. Best is trial 1 with value: 0.8627822824951703.

Средний NDCG: 0.8614
Средний Precision: 0.7783
Средний Recall: 0.8355
Средний F1-Score: 0.7946
🏃 View run 2 at: http://127.0.0.1:5000/#/experiments/4/runs/0107647837d64a98b5f81dc389297d06
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8680
Средний Precision: 0.7580
Средний Recall: 0.8515
Средний F1-Score: 0.7885
Средний NDCG: 0.8583
Средний Precision: 0.7500
Средний Recall: 0.8403
Средний F1-Score: 0.7789

[I 2026-05-08 13:52:42,541] Trial 3 finished with value: 0.8630777999467981 and parameters: {'n_estimators': 250, 'max_depth': 6, 'learning_rate': 0.05958389350068958, 'num_leaves': 141, 'min_child_samples': 32}. Best is trial 3 with value: 0.8630777999467981.

Средний NDCG: 0.8631
Средний Precision: 0.7580
Средний Recall: 0.8445
Средний F1-Score: 0.7857
🏃 View run 3 at: http://127.0.0.1:5000/#/experiments/4/runs/31f7e801a9c4459bb7547be627566bbc
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8679
Средний Precision: 0.7377
Средний Recall: 0.8542
Средний F1-Score: 0.7764
Средний NDCG: 0.8580
Средний Precision: 0.7316
Средний Recall: 0.8442
Средний F1-Score: 0.7689

[I 2026-05-08 13:53:02,182] Trial 4 finished with value: 0.863312213286162 and parameters: {'n_estimators': 650, 'max_depth': 4, 'learning_rate': 0.027010527749605478, 'num_leaves': 122, 'min_child_samples': 48}. Best is trial 4 with value: 0.863312213286162.

Средний NDCG: 0.8633
Средний Precision: 0.7381
Средний Recall: 0.8496
Средний F1-Score: 0.7752
🏃 View run 4 at: http://127.0.0.1:5000/#/experiments/4/runs/4f57e3654e9d4939a3ee79af53914c4a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8681
Средний Precision: 0.7759
Средний Recall: 0.8482
Средний F1-Score: 0.7982
Средний NDCG: 0.8573
Средний Precision: 0.7634
Средний Recall: 0.8371
Средний F1-Score: 0.7860

[I 2026-05-08 13:53:30,162] Trial 5 finished with value: 0.8634487116696149 and parameters: {'n_estimators': 800, 'max_depth': 5, 'learning_rate': 0.05748924681991978, 'num_leaves': 186, 'min_child_samples': 9}. Best is trial 5 with value: 0.8634487116696149.

Средний NDCG: 0.8634
Средний Precision: 0.7742
Средний Recall: 0.8415
Средний F1-Score: 0.7946
🏃 View run 5 at: http://127.0.0.1:5000/#/experiments/4/runs/2c9cbb160ec84e538ff044f2f6eb0a7a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8678
Средний Precision: 0.7347
Средний Recall: 0.8530
Средний F1-Score: 0.7737
Средний NDCG: 0.8579
Средний Precision: 0.7273
Средний Recall: 0.8428
Средний F1-Score: 0.7658

[I 2026-05-08 13:53:55,857] Trial 6 finished with value: 0.8630086763310024 and parameters: {'n_estimators': 650, 'max_depth': 5, 'learning_rate': 0.012476394272569451, 'num_leaves': 286, 'min_child_samples': 97}. Best is trial 5 with value: 0.8634487116696149.

Средний NDCG: 0.8630
Средний Precision: 0.7344
Средний Recall: 0.8482
Средний F1-Score: 0.7722
🏃 View run 6 at: http://127.0.0.1:5000/#/experiments/4/runs/b3a521fc658e4f6ba1a423c65feadfaa
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8681
Средний Precision: 0.7514
Средний Recall: 0.8529
Средний F1-Score: 0.7846
Средний NDCG: 0.8586
Средний Precision: 0.7419
Средний Recall: 0.8406
Средний F1-Score: 0.7740

[I 2026-05-08 13:54:35,661] Trial 7 finished with value: 0.8632690819269457 and parameters: {'n_estimators': 850, 'max_depth': 6, 'learning_rate': 0.013940346079873234, 'num_leaves': 212, 'min_child_samples': 47}. Best is trial 5 with value: 0.8634487116696149.

Средний NDCG: 0.8633
Средний Precision: 0.7522
Средний Recall: 0.8454
Средний F1-Score: 0.7824
🏃 View run 7 at: http://127.0.0.1:5000/#/experiments/4/runs/0b69eb8c6a684f28a019bf542dc7342e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8664
Средний Precision: 0.7503
Средний Recall: 0.8477
Средний F1-Score: 0.7820
Средний NDCG: 0.8570
Средний Precision: 0.7428
Средний Recall: 0.8378
Средний F1-Score: 0.7731

[I 2026-05-08 13:55:22,654] Trial 8 finished with value: 0.8615850779882726 and parameters: {'n_estimators': 200, 'max_depth': 9, 'learning_rate': 0.011240768803005551, 'num_leaves': 275, 'min_child_samples': 29}. Best is trial 5 with value: 0.8634487116696149.

Средний NDCG: 0.8616
Средний Precision: 0.7476
Средний Recall: 0.8416
Средний F1-Score: 0.7777
🏃 View run 8 at: http://127.0.0.1:5000/#/experiments/4/runs/e766122548314d378646b17f829e4c92
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8680
Средний Precision: 0.7956
Средний Recall: 0.8356
Средний F1-Score: 0.8049
Средний NDCG: 0.8577
Средний Precision: 0.7853
Средний Recall: 0.8291
Средний F1-Score: 0.7956

[I 2026-05-08 13:56:11,388] Trial 9 finished with value: 0.8636492056769529 and parameters: {'n_estimators': 700, 'max_depth': 7, 'learning_rate': 0.05864129169696527, 'num_leaves': 173, 'min_child_samples': 22}. Best is trial 9 with value: 0.8636492056769529.

Средний NDCG: 0.8636
Средний Precision: 0.7923
Средний Recall: 0.8313
Средний F1-Score: 0.8011
🏃 View run 9 at: http://127.0.0.1:5000/#/experiments/4/runs/e878a0086bbe49218bbd59f2db34be53
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8682
Средний Precision: 0.7692
Средний Recall: 0.8500
Средний F1-Score: 0.7950
Средний NDCG: 0.8581
Средний Precision: 0.7612
Средний Recall: 0.8395
Средний F1-Score: 0.7861

[I 2026-05-08 13:56:45,434] Trial 10 finished with value: 0.8637826748847499 and parameters: {'n_estimators': 1000, 'max_depth': 10, 'learning_rate': 0.03001215871999436, 'num_leaves': 25, 'min_child_samples': 67}. Best is trial 10 with value: 0.8637826748847499.

Средний NDCG: 0.8638
Средний Precision: 0.7713
Средний Recall: 0.8447
Средний F1-Score: 0.7940
🏃 View run 10 at: http://127.0.0.1:5000/#/experiments/4/runs/8fd04dce9d794c1b9c2602c07dd8dbaa
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8681
Средний Precision: 0.7830
Средний Recall: 0.8446
Средний F1-Score: 0.8015
Средний NDCG: 0.8582
Средний Precision: 0.7733
Средний Recall: 0.8350
Средний F1-Score: 0.7914

[I 2026-05-08 13:57:30,686] Trial 11 finished with value: 0.8629233357693797 and parameters: {'n_estimators': 950, 'max_depth': 10, 'learning_rate': 0.03064831166443401, 'num_leaves': 44, 'min_child_samples': 75}. Best is trial 10 with value: 0.8637826748847499.

Средний NDCG: 0.8629
Средний Precision: 0.7800
Средний Recall: 0.8381
Средний F1-Score: 0.7963
🏃 View run 11 at: http://127.0.0.1:5000/#/experiments/4/runs/5037a084b2404cb199f4f23028a8d66a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8682
Средний Precision: 0.7803
Средний Recall: 0.8484
Средний F1-Score: 0.8011
Средний NDCG: 0.8581
Средний Precision: 0.7688
Средний Recall: 0.8385
Средний F1-Score: 0.7901

[I 2026-05-08 13:58:11,103] Trial 12 finished with value: 0.8627724170334539 and parameters: {'n_estimators': 1000, 'max_depth': 10, 'learning_rate': 0.03027496914953271, 'num_leaves': 34, 'min_child_samples': 69}. Best is trial 10 with value: 0.8637826748847499.

Средний NDCG: 0.8628
Средний Precision: 0.7779
Средний Recall: 0.8419
Средний F1-Score: 0.7970
🏃 View run 12 at: http://127.0.0.1:5000/#/experiments/4/runs/f55e147c851e4dee9f8044109e667f88
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8681
Средний Precision: 0.8021
Средний Recall: 0.8307
Средний F1-Score: 0.8064
Средний NDCG: 0.8579
Средний Precision: 0.7931
Средний Recall: 0.8233
Средний F1-Score: 0.7981

[I 2026-05-08 13:58:55,519] Trial 13 finished with value: 0.8636509139892738 and parameters: {'n_estimators': 550, 'max_depth': 8, 'learning_rate': 0.0914724739300992, 'num_leaves': 95, 'min_child_samples': 57}. Best is trial 10 with value: 0.8637826748847499.

Средний NDCG: 0.8637
Средний Precision: 0.7985
Средний Recall: 0.8245
Средний F1-Score: 0.8012
🏃 View run 13 at: http://127.0.0.1:5000/#/experiments/4/runs/5b68162ef9944183b6a3e177d2a4daf2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8680
Средний Precision: 0.8031
Средний Recall: 0.8274
Средний F1-Score: 0.8055
Средний NDCG: 0.8572
Средний Precision: 0.7954
Средний Recall: 0.8200
Средний F1-Score: 0.7978

[I 2026-05-08 13:59:39,367] Trial 14 finished with value: 0.8631637422090997 and parameters: {'n_estimators': 450, 'max_depth': 12, 'learning_rate': 0.10404269480978773, 'num_leaves': 92, 'min_child_samples': 61}. Best is trial 10 with value: 0.8637826748847499.

Средний NDCG: 0.8632
Средний Precision: 0.7988
Средний Recall: 0.8213
Средний F1-Score: 0.7998
🏃 View run 14 at: http://127.0.0.1:5000/#/experiments/4/runs/4cbab90893ff495ca8f4c6eb2eb613f3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8672
Средний Precision: 0.8073
Средний Recall: 0.8184
Средний F1-Score: 0.8037
Средний NDCG: 0.7666
Средний Precision: 0.6436
Средний Recall: 0.8206
Средний F1-Score: 0.6987

[I 2026-05-08 14:00:14,386] Trial 15 finished with value: 0.8620325641498809 and parameters: {'n_estimators': 500, 'max_depth': 8, 'learning_rate': 0.29596284206078843, 'num_leaves': 72, 'min_child_samples': 94}. Best is trial 10 with value: 0.8637826748847499.

Средний NDCG: 0.8620
Средний Precision: 0.8050
Средний Recall: 0.8139
Средний F1-Score: 0.7994
🏃 View run 15 at: http://127.0.0.1:5000/#/experiments/4/runs/0f9f2ac9b8034866a23be7e8e265573f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8686
Средний Precision: 0.7603
Средний Recall: 0.8523
Средний F1-Score: 0.7900
Средний NDCG: 0.8583
Средний Precision: 0.7499
Средний Recall: 0.8416
Средний F1-Score: 0.7798

[I 2026-05-08 14:00:45,610] Trial 16 finished with value: 0.8636133049218494 and parameters: {'n_estimators': 850, 'max_depth': 13, 'learning_rate': 0.021471858797027003, 'num_leaves': 25, 'min_child_samples': 82}. Best is trial 10 with value: 0.8637826748847499.

Средний NDCG: 0.8636
Средний Precision: 0.7599
Средний Recall: 0.8464
Средний F1-Score: 0.7875
🏃 View run 16 at: http://127.0.0.1:5000/#/experiments/4/runs/b7f02b3df0704541bc5e0291ed3d6fda
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8683
Средний Precision: 0.7896
Средний Recall: 0.8431
Средний F1-Score: 0.8045
Средний NDCG: 0.8582
Средний Precision: 0.7772
Средний Recall: 0.8337
Средний F1-Score: 0.7931

[I 2026-05-08 14:01:26,446] Trial 17 finished with value: 0.8629984049136082 and parameters: {'n_estimators': 350, 'max_depth': 12, 'learning_rate': 0.04171369403085501, 'num_leaves': 108, 'min_child_samples': 59}. Best is trial 10 with value: 0.8637826748847499.

Средний NDCG: 0.8630
Средний Precision: 0.7841
Средний Recall: 0.8354
Средний F1-Score: 0.7979
🏃 View run 17 at: http://127.0.0.1:5000/#/experiments/4/runs/1ce964a387e54c9b966ea4d3ed80a590
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8673
Средний Precision: 0.8007
Средний Recall: 0.8323
Средний F1-Score: 0.8069
Средний NDCG: 0.8576
Средний Precision: 0.7906
Средний Recall: 0.8217
Средний F1-Score: 0.7958

[I 2026-05-08 14:02:06,475] Trial 18 finished with value: 0.8634932238860895 and parameters: {'n_estimators': 600, 'max_depth': 10, 'learning_rate': 0.09176451790538694, 'num_leaves': 61, 'min_child_samples': 43}. Best is trial 10 with value: 0.8637826748847499.

Средний NDCG: 0.8635
Средний Precision: 0.7972
Средний Recall: 0.8239
Средний F1-Score: 0.8002
🏃 View run 18 at: http://127.0.0.1:5000/#/experiments/4/runs/32d5f66a2ea5446383736b406039723a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8680
Средний Precision: 0.7721
Средний Recall: 0.8482
Средний F1-Score: 0.7957
Средний NDCG: 0.8585
Средний Precision: 0.7633
Средний Recall: 0.8384
Средний F1-Score: 0.7867

[I 2026-05-08 14:03:07,333] Trial 19 finished with value: 0.8631535804301455 and parameters: {'n_estimators': 750, 'max_depth': 8, 'learning_rate': 0.018472389063302307, 'num_leaves': 138, 'min_child_samples': 86}. Best is trial 10 with value: 0.8637826748847499.

Средний NDCG: 0.8632
Средний Precision: 0.7691
Средний Recall: 0.8418
Средний F1-Score: 0.7913
🏃 View run 19 at: http://127.0.0.1:5000/#/experiments/4/runs/f5670aac7981490d8e2f5322a31f4899
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Number of finished trials: 20
Best params LGBM: {'n_estimators': 1000, 'max_depth': 10, 'learning_rate': 0.03001215871999436, 'num_leaves': 25, 'min_child_samples': 67}

In [165]:
pipeline_lgbm_best = Pipeline([
    ('preprocessing', ColumnTransformer([
        ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
    ], remainder='passthrough')),
    ('model', LGBMClassifier(
        random_state=RANDOM_STATE, 
        verbose=-1,
        class_weight='balanced'
    ))
])

pipeline_lgbm_best.set_params(**study_lgbm.best_trial.user_attrs['pipeline_params'])
pipeline_lgbm_best.fit(X_train, y_train)

y_pred_proba_lgbm = pipeline_lgbm_best.predict_proba(X_test)

df_test_lgbm = df.loc[X_test.index].copy()
df_test_lgbm['y_pred_proba'] = y_pred_proba_lgbm[:, 1]

ndcg_lgbm_als, precision_lgbm_als, recall_lgbm_als, f1_lgbm_als = calculate_metrics(df_test_lgbm)
metrics_lgbm_als = {
    'NDCG': ndcg_lgbm_als,
    'Precision': precision_lgbm_als,
    'Recall': recall_lgbm_als,
    'F1': f1_lgbm_als
}

Средний NDCG: 0.7814
Средний Precision: 0.6846
Средний Recall: 0.7595
Средний F1-Score: 0.7064

In [166]:
RUN_NAME_LGBM = "best_optuna_lgbm_als"
REGISTRY_MODEL_NAME_LGBM = "best_optuna_lgbm_als"

signature = mlflow.models.infer_signature(X_test, y_test)
input_example = X_test[:10]
code_paths = ["ML_Experiments.ipynb"]

with mlflow.start_run(run_name=RUN_NAME_LGBM, experiment_id=experiment_id) as run:
    run_id = run.info.run_id
    
    lgbm_info = mlflow.sklearn.log_model(sk_model=pipeline_lgbm_best, 
                                        artifact_path='best_optuna_lgbm_als',
                                        registered_model_name=REGISTRY_MODEL_NAME_LGBM,
                                        input_example=input_example,
                                        code_paths=code_paths,
                                        await_registration_for=60
                                       )
    mlflow.log_metrics(metrics_lgbm_als)
    mlflow.log_params(best_params_lgbm)

Registered model 'best_optuna_lgbm_als' already exists. Creating a new version of this model...
2026/05/08 14:03:21 INFO mlflow.store.model_registry.abstract_store: Waiting up to 60 seconds for model version to finish creation. Model name: best_optuna_lgbm_als, version 9

🏃 View run best_optuna_lgbm_als at: http://127.0.0.1:5000/#/experiments/4/runs/f95b58aa02a748da9021dcaa4bdd0358
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

Created version '9' of model 'best_optuna_lgbm_als'.

## CatBoostClassifier

In [167]:
def objective_catboost(trial: optuna.Trial) -> float:
    params = {
        'model__iterations': trial.suggest_int('iterations', 100, 1000, step=50),
        'model__depth': trial.suggest_int('depth', 3, 10),
        'model__learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'model__l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 1, 10, log=True)
    }
    
    pipeline_catboost = Pipeline([
        ('preprocessing', ColumnTransformer([
            ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
        ], remainder='passthrough')),
        ('model', CatBoostClassifier(
            random_state=RANDOM_STATE, 
            verbose=0, 
            auto_class_weights='Balanced'
        ))
    ])
    
    pipeline_catboost.set_params(**params)
    
    kfold = StratifiedKFold(n_splits=3, shuffle=True, random_state=RANDOM_STATE)
    
    for train_idx, val_idx in kfold.split(X_train, y_train):
        X_fold_train, X_fold_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_fold_train, y_fold_val = y_train.iloc[train_idx], y_train.iloc[val_idx]
        
        pipeline_catboost.fit(X_fold_train, y_fold_train)
        y_pred_proba = pipeline_catboost.predict_proba(X_fold_val)
        
        df_val = df.loc[X_fold_val.index].copy()
        df_val['y_pred_proba'] = y_pred_proba[:, 1]
        
        ndcg, _, _, _ = calculate_metrics(df_val)
        
        trial.set_user_attr('pipeline_params', params)
    
    return ndcg

In [168]:
RUN_NAME_OPTUNE_CATBOOST = 'CatBoostClassifier_optuna_als'

with mlflow.start_run(run_name=RUN_NAME_OPTUNE_CATBOOST, experiment_id=experiment_id) as run:
    run_id_catboost = run.info.run_id

🏃 View run CatBoostClassifier_optuna_als at: http://127.0.0.1:5000/#/experiments/4/runs/7c6550a9b25b4ba8ad5533ae07e4c47e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

In [169]:
STUDY_NAME_CATBOOST = "CatBoostClassifier_optuna_als"

mlflc_catboost = MLflowCallback(
    tracking_uri=f'http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}',
    metric_name="NDCG",
    create_experiment=False,
    mlflow_kwargs={'experiment_id': experiment_id, 'tags': {MLFLOW_PARENT_RUN_ID: run_id_catboost}}
)

In [170]:
study_catboost = optuna.create_study(direction='maximize', 
                                     sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
                                     study_name=STUDY_NAME_CATBOOST,
                                     storage=STUDY_DB_NAME,
                                     load_if_exists=True)

study_catboost.optimize(objective_catboost, 
                        n_trials=20, 
                        callbacks=[mlflc_catboost]
                       )

best_params_catboost = study_catboost.best_params
print(f"Number of finished trials: {len(study_catboost.trials)}")
print(f"Best params CatBoost: {best_params_catboost}")

[I 2026-05-08 14:03:21,241] A new study created in RDB with name: CatBoostClassifier_optuna_als

Средний NDCG: 0.8675
Средний Precision: 0.7940
Средний Recall: 0.8398
Средний F1-Score: 0.8061
Средний NDCG: 0.8574
Средний Precision: 0.7767
Средний Recall: 0.8346
Средний F1-Score: 0.7937

[I 2026-05-08 14:03:47,464] Trial 0 finished with value: 0.8630071503949772 and parameters: {'iterations': 450, 'depth': 10, 'learning_rate': 0.1205712628744377, 'l2_leaf_reg': 3.968793330444372}. Best is trial 0 with value: 0.8630071503949772.

Средний NDCG: 0.8630
Средний Precision: 0.7867
Средний Recall: 0.8376
Средний F1-Score: 0.8003
🏃 View run 0 at: http://127.0.0.1:5000/#/experiments/4/runs/f12c56023b48402392667bdb7e6f37a4
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8648
Средний Precision: 0.7135
Средний Recall: 0.8486
Средний F1-Score: 0.7581
Средний NDCG: 0.8546
Средний Precision: 0.7048
Средний Recall: 0.8401
Средний F1-Score: 0.7491

[I 2026-05-08 14:04:02,658] Trial 1 finished with value: 0.859660166890884 and parameters: {'iterations': 200, 'depth': 4, 'learning_rate': 0.012184186502221764, 'l2_leaf_reg': 7.348118405270449}. Best is trial 0 with value: 0.8630071503949772.

Средний NDCG: 0.8597
Средний Precision: 0.7160
Средний Recall: 0.8441
Средний F1-Score: 0.7582
🏃 View run 1 at: http://127.0.0.1:5000/#/experiments/4/runs/afad5f0c8aab4094b2919d15b9a389a2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8674
Средний Precision: 0.7365
Средний Recall: 0.8537
Средний F1-Score: 0.7752
Средний NDCG: 0.8576
Средний Precision: 0.7267
Средний Recall: 0.8436
Средний F1-Score: 0.7656

[I 2026-05-08 14:04:26,770] Trial 2 finished with value: 0.8633058135239318 and parameters: {'iterations': 650, 'depth': 8, 'learning_rate': 0.010725209743171997, 'l2_leaf_reg': 9.330606024425668}. Best is trial 2 with value: 0.8633058135239318.

Средний NDCG: 0.8633
Средний Precision: 0.7360
Средний Recall: 0.8484
Средний F1-Score: 0.7735
🏃 View run 2 at: http://127.0.0.1:5000/#/experiments/4/runs/7c18f5292b9b4030b9018801430a0bff
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8669
Средний Precision: 0.7316
Средний Recall: 0.8549
Средний F1-Score: 0.7722
Средний NDCG: 0.8576
Средний Precision: 0.7233
Средний Recall: 0.8442
Средний F1-Score: 0.7638

[I 2026-05-08 14:04:48,566] Trial 3 finished with value: 0.862283149144489 and parameters: {'iterations': 850, 'depth': 4, 'learning_rate': 0.01855998084649058, 'l2_leaf_reg': 1.5254729458052607}. Best is trial 2 with value: 0.8633058135239318.

Средний NDCG: 0.8623
Средний Precision: 0.7325
Средний Recall: 0.8484
Средний F1-Score: 0.7712
🏃 View run 3 at: http://127.0.0.1:5000/#/experiments/4/runs/3baeca9a51a14197846218f7261a634e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8677
Средний Precision: 0.7457
Средний Recall: 0.8535
Средний F1-Score: 0.7811
Средний NDCG: 0.8583
Средний Precision: 0.7364
Средний Recall: 0.8431
Средний F1-Score: 0.7716

[I 2026-05-08 14:05:06,461] Trial 4 finished with value: 0.8637070436546284 and parameters: {'iterations': 350, 'depth': 7, 'learning_rate': 0.04345454109729477, 'l2_leaf_reg': 1.9553708662745248}. Best is trial 4 with value: 0.8637070436546284.

Средний NDCG: 0.8637
Средний Precision: 0.7502
Средний Recall: 0.8479
Средний F1-Score: 0.7824
🏃 View run 4 at: http://127.0.0.1:5000/#/experiments/4/runs/333b4231c7fd44cdba974b7f4a71986f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8673
Средний Precision: 0.7332
Средний Recall: 0.8546
Средний F1-Score: 0.7732
Средний NDCG: 0.8576
Средний Precision: 0.7247
Средний Recall: 0.8445
Средний F1-Score: 0.7647

[I 2026-05-08 14:05:26,197] Trial 5 finished with value: 0.8620598427047703 and parameters: {'iterations': 650, 'depth': 4, 'learning_rate': 0.027010527749605478, 'l2_leaf_reg': 2.324672848950434}. Best is trial 4 with value: 0.8637070436546284.

Средний NDCG: 0.8621
Средний Precision: 0.7340
Средний Recall: 0.8498
Средний F1-Score: 0.7727
🏃 View run 5 at: http://127.0.0.1:5000/#/experiments/4/runs/e74c5793da5242d4a57bb45c7a437144
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8680
Средний Precision: 0.7496
Средний Recall: 0.8530
Средний F1-Score: 0.7835
Средний NDCG: 0.8583
Средний Precision: 0.7388
Средний Recall: 0.8424
Средний F1-Score: 0.7730

[I 2026-05-08 14:05:49,899] Trial 6 finished with value: 0.863485014604646 and parameters: {'iterations': 500, 'depth': 9, 'learning_rate': 0.019721610970574007, 'l2_leaf_reg': 3.2676417657817622}. Best is trial 4 with value: 0.8637070436546284.

Средний NDCG: 0.8635
Средний Precision: 0.7511
Средний Recall: 0.8464
Средний F1-Score: 0.7824
🏃 View run 6 at: http://127.0.0.1:5000/#/experiments/4/runs/8dbc1781bca04a3fb3930b597e016e8d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8680
Средний Precision: 0.7408
Средний Recall: 0.8545
Средний F1-Score: 0.7783
Средний NDCG: 0.8576
Средний Precision: 0.7334
Средний Recall: 0.8446
Средний F1-Score: 0.7703

[I 2026-05-08 14:06:08,913] Trial 7 finished with value: 0.8628064681814461 and parameters: {'iterations': 650, 'depth': 3, 'learning_rate': 0.07896186801026692, 'l2_leaf_reg': 1.4808945119975185}. Best is trial 4 with value: 0.8637070436546284.

Средний NDCG: 0.8628
Средний Precision: 0.7402
Средний Recall: 0.8491
Средний F1-Score: 0.7768
🏃 View run 7 at: http://127.0.0.1:5000/#/experiments/4/runs/48fdc7ee57c1486d89e96462a9903d3a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8678
Средний Precision: 0.7622
Средний Recall: 0.8504
Средний F1-Score: 0.7907
Средний NDCG: 0.8579
Средний Precision: 0.7520
Средний Recall: 0.8406
Средний F1-Score: 0.7806

[I 2026-05-08 14:06:24,623] Trial 8 finished with value: 0.8629998576474387 and parameters: {'iterations': 150, 'depth': 10, 'learning_rate': 0.26690431824362526, 'l2_leaf_reg': 6.432759992849893}. Best is trial 4 with value: 0.8637070436546284.

Средний NDCG: 0.8630
Средний Precision: 0.7628
Средний Recall: 0.8430
Средний F1-Score: 0.7879
🏃 View run 8 at: http://127.0.0.1:5000/#/experiments/4/runs/bb69f8475d644086ba49e04b741ace03
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8679
Средний Precision: 0.7345
Средний Recall: 0.8534
Средний F1-Score: 0.7738
Средний NDCG: 0.8575
Средний Precision: 0.7312
Средний Recall: 0.8444
Средний F1-Score: 0.7688

[I 2026-05-08 14:06:40,732] Trial 9 finished with value: 0.8625514548698989 and parameters: {'iterations': 350, 'depth': 3, 'learning_rate': 0.1024932221692416, 'l2_leaf_reg': 2.7551959649510764}. Best is trial 4 with value: 0.8637070436546284.

Средний NDCG: 0.8626
Средний Precision: 0.7385
Средний Recall: 0.8494
Средний F1-Score: 0.7757
🏃 View run 9 at: http://127.0.0.1:5000/#/experiments/4/runs/c5d46f50d49e49f5bddceb0f46d6f61f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8680
Средний Precision: 0.7610
Средний Recall: 0.8523
Средний F1-Score: 0.7908
Средний NDCG: 0.8578
Средний Precision: 0.7504
Средний Recall: 0.8414
Средний F1-Score: 0.7798

[I 2026-05-08 14:07:06,136] Trial 10 finished with value: 0.863442131762524 and parameters: {'iterations': 950, 'depth': 6, 'learning_rate': 0.0431646733732235, 'l2_leaf_reg': 1.0422259339479671}. Best is trial 4 with value: 0.8637070436546284.

Средний NDCG: 0.8634
Средний Precision: 0.7613
Средний Recall: 0.8470
Средний F1-Score: 0.7890
🏃 View run 10 at: http://127.0.0.1:5000/#/experiments/4/runs/5aeec23a1eba4f769950e08957654308
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8677
Средний Precision: 0.7472
Средний Recall: 0.8543
Средний F1-Score: 0.7824
Средний NDCG: 0.8580
Средний Precision: 0.7366
Средний Recall: 0.8433
Средний F1-Score: 0.7717

[I 2026-05-08 14:07:25,074] Trial 11 finished with value: 0.8635067451952506 and parameters: {'iterations': 350, 'depth': 8, 'learning_rate': 0.03336774144514092, 'l2_leaf_reg': 4.208075538548374}. Best is trial 4 with value: 0.8637070436546284.

Средний NDCG: 0.8635
Средний Precision: 0.7476
Средний Recall: 0.8478
Средний F1-Score: 0.7804
🏃 View run 11 at: http://127.0.0.1:5000/#/experiments/4/runs/00ce138abdf948d1a0b51f810713bac2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8679
Средний Precision: 0.7429
Средний Recall: 0.8541
Средний F1-Score: 0.7794
Средний NDCG: 0.8581
Средний Precision: 0.7343
Средний Recall: 0.8434
Средний F1-Score: 0.7705

[I 2026-05-08 14:07:42,271] Trial 12 finished with value: 0.8632017842472168 and parameters: {'iterations': 300, 'depth': 7, 'learning_rate': 0.0435527342638097, 'l2_leaf_reg': 4.545919880494837}. Best is trial 4 with value: 0.8637070436546284.

Средний NDCG: 0.8632
Средний Precision: 0.7446
Средний Recall: 0.8481
Средний F1-Score: 0.7788
🏃 View run 12 at: http://127.0.0.1:5000/#/experiments/4/runs/dc4c9ee1d31b433d898a8fb917eb25f0
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8674
Средний Precision: 0.7370
Средний Recall: 0.8548
Средний F1-Score: 0.7760
Средний NDCG: 0.8580
Средний Precision: 0.7261
Средний Recall: 0.8436
Средний F1-Score: 0.7651

[I 2026-05-08 14:07:59,758] Trial 13 finished with value: 0.8628845185552917 and parameters: {'iterations': 350, 'depth': 6, 'learning_rate': 0.03205809078417295, 'l2_leaf_reg': 2.081067898791295}. Best is trial 4 with value: 0.8637070436546284.

Средний NDCG: 0.8629
Средний Precision: 0.7358
Средний Recall: 0.8480
Средний F1-Score: 0.7733
🏃 View run 13 at: http://127.0.0.1:5000/#/experiments/4/runs/ceb60e3dceef4049988136b99eeef42b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8671
Средний Precision: 0.7281
Средний Recall: 0.8548
Средний F1-Score: 0.7700
Средний NDCG: 0.8570
Средний Precision: 0.7201
Средний Recall: 0.8426
Средний F1-Score: 0.7607

[I 2026-05-08 14:08:13,469] Trial 14 finished with value: 0.862717737194281 and parameters: {'iterations': 100, 'depth': 8, 'learning_rate': 0.07235090658068707, 'l2_leaf_reg': 5.0401290506972325}. Best is trial 4 with value: 0.8637070436546284.

Средний NDCG: 0.8627
Средний Precision: 0.7265
Средний Recall: 0.8473
Средний F1-Score: 0.7667
🏃 View run 14 at: http://127.0.0.1:5000/#/experiments/4/runs/4c5e2c75ad07427f96ef99f21d209884
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8677
Средний Precision: 0.7669
Средний Recall: 0.8484
Средний F1-Score: 0.7929
Средний NDCG: 0.8573
Средний Precision: 0.7583
Средний Recall: 0.8395
Средний F1-Score: 0.7841

[I 2026-05-08 14:08:29,852] Trial 15 finished with value: 0.8632186192544116 and parameters: {'iterations': 250, 'depth': 7, 'learning_rate': 0.1566833742481893, 'l2_leaf_reg': 1.8814166075210883}. Best is trial 4 with value: 0.8637070436546284.

Средний NDCG: 0.8632
Средний Precision: 0.7645
Средний Recall: 0.8439
Средний F1-Score: 0.7901
🏃 View run 15 at: http://127.0.0.1:5000/#/experiments/4/runs/9a4c7087348943e5b584d54a63fa7f35
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8681
Средний Precision: 0.7650
Средний Recall: 0.8514
Средний F1-Score: 0.7930
Средний NDCG: 0.8579
Средний Precision: 0.7548
Средний Recall: 0.8408
Средний F1-Score: 0.7826

[I 2026-05-08 14:08:50,379] Trial 16 finished with value: 0.8638302816847026 and parameters: {'iterations': 450, 'depth': 8, 'learning_rate': 0.055091259509447536, 'l2_leaf_reg': 3.1496925034466776}. Best is trial 16 with value: 0.8638302816847026.

Средний NDCG: 0.8638
Средний Precision: 0.7654
Средний Recall: 0.8448
Средний F1-Score: 0.7906
🏃 View run 16 at: http://127.0.0.1:5000/#/experiments/4/runs/c57db10dbd424103bde011e2e379292b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8677
Средний Precision: 0.7494
Средний Recall: 0.8539
Средний F1-Score: 0.7839
Средний NDCG: 0.8582
Средний Precision: 0.7401
Средний Recall: 0.8428
Средний F1-Score: 0.7740

[I 2026-05-08 14:09:09,902] Trial 17 finished with value: 0.8633226619530092 and parameters: {'iterations': 550, 'depth': 5, 'learning_rate': 0.06817779343845322, 'l2_leaf_reg': 3.090653980194989}. Best is trial 16 with value: 0.8638302816847026.

Средний NDCG: 0.8633
Средний Precision: 0.7499
Средний Recall: 0.8482
Средний F1-Score: 0.7823
🏃 View run 17 at: http://127.0.0.1:5000/#/experiments/4/runs/521ccba001d54fc2be98d89ebd8aeb6c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8678
Средний Precision: 0.7748
Средний Recall: 0.8477
Средний F1-Score: 0.7978
Средний NDCG: 0.8580
Средний Precision: 0.7673
Средний Recall: 0.8377
Средний F1-Score: 0.7889

[I 2026-05-08 14:09:32,263] Trial 18 finished with value: 0.8637405989677146 and parameters: {'iterations': 450, 'depth': 9, 'learning_rate': 0.05423197245433309, 'l2_leaf_reg': 1.1365679800644353}. Best is trial 16 with value: 0.8638302816847026.

Средний NDCG: 0.8637
Средний Precision: 0.7764
Средний Recall: 0.8405
Средний F1-Score: 0.7952
🏃 View run 18 at: http://127.0.0.1:5000/#/experiments/4/runs/3102e32c0fb241e1919a0792836be5ad
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Средний NDCG: 0.8673
Средний Precision: 0.7998
Средний Recall: 0.8317
Средний F1-Score: 0.8057
Средний NDCG: 0.8570
Средний Precision: 0.7901
Средний Recall: 0.8271
Средний F1-Score: 0.7979

[I 2026-05-08 14:09:58,566] Trial 19 finished with value: 0.8629210581911069 and parameters: {'iterations': 750, 'depth': 9, 'learning_rate': 0.18266145263423655, 'l2_leaf_reg': 1.0072079372182763}. Best is trial 16 with value: 0.8638302816847026.

Средний NDCG: 0.8629
Средний Precision: 0.7954
Средний Recall: 0.8303
Средний F1-Score: 0.8020
🏃 View run 19 at: http://127.0.0.1:5000/#/experiments/4/runs/6c5b94f07f834d6abe665c8d62024e29
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Number of finished trials: 20
Best params CatBoost: {'iterations': 450, 'depth': 8, 'learning_rate': 0.055091259509447536, 'l2_leaf_reg': 3.1496925034466776}

In [171]:
pipeline_catboost_best = Pipeline([
    ('preprocessing', ColumnTransformer([
        ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
    ], remainder='passthrough')),
    ('model', CatBoostClassifier(
        random_state=RANDOM_STATE, 
        verbose=0, 
        auto_class_weights='Balanced'
    ))
])

pipeline_catboost_best.set_params(**study_catboost.best_trial.user_attrs['pipeline_params'])
pipeline_catboost_best.fit(X_train, y_train)

y_pred_proba_catboost = pipeline_catboost_best.predict_proba(X_test)

df_test_catboost = df.loc[X_test.index].copy()
df_test_catboost['y_pred_proba'] = y_pred_proba_catboost[:, 1]

ndcg_catboost_als, precision_catboost_als, recall_catboost_als, f1_catboost_als = calculate_metrics(df_test_catboost)
metrics_catboost_als = {
    'NDCG': ndcg_catboost_als,
    'Precision': precision_catboost_als,
    'Recall': recall_catboost_als,
    'F1': f1_catboost_als
}

Средний NDCG: 0.7815
Средний Precision: 0.6839
Средний Recall: 0.7587
Средний F1-Score: 0.7052

In [172]:
Средний NDCG: 0.7814
Средний Precision: 0.6823
Средний Recall: 0.7589
Средний F1-Score: 0.7043

SyntaxError: invalid syntax (2067940828.py, line 1)

In [173]:
RUN_NAME_CATBOOST = "best_optuna_catboost_als"
REGISTRY_MODEL_NAME_CATBOOST = "best_optuna_catboost_als"

signature = mlflow.models.infer_signature(X_test, y_test)
input_example = X_test[:10]
code_paths = ["ML_Experiments.ipynb"]

with mlflow.start_run(run_name=RUN_NAME_CATBOOST, experiment_id=experiment_id) as run:
    run_id = run.info.run_id
    
    catboost_info = mlflow.sklearn.log_model(sk_model=pipeline_catboost_best, 
                                             artifact_path='best_optuna_catboost_als',
                                             registered_model_name=REGISTRY_MODEL_NAME_CATBOOST,
                                             input_example=input_example,
                                             code_paths=code_paths,
                                             await_registration_for=60
                                            )
    mlflow.log_metrics(metrics_catboost_als)
    mlflow.log_params(best_params_catboost)

Registered model 'best_optuna_catboost_als' already exists. Creating a new version of this model...
2026/05/08 14:10:20 INFO mlflow.store.model_registry.abstract_store: Waiting up to 60 seconds for model version to finish creation. Model name: best_optuna_catboost_als, version 10

🏃 View run best_optuna_catboost_als at: http://127.0.0.1:5000/#/experiments/4/runs/81398d23622d4556847d5ca29f0d83db
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

Created version '10' of model 'best_optuna_catboost_als'.

## Model comparison

In [174]:
models_comparison = pd.DataFrame({
    'Model': ['LogisticRegression', 'RandomForest', 'XGBoost', 'LightGBM', 'CatBoost', 'XGBoost + ALS', 'LightGBM + ALS', 'CatBoost + ALS'],
    'NDCG': [ndcg_lr, ndcg_rf, ndcg_xgb, ndcg_lgbm, ndcg_catboost, ndcg_xgb_als, ndcg_lgbm_als, ndcg_catboost_als],
    'Precision': [precision_lr, precision_rf, precision_xgb, precision_lgbm, precision_catboost, precision_xgb_als, precision_lgbm_als, precision_catboost_als],
    'Recall': [recall_lr, recall_rf, recall_xgb, recall_lgbm, recall_catboost, recall_xgb_als, recall_lgbm_als, recall_catboost_als],
    'F1': [f1_lr, f1_rf, f1_xgb, f1_lgbm, f1_catboost, f1_xgb_als, f1_lgbm_als, f1_catboost_als]
})

models_comparison

                Model      NDCG  Precision    Recall        F1
0  LogisticRegression  0.751349   0.637015  0.596379  0.599915
1        RandomForest  0.775653   0.660585  0.742407  0.682372
2             XGBoost  0.778059   0.698832  0.734174  0.703595
3            LightGBM  0.778390   0.669718  0.750699  0.691776
4            CatBoost  0.778681   0.678187  0.747071  0.695479
5       XGBoost + ALS  0.781613   0.703480  0.754967  0.715932
6      LightGBM + ALS  0.781421   0.684584  0.759509  0.706448
7      CatBoost + ALS  0.781456   0.683924  0.758717  0.705194

In [ ]:
Model	NDCG	Precision	Recall	F1
0	LogisticRegression	0.751349	0.637015	0.596379	0.599915
1	RandomForest	0.775653	0.660585	0.742407	0.682372
2	XGBoost	0.778059	0.698832	0.734174	0.703595
3	LightGBM	0.778390	0.669718	0.750699	0.691776
4	CatBoost	0.778681	0.678187	0.747071	0.695479
5	XGBoost + ALS	0.781090	0.669943	0.763557	0.698493
6	LightGBM + ALS	0.781279	0.704709	0.749976	0.714586
7	CatBoost + ALS	0.780736	0.669796	0.762115	0.697661

In [ ]:
best_model_idx = models_comparison['NDCG'].idxmax()
print(f"\nЛучшая модель: {models_comparison.iloc[best_model_idx]['Model']} с NDCG = {models_comparison.iloc[best_model_idx]['NDCG']:.4f}")

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

Сохраним обученный итоговый пайплайн.

</div>

In [ ]:
MODEL_NAME = 'pipeline_lgb_best.pkl'
with open(MODEL_NAME, 'wb') as file:
    pickle.dump(pipeline_lgbm_best, file)

In [ ]:
def show_vacancy_predictions(pipeline, X_test, y_test, df,
                             n_top=10, vacancy_id=None, random_state=None):
    """
    Показывает предсказания пайплайна для выбранной вакансии из тест-сета.

    Args:
        pipeline     : обученный sklearn Pipeline
        X_test       : тестовые признаки (те же колонки, на которых обучался pipeline)
        y_test       : истинные метки
        df           : исходный датафрейм со всеми колонками (для отображения)
        n_top        : сколько топ-резюме показать
        vacancy_id   : None = случайная вакансия; иначе конкретный ID
        random_state : seed для воспроизводимости случайного выбора

    Returns:
        pd.DataFrame, отсортированный по pred_proba убыванием
    """
    df_test = df.loc[X_test.index].copy()
    df_test['target'] = y_test.values

    if vacancy_id is None:
        rng = np.random.RandomState(random_state)
        vacancy_id = rng.choice(df_test['vacancy_id'].unique())

    mask = df_test['vacancy_id'] == vacancy_id
    if not mask.any():
        print(f"[!] vacancy_id={vacancy_id} не найден в тестовой выборке.")
        return None

    df_vac = df_test[mask].copy()
    X_vac  = X_test.loc[df_vac.index]

    df_vac['pred_proba'] = pipeline.predict_proba(X_vac)[:, 1]
    df_vac = df_vac.sort_values('pred_proba', ascending=False).reset_index(drop=True)

    r0       = df_vac.iloc[0]
    vac_name = str(r0.get('vacancy_name', '—'))
    vac_desc = str(r0.get('vacancy_description', '—'))
    SEP, SEP2 = "=" * 90, "─" * 90

    print(SEP)
    print(f"  ВАКАНСИЯ : {vac_name}   [id={vacancy_id}]")
    print(f"  Опыт     : {r0.get('vacancy_experience','—')}  |  "
          f"Занятость : {r0.get('vacancy_employment','—')}  |  "
          f"График : {r0.get('vacancy_schedule','—')}")
    print(SEP2)
    print("  ОПИСАНИЕ ВАКАНСИИ:")
    for line in vac_desc[:1200].split('\n')[:25]:
        if line.strip():
            print(f"    {line.strip()}")
    if len(vac_desc) > 1200:
        print("    [... сокращено]")
    print(SEP)

    n_pos = int(df_vac['target'].sum())
    print(f"\n  ТОП-{n_top} из {len(df_vac)} кандидатов  "
          f"(всего реально подходящих в выборке: {n_pos})\n")

    for rank, (_, row) in enumerate(df_vac.head(n_top).iterrows(), 1):
        icon   = "✅" if row['target'] == 1 else "❌"
        exp    = str(row.get('resume_last_experience_description', '—'))
        skills = str(row.get('resume_skills', '—'))
        print(SEP2)
        print(f"  #{rank}  {icon}  score={row['pred_proba']:.4f}  "
              f"target={int(row['target'])}  [resume_id={row.get('resume_id','—')}]")
        print(f"  Должность : {row.get('resume_last_position','—')}")
        print(f"  Локация   : {row.get('resume_location','—')}  |  "
              f"Опыт: {row.get('resume_experience_months','—')} мес.")
        print(f"  Навыки    : {skills[:180]}{'...' if len(skills) > 180 else ''}")
        print(f"  Описание последнего места:")
        for line in exp[:700].split('\n')[:14]:
            if line.strip():
                print(f"    {line.strip()}")
        if len(exp) > 700:
            print("    [... сокращено]")
        print()

    print(SEP2)
    n_hit = int(df_vac.head(n_top)['target'].sum())
    print(f"\n  Попаданий в топ-{n_top}: {n_hit}/{n_top} ({100*n_hit//n_top}%)")
    print(f"  Всего релевантных в тест-сете для этой вакансии: {n_pos}\n")

    return df_vac

In [ ]:
# Случайная вакансия из тест-сета, лучший пайплайн
result = show_vacancy_predictions(pipeline_lgbm_best, X_test, y_test, df,
                                  n_top=10, vacancy_id=126372900)

# Зафиксировать вакансию и сравнить другой пайплайн:
# vacancy_id_fixed = result.iloc[0]['vacancy_id']
# show_vacancy_predictions(pipeline_lgbm_als, X_test, y_test, df,
#                          n_top=10, vacancy_id=vacancy_id_fixed)