In [1]:
import re
import pandas as pd
import numpy as np
import nltk
import pymorphy3
import optuna
import mlflow
import pickle
import implicit

from implicit.als import AlternatingLeastSquares
from scipy.sparse import coo_matrix, csr_matrix, vstack
from optuna.integration.mlflow import MLflowCallback
from mlflow.utils.mlflow_tags import MLFLOW_PARENT_RUN_ID
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import ndcg_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from nltk.corpus import stopwords
from tqdm import tqdm
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from gensim.utils import simple_preprocess
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

import warnings
warnings.simplefilter('ignore', FutureWarning)

from sklearn import set_config
set_config(display='diagram')

In [2]:
RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

In [3]:
TRACKING_SERVER_HOST = "127.0.0.1"
TRACKING_SERVER_PORT = 5000

EXPERIMENT_NAME = "hr-ai-scout"
STUDY_DB_NAME = "sqlite:///local.study.db"

mlflow.set_tracking_uri(f"http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}")
mlflow.set_registry_uri(f"http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}")

# Load data

In [4]:
df = pd.read_csv('/Users/user/Documents/Magistracy/year_project/hr-ai-scout/total_df.csv')
df.head()

,vacancy_id,vacancy_name,vacancy_area,vacancy_experience,vacancy_employment,vacancy_schedule,vacancy_salary_from,vacancy_salary_to,vacancy_salary_currency,vacancy_salary_gross,...,resume_education,resume_courses,resume_salary,resume_age,resume_total_experience,resume_experience_months,resume_location,resume_gender,resume_applicant_status,target
0,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,300000.0,NaN,RUR,False,...,['Казанский Авиационный Институт'],NaN,NaN,65.0,19 лет,228.0,Москва,Мужчина,Рассматривает предложения,1
1,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,300000.0,NaN,RUR,False,...,"['ООО ""Открытый Учебный Центр СофтБаланс"", г. ...","['ООО ""Открытый Учебный Центр СофтБаланс"", г. ...",NaN,43.0,17 лет 4 месяца,208.0,Москва,Мужчина,Рассматривает предложения,1
2,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,300000.0,NaN,RUR,False,...,['Орский государственный педагогический инстит...,NaN,200 000 ₽ на руки,52.0,30 лет,360.0,Москва,Женщина,NaN,1
3,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,300000.0,NaN,RUR,False,...,['Красноярский государственный университет'],NaN,500 000 ₽ на руки,56.0,29 лет 8 месяцев,356.0,Красноярск,Мужчина,Рассматривает предложения,1
4,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,300000.0,NaN,RUR,False,...,['Белоруский Гос. Университет Информатики и Ра...,"['SAP CIS, SAP XI', 'Школа Логистики МАДИ', 'S...",NaN,48.0,25 лет 1 месяц,301.0,Moscow,Male,NaN,1

# Preprocessing

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">
В первую очередь уберем строки, где пропущены все ключевые значения в резюме:
</div>

In [5]:
t1 = df.shape[0]
df = df.dropna(subset= ["resume_education",
                        "resume_last_experience_description",
                        "resume_last_position",
                        "resume_last_company_experience_period",
                        "resume_total_experience",
                        "resume_experience_months",
                        "resume_location",
                        "resume_specialization",
                        # "resume_gender",
                        # "resume_title"
                       ], how="all")
t2 = df.shape[0]
print('Удалено ', t1 - t2 ,' строки')

Удалено  84  строки

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">
Удалим еще те строки, где случился технический сбой в парсинге, где у кандидата общий опыт есть, а последний опыт не указан (и наоборот):
</div>

In [6]:
t1 = df.shape[0]
df = df.loc[~(df["resume_total_experience"].notna()
        & df["resume_last_experience_description"].isna()
        & df["resume_last_position"].isna())]
t2 = df.shape[0]
print('Удалено ', t1 - t2 ,' строк')

Удалено  1543  строк

In [7]:
t1 = df.shape[0]
df = df.loc[~(df["resume_total_experience"].isna()
        & df["resume_last_experience_description"].notna()
        & df["resume_last_position"].notna())]
t2 = df.shape[0]
print('Удалено ', t1 - t2 ,' строк')

Удалено  0  строк

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">
Посмотрим на пропуски отдельно по категориальным и числовым признакам.
</div>

In [8]:
num_cols = df.select_dtypes(include=[np.number]).columns
cat_cols = df.select_dtypes(include=['object']).columns

In [9]:
df[cat_cols] = df[cat_cols].fillna('NDT')

In [10]:
df.loc[df['resume_experience_months'].isna(), 'resume_last_experience_description'].unique()

array(['NDT'], dtype=object)

In [11]:
df['resume_age'] = df['resume_age'].fillna(df['resume_age'].mean())
df['resume_experience_months'] = df['resume_experience_months'].fillna(0)

In [12]:
df = df.drop(['vacancy_salary_to', 'vacancy_salary_from',
              'vacancy_salary_currency', 'vacancy_salary_gross'], axis=1)

In [13]:
df.loc[df['resume_last_company_experience_period'] == 'NDT', 'resume_last_experience_description'].unique()

array(['NDT'], dtype=object)

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">
Преобразуем сначала ожидаемые зарплаты
</div>

In [14]:
df['resume_salary_split'] = df['resume_salary'].apply(lambda x: x.split())

df['salary_int'] = df['resume_salary_split'].apply(
    lambda x: int(''.join(part for part in x if re.fullmatch(r'\d+', part)))
              if any(re.fullmatch(r'\d+', part) for part in x)
              else np.nan
)

currency_symbols = ['₽', '$', '€', '₴', '₸', '₼', '₾', 'Br', "so'm"]

rates_rub = {
    "₽": 1.0,
    "$": 80.85,
    "€": 94.14,
    "₴": 1.94,
    "₸": 0.150,
    "₼": 47.8,
    "₾": 33.5,
    "Br": 28.7,
    "so'm": 0.0068
}

df['currency_symbol'] = df['resume_salary_split'].apply(
    lambda x: next((sym for sym in x if sym in currency_symbols), np.nan)
)

df['salary_converted'] = (df['salary_int'] * df['currency_symbol'].map(rates_rub)).fillna(0)

df['resume_salary'] = df['salary_converted']

df = df.drop(['resume_salary_split', 'salary_int', 'currency_symbol', 'salary_converted'], axis=1)

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">
Добавим дополнительный столбец с опытом работы в последней компании в месяцах для удобства
</div>

In [15]:
def experience_to_months(experience_text):
    months = 0
    # Опыт в годах
    years_match = re.search(r'(\d+)\s*год', experience_text)
    if years_match:
        months += int(years_match.group(1)) * 12

    years_match = re.search(r'(\d+)\s*лет', experience_text)
    if years_match:
        months += int(years_match.group(1)) * 12

    # Опыт в месяцах
    months_match = re.search(r'(\d+)\s*месяц', experience_text)
    if months_match:
        months += int(months_match.group(1))

    return months if months > 0 else np.nan

In [16]:
df['resume_last_company_experience_months'] = df['resume_last_company_experience_period'].apply(experience_to_months)

In [17]:
df.loc[df['resume_last_company_experience_period'] == 'NDT', 'resume_last_experience_description'].unique()

array(['NDT'], dtype=object)

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">
Т.к. в названии компании стоит NDT, можно столбец resume_last_company_experience_months заполнять нулевыми значениями.
</div>

In [18]:
df['resume_last_company_experience_months'] = df['resume_last_company_experience_months'].fillna(0)

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

- Ограничим выбросы по зарплате, потому что ровно одно значение по ожидаемой заработоной плате = 999,999,999 (смешно, но нет)

- Ограничим опыт общий и внутри одной компании до 720 месяцев (60 лет, ничего себе уже)

- Уберем возраст > 90, не ждем, что эти кандидаты находятся в поиске вакансии
</div>

In [19]:
df = df[~(df.resume_salary > 1e7)]
df.loc[df['resume_experience_months'] > 720, 'resume_experience_months'] = 720
df.loc[df['resume_last_company_experience_months'] > 720, 'resume_last_company_experience_months'] = 720
df = df[~(df.resume_age > 90)]

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

- Также уберем строки, где последний опыт кандидата больше, чем общий

- И где общий опыт кандидата +16 лет больше чем возраст (хоть так)

</div>

In [20]:
df = df[~(df.resume_experience_months < df.resume_last_company_experience_months)]
df = df[~(df.resume_age < (df.resume_experience_months // 12) + 16)]

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

Заменим текущий формат разброса полов в датасете на унифицированный

</div>

In [21]:
gender_map = {
    'Мужчина': 'Мужчина',
    'Male': 'Мужчина',
    'Женщина': 'Женщина',
    'Female': 'Женщина'
}

df['resume_gender'] = df['resume_gender'].apply(lambda x: gender_map[x] if x in gender_map else 'Неизвестно')

In [22]:
print(f"Датасет после очистки: {df.shape}")

Датасет после очистки: (325543, 25)

# Feature engineering

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">
Добавим признак матчинга локации вакансии и резюме

</div>

In [23]:
df['location_matching'] = df.apply(lambda row: 1 if row['vacancy_area'] == row['resume_location'] else 0, axis=1)

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

Сделаем новый признак, а именно посчитаем количество навыков кандидата, которые указаны в вакансии.

</div>

In [24]:
def resume_skill_count_in_vacancy(row):
    count = 0
    skill_list = row['resume_skills'].replace('[', '').replace(']', '').replace("'", "").split(', ')
    for i in skill_list:
        if i in row['vacancy_description']:
            count += 1
    return count

df['resume_skill_count_in_vacancy'] = df.apply(resume_skill_count_in_vacancy, axis=1)

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

Также посчитаем долю слов из последней должности в резюме, которые указаны в вакансии.

</div>

In [25]:
def last_position_in_vacancy(row):
    bow = []
    seps = [' ', '-', '_']
    for sep in seps:
        bow += row['resume_last_position'].split(sep=sep)
        bow = list(set(bow))
    
    c = 0
    for word in bow:
        if word in row['vacancy_description']:
            c +=1
    
    return c / len(bow)

In [26]:
df['last_position_in_vacancy'] = df.apply(last_position_in_vacancy, axis=1)

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

Теперь закодируем описание вакансии и последнего опыта работы и сравним через косинусное расстояние.

</div>

In [27]:
def preprocess_data(df):
    """Обработка пропущенных значений в текстовых полях"""
    print("Проверка пропущенных значений...")
    print(f"Пропуски в vacancy_description: {df['vacancy_description'].isna().sum()}")
    print(f"Пропуски в resume_last_experience_description: {df['resume_last_experience_description'].isna().sum()}")
    
    # Заполняем пропуски пустыми строками
    df['vacancy_description'] = df['vacancy_description'].fillna('')
    df['resume_last_experience_description'] = df['resume_last_experience_description'].fillna('')
    
    # Проверяем, что все значения теперь строковые
    df['vacancy_description'] = df['vacancy_description'].astype(str)
    df['resume_last_experience_description'] = df['resume_last_experience_description'].astype(str)
    
    return df

In [28]:
def save_results(df, output_file):
    """Сохранение результатов в CSV файл"""
    df.to_csv(output_file, index=False, encoding='utf-8')
    print(f"Результаты сохранены в файл: {output_file}")

In [29]:
def calculate_cosine_similarity(embeddings1, embeddings2):
    """Вычисление косинусного сходства между двумя наборами эмбеддингов"""
    similarities = []
    
    for i in tqdm(range(embeddings1.shape[0])):
        emb1_row = embeddings1[i]
        emb2_row = embeddings2[i]
        
        similarity = cosine_similarity(emb1_row, emb2_row)[0][0]
        similarities.append(similarity)
    
    return similarities

In [30]:
warnings.filterwarnings('ignore')

try:
    nltk.data.find('corpora/stopwords')
except LookupError:
    nltk.download('stopwords')

try:
    nltk.data.find('taggers/averaged_perceptron_tagger_ru')
except LookupError:
    nltk.download('averaged_perceptron_tagger_ru')

try:
    nltk.data.find('corpora/wordnet')
except LookupError:
    nltk.download('wordnet')

morph = pymorphy3.MorphAnalyzer()

[nltk_data] Downloading package wordnet to /Users/user/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [31]:
def lemmatize_russian(tokens):
    """Лемматизация русских слов"""
    lemmas = []
    for token in tokens:
        parsed = morph.parse(token)[0]  # Берем самый вероятный разбор
        lemmas.append(parsed.normal_form)
    return lemmas

In [32]:
def tokenize_and_lemmatize(text):
    """Токенизация текста с лемматизацией и удалением стоп-слов"""
    tokens = simple_preprocess(text, deacc=True, min_len=2)
    stop_words = set(stopwords.words('russian') + stopwords.words('english'))
    tokens = [token for token in tokens if token not in stop_words]
    lemmatized_tokens = lemmatize_russian(tokens)
    
    return lemmatized_tokens

In [33]:
def get_tfidf_embeddings(texts, vectorizer=None, fit=True):
    """Создание TF-IDF эмбеддингов для списка текстов с лемматизацией"""
    if fit:
        vectorizer = TfidfVectorizer(
            max_features=5000,
            min_df=2,
            max_df=0.8,
            ngram_range=(1, 2),
            tokenizer=tokenize_and_lemmatize,
            token_pattern=None,
            lowercase=False  # Уже сделано в токенизации
        )
        embeddings = vectorizer.fit_transform(texts)
    else:
        embeddings = vectorizer.transform(texts)
    
    return embeddings, vectorizer

In [34]:
def get_tfidf_vacancy_embeddings(df, vectorizer=None):
    """Создание эмбеддингов для уникальных вакансий с лемматизацией"""
    unique_vacancies = df[['vacancy_id', 'vacancy_description']].drop_duplicates()
    
    unique_embeddings, vectorizer = get_tfidf_embeddings(
        unique_vacancies['vacancy_description'].tolist(), 
        vectorizer=vectorizer, 
        fit=(vectorizer is None)
    )
    
    vacancy_embedding_dict = dict(zip(unique_vacancies['vacancy_id'], unique_embeddings))
    
    rows = []
    for vid in df['vacancy_id']:
        rows.append(vacancy_embedding_dict[vid])
    
    all_vacancy_embeddings = vstack(rows)
    
    return all_vacancy_embeddings, vectorizer

In [35]:
def process_similarity_scores_tfidf(df, vectorizer=None, fit=True):
    """Функция для вычисления схожести с использованием TF-IDF и лемматизации"""
    df = preprocess_data(df)
    
    print("Создание TF-IDF эмбеддингов для описаний опыта в резюме...")
    experience_embeddings, tfidf_vectorizer = get_tfidf_embeddings(df['resume_last_experience_description'].tolist(), vectorizer=vectorizer, fit=fit)
    
    print("Создание TF-IDF эмбеддингов для описаний вакансий...")
    vacancy_embeddings, _ = get_tfidf_vacancy_embeddings(df, vectorizer=tfidf_vectorizer)
    
    print("Вычисление косинусного сходства...")
    similarity_scores = calculate_cosine_similarity(vacancy_embeddings, experience_embeddings)
    
    df['similarity_score_tfidf'] = similarity_scores
    
    return df, tfidf_vectorizer

In [36]:
try:
    df_tfidf = pd.read_csv('description_df_with_scores_tfidf.csv')
except:
    df_tfidf = process_similarity_scores_tfidf(df.copy())
    save_results(df_tfidf, 'description_df_with_scores_tfidf.csv')

In [37]:
df = df.merge(df_tfidf)

In [38]:
df.head()

,vacancy_id,vacancy_name,vacancy_area,vacancy_experience,vacancy_employment,vacancy_schedule,vacancy_description,resume_id,resume_title,resume_specialization,...,resume_location,resume_gender,resume_applicant_status,target,resume_last_company_experience_months,location_matching,resume_skill_count_in_vacancy,last_position_in_vacancy,resume_skill_count,similarity_score_tfidf
0,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,"Привет!.redev — технологическая компания, созд...",6969174,ABAP-разработчик,"['Программист, разработчик']",...,Москва,Мужчина,Рассматривает предложения,1,76.0,1,3,0.666667,3,0.284047
1,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,"Привет!.redev — технологическая компания, созд...",9100077,"ABAP разработчик - SAP HCM, CRM, S/4HANA ERP(F...","['Программист, разработчик']",...,Москва,Мужчина,Рассматривает предложения,1,8.0,1,2,0.500000,2,0.308726
2,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,"Привет!.redev — технологическая компания, созд...",32644957,Разработчик ABAP,"['Программист, разработчик']",...,Москва,Женщина,NDT,1,136.0,1,1,0.000000,1,0.510093
3,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,"Привет!.redev — технологическая компания, созд...",27220466,ABAP-разработчик,"['Программист, разработчик']",...,Красноярск,Мужчина,Рассматривает предложения,1,135.0,0,2,0.333333,2,0.301062
4,126167948,Разработчик SAP ABAP,Москва,Более 6 лет,Полная занятость,Удаленная работа,"Привет!.redev — технологическая компания, созд...",7532708,ABAP разработчик. Senior ABAP Developer. SAP T...,"['Programmer, developer']",...,Moscow,Мужчина,NDT,1,0.0,0,2,0.600000,2,0.075429

# Train-test split

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

Добавим новые признаки в обучение и тестирование

</div>

In [39]:
features = [
    'vacancy_area',
    'vacancy_experience',
    'vacancy_employment', 
    'vacancy_schedule',
    # 'resume_specialization',
    # 'resume_education', 
    # 'resume_courses', 
    'resume_salary',
    'resume_age', 
    'resume_experience_months',
    'resume_location',
    'resume_gender', 
    'resume_applicant_status', 
    'resume_last_company_experience_months', 
    'location_matching',
    'resume_skill_count_in_vacancy',
    'last_position_in_vacancy',
    'similarity_score_tfidf'
]
df[features]

,vacancy_area,vacancy_experience,vacancy_employment,vacancy_schedule,resume_salary,resume_age,resume_experience_months,resume_location,resume_gender,resume_applicant_status,resume_last_company_experience_months,location_matching,resume_skill_count_in_vacancy,last_position_in_vacancy,similarity_score_tfidf
0,Москва,Более 6 лет,Полная занятость,Удаленная работа,0.0,65.000000,228.0,Москва,Мужчина,Рассматривает предложения,76.0,1,3,0.666667,0.284047
1,Москва,Более 6 лет,Полная занятость,Удаленная работа,0.0,43.000000,208.0,Москва,Мужчина,Рассматривает предложения,8.0,1,2,0.500000,0.308726
2,Москва,Более 6 лет,Полная занятость,Удаленная работа,200000.0,52.000000,360.0,Москва,Женщина,NDT,136.0,1,1,0.000000,0.510093
3,Москва,Более 6 лет,Полная занятость,Удаленная работа,500000.0,56.000000,356.0,Красноярск,Мужчина,Рассматривает предложения,135.0,0,2,0.333333,0.301062
4,Москва,Более 6 лет,Полная занятость,Удаленная работа,0.0,48.000000,301.0,Moscow,Мужчина,NDT,0.0,0,2,0.600000,0.075429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321637,Москва,От 3 до 6 лет,Полная занятость,Удаленная работа,242550.0,66.000000,521.0,Санкт-Петербург,Женщина,NDT,270.0,0,0,0.166667,0.072670
321638,Москва,От 3 до 6 лет,Полная занятость,Удаленная работа,0.0,40.000000,213.0,Москва,Мужчина,Активно ищет работу,35.0,1,0,0.000000,0.000000
321639,Москва,От 3 до 6 лет,Полная занятость,Удаленная работа,80000.0,44.060813,121.0,Москва,Мужчина,NDT,44.0,1,0,0.200000,0.047398
321640,Москва,От 3 до 6 лет,Полная занятость,Удаленная работа,0.0,32.000000,117.0,Москва,Женщина,NDT,96.0,1,0,0.200000,0.029086
321641,Москва,От 3 до 6 лет,Полная занятость,Удаленная работа,0.0,63.000000,513.0,Москва,Мужчина,NDT,262.0,1,0,0.000000,0.043344

In [40]:
numeric_features = df[features].select_dtypes(include=np.number).columns
categorical_features = df[features].select_dtypes(exclude=np.number).columns

In [41]:
X = df[features].copy()
y = df['target'].copy()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=RANDOM_STATE, stratify=y)

In [42]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((257313, 15), (64329, 15), (257313,), (64329,))

In [43]:
def calculate_metrics(df_test: pd.DataFrame) -> pd.DataFrame:
    ndcg_scores = []
    precision_scores = []
    recall_scores = []
    f1_scores = []
    vacancy_ids = df_test['vacancy_id'].unique()
    
    for vacancy_id in vacancy_ids:
        mask = df_test['vacancy_id'] == vacancy_id
        y_true = df_test.loc[mask, 'target'].values
        y_score = df_test.loc[mask, 'y_pred_proba'].values
        
        if len(y_true) <= 1:
            continue
        
        y_true_2d = y_true.reshape(1, -1)
        y_score_2d = y_score.reshape(1, -1)
        
        ndcg = ndcg_score(y_true_2d, y_score_2d)
        ndcg_scores.append(ndcg)
        
        y_pred_binary = (y_score >= 0.5).astype(int)
        
        precision = precision_score(y_true, y_pred_binary, zero_division=0)
        recall = recall_score(y_true, y_pred_binary, zero_division=0)
        f1 = f1_score(y_true, y_pred_binary, zero_division=0)
        
        precision_scores.append(precision)
        recall_scores.append(recall)
        f1_scores.append(f1)
    
    if ndcg_scores:
        print(f"Средний NDCG: {np.mean(ndcg_scores):.4f}")
        print(f"Средний Precision: {np.mean(precision_scores):.4f}")
        print(f"Средний Recall: {np.mean(recall_scores):.4f}")
        print(f"Средний F1-Score: {np.mean(f1_scores):.4f}")

        return np.mean(ndcg_scores), np.mean(precision_scores), np.mean(recall_scores), np.mean(f1_scores)
    else:
        print("Недостаточно данных для расчета метрик")

        return None, None, None, None

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

Обучим с подбором гиперпараметров `LogisticRegression`, как бейзлайн для сравнения с нелинейными моделями, `RandomForestClassifier`, как разновидность бэггинга, и три разные вида градиентного бустинга: `XGBClassifier`, `LGBMClassifier` и `CatBoostClassifier`.

</div>

# LogisticRegression

In [44]:
def objective(trial: optuna.Trial) -> float:
    params = {
        'model__C': trial.suggest_float('C', 1e-4, 1e4, log=True),
        'model__penalty': trial.suggest_categorical('penalty', ['l1', 'l2']),
        'model__solver': trial.suggest_categorical('solver', ['liblinear', 'saga'])
    }
    
    pipeline_lr_optuna = Pipeline([
        ('preprocessing', ColumnTransformer([
            ('numeric_scaling', StandardScaler(), numeric_features),
            ('categorical_encoding', OneHotEncoder(drop='first', handle_unknown='ignore'), categorical_features)
        ])),
        ('model', LogisticRegression(random_state=RANDOM_STATE, class_weight='balanced'))
    ])
    
    pipeline_lr_optuna.set_params(**params)
    
    kfold = StratifiedKFold(n_splits=3, shuffle=True, random_state=RANDOM_STATE)
    
    for train_idx, val_idx in kfold.split(X_train, y_train):
        X_fold_train, X_fold_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_fold_train, y_fold_val = y_train.iloc[train_idx], y_train.iloc[val_idx]
        
        pipeline_lr_optuna.fit(X_fold_train, y_fold_train)
        y_pred_proba = pipeline_lr_optuna.predict_proba(X_fold_val)
        

        df_val = df.loc[X_fold_val.index].copy()
        df_val['y_pred_proba'] = y_pred_proba[:, 1]
        
        ndcg, _, _, _ = calculate_metrics(df_val)

        trial.set_user_attr('pipeline_params', params)
    
    return ndcg

In [45]:
try:
    experiment_id = mlflow.get_experiment_by_name(EXPERIMENT_NAME).experiment_id
except:
    experiment_id = mlflow.create_experiment(EXPERIMENT_NAME)

RUN_NAME_OPTUNE = 'LogisticRegression_optuna'

with mlflow.start_run(run_name=RUN_NAME_OPTUNE, experiment_id=experiment_id) as run:
    run_id = run.info.run_id

🏃 View run LogisticRegression_optuna at: http://127.0.0.1:5000/#/experiments/1/runs/f89e70c8bbc04aa4bdfd3b3a81a7baa0
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

In [46]:
STUDY_NAME = "LogisticRegression_optuna"

mlflc = MLflowCallback(
    tracking_uri=f'http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}',
    metric_name="NDCG",
    create_experiment=False,
    mlflow_kwargs={'experiment_id': experiment_id, 'tags': {MLFLOW_PARENT_RUN_ID: run_id}}
)

In [47]:
study = optuna.create_study(direction='maximize', 
                            sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
                            study_name=STUDY_NAME,
                            storage=STUDY_DB_NAME,
                            load_if_exists=False)
study.optimize(objective, 
               n_trials=20, 
               callbacks=[mlflc]
              )
best_params_optuna = study.best_params

print(f"Number of finished trials: {len(study.trials)}")
print(f"Best params: {best_params_optuna}")

[I 2026-05-08 16:11:30,917] A new study created in RDB with name: LogisticRegression_optuna

Средний NDCG: 0.8300
Средний Precision: 0.5702
Средний Recall: 0.7888
Средний F1-Score: 0.6312
Средний NDCG: 0.8191
Средний Precision: 0.5614
Средний Recall: 0.7788
Средний F1-Score: 0.6213

[I 2026-05-08 16:12:08,649] Trial 0 finished with value: 0.8270779138714848 and parameters: {'C': 0.09915644566638405, 'penalty': 'l1', 'solver': 'liblinear'}. Best is trial 0 with value: 0.8270779138714848.

Средний NDCG: 0.8271
Средний Precision: 0.5711
Средний Recall: 0.7823
Средний F1-Score: 0.6304
🏃 View run 0 at: http://127.0.0.1:5000/#/experiments/1/runs/d8f88ea51cf94f2081fdc9f99fe80a45
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8260
Средний Precision: 0.5665
Средний Recall: 0.7821
Средний F1-Score: 0.6264
Средний NDCG: 0.8150
Средний Precision: 0.5597
Средний Recall: 0.7711
Средний F1-Score: 0.6166

[I 2026-05-08 16:12:27,362] Trial 1 finished with value: 0.8219108201868665 and parameters: {'C': 0.001769930294063334, 'penalty': 'l2', 'solver': 'saga'}. Best is trial 0 with value: 0.8270779138714848.

Средний NDCG: 0.8219
Средний Precision: 0.5667
Средний Recall: 0.7771
Средний F1-Score: 0.6251
🏃 View run 1 at: http://127.0.0.1:5000/#/experiments/1/runs/e1235e44a9b74b5c8c65bb1f0fd9a248
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8195
Средний Precision: 0.5155
Средний Recall: 0.7796
Средний F1-Score: 0.5887
Средний NDCG: 0.8106
Средний Precision: 0.5041
Средний Recall: 0.7665
Средний F1-Score: 0.5753

[I 2026-05-08 16:12:40,066] Trial 2 finished with value: 0.8157981400733071 and parameters: {'C': 0.00014610865886287216, 'penalty': 'l1', 'solver': 'liblinear'}. Best is trial 0 with value: 0.8270779138714848.

Средний NDCG: 0.8158
Средний Precision: 0.5076
Средний Recall: 0.7715
Средний F1-Score: 0.5811
🏃 View run 2 at: http://127.0.0.1:5000/#/experiments/1/runs/747f53f18d2b45819b91d5703f07fd04
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8266
Средний Precision: 0.5666
Средний Recall: 0.7838
Средний F1-Score: 0.6272
Средний NDCG: 0.8153
Средний Precision: 0.5598
Средний Recall: 0.7739
Средний F1-Score: 0.6176

[I 2026-05-08 16:12:52,743] Trial 3 finished with value: 0.8226595212568117 and parameters: {'C': 0.0029324868872723777, 'penalty': 'l2', 'solver': 'liblinear'}. Best is trial 0 with value: 0.8270779138714848.

Средний NDCG: 0.8227
Средний Precision: 0.5661
Средний Recall: 0.7795
Средний F1-Score: 0.6257
🏃 View run 3 at: http://127.0.0.1:5000/#/experiments/1/runs/d7b31dd61db445b68dac540c63d84502
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8304
Средний Precision: 0.5688
Средний Recall: 0.7896
Средний F1-Score: 0.6306
Средний NDCG: 0.8191
Средний Precision: 0.5620
Средний Recall: 0.7794
Средний F1-Score: 0.6220

[I 2026-05-08 16:13:11,372] Trial 4 finished with value: 0.8269999989560172 and parameters: {'C': 7.849159562555087, 'penalty': 'l2', 'solver': 'saga'}. Best is trial 0 with value: 0.8270779138714848.

Средний NDCG: 0.8270
Средний Precision: 0.5715
Средний Recall: 0.7817
Средний F1-Score: 0.6303
🏃 View run 4 at: http://127.0.0.1:5000/#/experiments/1/runs/9af0ec81ed874419b3c2e474062734e4
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8297
Средний Precision: 0.5677
Средний Recall: 0.7879
Средний F1-Score: 0.6293
Средний NDCG: 0.8188
Средний Precision: 0.5624
Средний Recall: 0.7794
Средний F1-Score: 0.6223

[I 2026-05-08 16:13:28,690] Trial 5 finished with value: 0.8264039116629283 and parameters: {'C': 191.16469627784286, 'penalty': 'l2', 'solver': 'liblinear'}. Best is trial 0 with value: 0.8270779138714848.

Средний NDCG: 0.8264
Средний Precision: 0.5702
Средний Recall: 0.7811
Средний F1-Score: 0.6294
🏃 View run 5 at: http://127.0.0.1:5000/#/experiments/1/runs/1611dd268b874f169aa92f8e786d637b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8304
Средний Precision: 0.5688
Средний Recall: 0.7896
Средний F1-Score: 0.6306
Средний NDCG: 0.8191
Средний Precision: 0.5618
Средний Recall: 0.7795
Средний F1-Score: 0.6219

[I 2026-05-08 16:15:12,943] Trial 6 finished with value: 0.8269902824978899 and parameters: {'C': 7.250347382396651, 'penalty': 'l1', 'solver': 'saga'}. Best is trial 0 with value: 0.8270779138714848.

Средний NDCG: 0.8270
Средний Precision: 0.5716
Средний Recall: 0.7817
Средний F1-Score: 0.6304
🏃 View run 6 at: http://127.0.0.1:5000/#/experiments/1/runs/72298821722e47cc85090cab7a6d81ed
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8296
Средний Precision: 0.5676
Средний Recall: 0.7878
Средний F1-Score: 0.6292
Средний NDCG: 0.8187
Средний Precision: 0.5622
Средний Recall: 0.7792
Средний F1-Score: 0.6222

[I 2026-05-08 16:18:03,101] Trial 7 finished with value: 0.8259835018149861 and parameters: {'C': 293.21000471832957, 'penalty': 'l1', 'solver': 'liblinear'}. Best is trial 0 with value: 0.8270779138714848.

Средний NDCG: 0.8260
Средний Precision: 0.5701
Средний Recall: 0.7807
Средний F1-Score: 0.6292
🏃 View run 7 at: http://127.0.0.1:5000/#/experiments/1/runs/0e4be598f5214f7d8a6f4a2f2fdb5fc3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8224
Средний Precision: 0.5508
Средний Recall: 0.7776
Средний F1-Score: 0.6133
Средний NDCG: 0.8117
Средний Precision: 0.5405
Средний Recall: 0.7621
Средний F1-Score: 0.6000

[I 2026-05-08 16:18:16,845] Trial 8 finished with value: 0.8184566752240834 and parameters: {'C': 0.000946903842177445, 'penalty': 'l1', 'solver': 'liblinear'}. Best is trial 0 with value: 0.8270779138714848.

Средний NDCG: 0.8185
Средний Precision: 0.5486
Средний Recall: 0.7686
Средний F1-Score: 0.6097
🏃 View run 8 at: http://127.0.0.1:5000/#/experiments/1/runs/f503810190c24231902752874ae0f532
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8299
Средний Precision: 0.5677
Средний Recall: 0.7880
Средний F1-Score: 0.6293
Средний NDCG: 0.8189
Средний Precision: 0.5618
Средний Recall: 0.7793
Средний F1-Score: 0.6220

[I 2026-05-08 16:18:32,766] Trial 9 finished with value: 0.8265828725577935 and parameters: {'C': 19.960815242513796, 'penalty': 'l2', 'solver': 'liblinear'}. Best is trial 0 with value: 0.8270779138714848.

Средний NDCG: 0.8266
Средний Precision: 0.5706
Средний Recall: 0.7817
Средний F1-Score: 0.6298
🏃 View run 9 at: http://127.0.0.1:5000/#/experiments/1/runs/726a556015514c60be0a0ea1de8cfbc9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8301
Средний Precision: 0.5694
Средний Recall: 0.7889
Средний F1-Score: 0.6307
Средний NDCG: 0.8188
Средний Precision: 0.5611
Средний Recall: 0.7790
Средний F1-Score: 0.6210

[I 2026-05-08 16:19:00,570] Trial 10 finished with value: 0.8269317028989807 and parameters: {'C': 0.09904054934226315, 'penalty': 'l1', 'solver': 'saga'}. Best is trial 0 with value: 0.8270779138714848.

Средний NDCG: 0.8269
Средний Precision: 0.5703
Средний Recall: 0.7818
Средний F1-Score: 0.6296
🏃 View run 10 at: http://127.0.0.1:5000/#/experiments/1/runs/28a52e767649438eb5740702b7649d48
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8303
Средний Precision: 0.5706
Средний Recall: 0.7893
Средний F1-Score: 0.6318
Средний NDCG: 0.8189
Средний Precision: 0.5634
Средний Recall: 0.7796
Средний F1-Score: 0.6227

[I 2026-05-08 16:19:19,731] Trial 11 finished with value: 0.8271110148455479 and parameters: {'C': 0.19394744414409867, 'penalty': 'l2', 'solver': 'saga'}. Best is trial 11 with value: 0.8271110148455479.

Средний NDCG: 0.8271
Средний Precision: 0.5719
Средний Recall: 0.7822
Средний F1-Score: 0.6308
🏃 View run 11 at: http://127.0.0.1:5000/#/experiments/1/runs/717384b537934198aaf9b6725e022975
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8302
Средний Precision: 0.5691
Средний Recall: 0.7890
Средний F1-Score: 0.6304
Средний NDCG: 0.8193
Средний Precision: 0.5627
Средний Recall: 0.7798
Средний F1-Score: 0.6222

[I 2026-05-08 16:19:53,448] Trial 12 finished with value: 0.8268011847889861 and parameters: {'C': 0.1995148618296573, 'penalty': 'l1', 'solver': 'saga'}. Best is trial 11 with value: 0.8271110148455479.

Средний NDCG: 0.8268
Средний Precision: 0.5707
Средний Recall: 0.7819
Средний F1-Score: 0.6300
🏃 View run 12 at: http://127.0.0.1:5000/#/experiments/1/runs/6b375961077b4bc1b4f84d9ababc8fa7
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8302
Средний Precision: 0.5703
Средний Recall: 0.7888
Средний F1-Score: 0.6314
Средний NDCG: 0.8190
Средний Precision: 0.5635
Средний Recall: 0.7788
Средний F1-Score: 0.6224

[I 2026-05-08 16:20:13,570] Trial 13 finished with value: 0.8266884643582342 and parameters: {'C': 0.10075976854563753, 'penalty': 'l2', 'solver': 'saga'}. Best is trial 11 with value: 0.8271110148455479.

Средний NDCG: 0.8267
Средний Precision: 0.5709
Средний Recall: 0.7822
Средний F1-Score: 0.6303
🏃 View run 13 at: http://127.0.0.1:5000/#/experiments/1/runs/320f69b334924339a23d25ce1c97d31e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8296
Средний Precision: 0.5717
Средний Recall: 0.7883
Средний F1-Score: 0.6322
Средний NDCG: 0.8174
Средний Precision: 0.5635
Средний Recall: 0.7773
Средний F1-Score: 0.6218

[I 2026-05-08 16:20:27,398] Trial 14 finished with value: 0.825204153904031 and parameters: {'C': 0.019356840324630174, 'penalty': 'l2', 'solver': 'liblinear'}. Best is trial 11 with value: 0.8271110148455479.

Средний NDCG: 0.8252
Средний Precision: 0.5720
Средний Recall: 0.7838
Средний F1-Score: 0.6316
🏃 View run 14 at: http://127.0.0.1:5000/#/experiments/1/runs/373934405f18466aae6b72dd7c942589
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8302
Средний Precision: 0.5693
Средний Recall: 0.7897
Средний F1-Score: 0.6309
Средний NDCG: 0.8192
Средний Precision: 0.5623
Средний Recall: 0.7797
Средний F1-Score: 0.6222

[I 2026-05-08 16:21:28,797] Trial 15 finished with value: 0.8270976678687342 and parameters: {'C': 0.9318427455155665, 'penalty': 'l1', 'solver': 'saga'}. Best is trial 11 with value: 0.8271110148455479.

Средний NDCG: 0.8271
Средний Precision: 0.5718
Средний Recall: 0.7821
Средний F1-Score: 0.6307
🏃 View run 15 at: http://127.0.0.1:5000/#/experiments/1/runs/ba3f5ed772ee4f06b5254156841c72d6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8304
Средний Precision: 0.5687
Средний Recall: 0.7896
Средний F1-Score: 0.6305
Средний NDCG: 0.8191
Средний Precision: 0.5619
Средний Recall: 0.7796
Средний F1-Score: 0.6220

[I 2026-05-08 16:22:50,517] Trial 16 finished with value: 0.8270355110684001 and parameters: {'C': 2.5649148563684383, 'penalty': 'l1', 'solver': 'saga'}. Best is trial 11 with value: 0.8271110148455479.

Средний NDCG: 0.8270
Средний Precision: 0.5716
Средний Recall: 0.7818
Средний F1-Score: 0.6305
🏃 View run 16 at: http://127.0.0.1:5000/#/experiments/1/runs/ba4b2fa8b0164a018f08ab1a18ce2607
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8304
Средний Precision: 0.5688
Средний Recall: 0.7896
Средний F1-Score: 0.6307
Средний NDCG: 0.8191
Средний Precision: 0.5618
Средний Recall: 0.7795
Средний F1-Score: 0.6220

[I 2026-05-08 16:23:09,197] Trial 17 finished with value: 0.8269474959568016 and parameters: {'C': 7183.895873930872, 'penalty': 'l2', 'solver': 'saga'}. Best is trial 11 with value: 0.8271110148455479.

Средний NDCG: 0.8269
Средний Precision: 0.5715
Средний Recall: 0.7817
Средний F1-Score: 0.6303
🏃 View run 17 at: http://127.0.0.1:5000/#/experiments/1/runs/618c699994b54e92846e68b87280f57e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8302
Средний Precision: 0.5693
Средний Recall: 0.7897
Средний F1-Score: 0.6310
Средний NDCG: 0.8192
Средний Precision: 0.5623
Средний Recall: 0.7797
Средний F1-Score: 0.6222

[I 2026-05-08 16:24:08,464] Trial 18 finished with value: 0.8271089575233356 and parameters: {'C': 0.940927363855838, 'penalty': 'l1', 'solver': 'saga'}. Best is trial 11 with value: 0.8271110148455479.

Средний NDCG: 0.8271
Средний Precision: 0.5718
Средний Recall: 0.7821
Средний F1-Score: 0.6307
🏃 View run 18 at: http://127.0.0.1:5000/#/experiments/1/runs/c5abb44aa621467e87a9794f9df37a9b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8304
Средний Precision: 0.5688
Средний Recall: 0.7896
Средний F1-Score: 0.6307
Средний NDCG: 0.8191
Средний Precision: 0.5618
Средний Recall: 0.7795
Средний F1-Score: 0.6220

[I 2026-05-08 16:24:27,686] Trial 19 finished with value: 0.8269458488463799 and parameters: {'C': 49.638930718338166, 'penalty': 'l2', 'solver': 'saga'}. Best is trial 11 with value: 0.8271110148455479.

Средний NDCG: 0.8269
Средний Precision: 0.5715
Средний Recall: 0.7817
Средний F1-Score: 0.6303
🏃 View run 19 at: http://127.0.0.1:5000/#/experiments/1/runs/47cc7dc7a4a6481e8c226f74c8ef0522
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Number of finished trials: 20
Best params: {'C': 0.19394744414409867, 'penalty': 'l2', 'solver': 'saga'}

In [48]:
study.best_trial.user_attrs['pipeline_params']

{'model__C': 0.19394744414409867,
 'model__penalty': 'l2',
 'model__solver': 'saga'}

In [49]:
pipeline_lr_best_optuna = Pipeline([
    ('preprocessing', ColumnTransformer([
        ('numeric_scaling', StandardScaler(), numeric_features),
        ('categorical_encoding', OneHotEncoder(drop='first', handle_unknown='ignore'), categorical_features)
    ])),
    ('model', LogisticRegression(random_state=RANDOM_STATE))
])

pipeline_lr_best_optuna.set_params(**study.best_trial.user_attrs['pipeline_params'])
pipeline_lr_best_optuna.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('numeric_scaling',
                                                  StandardScaler(),
                                                  Index(['resume_salary', 'resume_age', 'resume_experience_months',
       'resume_last_company_experience_months', 'location_matching',
       'resume_skill_count_in_vacancy', 'last_position_in_vacancy',
       'similarity_score_tfidf'],
      dtype='object')),
                                                 ('categorical_encoding',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  Index(['vacancy_area', 'vacancy_experience', 'vacancy_employment',
       'vacancy_schedule', 'resume_location', 'resume_gender',
       'resume_applicant_status'],
      dtype='object'))])),
                ('model',
                 LogisticRegression(C=0.19394744414409867, penalty='l2',
                                    random_state=42, solver='saga'))])

In [50]:
y_pred_proba = pipeline_lr_best_optuna.predict_proba(X_test)

df_test = df.loc[X_test.index].copy()
df_test['y_pred_proba'] = y_pred_proba[:, 1]

In [51]:
ndcg_lr, precision_lr, recall_lr, f1_lr = calculate_metrics(df_test)

metrics_lr = {
    'NDCG': ndcg_lr,
    'Precision': precision_lr,
    'Recall': recall_lr,
    'F1': f1_lr
}

Средний NDCG: 0.7516
Средний Precision: 0.6371
Средний Recall: 0.5965
Средний F1-Score: 0.6003

In [52]:
RUN_NAME = "best_optuna_lr" 
REGISTRY_MODEL_NAME = "best_optuna_lr"

In [53]:
signature = mlflow.models.infer_signature(X_test, y_test)
input_example = X_test[:10]
code_paths = ["ML_Experiments.ipynb"]

try:
    experiment_id = mlflow.get_experiment_by_name(EXPERIMENT_NAME).experiment_id
except:
    experiment_id = mlflow.create_experiment(EXPERIMENT_NAME)

with mlflow.start_run(run_name=RUN_NAME, experiment_id=experiment_id) as run:
    run_id = run.info.run_id

    lr_info = mlflow.sklearn.log_model(sk_model=pipeline_lr_best_optuna, 
                                       artifact_path='best_optuna_lr',
                                       registered_model_name=REGISTRY_MODEL_NAME,
                                       input_example=input_example,
                                       code_paths=code_paths,
                                       await_registration_for=60
                                      )
    mlflow.log_metrics(metrics_lr)
    mlflow.log_params(best_params_optuna)

Successfully registered model 'best_optuna_lr'.
2026/05/08 16:24:38 INFO mlflow.store.model_registry.abstract_store: Waiting up to 60 seconds for model version to finish creation. Model name: best_optuna_lr, version 1

🏃 View run best_optuna_lr at: http://127.0.0.1:5000/#/experiments/1/runs/3ccd2c4f94c44a8f9da7432ac80ac2d1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

Created version '1' of model 'best_optuna_lr'.

# RandomForestClassifier

In [54]:
def objective(trial: optuna.Trial) -> float:
    params = {
        'model__n_estimators': trial.suggest_int('n_estimators', 100, 1000, step=50),
        'model__max_depth': trial.suggest_int('max_depth', 3, 30),
        'model__min_samples_split': trial.suggest_int('min_samples_split', 2, 20),
        'model__min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 20)
    }
    
    pipeline_rf = Pipeline([
        ('preprocessing', ColumnTransformer([
            ('numeric_scaling', StandardScaler(), numeric_features),
            ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
        ])),
        ('model', RandomForestClassifier(random_state=RANDOM_STATE, class_weight='balanced'))
    ])
    
    pipeline_rf.set_params(**params)
    
    kfold = StratifiedKFold(n_splits=3, shuffle=True, random_state=RANDOM_STATE)
    
    for train_idx, val_idx in kfold.split(X_train, y_train):
        X_fold_train, X_fold_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_fold_train, y_fold_val = y_train.iloc[train_idx], y_train.iloc[val_idx]
        
        pipeline_rf.fit(X_fold_train, y_fold_train)
        y_pred_proba = pipeline_rf.predict_proba(X_fold_val)
        

        df_val = df.loc[X_fold_val.index].copy()
        df_val['y_pred_proba'] = y_pred_proba[:, 1]
        
        ndcg, _, _, _ = calculate_metrics(df_val)

        trial.set_user_attr('pipeline_params', params)
    
    return ndcg

In [55]:
try:
    experiment_id = mlflow.get_experiment_by_name(EXPERIMENT_NAME).experiment_id
except:
    experiment_id = mlflow.create_experiment(EXPERIMENT_NAME)

RUN_NAME_OPTUNE = 'RandomForestClassifier_optuna'

with mlflow.start_run(run_name=RUN_NAME_OPTUNE, experiment_id=experiment_id) as run:
    run_id = run.info.run_id

🏃 View run RandomForestClassifier_optuna at: http://127.0.0.1:5000/#/experiments/1/runs/b194102d3ba346fa850a1c0eba59f125
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

In [56]:
STUDY_NAME = "RandomForestClassifier_optuna"

mlflc = MLflowCallback(
    tracking_uri=f'http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}',
    metric_name="NDCG",
    create_experiment=False,
    mlflow_kwargs={'experiment_id': experiment_id, 'tags': {MLFLOW_PARENT_RUN_ID: run_id}}
)

In [57]:
study = optuna.create_study(direction='maximize', 
                            sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
                            study_name=STUDY_NAME,
                            storage=STUDY_DB_NAME,
                            load_if_exists=False)
study.optimize(objective, 
               n_trials=20, 
               callbacks=[mlflc]
              )
best_params_optuna = study.best_params

print(f"Number of finished trials: {len(study.trials)}")
print(f"Best params: {best_params_optuna}")

[I 2026-05-08 16:24:38,851] A new study created in RDB with name: RandomForestClassifier_optuna

Средний NDCG: 0.8564
Средний Precision: 0.6951
Средний Recall: 0.8292
Средний F1-Score: 0.7345
Средний NDCG: 0.8447
Средний Precision: 0.6848
Средний Recall: 0.8185
Средний F1-Score: 0.7240

[I 2026-05-08 16:26:22,825] Trial 0 finished with value: 0.8523321436552282 and parameters: {'n_estimators': 450, 'max_depth': 29, 'min_samples_split': 15, 'min_samples_leaf': 12}. Best is trial 0 with value: 0.8523321436552282.

Средний NDCG: 0.8523
Средний Precision: 0.6910
Средний Recall: 0.8239
Средний F1-Score: 0.7303
🏃 View run 0 at: http://127.0.0.1:5000/#/experiments/1/runs/15465de5aaca41de8841b8f8273c5ba0
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8332
Средний Precision: 0.6222
Средний Recall: 0.7997
Средний F1-Score: 0.6726
Средний NDCG: 0.8211
Средний Precision: 0.5975
Средний Recall: 0.7907
Средний F1-Score: 0.6518

[I 2026-05-08 16:26:57,471] Trial 1 finished with value: 0.8295085461850679 and parameters: {'n_estimators': 200, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 18}. Best is trial 0 with value: 0.8523321436552282.

Средний NDCG: 0.8295
Средний Precision: 0.6107
Средний Recall: 0.7980
Средний F1-Score: 0.6638
🏃 View run 1 at: http://127.0.0.1:5000/#/experiments/1/runs/26bce9a77b0146909f1fcf4bbf4d637f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8542
Средний Precision: 0.6749
Средний Recall: 0.8332
Средний F1-Score: 0.7225
Средний NDCG: 0.8431
Средний Precision: 0.6603
Средний Recall: 0.8219
Средний F1-Score: 0.7091

[I 2026-05-08 16:29:18,067] Trial 2 finished with value: 0.8504921953023532 and parameters: {'n_estimators': 650, 'max_depth': 22, 'min_samples_split': 2, 'min_samples_leaf': 20}. Best is trial 0 with value: 0.8523321436552282.

Средний NDCG: 0.8505
Средний Precision: 0.6704
Средний Recall: 0.8263
Средний F1-Score: 0.7174
🏃 View run 2 at: http://127.0.0.1:5000/#/experiments/1/runs/63c6900866464bae8c6b6d350ba60cca
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8407
Средний Precision: 0.6366
Средний Recall: 0.8081
Средний F1-Score: 0.6858
Средний NDCG: 0.8272
Средний Precision: 0.6154
Средний Recall: 0.7955
Средний F1-Score: 0.6663

[I 2026-05-08 16:31:15,863] Trial 3 finished with value: 0.8367149550025557 and parameters: {'n_estimators': 850, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.8523321436552282.

Средний NDCG: 0.8367
Средний Precision: 0.6321
Средний Recall: 0.8021
Средний F1-Score: 0.6807
🏃 View run 3 at: http://127.0.0.1:5000/#/experiments/1/runs/6d0fefccff2140e597a27a0851fc069e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8578
Средний Precision: 0.7195
Средний Recall: 0.8227
Средний F1-Score: 0.7480
Средний NDCG: 0.8458
Средний Precision: 0.7089
Средний Recall: 0.8107
Средний F1-Score: 0.7367

[I 2026-05-08 16:32:37,176] Trial 4 finished with value: 0.8538255587853936 and parameters: {'n_estimators': 350, 'max_depth': 17, 'min_samples_split': 10, 'min_samples_leaf': 6}. Best is trial 4 with value: 0.8538255587853936.

Средний NDCG: 0.8538
Средний Precision: 0.7147
Средний Recall: 0.8168
Средний F1-Score: 0.7427
🏃 View run 4 at: http://127.0.0.1:5000/#/experiments/1/runs/55d3e5f05fd143df8846b3f65bf154f8
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8277
Средний Precision: 0.6095
Средний Recall: 0.7963
Средний F1-Score: 0.6626
Средний NDCG: 0.8131
Средний Precision: 0.5863
Средний Recall: 0.7872
Средний F1-Score: 0.6425

[I 2026-05-08 16:33:53,664] Trial 5 finished with value: 0.822946864692375 and parameters: {'n_estimators': 650, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 8}. Best is trial 4 with value: 0.8538255587853936.

Средний NDCG: 0.8229
Средний Precision: 0.6000
Средний Recall: 0.7956
Средний F1-Score: 0.6559
🏃 View run 5 at: http://127.0.0.1:5000/#/experiments/1/runs/9d661943d639405b92bb49c361c2b94d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8565
Средний Precision: 0.6990
Средний Recall: 0.8279
Средний F1-Score: 0.7366
Средний NDCG: 0.8450
Средний Precision: 0.6890
Средний Recall: 0.8183
Средний F1-Score: 0.7268

[I 2026-05-08 16:35:46,363] Trial 6 finished with value: 0.8530654852788387 and parameters: {'n_estimators': 500, 'max_depth': 24, 'min_samples_split': 5, 'min_samples_leaf': 11}. Best is trial 4 with value: 0.8538255587853936.

Средний NDCG: 0.8531
Средний Precision: 0.6929
Средний Recall: 0.8232
Средний F1-Score: 0.7312
🏃 View run 6 at: http://127.0.0.1:5000/#/experiments/1/runs/b2b63b3fa783454399f8498301d561e1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8121
Средний Precision: 0.5637
Средний Recall: 0.7881
Средний F1-Score: 0.6272
Средний NDCG: 0.7965
Средний Precision: 0.5436
Средний Recall: 0.7743
Средний F1-Score: 0.6076

[I 2026-05-08 16:36:44,572] Trial 7 finished with value: 0.8051316004865074 and parameters: {'n_estimators': 650, 'max_depth': 4, 'min_samples_split': 13, 'min_samples_leaf': 4}. Best is trial 4 with value: 0.8538255587853936.

Средний NDCG: 0.8051
Средний Precision: 0.5594
Средний Recall: 0.7823
Средний F1-Score: 0.6226
🏃 View run 7 at: http://127.0.0.1:5000/#/experiments/1/runs/fc6622720a6c4d6e998042565a469575
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8542
Средний Precision: 0.6828
Средний Recall: 0.8311
Средний F1-Score: 0.7270
Средний NDCG: 0.8434
Средний Precision: 0.6663
Средний Recall: 0.8208
Средний F1-Score: 0.7128

[I 2026-05-08 16:37:26,549] Trial 8 finished with value: 0.850158502450918 and parameters: {'n_estimators': 150, 'max_depth': 29, 'min_samples_split': 20, 'min_samples_leaf': 17}. Best is trial 4 with value: 0.8538255587853936.

Средний NDCG: 0.8502
Средний Precision: 0.6763
Средний Recall: 0.8267
Средний F1-Score: 0.7220
🏃 View run 8 at: http://127.0.0.1:5000/#/experiments/1/runs/3321be9723b646088fc6f5d0459ebd1e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8178
Средний Precision: 0.5822
Средний Recall: 0.7942
Средний F1-Score: 0.6428
Средний NDCG: 0.8031
Средний Precision: 0.5604
Средний Recall: 0.7830
Средний F1-Score: 0.6222

[I 2026-05-08 16:38:08,350] Trial 9 finished with value: 0.8127352825473224 and parameters: {'n_estimators': 350, 'max_depth': 5, 'min_samples_split': 15, 'min_samples_leaf': 9}. Best is trial 4 with value: 0.8538255587853936.

Средний NDCG: 0.8127
Средний Precision: 0.5802
Средний Recall: 0.7886
Средний F1-Score: 0.6395
🏃 View run 9 at: http://127.0.0.1:5000/#/experiments/1/runs/56314d885c024a63b4ca5be598f4172d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8548
Средний Precision: 0.7096
Средний Recall: 0.8191
Средний F1-Score: 0.7396
Средний NDCG: 0.8432
Средний Precision: 0.6937
Средний Recall: 0.8096
Средний F1-Score: 0.7261

[I 2026-05-08 16:41:08,375] Trial 10 finished with value: 0.8514996300652127 and parameters: {'n_estimators': 950, 'max_depth': 13, 'min_samples_split': 9, 'min_samples_leaf': 1}. Best is trial 4 with value: 0.8538255587853936.

Средний NDCG: 0.8515
Средний Precision: 0.7040
Средний Recall: 0.8167
Средний F1-Score: 0.7352
🏃 View run 10 at: http://127.0.0.1:5000/#/experiments/1/runs/702d4ebf8340433b8df0297367c9a3e6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8562
Средний Precision: 0.6914
Средний Recall: 0.8304
Средний F1-Score: 0.7325
Средний NDCG: 0.8446
Средний Precision: 0.6804
Средний Recall: 0.8189
Средний F1-Score: 0.7214

[I 2026-05-08 16:42:30,113] Trial 11 finished with value: 0.8519503167770816 and parameters: {'n_estimators': 350, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 13}. Best is trial 4 with value: 0.8538255587853936.

Средний NDCG: 0.8520
Средний Precision: 0.6868
Средний Recall: 0.8224
Средний F1-Score: 0.7265
🏃 View run 11 at: http://127.0.0.1:5000/#/experiments/1/runs/c247ee695bbf407695e5b7f91a4b99cb
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8579
Средний Precision: 0.7179
Средний Recall: 0.8228
Средний F1-Score: 0.7470
Средний NDCG: 0.8463
Средний Precision: 0.7086
Средний Recall: 0.8121
Средний F1-Score: 0.7373

[I 2026-05-08 16:44:24,730] Trial 12 finished with value: 0.8542383039297237 and parameters: {'n_estimators': 500, 'max_depth': 23, 'min_samples_split': 7, 'min_samples_leaf': 7}. Best is trial 12 with value: 0.8542383039297237.

Средний NDCG: 0.8542
Средний Precision: 0.7142
Средний Recall: 0.8173
Средний F1-Score: 0.7426
🏃 View run 12 at: http://127.0.0.1:5000/#/experiments/1/runs/b3893236a9f34563b1ff28273e7fa4b1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8568
Средний Precision: 0.7131
Средний Recall: 0.8234
Средний F1-Score: 0.7440
Средний NDCG: 0.8453
Средний Precision: 0.6995
Средний Recall: 0.8116
Средний F1-Score: 0.7310

[I 2026-05-08 16:45:34,286] Trial 13 finished with value: 0.8529135720135553 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 6}. Best is trial 12 with value: 0.8542383039297237.

Средний NDCG: 0.8529
Средний Precision: 0.7065
Средний Recall: 0.8171
Средний F1-Score: 0.7373
🏃 View run 13 at: http://127.0.0.1:5000/#/experiments/1/runs/d96e69bf894b4aab9ed1b35275588ea2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8588
Средний Precision: 0.7452
Средний Recall: 0.8134
Средний F1-Score: 0.7605
Средний NDCG: 0.8473
Средний Precision: 0.7326
Средний Recall: 0.8005
Средний F1-Score: 0.7477

[I 2026-05-08 16:47:30,676] Trial 14 finished with value: 0.8547657516449213 and parameters: {'n_estimators': 500, 'max_depth': 19, 'min_samples_split': 13, 'min_samples_leaf': 1}. Best is trial 14 with value: 0.8547657516449213.

Средний NDCG: 0.8548
Средний Precision: 0.7364
Средний Recall: 0.8062
Средний F1-Score: 0.7525
🏃 View run 14 at: http://127.0.0.1:5000/#/experiments/1/runs/6b2e568061ea4d13bbdcbabfc04ac863
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8604
Средний Precision: 0.7450
Средний Recall: 0.8139
Средний F1-Score: 0.7608
Средний NDCG: 0.8479
Средний Precision: 0.7338
Средний Recall: 0.8022
Средний F1-Score: 0.7494

[I 2026-05-08 16:50:25,293] Trial 15 finished with value: 0.8552750704974597 and parameters: {'n_estimators': 750, 'max_depth': 25, 'min_samples_split': 13, 'min_samples_leaf': 2}. Best is trial 15 with value: 0.8552750704974597.

Средний NDCG: 0.8553
Средний Precision: 0.7379
Средний Recall: 0.8065
Средний F1-Score: 0.7539
🏃 View run 15 at: http://127.0.0.1:5000/#/experiments/1/runs/96370798cd6e4a40a632c1781fd7d7ca
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8595
Средний Precision: 0.7457
Средний Recall: 0.8151
Средний F1-Score: 0.7617
Средний NDCG: 0.8477
Средний Precision: 0.7329
Средний Recall: 0.8017
Средний F1-Score: 0.7486

[I 2026-05-08 16:53:24,815] Trial 16 finished with value: 0.8557538330964121 and parameters: {'n_estimators': 800, 'max_depth': 26, 'min_samples_split': 17, 'min_samples_leaf': 1}. Best is trial 16 with value: 0.8557538330964121.

Средний NDCG: 0.8558
Средний Precision: 0.7381
Средний Recall: 0.8068
Средний F1-Score: 0.7538
🏃 View run 16 at: http://127.0.0.1:5000/#/experiments/1/runs/bdf76166017f4344a2c8b86b6675c39b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8591
Средний Precision: 0.7282
Средний Recall: 0.8206
Средний F1-Score: 0.7532
Средний NDCG: 0.8470
Средний Precision: 0.7156
Средний Recall: 0.8092
Средний F1-Score: 0.7408

[I 2026-05-08 16:56:42,027] Trial 17 finished with value: 0.8545694734215402 and parameters: {'n_estimators': 900, 'max_depth': 26, 'min_samples_split': 20, 'min_samples_leaf': 3}. Best is trial 16 with value: 0.8557538330964121.

Средний NDCG: 0.8546
Средний Precision: 0.7243
Средний Recall: 0.8152
Средний F1-Score: 0.7484
🏃 View run 17 at: http://127.0.0.1:5000/#/experiments/1/runs/ce4c40a3f87f4918ae1c254c45c0d256
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8595
Средний Precision: 0.7456
Средний Recall: 0.8148
Средний F1-Score: 0.7614
Средний NDCG: 0.8477
Средний Precision: 0.7323
Средний Recall: 0.8015
Средний F1-Score: 0.7483

[I 2026-05-08 16:59:31,124] Trial 18 finished with value: 0.855576057230516 and parameters: {'n_estimators': 750, 'max_depth': 26, 'min_samples_split': 17, 'min_samples_leaf': 1}. Best is trial 16 with value: 0.8557538330964121.

Средний NDCG: 0.8556
Средний Precision: 0.7382
Средний Recall: 0.8071
Средний F1-Score: 0.7541
🏃 View run 18 at: http://127.0.0.1:5000/#/experiments/1/runs/5f8c35e89d2c4ae39e77026837e0a187
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8555
Средний Precision: 0.6860
Средний Recall: 0.8306
Средний F1-Score: 0.7292
Средний NDCG: 0.8441
Средний Precision: 0.6733
Средний Recall: 0.8199
Средний F1-Score: 0.7170

[I 2026-05-08 17:13:30,591] Trial 19 finished with value: 0.8514907068762502 and parameters: {'n_estimators': 1000, 'max_depth': 30, 'min_samples_split': 18, 'min_samples_leaf': 15}. Best is trial 16 with value: 0.8557538330964121.

Средний NDCG: 0.8515
Средний Precision: 0.6815
Средний Recall: 0.8254
Средний F1-Score: 0.7248
🏃 View run 19 at: http://127.0.0.1:5000/#/experiments/1/runs/41839114667745bdb509f437d14b415b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Number of finished trials: 20
Best params: {'n_estimators': 800, 'max_depth': 26, 'min_samples_split': 17, 'min_samples_leaf': 1}

In [58]:
study.best_trial.user_attrs['pipeline_params']

{'model__n_estimators': 800,
 'model__max_depth': 26,
 'model__min_samples_split': 17,
 'model__min_samples_leaf': 1}

In [59]:
pipeline_rf_best_optuna = Pipeline([
        ('preprocessing', ColumnTransformer([
            ('numeric_scaling', StandardScaler(), numeric_features),
            ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
        ])),
        ('model', RandomForestClassifier(random_state=RANDOM_STATE, class_weight='balanced'))
    ])

pipeline_rf_best_optuna.set_params(**study.best_trial.user_attrs['pipeline_params'])
pipeline_rf_best_optuna.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('numeric_scaling',
                                                  StandardScaler(),
                                                  Index(['resume_salary', 'resume_age', 'resume_experience_months',
       'resume_last_company_experience_months', 'location_matching',
       'resume_skill_count_in_vacancy', 'last_position_in_vacancy',
       'similarity_score_tfidf'],
      dtype='object')),
                                                 ('categorical_encoding',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  Index(['vacancy_area', 'vacancy_experience', 'vacancy_employment',
       'vacancy_schedule', 'resume_location', 'resume_gender',
       'resume_applicant_status'],
      dtype='object'))])),
                ('model',
                 RandomForestClassifier(class_weight='balanced', max_depth=26,
                                        min_samples_split=17, n_estimators=800,
                                        random_state=42))])

In [60]:
y_pred_proba = pipeline_rf_best_optuna.predict_proba(X_test)

df_test = df.loc[X_test.index].copy()
df_test['y_pred_proba'] = y_pred_proba[:, 1]

In [61]:
ndcg_rf, precision_rf, recall_rf, f1_rf = calculate_metrics(df_test)

metrics_rf = {
    'NDCG': ndcg_rf,
    'Precision': precision_rf,
    'Recall': recall_rf,
    'F1': f1_rf
}

Средний NDCG: 0.7776
Средний Precision: 0.6830
Средний Recall: 0.7355
Средний F1-Score: 0.6934

In [62]:
RUN_NAME = "best_optuna_rf" 
REGISTRY_MODEL_NAME = "best_optuna_rf"

In [63]:
signature = mlflow.models.infer_signature(X_test, y_test)
input_example = X_test[:10]
code_paths = ["ML_Experiments.ipynb"]

try:
    experiment_id = mlflow.get_experiment_by_name(EXPERIMENT_NAME).experiment_id
except:
    experiment_id = mlflow.create_experiment(EXPERIMENT_NAME)

with mlflow.start_run(run_name=RUN_NAME, experiment_id=experiment_id) as run:
    run_id = run.info.run_id

    lr_info = mlflow.sklearn.log_model(sk_model=pipeline_rf_best_optuna, 
                                       artifact_path='best_optuna_rf',
                                       registered_model_name=REGISTRY_MODEL_NAME,
                                       input_example=input_example,
                                       code_paths=code_paths,
                                       await_registration_for=60
                                      )
    mlflow.log_metrics(metrics_rf)
    mlflow.log_params(best_params_optuna)

Successfully registered model 'best_optuna_rf'.
2026/05/08 17:15:02 INFO mlflow.store.model_registry.abstract_store: Waiting up to 60 seconds for model version to finish creation. Model name: best_optuna_rf, version 1

🏃 View run best_optuna_rf at: http://127.0.0.1:5000/#/experiments/1/runs/886fbc90fa7a45ada1c14aa7a5ed25e3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

Created version '1' of model 'best_optuna_rf'.

# XGBClassifier

In [64]:
def objective_xgb(trial: optuna.Trial) -> float:
    params = {
        'model__n_estimators': trial.suggest_int('n_estimators', 100, 1000, step=50),
        'model__max_depth': trial.suggest_int('max_depth', 3, 15),
        'model__learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'model__min_child_weight': trial.suggest_int('min_child_weight', 1, 10)
    }
    
    pipeline_xgb = Pipeline([
        ('preprocessing', ColumnTransformer([
            ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
        ], remainder='passthrough')),
        ('model', XGBClassifier(
            random_state=RANDOM_STATE, 
            eval_metric='logloss', 
            use_label_encoder=False, 
            verbosity=0,
            scale_pos_weight=(len(y_train) - sum(y_train)) / sum(y_train)
        ))
    ])
    
    pipeline_xgb.set_params(**params)
    
    kfold = StratifiedKFold(n_splits=3, shuffle=True, random_state=RANDOM_STATE)
    
    for train_idx, val_idx in kfold.split(X_train, y_train):
        X_fold_train, X_fold_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_fold_train, y_fold_val = y_train.iloc[train_idx], y_train.iloc[val_idx]
        
        pipeline_xgb.fit(X_fold_train, y_fold_train)
        y_pred_proba = pipeline_xgb.predict_proba(X_fold_val)
        
        df_val = df.loc[X_fold_val.index].copy()
        df_val['y_pred_proba'] = y_pred_proba[:, 1]
        
        ndcg, _, _, _ = calculate_metrics(df_val)
        
        trial.set_user_attr('pipeline_params', params)
    
    return ndcg

In [65]:
try:
    experiment_id = mlflow.get_experiment_by_name(EXPERIMENT_NAME).experiment_id
except:
    experiment_id = mlflow.create_experiment(EXPERIMENT_NAME)

RUN_NAME_OPTUNE_XGB = 'XGBClassifier_optuna'

with mlflow.start_run(run_name=RUN_NAME_OPTUNE_XGB, experiment_id=experiment_id) as run:
    run_id_xgb = run.info.run_id

🏃 View run XGBClassifier_optuna at: http://127.0.0.1:5000/#/experiments/1/runs/ee3f6916f8ec4dc3b614739e8bca15f5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

In [66]:
STUDY_NAME_XGB = "XGBClassifier_optuna"

mlflc_xgb = MLflowCallback(
    tracking_uri=f'http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}',
    metric_name="NDCG",
    create_experiment=False,
    mlflow_kwargs={'experiment_id': experiment_id, 'tags': {MLFLOW_PARENT_RUN_ID: run_id_xgb}}
)

In [67]:
study_xgb = optuna.create_study(direction='maximize', 
                                sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
                                study_name=STUDY_NAME_XGB,
                                storage=STUDY_DB_NAME,
                                load_if_exists=False)

study_xgb.optimize(objective_xgb, 
                   n_trials=20, 
                   callbacks=[mlflc_xgb]
                  )

best_params_xgb = study_xgb.best_params
print(f"Number of finished trials: {len(study_xgb.trials)}")
print(f"Best params XGBoost: {best_params_xgb}")

[I 2026-05-08 17:15:02,200] A new study created in RDB with name: XGBClassifier_optuna

Средний NDCG: 0.8600
Средний Precision: 0.7702
Средний Recall: 0.8029
Средний F1-Score: 0.7708
Средний NDCG: 0.8474
Средний Precision: 0.7509
Средний Recall: 0.7874
Средний F1-Score: 0.7534

[I 2026-05-08 17:15:22,727] Trial 0 finished with value: 0.8558738164850641 and parameters: {'n_estimators': 450, 'max_depth': 15, 'learning_rate': 0.1205712628744377, 'min_child_weight': 6}. Best is trial 0 with value: 0.8558738164850641.

Средний NDCG: 0.8559
Средний Precision: 0.7618
Средний Recall: 0.7934
Средний F1-Score: 0.7620
🏃 View run 0 at: http://127.0.0.1:5000/#/experiments/1/runs/ce9c9e5208da4a809793aa36be09a522
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8386
Средний Precision: 0.6220
Средний Recall: 0.8042
Средний F1-Score: 0.6742
Средний NDCG: 0.8291
Средний Precision: 0.6081
Средний Recall: 0.7930
Средний F1-Score: 0.6597

[I 2026-05-08 17:15:36,277] Trial 1 finished with value: 0.8353950197667808 and parameters: {'n_estimators': 200, 'max_depth': 5, 'learning_rate': 0.012184186502221764, 'min_child_weight': 9}. Best is trial 0 with value: 0.8558738164850641.

Средний NDCG: 0.8354
Средний Precision: 0.6198
Средний Recall: 0.7989
Средний F1-Score: 0.6712
🏃 View run 1 at: http://127.0.0.1:5000/#/experiments/1/runs/03bfb1fd3c6c4920ae7a98136a512b53
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8572
Средний Precision: 0.7214
Средний Recall: 0.8251
Средний F1-Score: 0.7505
Средний NDCG: 0.8460
Средний Precision: 0.7055
Средний Recall: 0.8125
Средний F1-Score: 0.7359

[I 2026-05-08 17:15:58,959] Trial 2 finished with value: 0.8536724408121985 and parameters: {'n_estimators': 650, 'max_depth': 12, 'learning_rate': 0.010725209743171997, 'min_child_weight': 10}. Best is trial 0 with value: 0.8558738164850641.

Средний NDCG: 0.8537
Средний Precision: 0.7149
Средний Recall: 0.8153
Средний F1-Score: 0.7429
🏃 View run 2 at: http://127.0.0.1:5000/#/experiments/1/runs/3cb4959b9e634a4880b5cddf1823696b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8549
Средний Precision: 0.6634
Средний Recall: 0.8323
Средний F1-Score: 0.7147
Средний NDCG: 0.8446
Средний Precision: 0.6555
Средний Recall: 0.8202
Средний F1-Score: 0.7042

[I 2026-05-08 17:16:17,020] Trial 3 finished with value: 0.851348108983658 and parameters: {'n_estimators': 850, 'max_depth': 5, 'learning_rate': 0.01855998084649058, 'min_child_weight': 2}. Best is trial 0 with value: 0.8558738164850641.

Средний NDCG: 0.8513
Средний Precision: 0.6651
Средний Recall: 0.8270
Средний F1-Score: 0.7139
🏃 View run 3 at: http://127.0.0.1:5000/#/experiments/1/runs/7ecea823ce7843cd9640e8661a8a7093
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8602
Средний Precision: 0.7239
Средний Recall: 0.8259
Средний F1-Score: 0.7525
Средний NDCG: 0.8471
Средний Precision: 0.7184
Средний Recall: 0.8187
Средний F1-Score: 0.7471

[I 2026-05-08 17:16:33,504] Trial 4 finished with value: 0.8556496280306192 and parameters: {'n_estimators': 350, 'max_depth': 9, 'learning_rate': 0.04345454109729477, 'min_child_weight': 3}. Best is trial 0 with value: 0.8558738164850641.

Средний NDCG: 0.8556
Средний Precision: 0.7239
Средний Recall: 0.8200
Средний F1-Score: 0.7509
🏃 View run 4 at: http://127.0.0.1:5000/#/experiments/1/runs/023bda9506ca4e438f321881c400f36e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8524
Средний Precision: 0.6530
Средний Recall: 0.8288
Средний F1-Score: 0.7061
Средний NDCG: 0.8414
Средний Precision: 0.6441
Средний Recall: 0.8188
Средний F1-Score: 0.6956

[I 2026-05-08 17:16:49,485] Trial 5 finished with value: 0.8485689474664239 and parameters: {'n_estimators': 650, 'max_depth': 4, 'learning_rate': 0.027010527749605478, 'min_child_weight': 4}. Best is trial 0 with value: 0.8558738164850641.

Средний NDCG: 0.8486
Средний Precision: 0.6517
Средний Recall: 0.8262
Средний F1-Score: 0.7043
🏃 View run 5 at: http://127.0.0.1:5000/#/experiments/1/runs/056f3ca1ef3940f9b0ff5eb470ca992d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8592
Средний Precision: 0.7420
Средний Recall: 0.8159
Средний F1-Score: 0.7593
Средний NDCG: 0.8471
Средний Precision: 0.7259
Средний Recall: 0.8049
Средний F1-Score: 0.7456

[I 2026-05-08 17:17:10,699] Trial 6 finished with value: 0.8553548180045428 and parameters: {'n_estimators': 500, 'max_depth': 13, 'learning_rate': 0.019721610970574007, 'min_child_weight': 6}. Best is trial 0 with value: 0.8558738164850641.

Средний NDCG: 0.8554
Средний Precision: 0.7387
Средний Recall: 0.8102
Средний F1-Score: 0.7558
🏃 View run 6 at: http://127.0.0.1:5000/#/experiments/1/runs/f5419d80a37944c8b91137e8f1dffc10
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8536
Средний Precision: 0.6616
Средний Recall: 0.8328
Средний F1-Score: 0.7134
Средний NDCG: 0.8449
Средний Precision: 0.6519
Средний Recall: 0.8230
Средний F1-Score: 0.7028

[I 2026-05-08 17:17:26,092] Trial 7 finished with value: 0.8500549667096924 and parameters: {'n_estimators': 650, 'max_depth': 3, 'learning_rate': 0.07896186801026692, 'min_child_weight': 2}. Best is trial 0 with value: 0.8558738164850641.

Средний NDCG: 0.8501
Средний Precision: 0.6606
Средний Recall: 0.8268
Средний F1-Score: 0.7106
🏃 View run 7 at: http://127.0.0.1:5000/#/experiments/1/runs/5418b9f21c694808b18115f3967d4709
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8592
Средний Precision: 0.7626
Средний Recall: 0.8094
Средний F1-Score: 0.7700
Средний NDCG: 0.8474
Средний Precision: 0.7515
Средний Recall: 0.7930
Средний F1-Score: 0.7564

[I 2026-05-08 17:17:41,303] Trial 8 finished with value: 0.8562507847014694 and parameters: {'n_estimators': 150, 'max_depth': 15, 'learning_rate': 0.26690431824362526, 'min_child_weight': 9}. Best is trial 8 with value: 0.8562507847014694.

Средний NDCG: 0.8563
Средний Precision: 0.7585
Средний Recall: 0.7979
Средний F1-Score: 0.7621
🏃 View run 8 at: http://127.0.0.1:5000/#/experiments/1/runs/277d2c96ecce451e9b26554ae0418ce6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8557
Средний Precision: 0.6731
Средний Recall: 0.8346
Средний F1-Score: 0.7226
Средний NDCG: 0.8456
Средний Precision: 0.6630
Средний Recall: 0.8226
Средний F1-Score: 0.7105

[I 2026-05-08 17:17:55,675] Trial 9 finished with value: 0.8521226821676651 and parameters: {'n_estimators': 350, 'max_depth': 4, 'learning_rate': 0.1024932221692416, 'min_child_weight': 5}. Best is trial 8 with value: 0.8562507847014694.

Средний NDCG: 0.8521
Средний Precision: 0.6753
Средний Recall: 0.8300
Средний F1-Score: 0.7218
🏃 View run 9 at: http://127.0.0.1:5000/#/experiments/1/runs/a1f3b1b17c3d41cf9a1112e9d55e60dd
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8600
Средний Precision: 0.7359
Средний Recall: 0.8238
Средний F1-Score: 0.7597
Средний NDCG: 0.8468
Средний Precision: 0.7276
Средний Recall: 0.8142
Средний F1-Score: 0.7511

[I 2026-05-08 17:18:09,282] Trial 10 finished with value: 0.8563397999832385 and parameters: {'n_estimators': 100, 'max_depth': 9, 'learning_rate': 0.27047297227177763, 'min_child_weight': 8}. Best is trial 10 with value: 0.8563397999832385.

Средний NDCG: 0.8563
Средний Precision: 0.7330
Средний Recall: 0.8169
Средний F1-Score: 0.7557
🏃 View run 10 at: http://127.0.0.1:5000/#/experiments/1/runs/47008ec451bd4534ad7177fd1fa46689
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8600
Средний Precision: 0.7384
Средний Recall: 0.8268
Средний F1-Score: 0.7623
Средний NDCG: 0.8472
Средний Precision: 0.7311
Средний Recall: 0.8125
Средний F1-Score: 0.7530

[I 2026-05-08 17:18:22,763] Trial 11 finished with value: 0.8555417103077537 and parameters: {'n_estimators': 100, 'max_depth': 9, 'learning_rate': 0.2871240081991256, 'min_child_weight': 8}. Best is trial 10 with value: 0.8563397999832385.

Средний NDCG: 0.8555
Средний Precision: 0.7421
Средний Recall: 0.8168
Средний F1-Score: 0.7609
🏃 View run 11 at: http://127.0.0.1:5000/#/experiments/1/runs/f0c3ab4ed26341df8bb650041b7fc5fc
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8606
Средний Precision: 0.7154
Средний Recall: 0.8352
Средний F1-Score: 0.7519
Средний NDCG: 0.8484
Средний Precision: 0.7070
Средний Recall: 0.8223
Средний F1-Score: 0.7413

[I 2026-05-08 17:18:36,130] Trial 12 finished with value: 0.8565776550663435 and parameters: {'n_estimators': 100, 'max_depth': 7, 'learning_rate': 0.2955427705844086, 'min_child_weight': 8}. Best is trial 12 with value: 0.8565776550663435.

Средний NDCG: 0.8566
Средний Precision: 0.7149
Средний Recall: 0.8258
Средний F1-Score: 0.7476
🏃 View run 12 at: http://127.0.0.1:5000/#/experiments/1/runs/37e4781b66dc46a88d5c76d77f3ab210
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8616
Средний Precision: 0.7349
Средний Recall: 0.8314
Средний F1-Score: 0.7623
Средний NDCG: 0.8480
Средний Precision: 0.7250
Средний Recall: 0.8191
Средний F1-Score: 0.7519

[I 2026-05-08 17:18:50,805] Trial 13 finished with value: 0.8567358977279521 and parameters: {'n_estimators': 250, 'max_depth': 7, 'learning_rate': 0.18678156098661158, 'min_child_weight': 7}. Best is trial 13 with value: 0.8567358977279521.

Средний NDCG: 0.8567
Средний Precision: 0.7295
Средний Recall: 0.8227
Средний F1-Score: 0.7557
🏃 View run 13 at: http://127.0.0.1:5000/#/experiments/1/runs/a08efef420f14bbc8dceacf5ade212f0
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8616
Средний Precision: 0.7322
Средний Recall: 0.8315
Средний F1-Score: 0.7603
Средний NDCG: 0.8481
Средний Precision: 0.7216
Средний Recall: 0.8205
Средний F1-Score: 0.7503

[I 2026-05-08 17:19:05,432] Trial 14 finished with value: 0.8574828172181674 and parameters: {'n_estimators': 250, 'max_depth': 7, 'learning_rate': 0.16401332399717264, 'min_child_weight': 7}. Best is trial 14 with value: 0.8574828172181674.

Средний NDCG: 0.8575
Средний Precision: 0.7287
Средний Recall: 0.8236
Средний F1-Score: 0.7556
🏃 View run 14 at: http://127.0.0.1:5000/#/experiments/1/runs/cecc8bd147a44f72bbbfbf1c81de27e9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8616
Средний Precision: 0.7360
Средний Recall: 0.8316
Средний F1-Score: 0.7630
Средний NDCG: 0.8481
Средний Precision: 0.7241
Средний Recall: 0.8159
Средний F1-Score: 0.7502

[I 2026-05-08 17:19:20,512] Trial 15 finished with value: 0.8572907063255862 and parameters: {'n_estimators': 300, 'max_depth': 7, 'learning_rate': 0.17230712267755632, 'min_child_weight': 7}. Best is trial 14 with value: 0.8574828172181674.

Средний NDCG: 0.8573
Средний Precision: 0.7347
Средний Recall: 0.8225
Средний F1-Score: 0.7593
🏃 View run 15 at: http://127.0.0.1:5000/#/experiments/1/runs/86b938ed268d404cb7ba3d535afddc24
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8611
Средний Precision: 0.7468
Средний Recall: 0.8295
Средний F1-Score: 0.7692
Средний NDCG: 0.8481
Средний Precision: 0.7346
Средний Recall: 0.8123
Средний F1-Score: 0.7548

[I 2026-05-08 17:19:36,563] Trial 16 finished with value: 0.8570136869025 and parameters: {'n_estimators': 400, 'max_depth': 7, 'learning_rate': 0.14819327912615757, 'min_child_weight': 5}. Best is trial 14 with value: 0.8574828172181674.

Средний NDCG: 0.8570
Средний Precision: 0.7403
Средний Recall: 0.8195
Средний F1-Score: 0.7617
🏃 View run 16 at: http://127.0.0.1:5000/#/experiments/1/runs/8ac650b7604447f5b7b84634882a72ce
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8605
Средний Precision: 0.7647
Средний Recall: 0.8079
Средний F1-Score: 0.7700
Средний NDCG: 0.8476
Средний Precision: 0.7565
Средний Recall: 0.7974
Средний F1-Score: 0.7616

[I 2026-05-08 17:20:02,660] Trial 17 finished with value: 0.8567614015517478 and parameters: {'n_estimators': 1000, 'max_depth': 11, 'learning_rate': 0.06817779343845322, 'min_child_weight': 7}. Best is trial 14 with value: 0.8574828172181674.

Средний NDCG: 0.8568
Средний Precision: 0.7616
Средний Recall: 0.7995
Средний F1-Score: 0.7647
🏃 View run 17 at: http://127.0.0.1:5000/#/experiments/1/runs/11fd108b49bf421382aeab8870cb481b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8550
Средний Precision: 0.6724
Средний Recall: 0.8353
Средний F1-Score: 0.7221
Средний NDCG: 0.8446
Средний Precision: 0.6637
Средний Recall: 0.8200
Средний F1-Score: 0.7096

[I 2026-05-08 17:20:17,177] Trial 18 finished with value: 0.8517045537157859 and parameters: {'n_estimators': 250, 'max_depth': 6, 'learning_rate': 0.0470590358414764, 'min_child_weight': 4}. Best is trial 14 with value: 0.8574828172181674.

Средний NDCG: 0.8517
Средний Precision: 0.6711
Средний Recall: 0.8284
Средний F1-Score: 0.7187
🏃 View run 18 at: http://127.0.0.1:5000/#/experiments/1/runs/759d5ba4b7d043d6abaa4432b5dc3bfc
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8601
Средний Precision: 0.7633
Средний Recall: 0.8121
Средний F1-Score: 0.7710
Средний NDCG: 0.8478
Средний Precision: 0.7506
Средний Recall: 0.8027
Средний F1-Score: 0.7606

[I 2026-05-08 17:20:33,530] Trial 19 finished with value: 0.8573114855204316 and parameters: {'n_estimators': 300, 'max_depth': 10, 'learning_rate': 0.18266145263423655, 'min_child_weight': 7}. Best is trial 14 with value: 0.8574828172181674.

Средний NDCG: 0.8573
Средний Precision: 0.7569
Средний Recall: 0.8053
Средний F1-Score: 0.7652
🏃 View run 19 at: http://127.0.0.1:5000/#/experiments/1/runs/5b9ddd91dc5a4e719757279a3f438bdd
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Number of finished trials: 20
Best params XGBoost: {'n_estimators': 250, 'max_depth': 7, 'learning_rate': 0.16401332399717264, 'min_child_weight': 7}

In [68]:
pipeline_xgb_best = Pipeline([
    ('preprocessing', ColumnTransformer([
        ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
    ], remainder='passthrough')),
    ('model', XGBClassifier(
        random_state=RANDOM_STATE, 
        eval_metric='logloss', 
        use_label_encoder=False, 
        verbosity=0,
        scale_pos_weight=(len(y_train) - sum(y_train)) / sum(y_train)
    ))
])

pipeline_xgb_best.set_params(**study_xgb.best_trial.user_attrs['pipeline_params'])
pipeline_xgb_best.fit(X_train, y_train)

y_pred_proba_xgb = pipeline_xgb_best.predict_proba(X_test)

df_test_xgb = df.loc[X_test.index].copy()
df_test_xgb['y_pred_proba'] = y_pred_proba_xgb[:, 1]

ndcg_xgb, precision_xgb, recall_xgb, f1_xgb = calculate_metrics(df_test_xgb)
metrics_xgb = {
    'NDCG': ndcg_xgb,
    'Precision': precision_xgb,
    'Recall': recall_xgb,
    'F1': f1_xgb
}

Средний NDCG: 0.7790
Средний Precision: 0.6673
Средний Recall: 0.7522
Средний F1-Score: 0.6915

In [69]:
RUN_NAME_XGB = "best_optuna_xgb"
REGISTRY_MODEL_NAME_XGB = "best_optuna_xgb"

signature = mlflow.models.infer_signature(X_test, y_test)
input_example = X_test[:10]
code_paths = ["ML_Experiments.ipynb"]

with mlflow.start_run(run_name=RUN_NAME_XGB, experiment_id=experiment_id) as run:
    run_id = run.info.run_id
    
    xgb_info = mlflow.sklearn.log_model(sk_model=pipeline_xgb_best, 
                                       artifact_path='best_optuna_xgb',
                                       registered_model_name=REGISTRY_MODEL_NAME_XGB,
                                       input_example=input_example,
                                       code_paths=code_paths,
                                       await_registration_for=60
                                      )
    mlflow.log_metrics(metrics_xgb)
    mlflow.log_params(best_params_xgb)

Successfully registered model 'best_optuna_xgb'.
2026/05/08 17:20:40 INFO mlflow.store.model_registry.abstract_store: Waiting up to 60 seconds for model version to finish creation. Model name: best_optuna_xgb, version 1

🏃 View run best_optuna_xgb at: http://127.0.0.1:5000/#/experiments/1/runs/5fd911c2983c4196a762137b4a0f0444
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

Created version '1' of model 'best_optuna_xgb'.

# LGBMClassifier

In [70]:
def objective_lgbm(trial: optuna.Trial) -> float:
    params = {
        'model__n_estimators': trial.suggest_int('n_estimators', 100, 1000, step=50),
        'model__max_depth': trial.suggest_int('max_depth', 3, 15),
        'model__learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'model__num_leaves': trial.suggest_int('num_leaves', 20, 300),
        'model__min_child_samples': trial.suggest_int('min_child_samples', 5, 100)
    }
    
    pipeline_lgbm = Pipeline([
        ('preprocessing', ColumnTransformer([
            ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
        ], remainder='passthrough')),
        ('model', LGBMClassifier(
            random_state=RANDOM_STATE, 
            verbose=-1,
            class_weight='balanced'
        ))
    ])
    
    pipeline_lgbm.set_params(**params)
    
    kfold = StratifiedKFold(n_splits=3, shuffle=True, random_state=RANDOM_STATE)
    
    for train_idx, val_idx in kfold.split(X_train, y_train):
        X_fold_train, X_fold_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_fold_train, y_fold_val = y_train.iloc[train_idx], y_train.iloc[val_idx]
        
        pipeline_lgbm.fit(X_fold_train, y_fold_train)
        y_pred_proba = pipeline_lgbm.predict_proba(X_fold_val)
        
        df_val = df.loc[X_fold_val.index].copy()
        df_val['y_pred_proba'] = y_pred_proba[:, 1]
        
        ndcg, _, _, _ = calculate_metrics(df_val)
        
        trial.set_user_attr('pipeline_params', params)
    
    return ndcg

In [71]:
RUN_NAME_OPTUNE_LGBM = 'LGBMClassifier_optuna'

with mlflow.start_run(run_name=RUN_NAME_OPTUNE_LGBM, experiment_id=experiment_id) as run:
    run_id_lgbm = run.info.run_id

🏃 View run LGBMClassifier_optuna at: http://127.0.0.1:5000/#/experiments/1/runs/a19ad18001e44077bcce90509eeaa80a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

In [72]:
STUDY_NAME_LGBM = "LGBMClassifier_optuna"

mlflc_lgbm = MLflowCallback(
    tracking_uri=f'http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}',
    metric_name="NDCG",
    create_experiment=False,
    mlflow_kwargs={'experiment_id': experiment_id, 'tags': {MLFLOW_PARENT_RUN_ID: run_id_lgbm}}
)

In [ ]:
study_lgbm = optuna.create_study(direction='maximize', 
                                 sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
                                 study_name=STUDY_NAME_LGBM,
                                 storage=STUDY_DB_NAME,
                                 load_if_exists=False)

study_lgbm.optimize(objective_lgbm, 
                    n_trials=20, 
                    callbacks=[mlflc_lgbm]
                   )

best_params_lgbm = study_lgbm.best_params
print(f"Number of finished trials: {len(study_lgbm.trials)}")
print(f"Best params LGBM: {best_params_lgbm}")

[I 2026-05-08 17:20:40,681] A new study created in RDB with name: LGBMClassifier_optuna

Средний NDCG: 0.8603
Средний Precision: 0.7741
Средний Recall: 0.7994
Средний F1-Score: 0.7718
Средний NDCG: 0.8472
Средний Precision: 0.7656
Средний Recall: 0.7870
Средний F1-Score: 0.7619

[I 2026-05-08 17:21:57,115] Trial 0 finished with value: 0.85649136123959 and parameters: {'n_estimators': 450, 'max_depth': 15, 'learning_rate': 0.1205712628744377, 'num_leaves': 188, 'min_child_samples': 19}. Best is trial 0 with value: 0.85649136123959.

Средний NDCG: 0.8565
Средний Precision: 0.7675
Средний Recall: 0.7869
Средний F1-Score: 0.7622
🏃 View run 0 at: http://127.0.0.1:5000/#/experiments/1/runs/1b42fdbc9fdc41ce98ff6a3794848627
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8525
Средний Precision: 0.6547
Средний Recall: 0.8323
Средний F1-Score: 0.7091
Средний NDCG: 0.8432
Средний Precision: 0.6440
Средний Recall: 0.8218
Средний F1-Score: 0.6971

[I 2026-05-08 17:22:10,963] Trial 1 finished with value: 0.8492437739747656 and parameters: {'n_estimators': 200, 'max_depth': 3, 'learning_rate': 0.19030368381735815, 'num_leaves': 188, 'min_child_samples': 72}. Best is trial 0 with value: 0.85649136123959.

Средний NDCG: 0.8492
Средний Precision: 0.6507
Средний Recall: 0.8265
Средний F1-Score: 0.7039
🏃 View run 1 at: http://127.0.0.1:5000/#/experiments/1/runs/646b847335b141bbbb8f0db60c5dd662
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8595
Средний Precision: 0.7153
Средний Recall: 0.8311
Средний F1-Score: 0.7496
Средний NDCG: 0.8483
Средний Precision: 0.7075
Средний Recall: 0.8216
Средний F1-Score: 0.7408

[I 2026-05-08 17:22:29,760] Trial 2 finished with value: 0.8571175629509271 and parameters: {'n_estimators': 100, 'max_depth': 15, 'learning_rate': 0.1696753360719655, 'num_leaves': 79, 'min_child_samples': 22}. Best is trial 2 with value: 0.8571175629509271.

Средний NDCG: 0.8571
Средний Precision: 0.7175
Средний Recall: 0.8259
Средний F1-Score: 0.7489
🏃 View run 2 at: http://127.0.0.1:5000/#/experiments/1/runs/4613104e45534152a353f3bfd62bdadb
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8563
Средний Precision: 0.6804
Средний Recall: 0.8347
Средний F1-Score: 0.7273
Средний NDCG: 0.8463
Средний Precision: 0.6695
Средний Recall: 0.8209
Средний F1-Score: 0.7145

[I 2026-05-08 17:22:50,196] Trial 3 finished with value: 0.852488913058401 and parameters: {'n_estimators': 250, 'max_depth': 6, 'learning_rate': 0.05958389350068958, 'num_leaves': 141, 'min_child_samples': 32}. Best is trial 2 with value: 0.8571175629509271.

Средний NDCG: 0.8525
Средний Precision: 0.6786
Средний Recall: 0.8286
Средний F1-Score: 0.7241
🏃 View run 3 at: http://127.0.0.1:5000/#/experiments/1/runs/952486af26d74d5dba308d3ef65e9d2a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8522
Средний Precision: 0.6533
Средний Recall: 0.8294
Средний F1-Score: 0.7067
Средний NDCG: 0.8420
Средний Precision: 0.6423
Средний Recall: 0.8185
Средний F1-Score: 0.6942

[I 2026-05-08 17:23:09,497] Trial 4 finished with value: 0.847984290013643 and parameters: {'n_estimators': 650, 'max_depth': 4, 'learning_rate': 0.027010527749605478, 'num_leaves': 122, 'min_child_samples': 48}. Best is trial 2 with value: 0.8571175629509271.

Средний NDCG: 0.8480
Средний Precision: 0.6501
Средний Recall: 0.8264
Средний F1-Score: 0.7039
🏃 View run 4 at: http://127.0.0.1:5000/#/experiments/1/runs/648cd8768fa44b3fbf4e1a4685c6d567
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8587
Средний Precision: 0.7008
Средний Recall: 0.8332
Средний F1-Score: 0.7412
Средний NDCG: 0.8468
Средний Precision: 0.6911
Средний Recall: 0.8223
Средний F1-Score: 0.7302

[I 2026-05-08 17:23:36,896] Trial 5 finished with value: 0.8565733933427125 and parameters: {'n_estimators': 800, 'max_depth': 5, 'learning_rate': 0.05748924681991978, 'num_leaves': 186, 'min_child_samples': 9}. Best is trial 2 with value: 0.8571175629509271.

Средний NDCG: 0.8566
Средний Precision: 0.7013
Средний Recall: 0.8283
Средний F1-Score: 0.7395
🏃 View run 5 at: http://127.0.0.1:5000/#/experiments/1/runs/2941e88442ee457ea978f15bf8de7f7d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8496
Средний Precision: 0.6449
Средний Recall: 0.8277
Средний F1-Score: 0.6996
Средний NDCG: 0.8388
Средний Precision: 0.6303
Средний Recall: 0.8180
Средний F1-Score: 0.6855

[I 2026-05-08 17:26:26,695] Trial 6 finished with value: 0.8457247017141889 and parameters: {'n_estimators': 650, 'max_depth': 5, 'learning_rate': 0.012476394272569451, 'num_leaves': 286, 'min_child_samples': 97}. Best is trial 2 with value: 0.8571175629509271.

Средний NDCG: 0.8457
Средний Precision: 0.6408
Средний Recall: 0.8210
Средний F1-Score: 0.6948
🏃 View run 6 at: http://127.0.0.1:5000/#/experiments/1/runs/12fc41bdbef04e858f1049c0cc20b9e5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8552
Средний Precision: 0.6698
Средний Recall: 0.8331
Средний F1-Score: 0.7193
Средний NDCG: 0.8448
Средний Precision: 0.6580
Средний Recall: 0.8213
Средний F1-Score: 0.7063

[I 2026-05-08 17:27:09,495] Trial 7 finished with value: 0.8523309120537447 and parameters: {'n_estimators': 850, 'max_depth': 6, 'learning_rate': 0.013940346079873234, 'num_leaves': 212, 'min_child_samples': 47}. Best is trial 2 with value: 0.8571175629509271.

Средний NDCG: 0.8523
Средний Precision: 0.6714
Средний Recall: 0.8276
Средний F1-Score: 0.7186
🏃 View run 7 at: http://127.0.0.1:5000/#/experiments/1/runs/be8d72bbfde6406a80fa4d4e9c51456f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8510
Средний Precision: 0.6632
Средний Recall: 0.8263
Средний F1-Score: 0.7113
Средний NDCG: 0.8396
Средний Precision: 0.6490
Средний Recall: 0.8145
Средний F1-Score: 0.6983

[I 2026-05-08 17:27:58,160] Trial 8 finished with value: 0.8468207651350818 and parameters: {'n_estimators': 200, 'max_depth': 9, 'learning_rate': 0.011240768803005551, 'num_leaves': 275, 'min_child_samples': 29}. Best is trial 2 with value: 0.8571175629509271.

Средний NDCG: 0.8468
Средний Precision: 0.6598
Средний Recall: 0.8218
Средний F1-Score: 0.7082
🏃 View run 8 at: http://127.0.0.1:5000/#/experiments/1/runs/9ec9bb54f87d47c1b0be83df047c89d9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8616
Средний Precision: 0.7351
Средний Recall: 0.8281
Средний F1-Score: 0.7609
Средний NDCG: 0.8478
Средний Precision: 0.7245
Средний Recall: 0.8169
Средний F1-Score: 0.7505

[I 2026-05-08 17:28:46,383] Trial 9 finished with value: 0.8572511149122544 and parameters: {'n_estimators': 700, 'max_depth': 7, 'learning_rate': 0.05864129169696527, 'num_leaves': 173, 'min_child_samples': 22}. Best is trial 9 with value: 0.8572511149122544.

Средний NDCG: 0.8573
Средний Precision: 0.7346
Средний Recall: 0.8201
Средний F1-Score: 0.7577
🏃 View run 9 at: http://127.0.0.1:5000/#/experiments/1/runs/401c1ddb438345adae2bec4b0a9e267b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8584
Средний Precision: 0.6918
Средний Recall: 0.8362
Средний F1-Score: 0.7361
Средний NDCG: 0.8479
Средний Precision: 0.6820
Средний Recall: 0.8254
Средний F1-Score: 0.7253

[I 2026-05-08 17:29:20,094] Trial 10 finished with value: 0.8557827407911096 and parameters: {'n_estimators': 1000, 'max_depth': 10, 'learning_rate': 0.03001215871999436, 'num_leaves': 25, 'min_child_samples': 67}. Best is trial 9 with value: 0.8572511149122544.

Средний NDCG: 0.8558
Средний Precision: 0.6949
Средний Recall: 0.8307
Средний F1-Score: 0.7360
🏃 View run 10 at: http://127.0.0.1:5000/#/experiments/1/runs/8d08b9c79b704757bd80b371639aac7c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8307
Средний Precision: 0.7217
Средний Recall: 0.8178
Средний F1-Score: 0.7478
Средний NDCG: 0.8232
Средний Precision: 0.7196
Средний Recall: 0.7965
Средний F1-Score: 0.7375

[I 2026-05-08 17:29:56,473] Trial 11 finished with value: 0.8204887461088198 and parameters: {'n_estimators': 400, 'max_depth': 15, 'learning_rate': 0.2763967942370457, 'num_leaves': 74, 'min_child_samples': 5}. Best is trial 9 with value: 0.8572511149122544.

Средний NDCG: 0.8205
Средний Precision: 0.7203
Средний Recall: 0.8000
Средний F1-Score: 0.7391
🏃 View run 11 at: http://127.0.0.1:5000/#/experiments/1/runs/fd6657b8234b422cada1e1d75d49d133
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8618
Средний Precision: 0.7619
Средний Recall: 0.8141
Средний F1-Score: 0.7723
Средний NDCG: 0.8493
Средний Precision: 0.7518
Средний Recall: 0.8041
Средний F1-Score: 0.7617

[I 2026-05-08 17:30:42,547] Trial 12 finished with value: 0.8578275187630338 and parameters: {'n_estimators': 450, 'max_depth': 11, 'learning_rate': 0.10681991291694365, 'num_leaves': 102, 'min_child_samples': 31}. Best is trial 12 with value: 0.8578275187630338.

Средний NDCG: 0.8578
Средний Precision: 0.7577
Средний Recall: 0.8093
Средний F1-Score: 0.7676
🏃 View run 12 at: http://127.0.0.1:5000/#/experiments/1/runs/7413d65de04c431c81dc5772d2a708c7
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8612
Средний Precision: 0.7639
Средний Recall: 0.8147
Средний F1-Score: 0.7737
Средний NDCG: 0.8490
Средний Precision: 0.7525
Средний Recall: 0.8013
Средний F1-Score: 0.7608

[I 2026-05-08 17:31:38,012] Trial 13 finished with value: 0.8572633898258065 and parameters: {'n_estimators': 550, 'max_depth': 10, 'learning_rate': 0.09540529615221287, 'num_leaves': 111, 'min_child_samples': 39}. Best is trial 12 with value: 0.8578275187630338.

Средний NDCG: 0.8573
Средний Precision: 0.7601
Средний Recall: 0.8047
Средний F1-Score: 0.7671
🏃 View run 13 at: http://127.0.0.1:5000/#/experiments/1/runs/0c934933486c4e4cae3376763635ed5c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8619
Средний Precision: 0.7576
Средний Recall: 0.8212
Средний F1-Score: 0.7727
Средний NDCG: 0.8483
Средний Precision: 0.7471
Средний Recall: 0.8058
Средний F1-Score: 0.7598

[I 2026-05-08 17:32:23,378] Trial 14 finished with value: 0.8572678552348955 and parameters: {'n_estimators': 450, 'max_depth': 12, 'learning_rate': 0.09732685045417536, 'num_leaves': 97, 'min_child_samples': 38}. Best is trial 12 with value: 0.8578275187630338.

Средний NDCG: 0.8573
Средний Precision: 0.7542
Средний Recall: 0.8116
Средний F1-Score: 0.7665
🏃 View run 14 at: http://127.0.0.1:5000/#/experiments/1/runs/20ac7357cd654b568e112d55008c4bc3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8613
Средний Precision: 0.7246
Средний Recall: 0.8333
Средний F1-Score: 0.7566
Средний NDCG: 0.8491
Средний Precision: 0.7146
Средний Recall: 0.8232
Средний F1-Score: 0.7470

[I 2026-05-08 17:32:49,391] Trial 15 finished with value: 0.8574324869518992 and parameters: {'n_estimators': 400, 'max_depth': 12, 'learning_rate': 0.09894162917596773, 'num_leaves': 42, 'min_child_samples': 66}. Best is trial 12 with value: 0.8578275187630338.

Средний NDCG: 0.8574
Средний Precision: 0.7259
Средний Recall: 0.8270
Средний F1-Score: 0.7549
🏃 View run 15 at: http://127.0.0.1:5000/#/experiments/1/runs/97e3334d901f4a2f8278e68a852884a8
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8561
Средний Precision: 0.6691
Средний Recall: 0.8349
Средний F1-Score: 0.7202
Средний NDCG: 0.8460
Средний Precision: 0.6616
Средний Recall: 0.8259
Средний F1-Score: 0.7110

[I 2026-05-08 17:33:12,505] Trial 16 finished with value: 0.8538396096109194 and parameters: {'n_estimators': 350, 'max_depth': 12, 'learning_rate': 0.03366291890434677, 'num_leaves': 36, 'min_child_samples': 67}. Best is trial 12 with value: 0.8578275187630338.

Средний NDCG: 0.8538
Средний Precision: 0.6756
Средний Recall: 0.8332
Средний F1-Score: 0.7240
🏃 View run 16 at: http://127.0.0.1:5000/#/experiments/1/runs/1c07043733e94de19c5ea9576f61b174
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8611
Средний Precision: 0.7585
Средний Recall: 0.8199
Средний F1-Score: 0.7724
Средний NDCG: 0.8487
Средний Precision: 0.7493
Средний Recall: 0.8086
Средний F1-Score: 0.7623

[I 2026-05-08 17:33:50,299] Trial 17 finished with value: 0.8574469512820642 and parameters: {'n_estimators': 550, 'max_depth': 13, 'learning_rate': 0.1357039061098737, 'num_leaves': 59, 'min_child_samples': 80}. Best is trial 12 with value: 0.8578275187630338.

Средний NDCG: 0.8574
Средний Precision: 0.7528
Средний Recall: 0.8113
Средний F1-Score: 0.7652
🏃 View run 17 at: http://127.0.0.1:5000/#/experiments/1/runs/ef5b2222387b453b87765281ce5126c2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Средний NDCG: 0.8606
Средний Precision: 0.7608
Средний Recall: 0.8150
Средний F1-Score: 0.7716
Средний NDCG: 0.8480
Средний Precision: 0.7521
Средний Recall: 0.8033
Средний F1-Score: 0.7623

[I 2026-05-08 17:34:27,829] Trial 18 finished with value: 0.8567673720184357 and parameters: {'n_estimators': 500, 'max_depth': 13, 'learning_rate': 0.16696881791330048, 'num_leaves': 65, 'min_child_samples': 90}. Best is trial 12 with value: 0.8578275187630338.

Средний NDCG: 0.8568
Средний Precision: 0.7569
Средний Recall: 0.8066
Средний F1-Score: 0.7664
🏃 View run 18 at: http://127.0.0.1:5000/#/experiments/1/runs/3f7b8b92289a4f698b035708584f3a68
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

In [ ]:
pipeline_lgbm_best = Pipeline([
    ('preprocessing', ColumnTransformer([
        ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
    ], remainder='passthrough')),
    ('model', LGBMClassifier(
        random_state=RANDOM_STATE, 
        verbose=-1,
        class_weight='balanced'
    ))
])

pipeline_lgbm_best.set_params(**study_lgbm.best_trial.user_attrs['pipeline_params'])
pipeline_lgbm_best.fit(X_train, y_train)

y_pred_proba_lgbm = pipeline_lgbm_best.predict_proba(X_test)

df_test_lgbm = df.loc[X_test.index].copy()
df_test_lgbm['y_pred_proba'] = y_pred_proba_lgbm[:, 1]

ndcg_lgbm, precision_lgbm, recall_lgbm, f1_lgbm = calculate_metrics(df_test_lgbm)
metrics_lgbm = {
    'NDCG': ndcg_lgbm,
    'Precision': precision_lgbm,
    'Recall': recall_lgbm,
    'F1': f1_lgbm
}

In [ ]:
RUN_NAME_LGBM = "best_optuna_lgbm"
REGISTRY_MODEL_NAME_LGBM = "best_optuna_lgbm"

signature = mlflow.models.infer_signature(X_test, y_test)
input_example = X_test[:10]
code_paths = ["ML_Experiments.ipynb"]

with mlflow.start_run(run_name=RUN_NAME_LGBM, experiment_id=experiment_id) as run:
    run_id = run.info.run_id
    
    lgbm_info = mlflow.sklearn.log_model(sk_model=pipeline_lgbm_best, 
                                        artifact_path='best_optuna_lgbm',
                                        registered_model_name=REGISTRY_MODEL_NAME_LGBM,
                                        input_example=input_example,
                                        code_paths=code_paths,
                                        await_registration_for=60
                                       )
    mlflow.log_metrics(metrics_lgbm)
    mlflow.log_params(best_params_lgbm)

# CatBoostClassifier

In [ ]:
def objective_catboost(trial: optuna.Trial) -> float:
    params = {
        'model__iterations': trial.suggest_int('iterations', 100, 1000, step=50),
        'model__depth': trial.suggest_int('depth', 3, 10),
        'model__learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'model__l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 1, 10, log=True)
    }
    
    pipeline_catboost = Pipeline([
        ('preprocessing', ColumnTransformer([
            ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
        ], remainder='passthrough')),
        ('model', CatBoostClassifier(
            random_state=RANDOM_STATE, 
            verbose=0, 
            auto_class_weights='Balanced'
        ))
    ])
    
    pipeline_catboost.set_params(**params)
    
    kfold = StratifiedKFold(n_splits=3, shuffle=True, random_state=RANDOM_STATE)
    
    for train_idx, val_idx in kfold.split(X_train, y_train):
        X_fold_train, X_fold_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_fold_train, y_fold_val = y_train.iloc[train_idx], y_train.iloc[val_idx]
        
        pipeline_catboost.fit(X_fold_train, y_fold_train)
        y_pred_proba = pipeline_catboost.predict_proba(X_fold_val)
        
        df_val = df.loc[X_fold_val.index].copy()
        df_val['y_pred_proba'] = y_pred_proba[:, 1]
        
        ndcg, _, _, _ = calculate_metrics(df_val)
        
        trial.set_user_attr('pipeline_params', params)
    
    return ndcg

In [ ]:
RUN_NAME_OPTUNE_CATBOOST = 'CatBoostClassifier_optuna'

with mlflow.start_run(run_name=RUN_NAME_OPTUNE_CATBOOST, experiment_id=experiment_id) as run:
    run_id_catboost = run.info.run_id

In [ ]:
STUDY_NAME_CATBOOST = "CatBoostClassifier_optuna"

mlflc_catboost = MLflowCallback(
    tracking_uri=f'http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}',
    metric_name="NDCG",
    create_experiment=False,
    mlflow_kwargs={'experiment_id': experiment_id, 'tags': {MLFLOW_PARENT_RUN_ID: run_id_catboost}}
)

In [ ]:
study_catboost = optuna.create_study(direction='maximize', 
                                     sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
                                     study_name=STUDY_NAME_CATBOOST,
                                     storage=STUDY_DB_NAME,
                                     load_if_exists=False)

study_catboost.optimize(objective_catboost, 
                        n_trials=20, 
                        callbacks=[mlflc_catboost]
                       )

best_params_catboost = study_catboost.best_params
print(f"Number of finished trials: {len(study_catboost.trials)}")
print(f"Best params CatBoost: {best_params_catboost}")

In [ ]:
pipeline_catboost_best = Pipeline([
    ('preprocessing', ColumnTransformer([
        ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
    ], remainder='passthrough')),
    ('model', CatBoostClassifier(
        random_state=RANDOM_STATE, 
        verbose=0, 
        auto_class_weights='Balanced'
    ))
])

pipeline_catboost_best.set_params(**study_catboost.best_trial.user_attrs['pipeline_params'])
pipeline_catboost_best.fit(X_train, y_train)

y_pred_proba_catboost = pipeline_catboost_best.predict_proba(X_test)

df_test_catboost = df.loc[X_test.index].copy()
df_test_catboost['y_pred_proba'] = y_pred_proba_catboost[:, 1]

ndcg_catboost, precision_catboost, recall_catboost, f1_catboost = calculate_metrics(df_test_catboost)
metrics_catboost = {
    'NDCG': ndcg_catboost,
    'Precision': precision_catboost,
    'Recall': recall_catboost,
    'F1': f1_catboost
}

In [ ]:
RUN_NAME_CATBOOST = "best_optuna_catboost"
REGISTRY_MODEL_NAME_CATBOOST = "best_optuna_catboost"

signature = mlflow.models.infer_signature(X_test, y_test)
input_example = X_test[:10]
code_paths = ["ML_Experiments.ipynb"]

with mlflow.start_run(run_name=RUN_NAME_CATBOOST, experiment_id=experiment_id) as run:
    run_id = run.info.run_id
    
    catboost_info = mlflow.sklearn.log_model(sk_model=pipeline_catboost_best, 
                                             artifact_path='best_optuna_catboost',
                                             registered_model_name=REGISTRY_MODEL_NAME_CATBOOST,
                                             input_example=input_example,
                                             code_paths=code_paths,
                                             await_registration_for=60
                                            )
    mlflow.log_metrics(metrics_catboost)
    mlflow.log_params(best_params_catboost)

# Model comparison

In [ ]:
models_comparison = pd.DataFrame({
    'Model': ['LogisticRegression', 'RandomForest', 'XGBoost', 'LightGBM', 'CatBoost'],
    'NDCG': [ndcg_lr, ndcg_rf, 
             ndcg_xgb, ndcg_lgbm, ndcg_catboost],
    'Precision': [precision_lr, precision_rf, 
                  precision_xgb, precision_lgbm, precision_catboost],
    'Recall': [recall_lr, recall_rf, 
               recall_xgb, recall_lgbm, recall_catboost],
    'F1': [f1_lr, f1_rf, 
           f1_xgb, f1_lgbm, f1_catboost]
})

models_comparison

In [ ]:
best_model_idx = models_comparison['NDCG'].idxmax()
print(f"\nЛучшая модель: {models_comparison.iloc[best_model_idx]['Model']} с NDCG = {models_comparison.iloc[best_model_idx]['NDCG']:.4f}")

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

По итогам подбора гиперпараметров лучшее качество показала модель `XGBClassifier`. Теперь попробуем добавить дополнительные признаки от кандидата генераторов. В первую очередь используем коллаборативную фильтрацию.

</div>

# ALS

## Feature engineering

In [ ]:
def create_interaction_matrix(df):
    unique_vacancies = df['vacancy_id'].unique().tolist()
    unique_resumes = df['resume_id'].unique().tolist()

    id2vacancy = dict(enumerate(unique_vacancies))
    id2resume = dict(enumerate(unique_resumes))
    vacancy2id = {v: k for k, v in id2vacancy.items()}
    resume2id = {v: k for k, v in id2resume.items()}

    rows = [vacancy2id[vacancy] for vacancy in df['vacancy_id']]
    cols = [resume2id[resume] for resume in df['resume_id']]

    interactions_matrix = csr_matrix(
        (df['target'], (rows, cols)),
        shape=(len(unique_vacancies), len(unique_resumes)),
        dtype=np.float32,
    )

    return interactions_matrix, id2vacancy, id2resume, vacancy2id, resume2id, unique_vacancies, unique_resumes

In [ ]:
interactions_matrix, id2vacancy, id2resume, vacancy2id, resume2id, unique_vacancies, unique_resumes = create_interaction_matrix(df)

print(f"Размерность матрицы взаимодействий: {interactions_matrix.shape}")
print(f"Плотность матрицы: {interactions_matrix.nnz / (interactions_matrix.shape[0] * interactions_matrix.shape[1]):.6f}")

In [ ]:
def get_factors(interactions_matrix):
    als_model = AlternatingLeastSquares(
        factors=64,          
        regularization=0.1,  
        iterations=30,       
        random_state=RANDOM_STATE,
        num_threads=0
    )
    
    als_model.fit(interactions_matrix.T)

    vacancy_factors = als_model.item_factors
    resume_factors = als_model.user_factors

    return vacancy_factors, resume_factors

In [ ]:
vacancy_factors, resume_factors = get_factors(interactions_matrix)

print(f"Размерность эмбеддингов вакансий: {vacancy_factors.shape}")
print(f"Размерность эмбеддингов резюме: {resume_factors.shape}")

In [ ]:
def get_als_score(vacancy_id, resume_id):
    if vacancy_id not in vacancy2id or resume_id not in resume2id:
        return 0
    else:
        vac_idx = vacancy2id[vacancy_id]
        res_idx = resume2id[resume_id]
        score = np.dot(vacancy_factors[vac_idx], resume_factors[res_idx])
        return score

df['als_score'] = df.apply(
    lambda row: get_als_score(row['vacancy_id'], row['resume_id']), 
    axis=1
)

In [ ]:
df[['vacancy_id', 'resume_id', 'target', 'als_score']].head()

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

Проверим схожесть резюме по латентным векторам.

</div>

In [ ]:
def find_similar_resumes(resume_id, resume_factors, n_similar=10, metric='cosine'):
    """
    Находит N наиболее похожих резюме на заданное.
    """
    if resume_id not in resume2id:
        print(f"Резюме с ID {resume_id} не найдено")
        return []

    target_idx = resume2id[resume_id]
    target_vector = resume_factors[target_idx].reshape(1, -1)
    
    if metric == 'cosine':
        similarities = cosine_similarity(target_vector, resume_factors)[0]
    else:
        similarities = np.dot(resume_factors, target_vector.T).flatten()
    
    similar_indices = np.argsort(similarities)[::-1][1:n_similar+1]
    
    similar_resumes = []
    for idx in similar_indices:
        sim_resume_id = unique_resumes[idx]
        similarity_score = similarities[idx]
        similar_resumes.append((sim_resume_id, similarity_score))
    
    return similar_resumes

def get_resume_profile(resume_id, df):
    """Вспомогательная функция для получения информации о резюме"""
    resume_data = df[df['resume_id'] == resume_id].iloc[0]
    return {
        'resume_id': resume_id,
        'title': resume_data.get('resume_title', 'N/A'),
        'specialization': resume_data.get('resume_specialization', 'N/A'),
        'skills': resume_data.get('resume_skills', 'N/A'),
        'experience': resume_data.get('resume_total_experience', 'N/A'),
        'salary': resume_data.get('resume_salary', 'N/A'),
        'location': resume_data.get('resume_location', 'N/A')
    }

In [ ]:
example_resume_id = df['resume_id'].sample(1, random_state=RANDOM_STATE).values[0].item()
print(f"Исходное резюме (ID: {example_resume_id}):")
original_profile = get_resume_profile(example_resume_id, df)
for key, value in original_profile.items():
    print(f"  {key}: {value}")

print(f"\nТоп-5 похожих резюме (косинусная близость):")
similar_resumes = find_similar_resumes(example_resume_id, resume_factors, n_similar=5, metric='cosine')

for i, (sim_id, score) in enumerate(similar_resumes, 1):
    profile = get_resume_profile(sim_id, df)
    print(f"\n{i}. Резюме ID: {sim_id} (сходство: {score:.4f})")
    print(f"   Должность: {profile['title']}")
    print(f"   Специализация: {profile['specialization']}")
    print(f"   Локация: {profile['location']}")
    print(f"   Опыт: {profile['experience']}")

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

Разделим тренировочную выборку еще на две, чтобы избежать подглядывания и добавить в признак `als_score` нулевые значения в тренировочный датасет, т.к. у нас могут быть вакансии и резюме без взаимодействий до обучения.

</div>

In [ ]:
X_train_als, X_test_als, y_train_als, y_test_als = train_test_split(X_train, y_train, test_size=0.3, random_state=RANDOM_STATE, stratify=y_train)

In [ ]:
train_als_interactions = df.loc[X_train_als.index, ['vacancy_id', 'resume_id', 'target']]

interactions_matrix, id2vacancy, id2resume, vacancy2id, resume2id, unique_vacancies, unique_resumes = create_interaction_matrix(train_als_interactions)
vacancy_factors, resume_factors = get_factors(interactions_matrix)

# возвращаем айдишники вакансий и резюме для расчета als score
X_train[['vacancy_id', 'resume_id']] = df.loc[X_train.index, ['vacancy_id', 'resume_id']]
X_train['als_score'] = X_train.apply(
    lambda row: get_als_score(row['vacancy_id'], row['resume_id']), 
    axis=1
)

X_train = X_train.drop(['vacancy_id', 'resume_id'], axis=1)

In [ ]:
# проверим есть ли вакансии и резюме без взаимодействий до обучения
X_train[X_train['als_score'] == 0]

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

Теперь добавим признак `als_score` для тестовой выборке, но уже возьмем матрицу интеракций на полной тренировочной выборке.

</div>

In [ ]:
train_interactions = df.loc[X_train.index, ['vacancy_id', 'resume_id', 'target']]

interactions_matrix, id2vacancy, id2resume, vacancy2id, resume2id, unique_vacancies, unique_resumes = create_interaction_matrix(train_interactions)
vacancy_factors, resume_factors = get_factors(interactions_matrix)

# возвращаем айдишники вакансий и резюме для расчета als score
X_test[['vacancy_id', 'resume_id']] = df.loc[X_test.index, ['vacancy_id', 'resume_id']]
X_test['als_score'] = X_test.apply(
    lambda row: get_als_score(row['vacancy_id'], row['resume_id']), 
    axis=1
)

X_test = X_test.drop(['vacancy_id', 'resume_id'], axis=1)

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

Выборки получены, обучим `XGBClassifier` с подбором гиперпараметров.

</div>

In [ ]:
X_train.info()

## XGBClassifier

In [ ]:
def objective_xgb(trial: optuna.Trial) -> float:
    params = {
        'model__n_estimators': trial.suggest_int('n_estimators', 100, 1000, step=50),
        'model__max_depth': trial.suggest_int('max_depth', 3, 15),
        'model__learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'model__min_child_weight': trial.suggest_int('min_child_weight', 1, 10)
    }
    
    pipeline_xgb = Pipeline([
        ('preprocessing', ColumnTransformer([
            ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
        ], remainder='passthrough')),
        ('model', XGBClassifier(
            random_state=RANDOM_STATE, 
            eval_metric='logloss', 
            use_label_encoder=False, 
            verbosity=0,
            scale_pos_weight=(len(y_train) - sum(y_train)) / sum(y_train)
        ))
    ])
    
    pipeline_xgb.set_params(**params)
    
    kfold = StratifiedKFold(n_splits=3, shuffle=True, random_state=RANDOM_STATE)
    
    for train_idx, val_idx in kfold.split(X_train, y_train):
        X_fold_train, X_fold_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_fold_train, y_fold_val = y_train.iloc[train_idx], y_train.iloc[val_idx]
        
        pipeline_xgb.fit(X_fold_train, y_fold_train)
        y_pred_proba = pipeline_xgb.predict_proba(X_fold_val)
        
        df_val = df.loc[X_fold_val.index].copy()
        df_val['y_pred_proba'] = y_pred_proba[:, 1]
        
        ndcg, _, _, _ = calculate_metrics(df_val)
        
        trial.set_user_attr('pipeline_params', params)
    
    return ndcg

In [ ]:
try:
    experiment_id = mlflow.get_experiment_by_name(EXPERIMENT_NAME).experiment_id
except:
    experiment_id = mlflow.create_experiment(EXPERIMENT_NAME)

RUN_NAME_OPTUNE_XGB = 'XGBClassifier_optuna_als'

with mlflow.start_run(run_name=RUN_NAME_OPTUNE_XGB, experiment_id=experiment_id) as run:
    run_id_xgb = run.info.run_id

In [ ]:
STUDY_NAME_XGB = "XGBClassifier_optuna_als"

mlflc_xgb = MLflowCallback(
    tracking_uri=f'http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}',
    metric_name="NDCG",
    create_experiment=False,
    mlflow_kwargs={'experiment_id': experiment_id, 'tags': {MLFLOW_PARENT_RUN_ID: run_id_xgb}}
)

In [ ]:
study_xgb = optuna.create_study(direction='maximize', 
                                sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
                                study_name=STUDY_NAME_XGB,
                                storage=STUDY_DB_NAME,
                                load_if_exists=False)

study_xgb.optimize(objective_xgb, 
                   n_trials=20, 
                   callbacks=[mlflc_xgb]
                  )

best_params_xgb = study_xgb.best_params
print(f"Number of finished trials: {len(study_xgb.trials)}")
print(f"Best params XGBoost: {best_params_xgb}")

In [ ]:
pipeline_xgb_best = Pipeline([
    ('preprocessing', ColumnTransformer([
        ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
    ], remainder='passthrough')),
    ('model', XGBClassifier(
        random_state=RANDOM_STATE, 
        eval_metric='logloss', 
        use_label_encoder=False, 
        verbosity=0,
        scale_pos_weight=(len(y_train) - sum(y_train)) / sum(y_train)
    ))
])

pipeline_xgb_best.set_params(**study_xgb.best_trial.user_attrs['pipeline_params'])
pipeline_xgb_best.fit(X_train, y_train)

y_pred_proba_xgb = pipeline_xgb_best.predict_proba(X_test)

df_test_xgb = df.loc[X_test.index].copy()
df_test_xgb['y_pred_proba'] = y_pred_proba_xgb[:, 1]

ndcg_xgb_als, precision_xgb_als, recall_xgb_als, f1_xgb_als = calculate_metrics(df_test_xgb)
metrics_xgb_als = {
    'NDCG': ndcg_xgb_als,
    'Precision': precision_xgb_als,
    'Recall': recall_xgb_als,
    'F1': f1_xgb_als
}

In [ ]:
RUN_NAME_XGB = "best_optuna_xgb_als"
REGISTRY_MODEL_NAME_XGB = "best_optuna_xgb_als"

signature = mlflow.models.infer_signature(X_test, y_test)
input_example = X_test[:10]
code_paths = ["ML_Experiments.ipynb"]

with mlflow.start_run(run_name=RUN_NAME_XGB, experiment_id=experiment_id) as run:
    run_id = run.info.run_id
    
    xgb_info = mlflow.sklearn.log_model(sk_model=pipeline_xgb_best, 
                                       artifact_path='best_optuna_xgb_als',
                                       registered_model_name=REGISTRY_MODEL_NAME_XGB,
                                       input_example=input_example,
                                       code_paths=code_paths,
                                       await_registration_for=60
                                      )
    mlflow.log_metrics(metrics_xgb_als)
    mlflow.log_params(best_params_xgb)

## LGBMClassifier

In [ ]:
def objective_lgbm(trial: optuna.Trial) -> float:
    params = {
        'model__n_estimators': trial.suggest_int('n_estimators', 100, 1000, step=50),
        'model__max_depth': trial.suggest_int('max_depth', 3, 15),
        'model__learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'model__num_leaves': trial.suggest_int('num_leaves', 20, 300),
        'model__min_child_samples': trial.suggest_int('min_child_samples', 5, 100)
    }
    
    pipeline_lgbm = Pipeline([
        ('preprocessing', ColumnTransformer([
            ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
        ], remainder='passthrough')),
        ('model', LGBMClassifier(
            random_state=RANDOM_STATE, 
            verbose=-1,
            class_weight='balanced'
        ))
    ])
    
    pipeline_lgbm.set_params(**params)
    
    kfold = StratifiedKFold(n_splits=3, shuffle=True, random_state=RANDOM_STATE)
    
    for train_idx, val_idx in kfold.split(X_train, y_train):
        X_fold_train, X_fold_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_fold_train, y_fold_val = y_train.iloc[train_idx], y_train.iloc[val_idx]
        
        pipeline_lgbm.fit(X_fold_train, y_fold_train)
        y_pred_proba = pipeline_lgbm.predict_proba(X_fold_val)
        
        df_val = df.loc[X_fold_val.index].copy()
        df_val['y_pred_proba'] = y_pred_proba[:, 1]
        
        ndcg, _, _, _ = calculate_metrics(df_val)
        
        trial.set_user_attr('pipeline_params', params)
    
    return ndcg

In [ ]:
RUN_NAME_OPTUNE_LGBM = 'LGBMClassifier_optuna_als'

with mlflow.start_run(run_name=RUN_NAME_OPTUNE_LGBM, experiment_id=experiment_id) as run:
    run_id_lgbm = run.info.run_id

In [ ]:
STUDY_NAME_LGBM = "LGBMClassifier_optuna_als"

mlflc_lgbm = MLflowCallback(
    tracking_uri=f'http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}',
    metric_name="NDCG",
    create_experiment=False,
    mlflow_kwargs={'experiment_id': experiment_id, 'tags': {MLFLOW_PARENT_RUN_ID: run_id_lgbm}}
)

In [ ]:
study_lgbm = optuna.create_study(direction='maximize', 
                                 sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
                                 study_name=STUDY_NAME_LGBM,
                                 storage=STUDY_DB_NAME,
                                 load_if_exists=False)

study_lgbm.optimize(objective_lgbm, 
                    n_trials=20, 
                    callbacks=[mlflc_lgbm]
                   )

best_params_lgbm = study_lgbm.best_params
print(f"Number of finished trials: {len(study_lgbm.trials)}")
print(f"Best params LGBM: {best_params_lgbm}")

In [ ]:
pipeline_lgbm_best = Pipeline([
    ('preprocessing', ColumnTransformer([
        ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
    ], remainder='passthrough')),
    ('model', LGBMClassifier(
        random_state=RANDOM_STATE, 
        verbose=-1,
        class_weight='balanced'
    ))
])

pipeline_lgbm_best.set_params(**study_lgbm.best_trial.user_attrs['pipeline_params'])
pipeline_lgbm_best.fit(X_train, y_train)

y_pred_proba_lgbm = pipeline_lgbm_best.predict_proba(X_test)

df_test_lgbm = df.loc[X_test.index].copy()
df_test_lgbm['y_pred_proba'] = y_pred_proba_lgbm[:, 1]

ndcg_lgbm_als, precision_lgbm_als, recall_lgbm_als, f1_lgbm_als = calculate_metrics(df_test_lgbm)
metrics_lgbm_als = {
    'NDCG': ndcg_lgbm_als,
    'Precision': precision_lgbm_als,
    'Recall': recall_lgbm_als,
    'F1': f1_lgbm_als
}

In [ ]:
RUN_NAME_LGBM = "best_optuna_lgbm_als"
REGISTRY_MODEL_NAME_LGBM = "best_optuna_lgbm_als"

signature = mlflow.models.infer_signature(X_test, y_test)
input_example = X_test[:10]
code_paths = ["ML_Experiments.ipynb"]

with mlflow.start_run(run_name=RUN_NAME_LGBM, experiment_id=experiment_id) as run:
    run_id = run.info.run_id
    
    lgbm_info = mlflow.sklearn.log_model(sk_model=pipeline_lgbm_best, 
                                        artifact_path='best_optuna_lgbm_als',
                                        registered_model_name=REGISTRY_MODEL_NAME_LGBM,
                                        input_example=input_example,
                                        code_paths=code_paths,
                                        await_registration_for=60
                                       )
    mlflow.log_metrics(metrics_lgbm_als)
    mlflow.log_params(best_params_lgbm)

## CatBoostClassifier

In [ ]:
def objective_catboost(trial: optuna.Trial) -> float:
    params = {
        'model__iterations': trial.suggest_int('iterations', 100, 1000, step=50),
        'model__depth': trial.suggest_int('depth', 3, 10),
        'model__learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'model__l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 1, 10, log=True)
    }
    
    pipeline_catboost = Pipeline([
        ('preprocessing', ColumnTransformer([
            ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
        ], remainder='passthrough')),
        ('model', CatBoostClassifier(
            random_state=RANDOM_STATE, 
            verbose=0, 
            auto_class_weights='Balanced'
        ))
    ])
    
    pipeline_catboost.set_params(**params)
    
    kfold = StratifiedKFold(n_splits=3, shuffle=True, random_state=RANDOM_STATE)
    
    for train_idx, val_idx in kfold.split(X_train, y_train):
        X_fold_train, X_fold_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_fold_train, y_fold_val = y_train.iloc[train_idx], y_train.iloc[val_idx]
        
        pipeline_catboost.fit(X_fold_train, y_fold_train)
        y_pred_proba = pipeline_catboost.predict_proba(X_fold_val)
        
        df_val = df.loc[X_fold_val.index].copy()
        df_val['y_pred_proba'] = y_pred_proba[:, 1]
        
        ndcg, _, _, _ = calculate_metrics(df_val)
        
        trial.set_user_attr('pipeline_params', params)
    
    return ndcg

In [ ]:
RUN_NAME_OPTUNE_CATBOOST = 'CatBoostClassifier_optuna_als'

with mlflow.start_run(run_name=RUN_NAME_OPTUNE_CATBOOST, experiment_id=experiment_id) as run:
    run_id_catboost = run.info.run_id

In [ ]:
STUDY_NAME_CATBOOST = "CatBoostClassifier_optuna_als"

mlflc_catboost = MLflowCallback(
    tracking_uri=f'http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}',
    metric_name="NDCG",
    create_experiment=False,
    mlflow_kwargs={'experiment_id': experiment_id, 'tags': {MLFLOW_PARENT_RUN_ID: run_id_catboost}}
)

In [ ]:
study_catboost = optuna.create_study(direction='maximize', 
                                     sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
                                     study_name=STUDY_NAME_CATBOOST,
                                     storage=STUDY_DB_NAME,
                                     load_if_exists=True)

study_catboost.optimize(objective_catboost, 
                        n_trials=20, 
                        callbacks=[mlflc_catboost]
                       )

best_params_catboost = study_catboost.best_params
print(f"Number of finished trials: {len(study_catboost.trials)}")
print(f"Best params CatBoost: {best_params_catboost}")

In [ ]:
pipeline_catboost_best = Pipeline([
    ('preprocessing', ColumnTransformer([
        ('categorical_encoding', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), categorical_features)
    ], remainder='passthrough')),
    ('model', CatBoostClassifier(
        random_state=RANDOM_STATE, 
        verbose=0, 
        auto_class_weights='Balanced'
    ))
])

pipeline_catboost_best.set_params(**study_catboost.best_trial.user_attrs['pipeline_params'])
pipeline_catboost_best.fit(X_train, y_train)

y_pred_proba_catboost = pipeline_catboost_best.predict_proba(X_test)

df_test_catboost = df.loc[X_test.index].copy()
df_test_catboost['y_pred_proba'] = y_pred_proba_catboost[:, 1]

ndcg_catboost_als, precision_catboost_als, recall_catboost_als, f1_catboost_als = calculate_metrics(df_test_catboost)
metrics_catboost_als = {
    'NDCG': ndcg_catboost_als,
    'Precision': precision_catboost_als,
    'Recall': recall_catboost_als,
    'F1': f1_catboost_als
}

In [ ]:
Средний NDCG: 0.7814
Средний Precision: 0.6823
Средний Recall: 0.7589
Средний F1-Score: 0.7043

In [ ]:
RUN_NAME_CATBOOST = "best_optuna_catboost_als"
REGISTRY_MODEL_NAME_CATBOOST = "best_optuna_catboost_als"

signature = mlflow.models.infer_signature(X_test, y_test)
input_example = X_test[:10]
code_paths = ["ML_Experiments.ipynb"]

with mlflow.start_run(run_name=RUN_NAME_CATBOOST, experiment_id=experiment_id) as run:
    run_id = run.info.run_id
    
    catboost_info = mlflow.sklearn.log_model(sk_model=pipeline_catboost_best, 
                                             artifact_path='best_optuna_catboost_als',
                                             registered_model_name=REGISTRY_MODEL_NAME_CATBOOST,
                                             input_example=input_example,
                                             code_paths=code_paths,
                                             await_registration_for=60
                                            )
    mlflow.log_metrics(metrics_catboost_als)
    mlflow.log_params(best_params_catboost)

## Model comparison

In [ ]:
models_comparison = pd.DataFrame({
    'Model': ['LogisticRegression', 'RandomForest', 'XGBoost', 'LightGBM', 'CatBoost', 'XGBoost + ALS', 'LightGBM + ALS', 'CatBoost + ALS'],
    'NDCG': [ndcg_lr, ndcg_rf, ndcg_xgb, ndcg_lgbm, ndcg_catboost, ndcg_xgb_als, ndcg_lgbm_als, ndcg_catboost_als],
    'Precision': [precision_lr, precision_rf, precision_xgb, precision_lgbm, precision_catboost, precision_xgb_als, precision_lgbm_als, precision_catboost_als],
    'Recall': [recall_lr, recall_rf, recall_xgb, recall_lgbm, recall_catboost, recall_xgb_als, recall_lgbm_als, recall_catboost_als],
    'F1': [f1_lr, f1_rf, f1_xgb, f1_lgbm, f1_catboost, f1_xgb_als, f1_lgbm_als, f1_catboost_als]
})

models_comparison

In [ ]:
Model	NDCG	Precision	Recall	F1
0	LogisticRegression	0.751349	0.637015	0.596379	0.599915
1	RandomForest	0.775653	0.660585	0.742407	0.682372
2	XGBoost	0.778059	0.698832	0.734174	0.703595
3	LightGBM	0.778390	0.669718	0.750699	0.691776
4	CatBoost	0.778681	0.678187	0.747071	0.695479
5	XGBoost + ALS	0.781090	0.669943	0.763557	0.698493
6	LightGBM + ALS	0.781279	0.704709	0.749976	0.714586
7	CatBoost + ALS	0.780736	0.669796	0.762115	0.697661

In [ ]:
best_model_idx = models_comparison['NDCG'].idxmax()
print(f"\nЛучшая модель: {models_comparison.iloc[best_model_idx]['Model']} с NDCG = {models_comparison.iloc[best_model_idx]['NDCG']:.4f}")

<div style="background-color: #98FB98; color: black; padding: 10px; border-radius: 5px;">

Сохраним обученный итоговый пайплайн.

</div>

In [ ]:
MODEL_NAME = 'pipeline_lgb_best.pkl'
with open(MODEL_NAME, 'wb') as file:
    pickle.dump(pipeline_lgbm_best, file)

In [ ]:
def show_vacancy_predictions(pipeline, X_test, y_test, df,
                             n_top=10, vacancy_id=None, random_state=None):
    """
    Показывает предсказания пайплайна для выбранной вакансии из тест-сета.

    Args:
        pipeline     : обученный sklearn Pipeline
        X_test       : тестовые признаки (те же колонки, на которых обучался pipeline)
        y_test       : истинные метки
        df           : исходный датафрейм со всеми колонками (для отображения)
        n_top        : сколько топ-резюме показать
        vacancy_id   : None = случайная вакансия; иначе конкретный ID
        random_state : seed для воспроизводимости случайного выбора

    Returns:
        pd.DataFrame, отсортированный по pred_proba убыванием
    """
    df_test = df.loc[X_test.index].copy()
    df_test['target'] = y_test.values

    if vacancy_id is None:
        rng = np.random.RandomState(random_state)
        vacancy_id = rng.choice(df_test['vacancy_id'].unique())

    mask = df_test['vacancy_id'] == vacancy_id
    if not mask.any():
        print(f"[!] vacancy_id={vacancy_id} не найден в тестовой выборке.")
        return None

    df_vac = df_test[mask].copy()
    X_vac  = X_test.loc[df_vac.index]

    df_vac['pred_proba'] = pipeline.predict_proba(X_vac)[:, 1]
    df_vac = df_vac.sort_values('pred_proba', ascending=False).reset_index(drop=True)

    r0       = df_vac.iloc[0]
    vac_name = str(r0.get('vacancy_name', '—'))
    vac_desc = str(r0.get('vacancy_description', '—'))
    SEP, SEP2 = "=" * 90, "─" * 90

    print(SEP)
    print(f"  ВАКАНСИЯ : {vac_name}   [id={vacancy_id}]")
    print(f"  Опыт     : {r0.get('vacancy_experience','—')}  |  "
          f"Занятость : {r0.get('vacancy_employment','—')}  |  "
          f"График : {r0.get('vacancy_schedule','—')}")
    print(SEP2)
    print("  ОПИСАНИЕ ВАКАНСИИ:")
    for line in vac_desc[:1200].split('\n')[:25]:
        if line.strip():
            print(f"    {line.strip()}")
    if len(vac_desc) > 1200:
        print("    [... сокращено]")
    print(SEP)

    n_pos = int(df_vac['target'].sum())
    print(f"\n  ТОП-{n_top} из {len(df_vac)} кандидатов  "
          f"(всего реально подходящих в выборке: {n_pos})\n")

    for rank, (_, row) in enumerate(df_vac.head(n_top).iterrows(), 1):
        icon   = "✅" if row['target'] == 1 else "❌"
        exp    = str(row.get('resume_last_experience_description', '—'))
        skills = str(row.get('resume_skills', '—'))
        print(SEP2)
        print(f"  #{rank}  {icon}  score={row['pred_proba']:.4f}  "
              f"target={int(row['target'])}  [resume_id={row.get('resume_id','—')}]")
        print(f"  Должность : {row.get('resume_last_position','—')}")
        print(f"  Локация   : {row.get('resume_location','—')}  |  "
              f"Опыт: {row.get('resume_experience_months','—')} мес.")
        print(f"  Навыки    : {skills[:180]}{'...' if len(skills) > 180 else ''}")
        print(f"  Описание последнего места:")
        for line in exp[:700].split('\n')[:14]:
            if line.strip():
                print(f"    {line.strip()}")
        if len(exp) > 700:
            print("    [... сокращено]")
        print()

    print(SEP2)
    n_hit = int(df_vac.head(n_top)['target'].sum())
    print(f"\n  Попаданий в топ-{n_top}: {n_hit}/{n_top} ({100*n_hit//n_top}%)")
    print(f"  Всего релевантных в тест-сете для этой вакансии: {n_pos}\n")

    return df_vac

In [ ]:
# Случайная вакансия из тест-сета, лучший пайплайн
result = show_vacancy_predictions(pipeline_lgbm_best, X_test, y_test, df,
                                  n_top=10, vacancy_id=126372900)

# Зафиксировать вакансию и сравнить другой пайплайн:
# vacancy_id_fixed = result.iloc[0]['vacancy_id']
# show_vacancy_predictions(pipeline_lgbm_als, X_test, y_test, df,
#                          n_top=10, vacancy_id=vacancy_id_fixed)